Repository vitejs/vite, pull requests merged in 2021-08, with the labels that each got.

#4431 refactor: cli mode options to common, reorder GlobalCLIOptions
  packages/vite/src/node/cli.ts
Labels: p1-chore :broom:

#4457 docs: document debug logging
  .github/contributing.md
  packages/vite/src/node/utils.ts
Labels: documentation

#4466 docs: make the Contributing Guidelines more discoverable
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#4187 fix: @vite/client http request is 404 not found
  packages/playground/extensions/__tests__/extensions.spec.ts
  packages/playground/extensions/index.html
  packages/playground/extensions/package.json
  packages/playground/extensions/vite.config.js
  packages/vite/src/client/client.ts
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#3534 fix: the return value of resolve by adding a namespace when processing a '@' in filter
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug :hammer:

#3627 fix: import sass file even if not listed in package.json
  packages/playground/css/__tests__/css.spec.ts
  packages/playground/css/index.html
  packages/playground/css/pkg-dep/_index.scss
  packages/playground/css/pkg-dep/index.js
  packages/playground/css/pkg-dep/package.json
  packages/playground/css/sass.scss
  packages/vite/src/node/plugins/resolve.ts
Labels: p2-has-workaround :cake:

#4088 fix(scan): improve import regex and allow multiline comments
  packages/vite/src/node/__tests__/scan.spec.ts
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug :hammer:

#4352 fix(build): respect rollup output.assetFileNames, fix #2944
  packages/vite/src/node/__tests__/asset.spec.ts
  packages/vite/src/node/plugins/asset.ts
Labels: p3-minor-bug :hammer:

#2521 feat: implement custom logger
  packages/vite/src/node/config.ts
  packages/vite/src/node/logger.ts
Labels: enhancement, p2-nice-to-have :cake:

#4478 docs: add a note on how to fix WSL2 watch issues
  docs/config/index.md
Labels: documentation

#3950 feat(ssr): tolerate circular imports
  packages/playground/ssr-react/__tests__/ssr-react.spec.ts
  packages/playground/ssr-react/src/add.js
  packages/playground/ssr-react/src/circular-dep-init/README.md
  packages/playground/ssr-react/src/circular-dep-init/circular-dep-init.js
  packages/playground/ssr-react/src/circular-dep-init/module-a.js
  packages/playground/ssr-react/src/circular-dep-init/module-b.js
  packages/playground/ssr-react/src/forked-deadlock/README.md
  packages/playground/ssr-react/src/forked-deadlock/common-module.js
  packages/playground/ssr-react/src/forked-deadlock/deadlock-fuse-module.js
  packages/playground/ssr-react/src/forked-deadlock/fuse-stuck-bridge-module.js
  packages/playground/ssr-react/src/forked-deadlock/middle-module.js
  packages/playground/ssr-react/src/forked-deadlock/stuck-module.js
  packages/playground/ssr-react/src/multiply.js
  packages/playground/ssr-react/src/pages/About.jsx
  packages/playground/ssr-react/src/pages/Home.jsx
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: feat: ssr, p3-downstream-blocker :hammer:

#4480 deps: update esbuild to 12.17
  packages/vite/package.json
  yarn.lock
Labels: dependencies

#4485 docs: Fix the confusing example of `server.proxy`
  docs/config/index.md
Labels: documentation

#4460 fix(server): keep port when modifying the config file
  packages/vite/src/node/server/hmr.ts
Labels: p3-minor-bug :hammer:

#4374 fix: close vite dev server before creating new one
  packages/vite/src/node/server/hmr.ts
Labels: p3-minor-bug :hammer:

#4484 refactor: isCSSRequest for all css
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p1-chore :broom:

#3957 feat: add `logger.hasErrorLogged(error)` method
  packages/vite/src/node/build.ts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/logger.ts
  packages/vite/src/node/optimizer/registerMissing.ts
  packages/vite/src/node/server/middlewares/error.ts
  packages/vite/src/node/server/middlewares/proxy.ts
  packages/vite/src/node/server/openBrowser.ts
  packages/vite/src/node/server/ws.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p2-nice-to-have :cake:

#4493 chore: KiB instead of kb unit
  packages/vite/src/node/plugins/reporter.ts
Labels: p1-chore :broom:

#4505 fix: prevent crash when a file imported from SCSS does not exist
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#4522 docs: indentation in code block
  docs/guide/static-deploy.md
Labels: documentation

#4525 docs: make link to existing integrations more prominent
  docs/guide/backend-integration.md
Labels: documentation

#4541 feat(create-app): add alternative command for yarn
  packages/create-app/index.js
Labels: p1-chore :broom:

#4534 chore(docs): improve gitlab pages deployment
  docs/guide/static-deploy.md
Labels: documentation

#3050 feat: add asset name (#3028)
  packages/vite/src/node/plugins/asset.ts
Labels: p2-nice-to-have :cake:

#4599 docs: Removed an unwanted closing parenthesis
  docs/config/index.md
Labels: documentation

#4565 fix: skip optimizer run on non-JS script tags
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug :hammer:

#4590 fix: support dangling comma and throw on circular dependency in tsconfig
  packages/playground/tsconfig-json/nested/tsconfig.json
  packages/vite/package.json
  packages/vite/src/node/plugins/esbuild.ts
Labels: p2-has-workaround :cake:

#2042 fix: add support for Yarn PnP mode by adding CSS preprocessors as opt…
  package.json
Labels: p1-chore :broom:

#4610 docs: align package.json serve script (fix #4609)
  docs/guide/static-deploy.md
Labels: documentation

#4426 fix: surface exception when failing to resolve package entry
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug :hammer:

#4616 fix: `Matcher` for chokidar WatchOptions#ignored
  packages/vite/src/node/index.ts
  packages/vite/src/node/server/index.ts
  packages/vite/types/anymatch.d.ts
  packages/vite/types/chokidar.d.ts
Labels: p1-chore :broom:

#4490 feat: Add `ssr.noExternal = true` option
  docs/config/index.md
  docs/guide/ssr.md
  packages/playground/ssr-webworker/__tests__/serve.js
  packages/playground/ssr-webworker/__tests__/ssr-webworker.spec.ts
  packages/playground/ssr-webworker/package.json
  packages/playground/ssr-webworker/src/entry-worker.jsx
  packages/playground/ssr-webworker/vite.config.js
  packages/playground/ssr-webworker/worker.js
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: p2-nice-to-have :cake:

#4618 feat: make redirect easier when visit a non-based page
  packages/vite/src/node/server/middlewares/base.ts
Labels: p2-nice-to-have :cake:

#4602 fix(scan): do not match 'export default' in comments
  packages/vite/src/node/__tests__/scan.spec.ts
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug :hammer:

#4596 fix(vite): unexptected overwriting for default export fix(#4553)
  packages/playground/optimize-deps/__tests__/optimize-deps.spec.ts
  packages/playground/optimize-deps/cjs-dynamic.js
  packages/playground/optimize-deps/dep-cjs-compiled-from-cjs/index.js
  packages/playground/optimize-deps/dep-cjs-compiled-from-cjs/package.json
  packages/playground/optimize-deps/dep-cjs-compiled-from-esm/index.js
  packages/playground/optimize-deps/dep-cjs-compiled-from-esm/package.json
  packages/playground/optimize-deps/index.html
  packages/playground/optimize-deps/package.json
  packages/vite/src/node/plugins/importAnalysis.ts
  yarn.lock
Labels: p3-minor-bug :hammer:

#4600 chore: upgrade sirv
  package.json
  packages/vite/package.json
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/decodeURI.ts
  yarn.lock
Labels: dependencies, p1-chore :broom:

#3333 fix(css): dynamic import css abnormal after build
  packages/playground/dynamic-import/__tests__/dynamic-import.spec.ts
  packages/playground/dynamic-import/css/index.css
  packages/playground/dynamic-import/index.html
  packages/playground/dynamic-import/nested/index.js
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-minor-bug :hammer:

#4592 fix: CSS dependencies are tracked incorrectly when base is set
  packages/playground/backend-integration/__tests__/backend-integration.spec.ts
  packages/playground/backend-integration/frontend/entrypoints/global.css
  packages/playground/backend-integration/frontend/entrypoints/index.html
  packages/playground/backend-integration/frontend/entrypoints/main.ts
  packages/playground/backend-integration/frontend/styles/tailwind.css
  packages/playground/backend-integration/package.json
  packages/playground/backend-integration/postcss.config.js
  packages/playground/backend-integration/tailwind.config.js
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#4638 refactor: delete unused try catch
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p1-chore :broom:

#4606 fix(create-vite): project name with only numbers as an argument
  packages/create-vite/index.js
Labels: p2-nice-to-have :cake:

#4656 chore: fix issue-workflow picture path
  CONTRIBUTING.md
Labels: p1-chore :broom:

#4659 chore: update code comment link to contributor's guide
  packages/vite/package.json
Labels: p1-chore :broom:

#4658 fix(css): minify css will transform rgba to #rrggbbaa
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#4675 refactor: remove unused placeholder `__ROOT__` in client.ts
  packages/vite/src/client/client.ts
  packages/vite/src/node/plugins/clientInjections.ts
Labels: p1-chore :broom:

#4275 fix: enable failing dependencies to be optimised by pre-processing them with esbuild
  packages/vite/src/node/optimizer/index.ts
Labels: p3-downstream-blocker :hammer:

#4197 docs: dependency resolution warning, closes #4089
  docs/guide/dep-pre-bundling.md
Labels: documentation, p1-chore :broom:

#4690 chore(docs): add prefix algorithm in Content Security Policy hash
  packages/plugin-legacy/README.md
Labels: documentation

#4753 fix: jest module naming collision
  jest.config.ts
Labels: p1-chore :broom:

#4732 fix: don't transform new URL(url, import.meta.url) in comments
  packages/playground/assets/index.html
  packages/vite/src/node/__tests__/scan.spec.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#4766 fix: special handling for ssr.noExternal in mergeConfig
  packages/playground/ssr-webworker/vite.config.js
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#4772 fix(ssr): resolve .cjs file extensions
  packages/vite/src/node/utils.ts
Labels: p3-downstream-blocker :hammer:, feat: ssr

#4775 deps: bump @vue/compiler-sfc to 3.2.6
  packages/create-vite/template-vue-ts/package.json
  packages/create-vite/template-vue/package.json
Labels: dependencies

#4634 feat(optimizer): nested optimization
  docs/config/index.md
  packages/playground/dynamic-import/css/index.css
  packages/playground/nested-deps/__tests__/nested-deps.spec.ts
  packages/playground/nested-deps/index.html
  packages/playground/nested-deps/package.json
  packages/playground/nested-deps/test-package-d/index.js
  packages/playground/nested-deps/test-package-d/package.json
  packages/playground/nested-deps/test-package-d/test-package-d-nested/index.js
  packages/playground/nested-deps/test-package-d/test-package-d-nested/package.json
  packages/playground/nested-deps/vite.config.js
  packages/playground/optimize-deps/__tests__/optimize-deps.spec.ts
  packages/playground/optimize-deps/index.html
  packages/playground/optimize-deps/nested-exclude/index.js
  packages/playground/optimize-deps/nested-exclude/nested-include/index.js
  packages/playground/optimize-deps/nested-exclude/nested-include/package.json
  packages/playground/optimize-deps/nested-exclude/package.json
  packages/playground/optimize-deps/package.json
  packages/playground/optimize-deps/vite.config.js
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/clientInjections.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/utils.ts
  yarn.lock
Labels: p4-important :exclamation:

#4739 chore: stabilize sorting of licenses
  packages/vite/LICENSE.md
  packages/vite/rollup.config.js
Labels: p1-chore :broom:
