Repository vitejs/vite, pull requests merged in 2021-05, with the labels that each got.

#3171 fix(dev): strip utf-8 bom (#3162)
  packages/playground/resolve/__tests__/resolve.spec.ts
  packages/playground/resolve/index.html
  packages/playground/resolve/utf8-bom/main.js
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p2-has-workaround :cake:

#3241 fix(plugin-legacy): correct log level to error
  packages/plugin-legacy/index.js
Labels: plugin: legacy

#2991 feat: add optimizeDeps.esbuildOptions
  packages/playground/optimize-deps/__tests__/optimize-deps.spec.ts
  packages/playground/optimize-deps/dep-esbuild-plugin-transform/index.js
  packages/playground/optimize-deps/dep-esbuild-plugin-transform/package.json
  packages/playground/optimize-deps/index.html
  packages/playground/optimize-deps/package.json
  packages/playground/optimize-deps/vite.config.js
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/scan.ts
  yarn.lock
Labels: p2-nice-to-have :cake:

#3226 chore(ci): remove circle and appveyor ci
  .circleci/config.yml
  README.md
  appveyor.yml
Labels: p1-chore :broom:

#2717 fix: only provide npm package names to resolveSSRExternal
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:, 🔍 review needed

#3256 chore: remove unused README references
  README.md
Labels: documentation, p1-chore :broom:

#2848 fix(resolve): normalize node_modules and bare imports, fix #2503
  packages/vite/src/node/plugins/resolve.ts
Labels: p4-important :exclamation:

#2977 fix(server): Listen only to 127.0.0.1 by default
  docs/config/index.md
  packages/vite/src/node/cli.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  scripts/jestPerTestSetup.ts
Labels: p4-important :exclamation:, security

#2988 fix(ci): fix ci lint step
  .github/workflows/ci.yml
  package.json
  packages/plugin-react-refresh/index.js
  packages/vite/package.json
  scripts/jestPerTestSetup.ts
Labels: p1-chore :broom:

#3177 fix(ssr): resolve dynamic import vars modules
  packages/playground/ssr-vue/src/pages/Home.vue
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-minor-bug :hammer:

#2976 refactor!: esbuild 0.11 upgrade, remove dynamic-import-polyfill
  docs/config/index.md
  docs/guide/backend-integration.md
  docs/guide/build.md
  docs/guide/comparisons.md
  docs/guide/features.md
  docs/guide/index.md
  packages/vite/package.json
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/dynamicImportPolyfill.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/index.ts
  scripts/jestPerTestSetup.ts
  yarn.lock
Labels: dependencies

#3282 fix(upstream): upgrade esbuild@0.11.19
  packages/vite/package.json
  yarn.lock
Labels: bug: upstream, p3-minor-bug :hammer:

#3251 refactor: vite middlewares as named functions
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/base.ts
  packages/vite/src/node/server/middlewares/decodeURI.ts
  packages/vite/src/node/server/middlewares/error.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/middlewares/proxy.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/server/middlewares/time.ts
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p1-chore :broom:

#3152 feat: set publicDir to false to disable copied static assets to build dist dir
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/server/index.ts
Labels: p2-has-workaround :cake:

#3151 feat: webworker ssr target
  docs/config/index.md
  docs/guide/ssr.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug :hammer:

#2850 fix: prevent serving unrestricted files (fix #2820)
  docs/config/index.md
  packages/vite/src/node/index.ts
  packages/vite/src/node/server/__tests__/fixtures/none/nested/package.json
  packages/vite/src/node/server/__tests__/fixtures/pnpm/nested/package.json
  packages/vite/src/node/server/__tests__/fixtures/pnpm/package.json
  packages/vite/src/node/server/__tests__/fixtures/pnpm/pnpm-workspace.yaml
  packages/vite/src/node/server/__tests__/fixtures/yarn/nested/package.json
  packages/vite/src/node/server/__tests__/fixtures/yarn/package.json
  packages/vite/src/node/server/__tests__/search-root.spec.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/server/searchRoot.ts
Labels: p4-important :exclamation:, security

#3269 refactor: rewrite after #2977
  packages/vite/src/node/logger.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
Labels: p1-chore :broom:

#3075 docs: more explicit defineComponent example
  packages/plugin-vue-jsx/README.md
Labels: documentation, p1-chore :broom:

#2193 docs: add note about assetsInlineLimit in library mode
  docs/config/index.md
Labels: documentation, p1-chore :broom:

#1992 fix(hmr): respect server https options when running as middleware
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/http.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/ws.ts
Labels: enhancement, feat: hmr, p2-nice-to-have :cake:

#3239 fix(dev): rewrite importee path at html files at spa fallback
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: p3-minor-bug :hammer:

#3204 test(create-app): add integration tests
  packages/create-app/__tests__/cli.spec.ts
Labels: p1-chore :broom:, test

#3353 fix: bump @rollup/plugin-commonjs to v19, fix #3312
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/build.ts
  yarn.lock
Labels: bug, bug: upstream, dependencies, p3-minor-bug :hammer:

#3350 fix: normalize url in `ensureServingAccess`
  packages/vite/src/node/server/middlewares/static.ts
Labels: p3-minor-bug :hammer:

#3374 fix: use the closest package.json as root when workspace not found fo…
  packages/vite/src/node/server/searchRoot.ts
Labels: p3-minor-bug :hammer:

#3377 fix: disable fsServe restrictions by default
  docs/config/index.md
  packages/vite/src/node/logger.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p5-urgent :fire:, security

#3385 deps: bump esbuild to 0.11.20, fix #3247
  packages/vite/package.json
  yarn.lock
Labels: dependencies

#3386 chore: change prettier version to exact
  docs/.vitepress/config.js
  docs/config/index.md
  docs/guide/api-plugin.md
  docs/guide/build.md
  docs/guide/ssr.md
  docs/guide/using-plugins.md
  package.json
  packages/create-app/index.js
  packages/create-app/template-lit-element-ts/package.json
  packages/create-app/template-lit-element/package.json
  packages/create-app/template-preact-ts/package.json
  packages/create-app/template-preact/package.json
  packages/create-app/template-react-ts/package.json
  packages/create-app/template-react/package.json
  packages/create-app/template-svelte-ts/package.json
  packages/create-app/template-svelte/package.json
  packages/create-app/template-vanilla-ts/package.json
  packages/create-app/template-vanilla/package.json
  packages/create-app/template-vue-ts/package.json
  packages/create-app/template-vue/package.json
  packages/playground/backend-integration/frontend/entrypoints/global.css
  packages/playground/backend-integration/references.css
  packages/playground/css-codesplit-cjs/main.css
  packages/playground/dynamic-import/mxd.json
  packages/playground/multiple-entrypoints/deps.json
  packages/playground/multiple-entrypoints/reference.scss
  packages/playground/ssr-vue/src/pages/Home.vue
  packages/playground/vue/Main.vue
  packages/plugin-react-refresh/README.md
  packages/plugin-vue/src/main.ts
  packages/plugin-vue/src/utils/query.ts
  packages/vite/client.d.ts
  packages/vite/src/client/client.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/dynamicImportPolyfill.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/ssr/ssrStacktrace.ts
  scripts/jestPerTestSetup.ts
  scripts/verifyCommit.js
  yarn.lock
Labels: dependencies, p1-chore :broom:

#3368 fix(css): fix sass importer error
  packages/playground/css/sass.scss
  packages/playground/css/vite.config.js
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#3415 docs: fix `build.assetsInlineLimit` link
  docs/guide/assets.md
Labels: documentation

#3432 test: fsServe strict mode during serve
  scripts/jestPerTestSetup.ts
Labels: p1-chore :broom:, test

#3433 docs(create-app): add pnpm commands
  packages/create-app/README.md
Labels: documentation, p1-chore :broom:

#3431 fix: skip fs fallback for out of root urls, fix #3364
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p3-minor-bug :hammer:

#3434 fix: restore dynamic-import-polyfill
  docs/config/index.md
  docs/guide/backend-integration.md
  packages/plugin-legacy/index.js
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/dynamicImportPolyfill.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-minor-bug :hammer:

#3406 fix(plugin-legacy): turn off babel loose mode
  packages/playground/legacy/__tests__/legacy.spec.ts
  packages/playground/legacy/index.html
  packages/playground/legacy/main.js
  packages/plugin-legacy/index.js
Labels: bug, p3-minor-bug :hammer:, plugin: legacy

#3463 docs: Add vanilla-ts in the Getting Started guide
  docs/guide/index.md
Labels: documentation, p1-chore :broom:

#3500 fix: invalidate import globs upon new/removed files (fix #3499)
  packages/playground/glob-import/__tests__/glob-import.spec.ts
  packages/vite/src/node/server/hmr.ts
Labels: p3-minor-bug :hammer:

#3497 fix: handle HMR for files with more than one glob import
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#2641 fix(plugin-legacy): respect custom filenames formats, fix #2356
  packages/playground/legacy/package.json
  packages/playground/legacy/vite.config-custom-filename.js
  packages/plugin-legacy/index.js
Labels: bug, p3-minor-bug :hammer:, plugin: legacy

#3214 feat(create-app): improve client types
  docs/guide/features.md
  packages/create-app/template-lit-element-ts/src/vite-env.d.ts
  packages/create-app/template-lit-element-ts/tsconfig.json
  packages/create-app/template-preact-ts/src/vite-env.d.ts
  packages/create-app/template-preact-ts/tsconfig.json
  packages/create-app/template-react-ts/src/vite-env.d.ts
  packages/create-app/template-react-ts/tsconfig.json
  packages/create-app/template-svelte-ts/src/vite-env.d.ts
  packages/create-app/template-svelte/src/vite-env.d.ts
  packages/create-app/template-vanilla-ts/src/vite-env.d.ts
  packages/create-app/template-vanilla-ts/tsconfig.json
  packages/create-app/template-vue-ts/src/vite-env.d.ts
  packages/create-app/template-vue-ts/tsconfig.json
Labels: p2-nice-to-have :cake:

#3506 fix(preview): support custom hostname
  packages/vite/src/node/cli.ts
  packages/vite/src/node/preview.ts
Labels: p3-minor-bug :hammer:

#3514 fix(preview): allow to disable HTTPS
  packages/vite/src/node/cli.ts
  packages/vite/src/node/preview.ts
Labels: p3-minor-bug :hammer:

#3512 fix: ensure new assets cache at build start, fix #3271
  packages/vite/src/node/plugins/asset.ts
Labels: p3-minor-bug :hammer:

#2871 feat: support serving `index.html` in middleware mode
  docs/config/index.md
  docs/guide/ssr.md
  packages/playground/ssr-react/server.js
  packages/playground/ssr-vue/server.js
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:

#3468 fix: inline webworker safari support
  packages/playground/worker/__tests__/worker.spec.ts
  packages/vite/src/node/plugins/worker.ts
Labels: p3-minor-bug :hammer:

#3005 fix: do not cache module while the file contains import.meta.glob
  packages/vite/src/node/server/hmr.ts
Labels: feat: ssr, p3-minor-bug :hammer:

#3402 fix: avoid css leaking into emitted javascript
  packages/playground/css/__tests__/css.spec.ts
  packages/playground/css/imported-without-variable.css
  packages/playground/css/index.html
  packages/playground/css/main.js
  packages/vite/src/node/plugins/css.ts
Labels: p3-minor-bug :hammer:

#3478 fix: track deps for css @import in build watch mode(fix #3387)
  packages/vite/src/node/plugins/css.ts
Labels: p3-minor-bug :hammer:

#3519 fix(types): add .module.pcss typings (#3518)
  packages/vite/client.d.ts
Labels: p3-minor-bug :hammer:

#3528 chore: fixing sort in rollup config
  packages/vite/rollup.config.js
Labels: p3-minor-bug :hammer:

#3530 fix: clean manifest plugin state at build start
  packages/vite/src/node/plugins/manifest.ts
Labels: p3-minor-bug :hammer:

#3516 fix: ensure new CSS modules cache at build start
  packages/vite/src/node/plugins/css.ts
Labels: p3-minor-bug :hammer:

#3529 fix: allow passing an array as sass / scss importer
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#3565 chore(deps): upgrade jest to 27
  package.json
  yarn.lock
Labels: dependencies

#3407 feat(config): add `envDir` option
  docs/config/index.md
  docs/guide/env-and-mode.md
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#3578 feat: added clientPort to HmrOptions
  docs/config/index.md
  packages/vite/src/node/plugins/clientInjections.ts
  packages/vite/src/node/server/hmr.ts
Labels: enhancement, feat: hmr

#3570 fix: update esbuild to 0.12
  packages/vite/package.json
  yarn.lock
Labels: dependencies

#2505 feat(plugins/worker): support SharedWorker (resolve #2093)
  docs/guide/assets.md
  docs/guide/features.md
  packages/playground/worker/__tests__/worker.spec.ts
  packages/playground/worker/index.html
  packages/playground/worker/my-shared-worker.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/worker.ts
Labels: enhancement

#3584 fix(playground): fix an eslint error in testUtils
  packages/playground/testUtils.ts
Labels: p1-chore :broom:

#3572 fix: cannot recognize JS url correctly(#3568)
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#3589 chore: disable explicit-module-boundary-types for js
  .eslintrc.js
Labels: p1-chore :broom:

#3498 docs: Adding Azure Static Web App deployment instructions
  docs/guide/static-deploy.md
Labels: documentation, p1-chore :broom:

#3573 fix: include/exclude options for vue-jsx .d.ts
  packages/plugin-vue-jsx/index.d.ts
Labels: plugin: vue-jsx

#3044 refactor(create-app): moves to prompts
  packages/create-app/__tests__/cli.spec.ts
  packages/create-app/index.js
  packages/create-app/package.json
Labels: enhancement, p2-nice-to-have :cake:
