Repository vitejs/vite, pull requests merged in 2021-04, with the labels that each got.

#2837 docs: note that `define` should be used for CONSTANTS not variables
  docs/config/index.md
Labels: documentation

#2541 fix: chunks are analysed multiple times
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-minor-bug :hammer:

#2843 build: add source map to vite
  packages/vite/package.json
  packages/vite/rollup.config.js
  yarn.lock
Labels: p2-nice-to-have :cake:

#2620 fix(create-app): change index.html templates' favicon.svg href to absolute URL
  packages/create-app/template-lit-element-ts/index.html
  packages/create-app/template-lit-element/index.html
  packages/create-app/template-preact-ts/index.html
  packages/create-app/template-preact/index.html
  packages/create-app/template-react-ts/index.html
  packages/create-app/template-react/index.html
Labels: bug: pending triage, 🔍 review needed

#2856 chore: add missing comma for docs
  docs/config/index.md
Labels: documentation, p1-chore :broom:

#2621 fix(build): support `cssCodeSplit` for cjs format
  packages/playground/css-codesplit-cjs/__tests__/css-codesplit.spec.ts
  packages/playground/css-codesplit-cjs/index.html
  packages/playground/css-codesplit-cjs/main.css
  packages/playground/css-codesplit-cjs/main.js
  packages/playground/css-codesplit-cjs/other.js
  packages/playground/css-codesplit-cjs/package.json
  packages/playground/css-codesplit-cjs/style.css
  packages/playground/css-codesplit-cjs/vite.config.js
  packages/vite/src/node/plugins/css.ts
Labels: p3-minor-bug :hammer:, 🔍 review needed

#1449 feat(cli): build watch mode
  docs/config/index.md
  docs/guide/build.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/cli.ts
Labels: enhancement, p2-nice-to-have :cake:

#2901 feat: export manifest types
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/manifest.ts
Labels: p1-chore :broom:

#2800 feat(plugin): plugin config hook supports return promise
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugin.ts
Labels: enhancement, p3-downstream-blocker :hammer:

#2810 fix(scan): avoid crawling type only import
  packages/playground/ssr-vue/dep-import-type/deep/index.d.ts
  packages/playground/ssr-vue/dep-import-type/package.json
  packages/playground/ssr-vue/package.json
  packages/playground/ssr-vue/src/components/ImportType.vue
  packages/playground/ssr-vue/src/pages/Home.vue
  packages/vite/src/node/optimizer/scan.ts
  yarn.lock
Labels: bug, p4-important :exclamation:

#2750 feat: parameter settings when packaging the library
  docs/config/index.md
  packages/vite/src/node/build.ts
Labels: enhancement, p2-nice-to-have :cake:

#2853 refactor(worker): use existing isBuild flag
  packages/vite/src/node/plugins/worker.ts
Labels: p1-chore :broom:

#2885 docs: format api-javascript.md
  docs/guide/api-javascript.md
Labels: documentation, p1-chore :broom:

#2023 feat(create-app): add template vanilla-ts
  packages/create-app/README.md
  packages/create-app/index.js
  packages/create-app/template-vanilla-ts/_gitignore
  packages/create-app/template-vanilla-ts/favicon.svg
  packages/create-app/template-vanilla-ts/index.html
  packages/create-app/template-vanilla-ts/package.json
  packages/create-app/template-vanilla-ts/src/main.ts
  packages/create-app/template-vanilla-ts/src/style.css
  packages/create-app/template-vanilla-ts/tsconfig.json
Labels: enhancement, p2-nice-to-have :cake:

#2933 fix(plugin-vue): add newline character before class components
  packages/plugin-vue/src/main.ts
Labels: p3-minor-bug :hammer:, plugin: vue

#2622 ci: use github actions
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#2936 ci: add caching step in GitHub Actions
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#2939 docs: Added Multi-Page App example using 'root'
  docs/guide/build.md
Labels: documentation, p1-chore :broom:

#2519 feat: support globbing from dependencies
  docs/guide/features.md
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-downstream-blocker :hammer:

#2948 test: fix flakiness of client-side routing test (fix #2646)
  packages/playground/ssr-react/__tests__/ssr-react.spec.ts
  packages/playground/ssr-vue/__tests__/ssr-vue.spec.ts
  packages/playground/testUtils.ts
Labels: feat: ssr, p3-minor-bug :hammer:, test

#2952 chore: fix Vite Land link in CoC [skip ci]
  CODE_OF_CONDUCT.md
Labels: documentation, p1-chore :broom:

#2947 fix(create-app): the node in the svelte template is incorrectly mounted.
  packages/create-app/template-svelte-ts/src/main.ts
  packages/create-app/template-svelte/src/main.js
Labels: p3-minor-bug :hammer:

#2954 fix(test): improve stability of ssr tests
  packages/playground/ssr-react/__tests__/ssr-react.spec.ts
  packages/playground/ssr-react/server.js
  packages/playground/ssr-vue/__tests__/ssr-vue.spec.ts
  packages/playground/ssr-vue/server.js
  packages/playground/testUtils.ts
Labels: feat: ssr, p1-chore :broom:, test

#2966 fix(ssr): fix ssrTransform catch clause error (fix #2667)
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: feat: ssr

#2935 fix: A static and dynamically imported module is loaded twice
  packages/playground/dynamic-import/__tests__/dynamic-import.spec.ts
  packages/playground/dynamic-import/index.html
  packages/playground/dynamic-import/mxd.js
  packages/playground/dynamic-import/mxd.json
  packages/playground/dynamic-import/nested/index.js
  packages/playground/dynamic-import/vite.config.js
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p3-minor-bug :hammer:

#2951 feat(plugin-api): support async configResolved hooks (fixes #2949)
  docs/guide/api-plugin.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugin.ts
Labels: p2-nice-to-have :cake:

#2860 fix(css): properly pass options to stylus compiler
  packages/playground/css/__tests__/css.spec.ts
  packages/playground/css/css-dep/index.styl
  packages/playground/css/index.html
  packages/playground/css/main.js
  packages/playground/css/nested/nested.styl
  packages/playground/css/options/absolute-import.styl
  packages/playground/css/options/relative-import.styl
  packages/playground/css/package.json
  packages/playground/css/stylus.styl
  packages/playground/css/vite.config.js
  packages/vite/src/node/plugins/css.ts
  yarn.lock
Labels: p2-has-workaround :cake:

#2992 chore: upgrade vue-tsc to 0.0.24
  packages/create-app/template-vue-ts/package.json
Labels: dependencies

#2946 docs: contributing.md extending test suite section
  .github/contributing.md
Labels: p1-chore :broom:

#2735 chore: @typescript-eslint/explicit-module-boundary-types
  packages/plugin-vue/src/handleHotUpdate.ts
  packages/plugin-vue/src/script.ts
  packages/plugin-vue/src/utils/descriptorCache.ts
  packages/plugin-vue/src/utils/query.ts
  packages/vite/src/client/client.ts
  packages/vite/src/client/overlay.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/registerMissing.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/http.ts
  packages/vite/src/node/server/middlewares/error.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/moduleGraph.ts
  packages/vite/src/node/server/send.ts
  packages/vite/src/node/server/sourcemap.ts
  packages/vite/src/node/ssr/ssrStacktrace.ts
  packages/vite/src/node/utils.ts
Labels: p1-chore :broom:

#2475 feat: add inlineConfig.envFile option to disable .env files
  docs/guide/api-javascript.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/server/hmr.ts
Labels: p2-nice-to-have :cake:

#2941 feat(create-app): two-level prompt for framework and variants
  packages/create-app/index.js
Labels: enhancement, p2-nice-to-have :cake:

#2847 fix(build): properly handle alias key in config merge
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
Labels: bug, p3-minor-bug :hammer:

#2996 fix: don't resolve import using browser during SSR (fix #2995)
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug :hammer:

#3015 test: revert Prevent regressions in static file serving of files outside the root (#2358)
  packages/playground/assets/__tests__/assets.spec.ts
  packages/playground/assets/index.html
  packages/playground/assets/vite.config.js
  packages/playground/css/nested/asset.png
Labels: test

#2888 fix: filter out empty srcset (#2863)
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/utils.ts
Labels: bug, p3-minor-bug :hammer:

#3021 chore: use more explicit lint disable
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/terser.ts
Labels: p1-chore :broom:

#3020 chore(deps): update lint related dependencies
  package.json
  yarn.lock
Labels: dependencies, p1-chore :broom:

#2903 fix(react-refresh): check FunctionDeclaration nodes properly
  packages/plugin-react-refresh/index.js
Labels: p3-minor-bug :hammer:, plugin: react-refresh

#3031 feat: watch the dependencies of config file
  packages/vite/src/node/config.ts
  packages/vite/src/node/server/hmr.ts
Labels: p2-nice-to-have :cake:

#2899 feat: support cacheDir
  docs/config/index.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/transform.ts
Labels: enhancement, p2-nice-to-have :cake:

#2636 fix: avoid endless loop in resolveSSRExternal (fix #2635)
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: bug, p3-minor-bug :hammer:

#2929 fix(optimizer): ensure consistency with replace define
  packages/vite/src/node/optimizer/index.ts
Labels: p3-minor-bug :hammer:

#3003 fix: require.resolve to correct sub node_modules
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
Labels: p3-minor-bug :hammer:

#2019 feat(createLogger): allow custom prefix for logger
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/logger.ts
Labels: enhancement, p2-nice-to-have :cake:, 🔍 review needed

#1953 feat: add extensions option to vue-jsx plugin
  packages/playground/vue-jsx/OtherExt.tesx
  packages/playground/vue-jsx/__tests__/vue-jsx.spec.ts
  packages/playground/vue-jsx/main.jsx
  packages/playground/vue-jsx/vite.config.js
  packages/plugin-vue-jsx/index.js
  packages/plugin-vue-jsx/package.json
Labels: p2-nice-to-have :cake:, 🔍 review needed

#3054 chore(ci): fix node memory issues
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#3056 test(setup): fix server closure
  packages/playground/ssr-react/__tests__/serve.js
  packages/playground/ssr-vue/__tests__/serve.js
Labels: feat: ssr, p1-chore :broom:, test

#3073 feat(vite): add marko file extensions
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:

#3095 fix(ci): set node memory limits on CircleCI
  .circleci/config.yml
Labels: p1-chore :broom:

#2897 fix(plugin): avoid duplicate import (#2640)
  packages/plugin-vue/src/main.ts
Labels: p2-has-workaround :cake:

#3098 chore(ci): build on node 16 (current)
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#3117 feat(create-app): improve non-empty message for current dir
  packages/create-app/index.js
Labels: p2-nice-to-have :cake:

#3123 corrected bullet point order
  docs/guide/static-deploy.md
Labels: documentation, p1-chore :broom:

#3074 fix: handle null/empty sources in source maps
  packages/vite/src/node/server/sourcemap.ts
Labels: p3-minor-bug :hammer:

#3130 fix: support postcss .pcss extension
  packages/vite/client.d.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-nice-to-have :cake:

#2997 fix: await bundle close in worker plugin
  packages/vite/src/node/plugins/worker.ts
Labels: p3-minor-bug :hammer:

#3132 fix: dymamic import polyfill path when base is a URL
  packages/vite/src/node/plugins/dynamicImportPolyfill.ts
Labels: p3-minor-bug :hammer:

#2934 fix(build): vendor chunk strategy uses static imports, fix #2672
  packages/vite/src/node/build.ts
Labels: p3-minor-bug :hammer:

#3072 chore: use recommended lint
  .eslintrc.js
  package.json
  packages/plugin-vue/src/main.ts
  packages/plugin-vue/src/style.ts
  packages/plugin-vue/src/template.ts
  packages/vite/src/client/client.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  yarn.lock
Labels: p1-chore :broom:

#3144 fix: revert #2541, fix #3084 #3101
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-minor-bug :hammer:

#3043 fix(emptyOutDir): never remove .git
  packages/vite/src/node/build.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#3154 fix: dependencies are analyzed multiple times
  packages/playground/multiple-entrypoints/__tests__/multiple-entrypoints.spec.ts
  packages/playground/multiple-entrypoints/deps.json
  packages/playground/multiple-entrypoints/dynamic-a.js
  packages/playground/multiple-entrypoints/dynamic-b.js
  packages/playground/multiple-entrypoints/entrypoints/a0.js
  packages/playground/multiple-entrypoints/entrypoints/a1.js
  packages/playground/multiple-entrypoints/entrypoints/a10.js
  packages/playground/multiple-entrypoints/entrypoints/a11.js
  packages/playground/multiple-entrypoints/entrypoints/a12.js
  packages/playground/multiple-entrypoints/entrypoints/a13.js
  packages/playground/multiple-entrypoints/entrypoints/a14.js
  packages/playground/multiple-entrypoints/entrypoints/a15.js
  packages/playground/multiple-entrypoints/entrypoints/a16.js
  packages/playground/multiple-entrypoints/entrypoints/a17.js
  packages/playground/multiple-entrypoints/entrypoints/a18.js
  packages/playground/multiple-entrypoints/entrypoints/a19.js
  packages/playground/multiple-entrypoints/entrypoints/a2.js
  packages/playground/multiple-entrypoints/entrypoints/a20.js
  packages/playground/multiple-entrypoints/entrypoints/a21.js
  packages/playground/multiple-entrypoints/entrypoints/a22.js
  packages/playground/multiple-entrypoints/entrypoints/a23.js
  packages/playground/multiple-entrypoints/entrypoints/a24.js
  packages/playground/multiple-entrypoints/entrypoints/a3.js
  packages/playground/multiple-entrypoints/entrypoints/a4.js
  packages/playground/multiple-entrypoints/entrypoints/a5.js
  packages/playground/multiple-entrypoints/entrypoints/a6.js
  packages/playground/multiple-entrypoints/entrypoints/a7.js
  packages/playground/multiple-entrypoints/entrypoints/a8.js
  packages/playground/multiple-entrypoints/entrypoints/a9.js
  packages/playground/multiple-entrypoints/index.html
  packages/playground/multiple-entrypoints/index.js
  packages/playground/multiple-entrypoints/package.json
  packages/playground/multiple-entrypoints/reference.js
  packages/playground/multiple-entrypoints/reference.scss
  packages/playground/multiple-entrypoints/vite.config.js
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-minor-bug :hammer:

#2961 fix(scan): improve script regular matching (fixes #2942)
  packages/vite/src/node/__tests__/scan.spec.ts
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug :hammer:

#3113 feat: Allow overwrite `TerserOptions.safari10` from `UserConfig`
  packages/vite/src/node/plugins/terser.ts
Labels: p2-nice-to-have :cake:

#3175 ci: use Node 14 & fix memory on AppVeyor
  appveyor.yml
Labels: test, windows only

#3019 chore: add a build script
  package.json
Labels: p1-chore :broom:

#3080 fix: call `buildStart` hook in middleware mode
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:

#3185 test: fix timeout hiding runtime build error
  packages/playground/ssr-react/__tests__/serve.js
  packages/playground/ssr-vue/__tests__/serve.js
  packages/plugin-legacy/index.js
  scripts/jestPerTestSetup.ts
Labels: test

#3081 test: coverage to settings related with backend integrations
  packages/playground/backend-integration/__tests__/backend-integration.spec.ts
  packages/playground/backend-integration/frontend/entrypoints/global.css
  packages/playground/backend-integration/frontend/entrypoints/index.html
  packages/playground/backend-integration/frontend/images/logo.png
  packages/playground/backend-integration/frontend/styles/background.css
  packages/playground/backend-integration/package.json
  packages/playground/backend-integration/references.css
  packages/playground/backend-integration/vite.config.js
Labels: p1-chore :broom:, test
