Repository vitejs/vite, pull requests merged in 2021-03, with the labels that each got.

#2313 fix: await bundle close
  packages/vite/src/node/build.ts
Labels: bug

#2510 fix: keep process running when fail to load config in restarting server
  packages/vite/src/node/server/hmr.ts
Labels: :hammer: p3-minor-bug

#2506 feat: upgrade esbuild to 0.9
  packages/vite/package.json
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/esbuild.ts
  yarn.lock
Labels: :cake: p2-nice-to-have

#2338 feat: allow custom websocket server
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/ws.ts
Labels: enhancement

#2435 fix: Improve injectQuery path handling (fix #2422)
  packages/vite/src/node/utils.ts
Labels: :exclamation: p4-important

#2441 fix(ssr): handle empty sourcemaps (fix #2391)
  .eslintrc.js
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/plugins/esbuild.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  packages/vite/src/node/utils.ts
  yarn.lock
Labels: :exclamation: p4-important

#2488 chore: Use @preact/preset-vite for Preact templates
  packages/create-app/template-preact-ts/package.json
  packages/create-app/template-preact-ts/vite.config.ts
  packages/create-app/template-preact/package.json
  packages/create-app/template-preact/vite.config.js
Labels: :cake: p2-nice-to-have

#2566 fix: update esbuild target to allow destructuring
  packages/vite/package.json
  packages/vite/src/node/build.ts
  yarn.lock
Labels: :fire: p5-urgent

#2619 fix(dev): remove process listeners on server close, fix #2616
  packages/vite/src/node/server/index.ts
Labels: :hammer: p3-minor-bug

#2649 chore(plugin-legacy): upgrade @babel/standalone to 7.13.12 (fix #2442)
  packages/plugin-legacy/package.json
  yarn.lock
Labels: :broom: p1-chore, dependencies

#2626 chore: code of conduct
  CODE_OF_CONDUCT.md
Labels: :broom: p1-chore

#2645 chore: improve issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :broom: p1-chore

#2651 Typo in plugin-legacy
  packages/plugin-legacy/index.js
Labels: bug, plugin: legacy, 🔍 review needed

#2611 chore(create-app): update svelte templates
  packages/create-app/template-svelte-ts/README.md
  packages/create-app/template-svelte-ts/package.json
  packages/create-app/template-svelte-ts/src/App.svelte
  packages/create-app/template-svelte-ts/src/global.d.ts
  packages/create-app/template-svelte-ts/src/lib/Counter.svelte
  packages/create-app/template-svelte-ts/src/lib/hmr-stores.ts
  packages/create-app/template-svelte-ts/tsconfig.json
  packages/create-app/template-svelte-ts/vite.config.js
  packages/create-app/template-svelte/README.md
  packages/create-app/template-svelte/jsconfig.json
  packages/create-app/template-svelte/package.json
  packages/create-app/template-svelte/src/App.svelte
  packages/create-app/template-svelte/src/global.d.ts
  packages/create-app/template-svelte/src/lib/Counter.svelte
  packages/create-app/template-svelte/src/lib/hmr-stores.js
  packages/create-app/template-svelte/vite.config.js
Labels: :cake: p2-nice-to-have

#2323 fix(css): using background url which match alias in sass/less, there will be link error (fix #2316)
  packages/playground/css/index.html
  packages/playground/css/nested/_index.scss
  packages/playground/css/nested/nested.less
  packages/vite/src/node/plugins/css.ts
Labels: :hammer: p3-minor-bug

#2548 fix: add a timeout to the res.sep when discovering new dependency
  packages/playground/dynamic-import/__tests__/dynamic-import.spec.ts
  packages/playground/dynamic-import/package.json
  packages/playground/dynamic-import/views/bar.js
  packages/vite/src/node/server/middlewares/transform.ts
  yarn.lock
Labels: :cake: p2-nice-to-have

#1649 feat: let `plugins` array contain falsy values
  packages/vite/src/node/config.ts
Labels: :cake: p2-nice-to-have

#2614 fix: handle paths with special characters in injectQuery (fix #2585)
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: :fire: p5-urgent

#2708 chore(create-app): Update `vue-tsc` dependency in `vue-ts` template
  packages/create-app/template-vue-ts/package.json
Labels: dependencies

#2715 chore: fix some typos
  .eslintrc.js
  packages/plugin-vue/src/index.ts
  packages/vite/src/client/client.ts
  packages/vite/src/client/env.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/registerMissing.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/middlewares/proxy.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  packages/vite/src/node/utils.ts
Labels: :broom: p1-chore, 🔍 review needed

#2730 chore: no-case-declarations
  packages/vite/src/client/client.ts
Labels: :broom: p1-chore

#2731 chore: no-irregular-whitespace
  packages/vite/src/node/cli.ts
Labels: p1-chore :broom:

#2732 chore: no-extra-boolean-cast
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p1-chore :broom:

#2703 fix(client): don't inject queries for data URLs (fixes #2658)
  packages/playground/dynamic-import/__tests__/dynamic-import.spec.ts
  packages/playground/dynamic-import/index.html
  packages/playground/dynamic-import/nested/index.js
  packages/vite/src/client/client.ts
Labels: p3-minor-bug :hammer:, 🔍 review needed

#2718 fix(resolve): fix resolver not following node resolve algorithm
  packages/playground/resolve/__tests__/resolve.spec.ts
  packages/playground/resolve/dir-with-ext.js/empty
  packages/playground/resolve/dir-with-ext/index.js
  packages/playground/resolve/exact-extension/file.js
  packages/playground/resolve/exact-extension/file.js.js
  packages/playground/resolve/index.html
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug :hammer:

#2701 fix(resolve): improve browser filed substitutions
  packages/playground/resolve/__tests__/resolve.spec.ts
  packages/playground/resolve/browser-field/multiple.dot.path.js
  packages/playground/resolve/browser-field/no-ext-index/index.js
  packages/playground/resolve/browser-field/no-ext.js
  packages/playground/resolve/browser-field/package.json
  packages/playground/resolve/browser-field/relative.js
  packages/playground/resolve/index.html
  packages/vite/src/node/plugins/resolve.ts
Labels: bug, p2-nice-to-have :cake:, 🔍 review needed

#2629 fix: invalidate module cache on unlinked
  packages/playground/file-delete-restore/App.jsx
  packages/playground/file-delete-restore/Child.jsx
  packages/playground/file-delete-restore/__tests__/file-delete-restore.spec.ts
  packages/playground/file-delete-restore/index.html
  packages/playground/file-delete-restore/package.json
  packages/playground/file-delete-restore/vite.config.js
  packages/vite/src/node/server/hmr.ts
Labels: bug, feat: hmr, p3-minor-bug :hammer:

#2765 Minor Typo
  docs/config/index.md
Labels: documentation

#2761 docs(wmr): remove future direction assumptions
  docs/guide/comparisons.md
Labels: documentation

#2675 fix(plugin-vue): allow to overwrite feature flags
  packages/plugin-vue/src/index.ts
Labels: p3-minor-bug :hammer:, plugin: vue, 🔍 review needed

#2227 refactor: preprocess type
  .eslintrc.js
  packages/vite/package.json
  packages/vite/src/node/plugins/css.ts
  yarn.lock
Labels: p1-chore :broom:

#2631 fix: assets ?url import test for windows, fix #2625
  packages/playground/assets/__tests__/assets.spec.ts
  packages/playground/testUtils.ts
Labels: bug, p1-chore :broom:, test, windows only

#2687 feat: Add `repository.directory` to `packages/**/package.json`
  packages/create-app/package.json
  packages/plugin-legacy/package.json
  packages/plugin-react-refresh/package.json
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue/package.json
  packages/vite/package.json
Labels: p1-chore :broom:, 🔍 review needed

#2690 dx: Include SSR in predefined env types
  packages/vite/types/importMeta.d.ts
Labels: enhancement, p2-nice-to-have :cake:, 🔍 review needed

#2742 feat(dev): support keepNames option for optimizeDeps config
  docs/config/index.md
  packages/vite/src/node/optimizer/index.ts
Labels: bug, p3-minor-bug :hammer:

#2340 fix: reload only once on socket reconnect
  packages/vite/src/client/client.ts
Labels: enhancement, p2-nice-to-have :cake:, 🔍 review needed

#2773 docs: add note about `import.meta.env` with TS
  docs/guide/env-and-mode.md
Labels: documentation, p1-chore :broom:

#2777 chore: Jest config in TypeScript format
  jest.config.ts
  package.json
  yarn.lock
Labels: p1-chore :broom:, test

#2772 fix(create-app): improved package name validation
  packages/create-app/index.js
Labels: p2-nice-to-have :cake:

#2780 fix: replace __dirname and __filename in config file
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#2743 docs: using plugins guide
  docs/.vitepress/config.js
  docs/config/index.md
  docs/guide/api-plugin.md
  docs/guide/using-plugins.md
  docs/plugins/index.md
Labels: documentation

#2766 fix: ignore babelrc
  packages/playground/react/package.json
  packages/plugin-react-refresh/index.js
  packages/plugin-vue-jsx/index.js
Labels: p2-nice-to-have :cake:

#2797 fix(plugin-vue): respect `hmr: false` server config
  packages/plugin-vue/src/main.ts
  packages/plugin-vue/src/template.ts
Labels: feat: hmr, p3-downstream-blocker :hammer:, plugin: vue

#2803 docs: add languages links
  docs/.vitepress/config.js
Labels: documentation

#2769 fix(static): serve .js, .jsx, .ts, .tsx as application/javascript
  packages/vite/src/node/server/middlewares/static.ts
Labels: p2-nice-to-have :cake:

#2758 feat: add async support for vite config file
  docs/config/index.md
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#2733 chore: prefer-const
  .eslintrc.js
  packages/plugin-vue/src/handleHotUpdate.ts
  packages/vite/src/client/client.ts
  packages/vite/src/node/importGlob.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/server/openBrowser.ts
Labels: p1-chore :broom:

#2801 fix: ignore babelrc in legacy plugin
  packages/plugin-legacy/index.js
Labels: bug: pending triage

#2688 chore: use eslint-define-config
  .eslintrc.js
  package.json
  yarn.lock
Labels: p1-chore :broom:

#2764 fix(define): ensure the normal use of NODE_ENV, fix #2759
  packages/vite/src/node/plugins/define.ts
Labels: bug, p2-has-workaround :cake:
