Repository vitejs/vite, pull requests merged in 2021-09, with the labels that each got.

#4813 fix(resolve): normalize optimized resolved path
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug :hammer:

#4811 chore: upgrate vitepress to fix highlight bug
  package.json
  yarn.lock
Labels: dependencies

#4699 fix: apply SSR externalization heuristic to devDependencies
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: feat: ssr

#4563 fix: hmr doesn't work when modifying the code of jsx in sfc
  packages/playground/vue-jsx/Script.vue
  packages/playground/vue-jsx/SrcImport.jsx
  packages/playground/vue-jsx/SrcImport.vue
  packages/playground/vue-jsx/__tests__/vue-jsx.spec.ts
  packages/playground/vue-jsx/main.jsx
  packages/playground/vue-jsx/package.json
  packages/playground/vue-jsx/vite.config.js
  packages/plugin-vue-jsx/index.js
  packages/plugin-vue/src/handleHotUpdate.ts
Labels: p3-minor-bug :hammer:

#4767 fix(plugin-legacy): avoid executing blank dynamic import
  packages/plugin-legacy/index.js
Labels: plugin: legacy, p3-minor-bug :hammer:

#4782 fix: handle error in numberToPos and formatError
  packages/vite/package.json
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/utils.ts
  packages/vite/types/shims.d.ts
  yarn.lock
Labels: p1-chore :broom:

#4822 chore: surface package resolution failures
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: p1-chore :broom:

#4829 docs: replace vercel-configuration.png
  docs/images/vercel-configuration.png
Labels: documentation

#4842 chore: recommend volar vscode extension
  .gitignore
  packages/create-vite/template-vue-ts/.vscode/extensions.json
  packages/create-vite/template-vue-ts/README.md
  packages/create-vite/template-vue/.vscode/extensions.json
  packages/create-vite/template-vue/README.md
Labels: p1-chore :broom:

#4843 docs: clarify env replacement gotcha
  docs/guide/env-and-mode.md
Labels: documentation

#4536 fix(plugin-legacy): skip in SSR build
  packages/plugin-legacy/index.js
Labels: feat: ssr

#4674 fix: check for Blob before creating worker URL (close #4462)
  packages/playground/worker/__tests__/worker.spec.ts
  packages/vite/src/node/plugins/worker.ts
Labels: p3-minor-bug :hammer:, feat: ssr, feat: web workers

#4872 chore: use shorthand syntax
  packages/vite/src/node/server/index.ts
Labels: p1-chore :broom:

#4617 chore: delete unused plugin hook 'watchChange'
  packages/vite/src/node/server/pluginContainer.ts
Labels: p1-chore :broom:

#4729 fix: compute getPkgName only when used
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/__tests__/packages/name/package.json
  packages/vite/src/node/__tests__/packages/noname/package.json
  packages/vite/src/node/build.ts
Labels: p3-minor-bug :hammer:

#4880 fix(css): return sourcemap in vite:css transform
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#4908 chore: give history middleware a name
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/spaFallback.ts
Labels: p1-chore :broom:

#4909 feat(ssr): exports `dynamicDeps` for ssrTransform, close #4898
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p2-nice-to-have :cake:

#4708 feat: add resolve.preserveSymlinks option
  docs/config/index.md
  packages/playground/preserve-symlinks/__tests__/preload.spec.ts
  packages/playground/preserve-symlinks/__tests__/serve.js
  packages/playground/preserve-symlinks/index.html
  packages/playground/preserve-symlinks/moduleA/package.json
  packages/playground/preserve-symlinks/moduleA/src/data.js
  packages/playground/preserve-symlinks/moduleA/src/index.js
  packages/playground/preserve-symlinks/package.json
  packages/playground/preserve-symlinks/src/main.js
  packages/playground/preserve-symlinks/vite.config.js
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:

#4555 feat(html): Inline entry chunk into html when possible
  packages/playground/html/__tests__/html.spec.ts
  packages/playground/html/inline/common.js
  packages/playground/html/inline/dep1.js
  packages/playground/html/inline/dep2.js
  packages/playground/html/inline/dep3.js
  packages/playground/html/inline/module-graph.dot
  packages/playground/html/inline/shared-1.html
  packages/playground/html/inline/shared-2.html
  packages/playground/html/inline/shared.js
  packages/playground/html/inline/unique.html
  packages/playground/html/inline/unique.js
  packages/playground/html/vite.config.js
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p2-nice-to-have :cake:

#4931 chore: format
  .github/semantic.yml
  packages/create-vite/index.js
  packages/playground/css/composes-path-resolving.module.css
  packages/playground/css/inlined.css
  packages/playground/dynamic-import/css/index.css
  packages/playground/env/index.html
  packages/playground/html/inline/common.js
  packages/playground/html/vite.config.js
  packages/playground/ssr-react/src/circular-dep-init/README.md
  packages/playground/ssr-react/src/forked-deadlock/README.md
  packages/playground/tailwind/index.css
  packages/playground/tailwind/src/App.vue
  packages/playground/tailwind/src/components/HelloWorld.vue
  packages/playground/tailwind/src/views/Page.vue
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: p1-chore :broom:

#4938 docs: authoring tips and vite-plugin-inspect
  docs/guide/api-plugin.md
  docs/images/vite-plugin-inspect.png
Labels: documentation

#4941 docs: add vite audio for pronunciation
  docs/.vitepress/theme/custom.css
  docs/guide/index.md
  docs/public/vite.mp3
  docs/public/voice.svg
Labels: documentation, p2-nice-to-have :cake:

#4864 feat: async script module support, close #3163
  packages/playground/html/__tests__/html.spec.ts
  packages/playground/html/scriptAsync.html
  packages/playground/html/scriptMixed.html
  packages/playground/html/vite.config.js
  packages/vite/src/node/plugins/html.ts
Labels: p2-nice-to-have :cake:

#4951 fix(css): revert return sourcemap in vite:css transform (#4880)
  packages/vite/src/node/plugins/css.ts
Labels: p3-minor-bug :hammer:

#4943 fix: force overlay LTR
  packages/vite/src/client/overlay.ts
Labels: p2-nice-to-have :cake:

#4955 docs: clarify assetsInclude
  docs/config/index.md
  packages/vite/src/node/config.ts
Labels: documentation

#4961 fix: use pkgId to get relative path (#4957)
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-downstream-blocker :hammer:

#4834 fix: plugin-react-refresh libraries sourcemaps
  packages/plugin-react/src/index.ts
Labels: plugin: react-refresh

#4881 fix: update *.wasm type (fix #4835)
  packages/vite/client.d.ts
Labels: p3-minor-bug :hammer:

#4889 refactor: tsconfck for esbuild compilerOptions tsconfig files
  .prettierignore
  packages/playground/testEnv.d.ts
  packages/playground/tsconfig-json-load-error/__tests__/tsconfig-json-load-error.spec.ts
  packages/playground/tsconfig-json-load-error/has-error/main.ts
  packages/playground/tsconfig-json-load-error/has-error/tsconfig.json
  packages/playground/tsconfig-json-load-error/index.html
  packages/playground/tsconfig-json-load-error/package.json
  packages/playground/tsconfig-json-load-error/src/main.ts
  packages/playground/tsconfig-json-load-error/tsconfig.json
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/plugins/esbuild.ts
  scripts/jestPerTestSetup.ts
  yarn.lock
Labels: dependencies, p2-nice-to-have :cake:

#4974 fix: docs for ssr manifest plugin and dedupe name
  docs/config/index.md
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
Labels: p1-chore :broom:

#4979 chore: vite as peer dep for plugin-vue
  packages/plugin-vue/package.json
Labels: dependencies

#4978 chore: change ci triggering
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#4987 chore: update prettierignore
  .prettierignore
Labels: p1-chore :broom:

#4986 test: SSR externals on Windows #4980
  packages/playground/ssr-vue/__tests__/ssr-vue.spec.ts
  packages/playground/ssr-vue/example-external-component/ExampleExternalComponent.vue
  packages/playground/ssr-vue/example-external-component/index.js
  packages/playground/ssr-vue/example-external-component/package.json
  packages/playground/ssr-vue/package.json
  packages/playground/ssr-vue/src/pages/External.vue
Labels: test

#4991 chore: correct async modules test cases
  packages/playground/html/scriptAsync.html
  packages/playground/html/scriptMixed.html
Labels: test

#4998 chore: fix lint warning
  packages/plugin-react/src/jsx-runtime/babel-restore-jsx.ts
Labels: p1-chore :broom:

#5001 docs: fix @vitejs/plugin-react broken link
  README.md
  docs/plugins/index.md
Labels: documentation

#4989 docs: typing env vars
  docs/guide/env-and-mode.md
Labels: documentation

#5033 chore: fix typo
  packages/vite/src/node/server/index.ts
Labels: p1-chore :broom:

#5017 fix: exclude missing dependencies from optimization during SSR
  packages/playground/optimize-missing-deps/__test__/optimize-missing-deps.spec.ts
  packages/playground/optimize-missing-deps/__test__/serve.js
  packages/playground/optimize-missing-deps/index.html
  packages/playground/optimize-missing-deps/main.js
  packages/playground/optimize-missing-deps/missing-dep/index.js
  packages/playground/optimize-missing-deps/missing-dep/package.json
  packages/playground/optimize-missing-deps/multi-entry-dep/index.browser.js
  packages/playground/optimize-missing-deps/multi-entry-dep/index.js
  packages/playground/optimize-missing-deps/multi-entry-dep/package.json
  packages/playground/optimize-missing-deps/package.json
  packages/playground/optimize-missing-deps/server.js
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/plugins/resolve.ts
  yarn.lock
Labels: feat: ssr

#4867 fix: exclude ?commonjs-external when building in JSON plugin
  packages/vite/src/node/plugins/json.ts
Labels: p3-minor-bug :hammer:, needs test

#5037 feat: pre transform direct imports before requests hit the server
  .github/workflows/ci.yml
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/error.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p4-important :exclamation:

#5041 feat: default build.minify to esbuild
  packages/vite/package.json
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/esbuild.ts
  yarn.lock
Labels: p4-important :exclamation:

#5052 chore: fix eslint invalid ecmaVersion value
  .eslintrc.js
Labels: bug, p1-chore :broom:

#4958 feat: expose `searchForWorkspaceRoot` util
  packages/vite/src/node/index.ts
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:

#5000 fix: injected tags indentation
  packages/vite/src/node/plugins/html.ts
Labels: p3-minor-bug :hammer:

#5067 fix(types): missing return type on `logError`
  packages/vite/src/node/server/middlewares/error.ts
Labels: p1-chore :broom:

#5065 fix: normalize away `base` in imported URLs
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p3-minor-bug :hammer:

#5024 feat(plugin-legacy): add externalSystemJS option
  packages/plugin-legacy/README.md
  packages/plugin-legacy/index.d.ts
  packages/plugin-legacy/index.js
Labels: plugin: legacy, p2-nice-to-have :cake:

#4999 fix: avoid module preload polyfill for zero js html
  packages/playground/html/__tests__/html.spec.ts
  packages/playground/html/vite.config.js
  packages/playground/html/zeroJS.html
  packages/vite/src/node/plugins/html.ts
Labels: p3-downstream-blocker :hammer:

#5014 feat: expose `preview` method
  packages/vite/src/node/index.ts
  packages/vite/src/node/preview.ts
Labels: p2-nice-to-have :cake:

#4928 docs: update env-and-mode.md to fix default modes
  docs/guide/env-and-mode.md
Labels: documentation

#5012 feat(create-vite): migrate lit-element to lit
  docs/guide/index.md
  packages/create-vite/README.md
  packages/create-vite/index.js
  packages/create-vite/template-lit-ts/_gitignore
  packages/create-vite/template-lit-ts/index.html
  packages/create-vite/template-lit-ts/package.json
  packages/create-vite/template-lit-ts/src/favicon.svg
  packages/create-vite/template-lit-ts/src/my-element.ts
  packages/create-vite/template-lit-ts/src/vite-env.d.ts
  packages/create-vite/template-lit-ts/tsconfig.json
  packages/create-vite/template-lit-ts/vite.config.ts
  packages/create-vite/template-lit/_gitignore
  packages/create-vite/template-lit/index.html
  packages/create-vite/template-lit/package.json
  packages/create-vite/template-lit/src/favicon.svg
  packages/create-vite/template-lit/src/my-element.js
  packages/create-vite/template-lit/vite.config.js
  packages/playground/ssr-vue/example-external-component/ExampleExternalComponent.vue
Labels: p2-nice-to-have :cake:

#5059 fix: server.address before listen, chdir in test, basic cli test
  packages/playground/cli/__tests__/cli.spec.ts
  packages/playground/cli/__tests__/serve.js
  packages/playground/cli/index.html
  packages/playground/cli/index.js
  packages/playground/cli/package.json
  packages/playground/cli/vite.config.js
  packages/playground/css/postcss-caching/css.spec.ts
  packages/playground/testUtils.ts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/logger.ts
  pnpm-lock.yaml
Labels: test

#5115 docs: fix code block display exception
  docs/config/index.md
Labels: documentation, p1-chore :broom:

#5113 fix: use global location for import.meta.url rewrite (fix #5087)
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
Labels: p3-minor-bug :hammer:, feat: web workers

#5121 chore: prettier format
  packages/playground/ssr-vue/__tests__/ssr-vue.spec.ts
  packages/playground/ssr-vue/example-external-component/ExampleExternalComponent.vue
  packages/plugin-legacy/index.js
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
Labels: p1-chore :broom:

#4932 chore(deps): upgrade typescript to 4.4
  package.json
  packages/vite/tsconfig.base.json
  pnpm-lock.yaml
Labels: dependencies

#5123 docs: fix typo in comment
  packages/vite/src/node/preview.ts
Labels: p1-chore :broom:

#5149 fix: properly handle postfix for getRealPath
  packages/vite/src/node/plugins/resolve.ts
Labels: p4-important :exclamation:
