Repository vitejs/vite, pull requests merged in 2021-10, with the labels that each got.

#5163 docs: clarify that `server.hmr.server` works with HTTP too
  docs/config/index.md
Labels: documentation

#5170 chore(deps): update eslint-define-config to v1.1.1
  package.json
  pnpm-lock.yaml
Labels: dependencies

#5177 fix(dev): read property of undefined
  packages/vite/src/node/logger.ts
Labels: p3-minor-bug :hammer:

#5192 fix: better error message for parse failures
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p2-nice-to-have :cake:

#5480 chore(deps): update jest
  package.json
  packages/vite/LICENSE.md
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#5468 chore(deps): update vite dependencies
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#5491 docs: add note about glob imports
  docs/guide/features.md
Labels: documentation
