Repository vitejs/vite, pull requests merged in 2021-11, with the labels that each got.

#5505 docs: virtual modules ID naming convention
  docs/guide/api-plugin.md
Labels: documentation

#5391 fix(server): use `options` argument in caching of `transformRequest` calls
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p5-urgent :fire:

#5418 fix(plugin-vue): template src isn't working when script setup
  packages/playground/vue/Main.vue
  packages/playground/vue/__tests__/vue.spec.ts
  packages/playground/vue/setup-import-template/SetupImportTemplate.vue
  packages/playground/vue/setup-import-template/template.html
  packages/plugin-vue/src/main.ts
  packages/plugin-vue/src/script.ts
Labels: p3-minor-bug :hammer:

#5510 feat: importing ts files using their corresponding js extesions
  packages/playground/resolve/__tests__/resolve.spec.ts
  packages/playground/resolve/index.html
  packages/playground/resolve/ts-extension/hello.ts
  packages/playground/resolve/ts-extension/index.ts
  packages/playground/resolve/vite.config.js
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:

#5482 docs: Update static deploy docs for firebase
  docs/guide/static-deploy.md
Labels: documentation

#5538 fix(esbuild): respect esbuild config on build
  packages/vite/src/node/plugins/esbuild.ts
Labels: p3-downstream-blocker :hammer:

#5569 chore(deps): update non critical deps
  package.json
  packages/playground/alias/package.json
  packages/playground/css/package.json
  packages/playground/extensions/package.json
  packages/playground/file-delete-restore/package.json
  packages/playground/json/package.json
  packages/playground/optimize-deps/dep-linked-include/package.json
  packages/playground/optimize-deps/package.json
  packages/playground/preload/package.json
  packages/playground/react-emotion/package.json
  packages/playground/react/package.json
  packages/playground/resolve/package.json
  packages/playground/ssr-react/package.json
  packages/playground/ssr-vue/package.json
  packages/playground/tailwind/package.json
  packages/playground/vue-jsx/package.json
  packages/playground/vue/package.json
  packages/plugin-legacy/package.json
  packages/plugin-react/package.json
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue/package.json
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies

#5514 feat: preview config
  docs/config/index.md
  docs/guide/api-javascript.md
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/http.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/logger.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:

#5574 chore(deps): massive major deps update
  .github/renovate.json5
  docs/config/index.md
  docs/guide/migration.md
  package.json
  packages/playground/backend-integration/package.json
  packages/playground/css/package.json
  packages/playground/file-delete-restore/package.json
  packages/playground/optimize-deps/dep-linked/package.json
  packages/playground/optimize-deps/package.json
  packages/playground/react-emotion/package.json
  packages/playground/react/package.json
  packages/playground/ssr-pug/package.json
  packages/playground/ssr-react/package.json
  packages/playground/ssr-webworker/package.json
  packages/playground/tailwind/package.json
  packages/playground/testEnv.d.ts
  packages/playground/vue/CustomBlockPlugin.ts
  packages/playground/vue/package.json
  packages/plugin-vue/README.md
  packages/plugin-vue/package.json
  packages/plugin-vue/src/main.ts
  packages/plugin-vue/src/script.ts
  packages/vite/package.json
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/http.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/logger.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/ws.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/ssr/ssrStacktrace.ts
  packages/vite/types/commonjs.d.ts
  pnpm-lock.yaml
  scripts/jestPerTestSetup.ts
Labels: dependencies, p1-chore :broom:

#5540 chore(deps): update dependency ws to v8
  packages/vite/package.json
  packages/vite/src/node/server/ws.ts
  pnpm-lock.yaml
Labels: dependencies

#5571 fix: replace server.origin in css plugin (fix #5408)
  packages/playground/tailwind/vite.config.ts
  packages/vite/src/node/plugins/css.ts
Labels: p3-minor-bug :hammer:

#5578 fix: Incompatible type in ImportMetaEnv interface
  docs/guide/env-and-mode.md
Labels: documentation

#5536 fix(hmr): revert early break from handleHotUpdate loop
  packages/vite/src/node/server/hmr.ts
Labels: feat: hmr, p3-downstream-blocker :hammer:

#5544 refactor: simplify `resolveSSRExternal`
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: feat: ssr

#5483 docs: dev and serve aliases
  docs/config/index.md
  docs/guide/api-javascript.md
  docs/guide/api-plugin.md
  docs/guide/index.md
  docs/guide/static-deploy.md
Labels: documentation, p1-chore :broom:

#5520 fix(server): watch correct env files
  packages/vite/src/node/server/hmr.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#5374 fix(plugin-vue): use __vccOpts for vue-class-component
  packages/plugin-vue/src/helper.ts
Labels: plugin: vue

#5255 fix(plugin-react): apply `babel.plugins` to project files only
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/jsx-runtime/restore-jsx.ts
Labels: p4-important :exclamation:, plugin: react

#5464 fix: handle local and module scripts separately
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
Labels: p3-downstream-blocker :hammer:

#5465 feat: support `moduleInfo.meta` in dev server
  packages/vite/src/node/index.ts
  packages/vite/src/node/server/__tests__/pluginContainer.spec.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/moduleGraph.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: p3-downstream-blocker :hammer:

#5609 docs: add build.ssr in config/index.md
  docs/config/index.md
Labels: documentation

#3951 fix(ssr): use `tryNodeResolve` instead of `resolveFrom`
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/ssrRequireHook.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-minor-bug :hammer:, needs test

#5512 fix: check exactly in proxyESM
  packages/playground/ssr-vue/__tests__/ssr-vue.spec.ts
  packages/playground/ssr-vue/package.json
  packages/playground/ssr-vue/src/pages/Store.vue
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  pnpm-lock.yaml
Labels: p4-important :exclamation:, feat: ssr, possible regression

#5648 fix(logger): no sameCount if clearScreen is false
  packages/vite/src/node/logger.ts
Labels: p2-nice-to-have :cake:

#5664 fix: tolerate undefined parent in `hookNodeResolve` callback
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p5-urgent :fire:

#5665 fix(resolve): check nested directories for package.json
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug :hammer:

#5669 fix(plugin-react): uncompiled JSX in linked pkgs
  packages/plugin-react/src/index.ts
Labels: p5-urgent :fire:, plugin: react

#5662 fix(ssr): prefer CJS but still allow ESM entries
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p5-urgent :fire:

#5674 fix(dev): Fix infinite recursion on query imports (#5671)
  packages/playground/worker/__tests__/worker.spec.ts
  packages/playground/worker/index.html
  packages/playground/worker/possible-ts-output-worker.mjs
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:, possible regression

#5677 test: ssr-vue example error when routerChanged
  packages/playground/ssr-vue/__tests__/ssr-vue.spec.ts
  packages/playground/ssr-vue/src/pages/About.vue
Labels: p1-chore :broom:, test

#5693 fix(ssr): avoid resolving ESM for CJS dependencies
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p5-urgent :fire:, feat: ssr

#5700 chore: Remove incorrect documentation
  packages/vite/src/node/server/index.ts
Labels: documentation, p1-chore :broom:

#5718 chore: format and fix typo
  packages/playground/ssr-vue/__tests__/ssr-vue.spec.ts
  packages/playground/tailwind/vite.config.ts
  packages/plugin-react/src/index.ts
  packages/plugin-vue/src/index.ts
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/css.ts
Labels: p1-chore :broom:

#5739 docs: add tip Note for build.cssCodeSplit
  docs/config/index.md
Labels: documentation, p1-chore :broom:

#5734 refactor: simplify array handling
  packages/plugin-vue/src/template.ts
  packages/vite/src/client/client.ts
Labels: p1-chore :broom:

#5735 chore: correct config transpile comment
  packages/vite/src/node/config.ts
Labels: p1-chore :broom:

#5388 fix: move package.json cache into ResolvedConfig
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/packages.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/index.ts
Labels: p4-important :exclamation:

#5377 fix(hmr): prevent SSR from setting `isSelfAccepting` to false
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: feat: hmr, p4-important :exclamation:

#5723 feat(dev): expose restart function on ViteDevServer
  docs/guide/api-javascript.md
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:

#5748 refactor: remove unused const
  packages/vite/src/client/client.ts
Labels: p1-chore :broom:

#5745 fix(transformCjsImport): make dev and build get the same result
  packages/vite/src/node/__tests__/plugins/import.spec.ts
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p3-minor-bug :hammer:

#5758 chore: remove invalid condition
  packages/plugin-vue/src/main.ts
Labels: plugin: vue

#5697 chore: fix typo
  docs/guide/features.md
  packages/vite/CHANGELOG.md
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p1-chore :broom:

#5761 fix(plugin-react): restore usage of extension instead of id
  packages/plugin-react/src/index.ts
Labels: needs test, plugin: react

#5760 fix(plugin-react): remove querystring from sourcemap filename
  packages/plugin-react/src/index.ts
Labels: plugin: react

#5730 fix: scoped variable with array destructuring & nested arguments
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: bug, feat: ssr

#5773 docs: fix pnpm link usage
  docs/guide/index.md
Labels: documentation

#5772 chore: delete useless condition
  packages/vite/src/node/config.ts
Labels: p1-chore :broom:

#5778 chore: optimize esm flag
  packages/vite/src/node/config.ts
Labels: p1-chore :broom:

#5729 fix: Replace asset references in CSS returned to JS
  packages/playground/css/__tests__/css.spec.ts
  packages/playground/css/inlined.css
  packages/playground/css/ok.png
  packages/vite/src/node/plugins/asset.ts
Labels: feat: css, p3-minor-bug :hammer:

#5785 fix: unminified build breaks __vitePreload
  packages/playground/preload/__tests__/preload.spec.ts
  packages/playground/preload/router.js
  packages/playground/preload/src/components/Hello.vue
  packages/playground/preload/src/components/Home.vue
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-minor-bug :hammer:

#5797 fix: packageManager config set error
  package.json
Labels: p4-important :exclamation:

#5809 fix: resolve addons using nodeResolve()
  packages/playground/ssr-vue/__tests__/ssr-vue.spec.ts
  packages/playground/ssr-vue/package.json
  packages/playground/ssr-vue/src/pages/Home.vue
  packages/playground/ssr-vue/vite.config.js
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, feat: ssr

#5816 fix: throw full error causing preprocessor to not load
  packages/vite/src/node/plugins/css.ts
Labels: feat: css

#5823 fix: unicode path html entry point (#5821)
  packages/playground/html/__tests__/html.spec.ts
  packages/playground/html/unicode-path/中文-にほんご-한글-🌕🌖🌗/index.html
  packages/playground/html/vite.config.js
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/middlewares/spaFallback.ts
Labels: feat: html, p3-minor-bug :hammer:

#4589 fix: circular dependency hmr causes refresh crash
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: feat: hmr

#5838 feat: lint for missing type="module" attribute (#5837)
  packages/vite/src/node/plugins/html.ts
Labels: p2-nice-to-have :cake:

#5846 fix: build pluginContext types error
  packages/vite/src/node/server/pluginContainer.ts
Labels: p3-minor-bug :hammer:

#5827 fix: `isBuiltin` using patched native `builtinModules`
  packages/vite/package.json
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, feat: ssr

#5870 fix(plugin-vue): misleading error thrown after refresh or hmr
  packages/plugin-vue/src/utils/error.ts
Labels: feat: hmr, plugin: vue

#5869 chore: format & check with prettier
  .github/workflows/ci.yml
  docs/config/index.md
  docs/guide/api-plugin.md
  packages/playground/html/unicode-path/中文-にほんご-한글-🌕🌖🌗/index.html
  packages/playground/resolve/config-dep.js
  packages/playground/resolve/vite.config.js
  packages/playground/ssr-vue/src/pages/Home.vue
  packages/plugin-vue/src/main.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
Labels: p1-chore :broom:

#5807 ci: add release tag action [ci skip]
  .github/workflows/release-tag.yml
Labels: p2-nice-to-have :cake:

#5872 fix(resolve): dont overwrite `isRequire` from `baseOptions`
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug :hammer:, needs test

#5877 chore: use cjs extension with scripts
  .eslintrc.cjs
  CONTRIBUTING.md
  jest.config.ts
  package.json
  packages/create-app/package.json
  packages/create-vite/package.json
  packages/playground/alias/package.json
  packages/playground/optimize-deps/package.json
  packages/playground/optimize-missing-deps/package.json
  packages/plugin-legacy/package.json
  packages/plugin-react/package.json
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue/package.json
  packages/vite/package.json
  packages/vite/scripts/patchTypes.cjs
  scripts/jestEnv.cjs
  scripts/jestGlobalSetup.cjs
  scripts/jestGlobalTeardown.cjs
  scripts/patchFileDeps.cjs
  scripts/release.cjs
  scripts/verifyCommit.cjs
Labels: p1-chore :broom:

#5909 docs: fix gitlab pages deploy syntax
  docs/guide/static-deploy.md
Labels: documentation, p1-chore :broom:

#5905 docs: add optimizeDeps.esbuildOptions & remove optimizeDeps.keepNames [ci skip]
  docs/config/index.md
Labels: documentation
