Repository vitejs/vite, pull requests merged in 2021-12, with the labels that each got.

#5917 chore: deprecated substr
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/asset.ts
Labels: p1-chore :broom:

#5850 fix(scan): handle local scripts with lang=ts
  packages/playground/vue/__tests__/vue.spec.ts
  packages/vite/src/node/optimizer/scan.ts
  scripts/jestPerTestSetup.ts
Labels: p3-minor-bug :hammer:

#5930 chore: deprecate `rollupOptions.output.output` to avoid subtle errors
  packages/vite/src/node/build.ts
Labels: p1-chore :broom:

#5928 fix(ssr): skip dedupe require if noExternal true
  packages/playground/ssr-webworker/vite.config.js
  packages/vite/src/node/plugins/ssrRequireHook.ts
Labels: p3-minor-bug :hammer:

#5926 docs: fix ssr note and change jsonc to json5 [ci skip]
  docs/guide/index.md
  docs/guide/ssr.md
Labels: documentation

#5881 test: refactor test for SSR dependencies
  packages/playground/ssr-deps/__tests__/serve.js
  packages/playground/ssr-deps/__tests__/ssr-deps.spec.ts
  packages/playground/ssr-deps/index.html
  packages/playground/ssr-deps/message
  packages/playground/ssr-deps/node-addon/README.md
  packages/playground/ssr-deps/node-addon/binding.gyp
  packages/playground/ssr-deps/node-addon/index.js
  packages/playground/ssr-deps/node-addon/main.cpp
  packages/playground/ssr-deps/node-addon/package.json
  packages/playground/ssr-deps/package.json
  packages/playground/ssr-deps/read-file-content/index.js
  packages/playground/ssr-deps/read-file-content/package.json
  packages/playground/ssr-deps/server.js
  packages/playground/ssr-deps/src/app.js
  packages/playground/ssr-deps/vite.config.js
  packages/playground/ssr-vue/__tests__/ssr-vue.spec.ts
  packages/playground/ssr-vue/package.json
  packages/playground/ssr-vue/prerender.js
  packages/playground/ssr-vue/server.js
  packages/playground/ssr-vue/src/entry-server.js
  packages/playground/ssr-vue/src/message
  packages/playground/ssr-vue/src/pages/Home.vue
  packages/playground/ssr-vue/vite.config.js
  pnpm-lock.yaml
Labels: p1-chore :broom:, feat: ssr, test

#5891 fix: invalidate inlined proxy scripts on change
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: p3-minor-bug :hammer:

#5927 fix: read the correct package.json in ssrExternal
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: p4-important :exclamation:, feat: ssr

#5923 fix: SSR import in dev can't resolve default import (fix #5706)
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: feat: ssr

#5951 chore: git ignores the compilation output dir
  .gitignore
  packages/playground/ssr-deps/node-addon/build/Makefile
  packages/playground/ssr-deps/node-addon/build/Release/.deps/Release/cpp_addon.node.d
  packages/playground/ssr-deps/node-addon/build/Release/.deps/Release/obj.target/cpp_addon.node.d
  packages/playground/ssr-deps/node-addon/build/Release/.deps/Release/obj.target/cpp_addon/main.o.d
  packages/playground/ssr-deps/node-addon/build/Release/cpp_addon.node
  packages/playground/ssr-deps/node-addon/build/Release/obj.target/cpp_addon.node
  packages/playground/ssr-deps/node-addon/build/Release/obj.target/cpp_addon/main.o
  packages/playground/ssr-deps/node-addon/build/binding.Makefile
  packages/playground/ssr-deps/node-addon/build/config.gypi
  packages/playground/ssr-deps/node-addon/build/cpp_addon.target.mk
Labels: p1-chore :broom:

#5984 docs(ssr): fix tip Note block render
  docs/guide/ssr.md
Labels: documentation

#5994 fix(plugin-vue): multiple vue files using the same src file (fix #5925, #5447)
  packages/playground/vue/src-import/SrcImport.vue
  packages/playground/vue/src-import/script.ts
  packages/playground/vue/src-import/srcImportStyle.vue
  packages/playground/vue/src-import/srcImportStyle2.vue
  packages/playground/vue/src-import/style2.css
  packages/playground/vue/src-import/template.html
  packages/plugin-vue/src/index.ts
  packages/plugin-vue/src/main.ts
  packages/plugin-vue/src/utils/descriptorCache.ts
  packages/plugin-vue/src/utils/query.ts
Labels: plugin: vue, p3-minor-bug :hammer:

#6019 chore: use node tsconfig in all src/node builds
  packages/vite/rollup.config.js
Labels: p5-urgent :fire:

#6036 test: use `bcrypt` instead of `node-addon`
  .gitignore
  packages/playground/ssr-deps/__tests__/ssr-deps.spec.ts
  packages/playground/ssr-deps/node-addon/README.md
  packages/playground/ssr-deps/node-addon/binding.gyp
  packages/playground/ssr-deps/node-addon/index.js
  packages/playground/ssr-deps/node-addon/main.cpp
  packages/playground/ssr-deps/node-addon/package.json
  packages/playground/ssr-deps/package.json
  packages/playground/ssr-deps/src/app.js
  packages/playground/ssr-deps/vite.config.js
  pnpm-lock.yaml
Labels: p1-chore :broom:, test

#6057 fix(html): empty script
  packages/playground/html/index.html
  packages/vite/src/node/plugins/html.ts
Labels: feat: html

#6072 fix: overwrite plugin-vue define with user define option
  packages/plugin-vue-jsx/index.js
  packages/plugin-vue/src/index.ts
Labels: plugin: vue-jsx, plugin: vue

#6047 fix(plugin-react): ignore babel config when running babel-restore-jsx (fixes #5082)
  packages/plugin-react/src/jsx-runtime/restore-jsx.ts
Labels: p5-urgent :fire:, plugin: react

#6084 docs: improve instructions for testing local changes against other packages
  CONTRIBUTING.md
Labels: documentation

#6053 fix(ssr): robust regexp to check cjs content
  packages/playground/ssr-deps/__tests__/ssr-deps.spec.ts
  packages/playground/ssr-deps/define-properties-exports/index.js
  packages/playground/ssr-deps/define-properties-exports/package.json
  packages/playground/ssr-deps/define-property-exports/index.js
  packages/playground/ssr-deps/define-property-exports/package.json
  packages/playground/ssr-deps/only-object-assigned-exports/index.js
  packages/playground/ssr-deps/only-object-assigned-exports/package.json
  packages/playground/ssr-deps/package.json
  packages/playground/ssr-deps/src/app.js
  packages/playground/ssr-deps/vite.config.js
  packages/vite/src/node/ssr/ssrExternal.ts
  pnpm-lock.yaml
Labels: feat: ssr

#6025 fix: do not overwrite rollupOptions.input in dev
  packages/vite/src/node/__tests__/dev.spec.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#6106 fix(plugin-vue): error.length is zero
  packages/plugin-vue/src/utils/descriptorCache.ts
Labels: p4-important :exclamation:

#6113 fix: Improve post-build asset update check
  packages/playground/html/emptyAttr.html
  packages/playground/html/link.html
  packages/playground/html/vite.config.js
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p3-downstream-blocker :hammer:

#6119 refactor: simplify filter callback
  packages/vite/src/node/build.ts
Labels: p1-chore :broom:

#6086 fix: improve warning message for malformed packages
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: p1-chore :broom:

#6120 fix: pending reload never timeout
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p3-minor-bug :hammer:

#6144 refactor: rename `mergeConfig` parameters
  packages/vite/src/node/config.ts
Labels: p1-chore :broom:

#6110 fix(plugin-react): restore-jsx bug when component name is lowercase
  packages/plugin-react/src/jsx-runtime/babel-restore-jsx.spec.ts
  packages/plugin-react/src/jsx-runtime/babel-restore-jsx.ts
Labels: p3-minor-bug :hammer:, plugin: react

#6160 chore: convert scripts to TS
  CONTRIBUTING.md
  package.json
  packages/create-vite/package.json
  packages/create-vite/updateVersions.ts
  packages/playground/alias/package.json
  packages/playground/optimize-deps/package.json
  packages/playground/optimize-missing-deps/package.json
  packages/playground/ssr-deps/package.json
  packages/plugin-legacy/package.json
  packages/plugin-react/package.json
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue/package.json
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/scripts/patchTypes.cjs
  packages/vite/scripts/patchTypes.ts
  pnpm-lock.yaml
  scripts/patchFileDeps.ts
  scripts/release.ts
  scripts/verifyCommit.ts
Labels: p1-chore :broom:

#6171 fix(ssr): ssrTransfrom function argument destructure
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug :hammer:

#6177 docs: update node version note
  docs/guide/index.md
  package.json
  packages/create-vite/README.md
Labels: documentation, p1-chore :broom:

#5777 fix: improve error message for HTML compilation error (fix #5769)
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p2-nice-to-have :cake:

#5873 fix: duplicate variable declaration caused by css modules
  packages/vite/src/node/plugins/css.ts
Labels: feat: css

#6153 docs(config): note for TS + define [ci skip]
  docs/config/index.md
Labels: documentation

#6212 fix: hmr full-reload encodeURI path
  packages/playground/hmr/__tests__/hmr.spec.ts
  packages/playground/hmr/unicode-path/中文-にほんご-한글-🌕🌖🌗/index.html
  packages/vite/src/client/client.ts
Labels: feat: hmr

#6224 fix(ssr): handle object destructure alias, close #6222
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: feat: ssr

#6225 fix: remove virtual module prefix while generating manifest
  packages/playground/legacy/__tests__/legacy.spec.ts
  packages/playground/legacy/vite.config.js
  packages/vite/src/node/plugins/manifest.ts
Labels: plugin: legacy

#6249 fix(ssr): nested destucture
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: feat: ssr

#6252 fix: update the vue version in the error message
  packages/plugin-vue/src/compiler.ts
Labels: plugin: vue

#6260 docs: typescript tips for using Type-Only Imports and Export
  docs/guide/features.md
Labels: documentation

#6184 fix(html): Show error overlay when parsing invalid file
  .prettierignore
  packages/playground/html/__tests__/html.spec.ts
  packages/playground/html/invalid.html
  packages/vite/src/client/client.ts
  packages/vite/src/node/server/middlewares/error.ts
Labels: feat: html, p3-minor-bug :hammer:

#6263 chore: update bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: p1-chore :broom:

#6209 fix: upgrade to launch-editor with picocolors
  packages/vite/LICENSE.md
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#6251 fix: seperate source and dep for dymamic import after build
  packages/vite/src/node/build.ts
Labels: p2-nice-to-have :cake:

#6247 chore: add more gitignore.
  packages/create-vite/template-lit-ts/_gitignore
  packages/create-vite/template-lit/_gitignore
  packages/create-vite/template-preact-ts/_gitignore
  packages/create-vite/template-preact/_gitignore
  packages/create-vite/template-react-ts/_gitignore
  packages/create-vite/template-react/_gitignore
  packages/create-vite/template-svelte-ts/_gitignore
  packages/create-vite/template-svelte/_gitignore
  packages/create-vite/template-vanilla-ts/_gitignore
  packages/create-vite/template-vanilla/_gitignore
  packages/create-vite/template-vue-ts/_gitignore
  packages/create-vite/template-vue/_gitignore
Labels: p2-nice-to-have :cake:

#6275 chore: remove acorn plugins
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/types/shims.d.ts
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#6281 fix(ssr): capture scope declaration correctly
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug :hammer:

#6277 fix: replace chalk with picocolors
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/rollup.config.js
  packages/vite/scripts/patchTypes.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/logger.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/registerMissing.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/esbuild.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/reporter.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/error.ts
  packages/vite/src/node/server/middlewares/proxy.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/openBrowser.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/server/ws.ts
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#6248 fix: upgrade postcss-modules
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/rollup.config.js
  pnpm-lock.yaml
Labels: dependencies

#5515 feat(define): prevent assignment
  packages/playground/define/index.html
  packages/playground/define/vite.config.js
  packages/vite/src/node/plugins/define.ts
Labels: p3-minor-bug :hammer:

#5545 feat: import.meta.glob support ?raw
  packages/playground/glob-import/__tests__/glob-import.spec.ts
  packages/playground/glob-import/index.html
  packages/vite/package.json
  packages/vite/src/node/importGlob.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#6272 fix: don't force terser on non-legacy (fix #6266)
  packages/playground/legacy/__tests__/legacy.spec.ts
  packages/plugin-legacy/index.js
  packages/plugin-legacy/package.json
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/terser.ts
Labels: plugin: legacy

#6297 chore(deps): update to typescript 4.5.4
  package.json
  packages/create-vite/template-lit-ts/package.json
  packages/create-vite/template-preact-ts/package.json
  packages/create-vite/template-react-ts/package.json
  packages/create-vite/template-svelte-ts/package.json
  packages/create-vite/template-vanilla-ts/package.json
  packages/create-vite/template-vue-ts/package.json
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#5861 chore(deps): update to esbuild 0.14.3
  docs/guide/features.md
  package.json
  packages/playground/tsconfig-json/__tests__/tsconfig-json.spec.ts
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/plugins/esbuild.ts
  pnpm-lock.yaml
Labels: dependencies, p2-nice-to-have :cake:, on hold

#6293 feat: catch postcss error messages
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:

#6306 fix(ssr): move `vite:ssr-require-hook` after user plugins
  packages/vite/src/node/plugins/index.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#6216 fix: correct ssr flag in resolve calls (fix #6213)
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/__tests__/pluginContainer.spec.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/moduleGraph.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: feat: ssr

#6314 docs(lib-mode): add a caveat to the build.minify docs for 'es' format
  docs/config/index.md
Labels: documentation

#6310 fix: use `hires: true` for SSR require hook source map
  packages/vite/src/node/plugins/ssrRequireHook.ts
Labels: feat: ssr

#6309 feat: option to disable pre-transform
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:, YAO

#6319 docs: fix preTransformRequests typo
  packages/vite/src/node/server/index.ts
Labels: documentation, p1-chore :broom:

#5580 feat(server): support headers configurable
  packages/playground/cli/vite.config.js
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/http.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/send.ts
Labels: p2-nice-to-have :cake:, YAO

#6313 fix: this._implicitHeader is not a function
  packages/vite/src/node/http.ts
Labels: p2-nice-to-have :cake:

#6321 fix(css): no emit assets in html style tag (fix #5968)
  packages/playground/assets/css/import.css
  packages/playground/assets/index.html
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#6312 chore: replace mime with mrmime
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/plugins/asset.ts
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#6325 chore: use forge partially to generate certificates
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/certificate.ts
  packages/vite/src/node/http.ts
  pnpm-lock.yaml
Labels: p1-chore :broom:

#6304 docs(env-and-mode): add override rule for the env
  docs/guide/env-and-mode.md
Labels: documentation

#6342 chore: replace chalk with picocolors
  package.json
  pnpm-lock.yaml
  scripts/release.ts
  scripts/verifyCommit.ts
Labels: dependencies, p1-chore :broom:

#6308 fix: prevent dev server crashing on malformed URI (fix #6300)
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p2-nice-to-have :cake:
