Repository vitejs/vite, pull requests merged in 2021-06, with the labels that each got.

#3591 fix(plugin-vue): rewrite default after ts compiled
  packages/playground/vue/CustomBlock.vue
  packages/plugin-vue/package.json
  packages/plugin-vue/src/main.ts
Labels: p3-minor-bug :hammer:

#3556 feat(ssr): include non-CSS assets in the manifest
  packages/playground/ssr-vue/src/App.vue
  packages/playground/ssr-vue/src/assets/fonts/Inter-Italic.woff
  packages/playground/ssr-vue/src/assets/fonts/Inter-Italic.woff2
  packages/playground/ssr-vue/src/entry-server.js
  packages/playground/ssr-vue/src/pages/Home.vue
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
Labels: p2-nice-to-have :cake:

#3618 fix(types): add '*?.sharedworker' typing
  docs/guide/assets.md
  packages/vite/client.d.ts
Labels: p3-minor-bug :hammer:

#3672 docs: fix build.assetsInlineLimit note for lib mode, fix #3643
  docs/config/index.md
Labels: documentation, p1-chore :broom:

#3656 fix: Include src files in vite npm bundle (for sourcemaps)
  packages/vite/.npmignore
  packages/vite/package.json
Labels: p4-important :exclamation:

#3680 fix: update `sirv` to decode url in preview
  package.json
  packages/vite/package.json
  yarn.lock
Labels: bug, p3-minor-bug :hammer:

#3557 chore(deps): update typescript to v4.3
  package.json
  packages/create-app/template-lit-element-ts/package.json
  packages/create-app/template-preact-ts/package.json
  packages/create-app/template-react-ts/package.json
  packages/create-app/template-svelte-ts/package.json
  packages/create-app/template-vanilla-ts/package.json
  packages/create-app/template-vue-ts/package.json
  packages/plugin-vue/tsconfig.json
  packages/vite/src/node/plugins/css.ts
  packages/vite/tsconfig.base.json
  yarn.lock
Labels: dependencies, p1-chore :broom:

#3694 chore: `files` instead of `.npmignore` for better readability
  packages/vite/.npmignore
  packages/vite/package.json
Labels: p1-chore :broom:

#3707 feat(css): support postcss dir-dependency message type
  packages/playground/css/__tests__/css.spec.ts
  packages/playground/css/glob-dep.css
  packages/playground/css/glob-dep/bar.css
  packages/playground/css/glob-dep/foo.css
  packages/playground/css/index.html
  packages/playground/css/main.js
  packages/playground/css/postcss.config.js
  packages/vite/package.json
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/server/hmr.ts
  yarn.lock
Labels: feat: css, p2-nice-to-have :cake:

#3718 fix: upgrade esbuild for esm compatibility
  packages/vite/package.json
  yarn.lock
Labels: dependencies

#3703 fix: don't replace `process.env` if `process` not global variable
  packages/playground/define/__tests__/define.spec.ts
  packages/playground/define/index.html
  packages/playground/define/vite.config.js
  packages/vite/src/node/plugins/define.ts
Labels: p3-minor-bug :hammer:

#3724 refactor: clean Windows recognition
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/utils.ts
Labels: p1-chore :broom:

#3684 feat: allow 'hidden' sourcemap to remove //# sourceMappingURL from generated maps
  docs/config/index.md
  packages/vite/src/node/build.ts
Labels: p2-nice-to-have :cake:

#3769 fix(create-app): improve prompt message
  packages/create-app/__tests__/cli.spec.ts
  packages/create-app/index.js
Labels: p3-minor-bug :hammer:

#3752 fix(css): #3729 filter out function name suffixes with url
  packages/vite/src/node/__tests__/plugins/css.spec.ts
  packages/vite/src/node/plugins/css.ts
Labels: p3-minor-bug :hammer:

#3805 fix: ?import with trailing = added by some servers
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#3747 fix(css): file or contents missing error in build watch (#3742)
  packages/playground/assets/__tests__/assets.spec.ts
  packages/playground/assets/vite.config.js
  packages/playground/testEnv.d.ts
  packages/playground/testUtils.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  scripts/jestPerTestSetup.ts
Labels: feat: css, p3-minor-bug :hammer:

#3889 fix(scan): 'for await' support in script setup for dev server
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug :hammer:

#3926 fix: multiple css url separation (fix #3922)
  packages/playground/css/__tests__/css.spec.ts
  packages/playground/css/imported.css
  packages/playground/css/index.html
  packages/vite/src/node/plugins/css.ts
Labels: p3-minor-bug :hammer:

#3659 fix: do not end server process in CI
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#3949 feat: generate inline sourcemaps for bundled vite.config.js files
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#3784 feat: fs-serve import graph awareness
  docs/config/index.md
  packages/playground/fs-serve/__tests__/fs-serve.spec.ts
  packages/playground/fs-serve/entry.js
  packages/playground/fs-serve/nested/foo.js
  packages/playground/fs-serve/package.json
  packages/playground/fs-serve/root/index.html
  packages/playground/fs-serve/root/vite.config.js
  packages/playground/fs-serve/safe.json
  packages/playground/fs-serve/unsafe.json
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/error.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/server/moduleGraph.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/utils.ts
  scripts/jestPerTestSetup.ts
Labels: p3-minor-bug :hammer:

#3638 feat: add client events to import.meta.hot.on
  docs/guide/api-hmr.md
  packages/playground/hmr/__tests__/hmr.spec.ts
  packages/playground/hmr/hmr.js
  packages/vite/client.d.ts
  packages/vite/src/client/client.ts
Labels: p2-nice-to-have :cake:

#3819 feat: support for regex for ssr.noExternal
  docs/config/index.md
  packages/playground/ssr-vue/package.json
  packages/playground/ssr-vue/vite.config.noexternal.js
  packages/vite/src/node/config.ts
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: enhancement, p2-nice-to-have :cake:

#3961 docs: clarify CommonJS with `optimizeDeps.exclude`
  docs/config/index.md
Labels: documentation

#3954 fix(ssr): not flatten export * as (fix #3934)
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: feat: ssr, p2-has-workaround :cake:

#3706 fix(ssr): normalize manifest filenames
  packages/plugin-vue-jsx/index.js
  packages/plugin-vue/src/main.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
Labels: feat: ssr, p3-minor-bug :hammer:

#3774 fix: don't force polyfillDynamicImport if renderLegacyChunks is false (#3695)
  packages/plugin-legacy/index.js
Labels: p3-minor-bug :hammer:

#3753 fix: resolve nested dependencies (#3254)
  packages/playground/nested-deps/__tests__/nested-deps.spec.ts
  packages/playground/nested-deps/index.html
  packages/playground/nested-deps/package.json
  packages/playground/nested-deps/test-package-a/index.js
  packages/playground/nested-deps/test-package-a/package.json
  packages/playground/nested-deps/test-package-b/index.js
  packages/playground/nested-deps/test-package-b/node_modules/test-package-a/index.js
  packages/playground/nested-deps/test-package-b/node_modules/test-package-a/package.json
  packages/playground/nested-deps/test-package-b/package.json
  packages/playground/nested-deps/vite.config.js
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  yarn.lock
Labels: p3-minor-bug :hammer:

#2494 fix(build): bundle non-inlined workers with rollup
  packages/playground/worker/__tests__/worker.spec.ts
  packages/playground/worker/index.html
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/worker.ts
Labels: p3-minor-bug :hammer:

#3047 feat: allow passing options to rollupjs dynamic import vars plugin
  docs/config/index.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/index.ts
  packages/vite/types/dynamicImportVars.d.ts
Labels: enhancement, p2-nice-to-have :cake:

#4001 fix: ensure that esbuild uses the same working directory as Vite
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug :hammer:
