Repository vitejs/vite, pull requests merged in 2021-07, with the labels that each got.

#4057 fix: skip redirect and error fallback on middleware mode
  packages/vite/src/node/server/middlewares/base.ts
Labels: p3-downstream-blocker :hammer:

#4053 fix(ssr): Transform named default exports without altering scope
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: feat: ssr

#4129 chore: remove unused cache
  packages/vite/src/node/optimizer/index.ts
Labels: p1-chore :broom:

#4133 chore: add dependencies label on renovate PR
  .github/renovate.json5
Labels: p1-chore :broom:

#4135 chore(docs): WebAssembly (no space)
  docs/guide/features.md
Labels: documentation, p1-chore :broom:

#4138 fix: specify full filepath to importMeta.d.ts, fix #4125
  packages/vite/client.d.ts
Labels: p3-minor-bug :hammer:

#4143 chore: regenerate license file
  packages/vite/LICENSE.md
Labels: p1-chore :broom:

#4127 fix(hmr): html registered as a PostCSS dependency, fix #3716
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/server/hmr.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#4137 chore(deps): update dependency open to v8
  packages/vite/package.json
  packages/vite/src/node/server/openBrowser.ts
  yarn.lock
Labels: dependencies

#4149 fix(build): resolve license files correctly
  packages/vite/LICENSE.md
  packages/vite/rollup.config.js
Labels: p1-chore :broom:

#4154 chore: improve prettier config
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/renovate.json5
  .github/workflows/ci.yml
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-labeled.yml
  .prettierignore
  .prettierrc
  .prettierrc.json
  docs/.vitepress/theme/sponsors.css
  docs/config/index.md
  docs/guide/api-hmr.md
  docs/guide/static-deploy.md
  package.json
  packages/create-app/template-lit-element-ts/package.json
  packages/create-app/template-lit-element/package.json
  packages/create-app/template-preact-ts/package.json
  packages/create-app/template-preact/package.json
  packages/create-app/template-react-ts/package.json
  packages/create-app/template-react/package.json
  packages/create-app/template-svelte-ts/package.json
  packages/create-app/template-svelte/package.json
  packages/create-app/template-vanilla-ts/package.json
  packages/create-app/template-vanilla/package.json
  packages/create-app/template-vue-ts/package.json
  packages/create-app/template-vue/package.json
  packages/create-app/template-vue/src/components/HelloWorld.vue
  packages/playground/css/glob-dep.css
  packages/playground/css/glob-dep/bar.css
  packages/playground/css/glob-dep/foo.css
  packages/playground/css/imported.css
  packages/playground/css/sass.scss
  packages/playground/vue/AsyncComponent.vue
  packages/plugin-legacy/README.md
  packages/plugin-vue-jsx/index.js
Labels: p1-chore :broom:

#3642 feat: cache certificate
  packages/vite/src/node/server/http.ts
Labels: p2-nice-to-have :cake:

#3780 fix(utils): add dot-all flag to match all characters, fix #3761
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#4163 fix: __VITE_PRELOAD__ replacement error, fix #3051
  packages/playground/preload/__tests__/preload.spec.ts
  packages/playground/preload/index.html
  packages/playground/preload/package.json
  packages/playground/preload/router.js
  packages/playground/preload/src/App.vue
  packages/playground/preload/src/components/About.vue
  packages/playground/preload/src/components/Home.vue
  packages/playground/preload/vite.config.js
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-minor-bug :hammer:

#4203 fix: update link to vue rfc (fix #4200)
  packages/create-app/template-vue/src/App.vue
Labels: p1-chore :broom:

#4122 feat: allow entryFileNames, chunkFileNames functions for legacy
  packages/playground/legacy/__tests__/legacy.spec.ts
  packages/playground/legacy/immutable-chunk.js
  packages/playground/legacy/index.html
  packages/playground/legacy/main.js
  packages/playground/legacy/vite.config.js
  packages/plugin-legacy/index.js
Labels: p2-nice-to-have :cake:, plugin: legacy

#4195 chore: lock closed issues after 14 days
  .github/workflows/lock-closed-issues.yml
Labels: p2-nice-to-have :cake:

#4223 fix: correctly ignore optional deps when bundling vite deps
  packages/vite/rollup.config.js
Labels: p3-minor-bug :hammer:

#4096 feat: extract `config.base` in `importAnalysisBuild.ts`
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: enhancement, p2-nice-to-have :cake:

#4233 chore: format
  README.md
  packages/create-vite/template-lit-element-ts/package.json
  packages/create-vite/template-lit-element/package.json
  packages/create-vite/template-preact-ts/package.json
  packages/create-vite/template-preact/package.json
  packages/create-vite/template-react-ts/package.json
  packages/create-vite/template-react/package.json
  packages/create-vite/template-svelte-ts/package.json
  packages/create-vite/template-svelte/package.json
  packages/create-vite/template-vanilla-ts/package.json
  packages/create-vite/template-vanilla/package.json
  packages/create-vite/template-vue-ts/package.json
  packages/create-vite/template-vue/package.json
  packages/create-vite/updateVersions.js
  packages/playground/preload/src/App.vue
  packages/playground/preload/src/components/About.vue
  packages/playground/preload/src/components/Home.vue
Labels: p1-chore :broom:

#4234 chore: use eslint rule eqeqeq
  .eslintrc.js
  packages/create-vite/index.js
  packages/playground/testUtils.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/utils.ts
Labels: p1-chore :broom:

#4235 chore: change workflow sentences
  .github/workflows/issue-labeled.yml
  .github/workflows/lock-closed-issues.yml
Labels: p1-chore :broom:

#4091 fix: nested dependencies from sub node_modules, fix #3254
  packages/playground/nested-deps/__tests__/nested-deps.spec.ts
  packages/playground/nested-deps/index.html
  packages/playground/nested-deps/package.json
  packages/playground/nested-deps/test-package-c/index-es.js
  packages/playground/nested-deps/test-package-c/index.js
  packages/playground/nested-deps/test-package-c/package.json
  packages/playground/nested-deps/test-package-c/side.js
  packages/playground/nested-deps/vite.config.js
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  yarn.lock
Labels: p3-minor-bug :hammer:

#4227 fix: improve indent of built html file
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p2-nice-to-have :cake:

#4247 fix: create-vite when targetDir is a valid packageName
  packages/create-vite/index.js
Labels: p3-minor-bug :hammer:

#3625 feat: enable usage of function as library fileName, close #3585
  docs/config/index.md
  docs/guide/build.md
  packages/playground/lib/index.dist.html
  packages/playground/lib/vite.config.js
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/build.ts
Labels: p2-nice-to-have :cake:

#4278 chore: temporarily shorten the time between locks
  .github/workflows/lock-closed-issues.yml
Labels: p1-chore :broom:

#4268 fix(playground/ssr-vue): remove crossorigin from image preloads
  packages/playground/ssr-vue/src/App.vue
  packages/playground/ssr-vue/src/entry-server.js
Labels: test

#4284 chore(docs): add colons to api pages
  docs/guide/api-javascript.md
  docs/guide/api-plugin.md
Labels: documentation, p1-chore :broom:

#4285 chore: set schedule of lock closed issue
  .github/workflows/lock-closed-issues.yml
Labels: p1-chore :broom:

#4310 fix(util): copyDir may cause an infinite loop
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#4314 chore: no implicit any for local vars
  packages/plugin-vue/src/main.ts
  packages/plugin-vue/src/template.ts
  packages/vite/src/client/overlay.ts
  packages/vite/src/node/importGlob.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/clientInjections.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/define.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/utils.ts
Labels: p1-chore :broom:

#4219 feat: `vite preview` port is used automatically `+1`
  packages/vite/src/node/cli.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/http.ts
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:

#4097 feat: library mode does not include preload
  packages/playground/lib/__tests__/lib.spec.ts
  packages/playground/lib/__tests__/serve.js
  packages/playground/lib/index.dist.html
  packages/playground/lib/src/main2.js
  packages/playground/lib/src/message.js
  packages/playground/lib/vite.dyimport.config.js
  packages/vite/src/node/importGlob.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: enhancement, p2-nice-to-have :cake:

#4267 fix: call createFileOnlyEntry() only for CSS deps, fix #4150
  packages/playground/tailwind/__test__/tailwind.spec.ts
  packages/playground/tailwind/index.css
  packages/playground/tailwind/index.html
  packages/playground/tailwind/package.json
  packages/playground/tailwind/postcss.config.js
  packages/playground/tailwind/public/favicon.ico
  packages/playground/tailwind/src/App.vue
  packages/playground/tailwind/src/assets/logo.png
  packages/playground/tailwind/src/components/HelloWorld.vue
  packages/playground/tailwind/src/main.js
  packages/playground/tailwind/src/router.ts
  packages/playground/tailwind/src/views/Page.vue
  packages/playground/tailwind/tailwind.config.js
  packages/playground/tailwind/vite.config.ts
  packages/vite/src/node/plugins/css.ts
Labels: bug, p4-important :exclamation:

#3906 fix(css): cachedPostcssConfig reused for multiple builds
  packages/playground/css/postcss-caching/blue-app/imported.css
  packages/playground/css/postcss-caching/blue-app/index.html
  packages/playground/css/postcss-caching/blue-app/main.js
  packages/playground/css/postcss-caching/blue-app/package.json
  packages/playground/css/postcss-caching/blue-app/postcss.config.js
  packages/playground/css/postcss-caching/css.spec.ts
  packages/playground/css/postcss-caching/green-app/imported.css
  packages/playground/css/postcss-caching/green-app/index.html
  packages/playground/css/postcss-caching/green-app/main.js
  packages/playground/css/postcss-caching/green-app/package.json
  packages/playground/css/postcss-caching/green-app/postcss.config.js
  packages/vite/src/node/plugins/css.ts
Labels: feat: css

#4318 fix: --https is invalid in preview
  packages/vite/src/node/cli.ts
  packages/vite/src/node/preview.ts
Labels: p2-nice-to-have :cake:

#4330 refactor: use utils.isObject insteads of typeof
  packages/vite/src/node/plugins/clientInjections.ts
  packages/vite/src/node/server/http.ts
  packages/vite/src/node/server/middlewares/proxy.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/server/ws.ts
Labels: p1-chore :broom:

#4224 fix: reuse the old preprocessor after changing the lang attr
  packages/playground/vue/PreProcessors.vue
  packages/playground/vue/__tests__/vue.spec.ts
  packages/plugin-vue/src/handleHotUpdate.ts
Labels: p3-minor-bug :hammer:

#2904 fix: ignore ENOENT in `injectSourcesContent`
  packages/vite/src/node/server/sourcemap.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p3-minor-bug :hammer:

#4342 chore: remove usage of querystring
  packages/vite/src/node/plugins/worker.ts
Labels: p1-chore :broom:

#4346 chore: lock every day
  .github/workflows/lock-closed-issues.yml
Labels: p1-chore :broom:

#4356 chore(types): remove unnecessary type assertions
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/ssr/ssrStacktrace.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p1-chore :broom:

#3885 fix(plugin-legacy): legacy fallback for dynamic import
  packages/plugin-legacy/README.md
  packages/plugin-legacy/index.js
Labels: p3-minor-bug :hammer:, plugin: legacy

#3640 fix: fix pre-bundling executes multiple times
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#4372 docs: clarify sourcemap options
  docs/config/index.md
Labels: documentation

#3739 Handle imports from dot directories
  packages/playground/optimize-deps/.hidden-dir/foo.js
  packages/playground/optimize-deps/__tests__/optimize-deps.spec.ts
  packages/playground/optimize-deps/index.html
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
Labels: p2-has-workaround :cake:

#4390 chore(create-vite): update version of vue-tsc
  packages/create-vite/template-vue-ts/package.json
Labels: dependencies

#4404 chore: update vite v2.4.4 changelog
  packages/vite/CHANGELOG.md
Labels: p1-chore :broom:

#4343 docs: exhibit defineConfig
  docs/config/index.md
  docs/guide/api-plugin.md
  docs/guide/backend-integration.md
  docs/guide/build.md
  docs/guide/features.md
  docs/guide/migration.md
  docs/guide/using-plugins.md
Labels: documentation, p1-chore :broom:

#4371 feat: minify css with esbuild, deprecate build.cleanCssOptions
  packages/playground/vue/vite.config.ts
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/types/clean-css.d.ts
  yarn.lock
Labels: enhancement

#4373 refactor: deprecate polyfillDynamicImport
  docs/config/index.md
  docs/guide/backend-integration.md
  packages/playground/multiple-entrypoints/vite.config.js
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/dynamicImportPolyfill.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/index.ts
Labels: p2-nice-to-have :cake:

#4132 chore: format every possible file on pre-commit and then lint ts files
  .eslintrc.js
  package.json
Labels: p1-chore :broom:

#4279 feat: respect tsconfig options that affects compilation results
  packages/playground/tsconfig-json/__tests__/tsconfig-json.spec.ts
  packages/playground/tsconfig-json/index.html
  packages/playground/tsconfig-json/nested-with-extends/main.ts
  packages/playground/tsconfig-json/nested-with-extends/not-used-type.ts
  packages/playground/tsconfig-json/nested-with-extends/tsconfig.json
  packages/playground/tsconfig-json/nested/main.ts
  packages/playground/tsconfig-json/nested/not-used-type.ts
  packages/playground/tsconfig-json/nested/tsconfig.json
  packages/playground/tsconfig-json/package.json
  packages/playground/tsconfig-json/src/main.ts
  packages/playground/tsconfig-json/src/not-used-type.ts
  packages/playground/tsconfig-json/tsconfig.json
  packages/vite/package.json
  packages/vite/src/node/plugins/esbuild.ts
  yarn.lock
Labels: p3-minor-bug :hammer:

#4420 docs: fix globalModulePaths type
  docs/config/index.md
Labels: documentation

#4413 build: emit .d.ts files during `yarn dev`
  packages/vite/rollup.config.js
Labels: p1-chore :broom:

#4424 chore: configure PR prefixes accepted by GitHub bot
  .github/semantic.yml
Labels: p1-chore :broom:

#4058 feat: modulepreload polyfill
  docs/config/index.md
  docs/guide/backend-integration.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/modulePreloadPolyfill.ts
Labels: p2-nice-to-have :cake:

#4421 chore(playground): fix lint warning
  packages/playground/testUtils.ts
Labels: p1-chore :broom:

#4440 fix(plugin-legacy): bake-in Promise polyfill, fix #4414
  packages/plugin-legacy/index.js
Labels: p3-minor-bug :hammer:, plugin: legacy

#4445 chore: typo
  docs/config/index.md
Labels: documentation

#4434 types: prefer auto inference
  packages/vite/src/node/cli.ts
  packages/vite/src/node/preview.ts
Labels: p1-chore :broom:

#4397 fix(build): fix define plugin spread operations
  packages/playground/define/__tests__/define.spec.ts
  packages/playground/define/index.html
  packages/vite/src/node/plugins/define.ts
Labels: p3-minor-bug :hammer:

#4104 fix: config port timing, fix #4094
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#4220 fix(create-vite): distinguish pnpm pkgManager
  packages/create-vite/index.js
Labels: p3-minor-bug :hammer:
