Repository vitejs/vite, pull requests merged in 2022-11, with the labels that each got.

#10741 fix(css): url() with variable in sass/less (fixes #3644, #7651)
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/composes-path-resolving.module.css
  playground/css/index.html
  playground/css/less.less
  playground/css/linked.css
  playground/css/nested/_index.scss
  playground/css/nested/nested.less
  playground/css/nested/nested.sss
  playground/css/nested/nested.styl
  playground/css/sass.scss
  playground/css/sugarss.sss
  playground/css/vite.config.js
Labels: feat: css, p3-minor-bug :hammer:

#10635 fix: transform import.meta.glob when scan JS/TS #10634
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug :hammer:, possible regression, feat: deps optimizer

#10554 test: fix ssr-vue server.js / prerender.js
  playground/ssr-vue/prerender.js
  playground/ssr-vue/server.js
Labels: p1-chore :broom:, test

#9810 feat: add `vite:afterUpdate` event
  docs/guide/api-hmr.md
  packages/vite/src/client/client.ts
  packages/vite/types/customEvent.d.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/tailwind/__test__/tailwind.spec.ts
Labels: enhancement, p2-to-be-discussed :cake:

#10798 docs: add note to use dotenv-expand (#10440)
  docs/guide/env-and-mode.md
Labels: documentation

#10801 refactor: change style.innerHTML to style.textContent
  packages/vite/src/client/client.ts
  packages/vite/src/node/plugins/css.ts
Labels: p2-nice-to-have :cake:

#10247 fix: inconsistent handling of non-ASCII `base` in `resolveConfig` and dev server
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#10815 test: add retry guard to css-dynamic-import test
  playground/css-dynamic-import/__tests__/css-dynamic-import.spec.ts
Labels: p1-chore :broom:, test

#10812 fix: prevent cache on optional package resolve
  packages/vite/src/node/utils.ts
Labels: feat: hmr, p3-downstream-blocker :hammer:

#10803 docs: adding postcss plugin load order explanation
  docs/guide/features.md
Labels: documentation

#10830 docs(plugin-vue): add link to plugin-vue-jsx
  packages/plugin-vue/README.md
Labels: documentation, plugin: vue

#9886 fix: throw missing name error only when 'umd' or 'iife' are used
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/build.ts
Labels: p2-nice-to-have :cake:, feat: library mode

#10831 docs: expand `server.proxy` description
  docs/config/server-options.md
Labels: documentation

#9590 feat!: transform jsx with esbuild instead of babel
  package.json
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/jsx-runtime/babel-import-to-require.ts
  packages/plugin-react/src/jsx-runtime/babel-restore-jsx.spec.ts
  packages/plugin-react/src/jsx-runtime/babel-restore-jsx.ts
  packages/plugin-react/src/jsx-runtime/restore-jsx.spec.ts
  packages/plugin-react/src/jsx-runtime/restore-jsx.ts
  pnpm-lock.yaml
Labels: plugin: react, p3-significant 🔨

#10777 docs: Added additional workaround steps for stalled requests
  docs/guide/troubleshooting.md
Labels: documentation

#10880 fix(ssr): improve missing file error
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/ssr/__tests__/fixtures/modules/has-invalid-import.js
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
Labels: feat: ssr

#10747 chore: remove parameters that are not used
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
Labels: p1-chore :broom:

#10475 feat: handle static assets in case-sensitive manner
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/utils.ts
  playground/assets/__tests__/assets.spec.ts
Labels: p3-downstream-blocker :hammer:, breaking change

#10723 feat: base without trailing slash
  docs/config/server-options.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/middlewares/base.ts
  packages/vite/src/node/utils.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/package.json
  playground/assets/vite.config.js
Labels: p3-downstream-blocker :hammer:

#10793 fix: gracefully handle forbidden filesystem access
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/__tests__/utils/isFileReadable/permission-test-file
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#10891 feat(hmr): deduplicate paths and join them with commas
  packages/vite/src/node/server/hmr.ts
  playground/tailwind/src/components/HelloWorld.vue
  playground/tailwind/src/utils.ts
  playground/tailwind/src/views/Page.vue
Labels: feat: hmr, p2-nice-to-have :cake:

#10902 chore: cleanup PluginContext Omit
  packages/vite/src/node/server/pluginContainer.ts
Labels: p1-chore :broom:

#10903 refactor(types)!: remove facade type files
  packages/vite/src/node/index.ts
  packages/vite/types/alias.d.ts
  packages/vite/types/anymatch.d.ts
  packages/vite/types/chokidar.d.ts
  packages/vite/types/commonjs.d.ts
  packages/vite/types/connect.d.ts
  packages/vite/types/dynamicImportVars.d.ts
  packages/vite/types/http-proxy.d.ts
  packages/vite/types/terser.d.ts
  packages/vite/types/ws.d.ts
Labels: p1-chore :broom:, breaking change

#10904 fix(types): remove `null` from `CSSModulesOptions.localsConvention`
  packages/vite/src/node/plugins/css.ts
Labels: p1-chore :broom:

#10901 fix: don't throw on malformed URLs
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: bug, p3-downstream-blocker :hammer:

#10878 refactor: use rollup hashing when emitting assets
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/manifest.ts
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
  playground/worker/__tests__/relative-base/relative-base-worker.spec.ts
Labels: p3-significant 🔨

#10909 refactor: move CSS emitFile logic closer to rollup
  packages/vite/src/node/__tests__/asset.spec.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/manifest.ts
Labels: p1-chore :broom:

#10905 perf: regexp perf issues, refactor regexp stylistic issues
  .eslintrc.cjs
  package.json
  packages/create-vite/src/index.ts
  packages/plugin-react/src/fast-refresh.ts
  packages/plugin-react/src/index.ts
  packages/plugin-vue/src/handleHotUpdate.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/define.ts
  packages/vite/src/node/plugins/esbuild.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/json.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/splitVendorChunk.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  packages/vite/src/node/server/sourcemap.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/ssr/ssrStacktrace.ts
  packages/vite/src/node/utils.ts
  playground/cli-module/__tests__/serve.ts
  playground/cli/__tests__/serve.ts
  playground/css/__tests__/css.spec.ts
  playground/lib/__tests__/lib.spec.ts
  playground/tsconfig-json-load-error/__tests__/tsconfig-json-load-error.spec.ts
  playground/vue-server-origin/__tests__/vue-server-origin.spec.ts
  playground/worker/__tests__/sourcemap-hidden/sourcemap-hidden-worker.spec.ts
  playground/worker/__tests__/sourcemap-inline/sourcemap-inline-worker.spec.ts
  playground/worker/__tests__/sourcemap/sourcemap-worker.spec.ts
  pnpm-lock.yaml
  scripts/rollupLicensePlugin.mjs
  scripts/verifyCommit.ts
Labels: p2-nice-to-have :cake:

#10920 fix(vue): skip url query request (fixes #10863)
  packages/plugin-vue/src/index.ts
  packages/plugin-vue/src/utils/query.ts
  playground/vue/Main.vue
  playground/vue/Null.vue
  playground/vue/Url.vue
  playground/vue/__tests__/vue.spec.ts
  playground/vue/tsconfig.json
  playground/vue/vite-env.d.ts
Labels: plugin: vue, p3-minor-bug :hammer:

#10593 fix(ssr): skip optional peer dep resolve
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-minor-bug :hammer:, feat: ssr, feat: deps optimizer

#9723 fix: make `addWatchFile()` work (fix #7024)
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/transform-plugin/__tests__/transform-plugin.spec.ts
  playground/transform-plugin/index.html
  playground/transform-plugin/index.js
  playground/transform-plugin/package.json
  playground/transform-plugin/plugin-dep.js
  playground/transform-plugin/vite.config.js
Labels: feat: hmr, p3-minor-bug :hammer:

#10964 refactor: import version from rollup
  packages/vite/src/node/server/pluginContainer.ts
Labels: p1-chore :broom:

#10927 feat: align default chunk and asset file names with rollup
  package.json
  packages/plugin-legacy/src/index.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/worker.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/__tests__/relative-base/relative-base-assets.spec.ts
  playground/assets/__tests__/runtime-base/runtime-base-assets.spec.ts
  playground/assets/vite.config-relative-base.js
  playground/assets/vite.config-runtime-base.js
  playground/backend-integration/__tests__/backend-integration.spec.ts
  playground/css-dynamic-import/__tests__/css-dynamic-import.spec.ts
  playground/css/__tests__/css.spec.ts
  playground/css/vite.config-relative-base.js
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/legacy/__tests__/legacy.spec.ts
  playground/legacy/vite.config-multiple-output.js
  playground/lib/__tests__/lib.spec.ts
  playground/preload/__tests__/preload.spec.ts
  playground/preload/__tests__/resolve-deps/preload-resolve-deps.spec.ts
  playground/ssr-vue/__tests__/ssr-vue.spec.ts
  playground/ssr-webworker/__tests__/ssr-webworker.spec.ts
  playground/vue-server-origin/__tests__/vue-server-origin.spec.ts
  playground/vue/__tests__/vue.spec.ts
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
  playground/worker/__tests__/relative-base/relative-base-worker.spec.ts
  playground/worker/__tests__/sourcemap-hidden/sourcemap-hidden-worker.spec.ts
  playground/worker/__tests__/sourcemap-inline/sourcemap-inline-worker.spec.ts
  playground/worker/__tests__/sourcemap/sourcemap-worker.spec.ts
  playground/worker/vite.config-es.js
  playground/worker/vite.config-iife.js
  playground/worker/vite.config-relative-base.js
  playground/worker/vite.config-sourcemap.js
  pnpm-lock.yaml
Labels: p3-significant 🔨

#10946 feat(hmr): invalidate message
  docs/guide/api-hmr.md
  packages/vite/src/client/client.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
  packages/vite/types/customEvent.d.ts
  packages/vite/types/hot.d.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/react/__tests__/react.spec.ts
Labels: p2-to-be-discussed :cake:

#10985 fix(mpa): support mpa fallback
  packages/vite/src/node/server/middlewares/htmlFallback.ts
Labels: feat: html, p3-minor-bug :hammer:

#11003 docs: update appType docs
  docs/config/shared-options.md
Labels: documentation

#10209 chore: proxy bypass do nothing with object result
  packages/vite/src/node/server/middlewares/proxy.ts
Labels: p2-to-be-discussed :cake:

#11028 test: update import assertion config
  playground/import-assertion/vite.config.js
Labels: p1-chore :broom:

#11032 feat: dedupe the `vue` in client bundle by default
  packages/plugin-vue/src/index.ts
Labels: plugin: vue

#10990 fix(html): transform relative path with long base in /index.html
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: feat: html, p3-minor-bug :hammer:

#9476 fix: missing js sourcemaps with rewritten imports broke debugging (#7767)
  packages/vite/src/node/server/transformRequest.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
  playground/js-sourcemap/qux.js
Labels: p3-minor-bug :hammer:

#10844 fix(plugin-vue): support scss/sass/less... hmr on custom template languages(fix #10677)
  packages/plugin-vue/src/handleHotUpdate.ts
  packages/vite/src/node/publicUtils.ts
Labels: feat: css, feat: hmr, plugin: vue, p3-minor-bug :hammer:

#10895 feat(build): cleaner logs output
  packages/vite/src/node/plugins/reporter.ts
Labels: p2-nice-to-have :cake:

#11047 docs(api-hmr): update hot.prune docs
  docs/guide/api-hmr.md
Labels: documentation

#10406 fix: preserve default export from externalized packages (fixes #10258)
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  playground/external/__tests__/external.spec.ts
  playground/external/dep-that-imports-vue/index.js
  playground/external/dep-that-imports-vue/package.json
  playground/external/dep-that-imports/index.js
  playground/external/dep-that-imports/package.json
  playground/external/dep-that-requires-vue/index.js
  playground/external/dep-that-requires-vue/package.json
  playground/external/dep-that-requires/index.js
  playground/external/dep-that-requires/package.json
  playground/external/index.html
  playground/external/package.json
  playground/external/src/main.js
  playground/external/vite.config.js
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, feat: deps optimizer

#11067 fix: export preprocessCSS in CJS
  packages/vite/index.cjs
Labels: p3-minor-bug :hammer:

#11025 docs: adds CLI section in guide
  docs/.vitepress/config.ts
  docs/guide/cli.md
  docs/guide/index.md
Labels: documentation, p1-chore :broom:

#11076 test: reduce ssr-vue playground flakiness
  playground/ssr-vue/__tests__/ssr-vue.spec.ts
  playground/ssr-vue/src/entry-client.js
Labels: p1-chore :broom:, test

#11077 test: reduce ssr-react playground flakiness
  playground/ssr-react/__tests__/ssr-react.spec.ts
  playground/ssr-react/src/entry-client.jsx
Labels: p1-chore :broom:, test

#11075 test: reduce hmr test flakiness
  playground/backend-integration/__tests__/backend-integration.spec.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/react/__tests__/react.spec.ts
  playground/tailwind/__test__/tailwind.spec.ts
  playground/test-utils.ts
Labels: p1-chore :broom:, test

#11059 fix(plugin-vue): invalidate script module cache when it changed in hot update
  packages/plugin-vue/src/handleHotUpdate.ts
  playground/vue/HmrTsx.vue
  playground/vue/Main.vue
  playground/vue/__tests__/vue.spec.ts
Labels: feat: hmr, plugin: vue, p3-minor-bug :hammer:

#11078 test: extend react-env timeout
  playground/react-env/__tests__/react.spec.ts
Labels: p1-chore :broom:, test

#11094 feat(css): deprecate css default export
  packages/vite/client.d.ts
  packages/vite/src/node/__tests__/plugins/importGlob/fixture.test.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/splitVendorChunk.ts
  playground/css/__tests__/css.spec.ts
  playground/css/imported-inline.css
  playground/css/main.js
Labels: p3-significant 🔨

#9063 feat!: support `safari14` by default for wider ES2020 compatibility
  docs/guide/build.md
  packages/vite/src/node/constants.ts
Labels: breaking change, p3-significant 🔨

#11056 fix: glob import parsing (#10949)
  package.json
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/plugins/importMetaGlob.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#11103 fix(importGlob): warn on default import css
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-c/a.css
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-c/b.css
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-c/c.module.css
  packages/vite/src/node/__tests__/plugins/importGlob/fixture.test.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
Labels: p3-minor-bug :hammer:

#11102 chore: allow breaking commit message
  scripts/verifyCommit.ts
Labels: p1-chore :broom:

#11101 feat(ssr)!: remove dedupe and mode support for CJS
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/ssrRequireHook.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p2-nice-to-have :cake:, feat: ssr, breaking change

#11045 fix(config)!: support development build
  docs/guide/env-and-mode.md
  packages/vite/src/node/__tests__/env.spec.ts
  packages/vite/src/node/__tests__/env/.env.development
  packages/vite/src/node/config.ts
  playground/react-env/.env.staging
Labels: breaking change, p3-significant 🔨

#11079 fix(css): handle environment with browser globals
  packages/vite/src/node/plugins/css.ts
  playground/css/vite.config.js
Labels: feat: css, p3-minor-bug :hammer:

#11120 fix(esbuild): handle inline sourcemap option
  packages/vite/src/node/__tests__/plugins/esbuild.spec.ts
  packages/vite/src/node/plugins/esbuild.ts
Labels: p3-minor-bug :hammer:

#11122 fix(importGlob): preserve line count for sourcemap
  packages/vite/src/node/__tests__/plugins/importGlob/__snapshots__/fixture.test.ts.snap
  packages/vite/src/node/__tests__/plugins/importGlob/fixture.test.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
Labels: p3-minor-bug :hammer:

#11123 fix: Dev SSR dep optimization + respect optimizeDeps.include
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug :hammer:, feat: ssr, feat: deps optimizer

#11057 fix(ssr): preserve require for external node
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
  playground/ssr-noexternal/__tests__/serve.ts
  playground/ssr-noexternal/__tests__/ssr-noexternal.spec.ts
  playground/ssr-noexternal/external-cjs/import.mjs
  playground/ssr-noexternal/external-cjs/package.json
  playground/ssr-noexternal/external-cjs/require.cjs
  playground/ssr-noexternal/index.html
  playground/ssr-noexternal/package.json
  playground/ssr-noexternal/require-external-cjs/main.js
  playground/ssr-noexternal/require-external-cjs/package.json
  playground/ssr-noexternal/server.js
  playground/ssr-noexternal/src/entry-server.js
  playground/ssr-noexternal/vite.config.js
  playground/test-utils.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, feat: ssr, feat: deps optimizer

#10999 refactor: use function to eval worker and glob options
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/__tests__/plugins/importGlob/parse.test.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#9669 feat: align object interface for `transformIndexHtml` hook
  docs/guide/api-plugin.md
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/html/vite.config.js
Labels: p2-nice-to-have :cake:

#11121 fix(importGlob): don't warn when CSS default import is not used
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-c/a.css
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-c/b.css
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-c/c.module.css
  packages/vite/src/node/__tests__/plugins/importGlob/fixture.test.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/glob-import/index.html
Labels: p3-minor-bug :hammer:

#11128 chore(create-vite): align vue template with create-vue
  packages/create-vite/template-vue-ts/.vscode/extensions.json
  packages/create-vite/template-vue-ts/README.md
  packages/create-vite/template-vue-ts/src/App.vue
  packages/create-vite/template-vue-ts/src/vite-env.d.ts
  packages/create-vite/template-vue/.vscode/extensions.json
  packages/create-vite/template-vue/README.md
  packages/create-vite/template-vue/src/App.vue
Labels: p1-chore :broom:

#10826 feat!: support multiline values in env files
  packages/vite/package.json
  packages/vite/src/node/env.ts
  pnpm-lock.yaml
Labels: breaking change, p3-significant 🔨

#11132 fix: reset global regex before match
  packages/vite/src/client/overlay.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/worker.ts
Labels: p3-minor-bug :hammer:
