Repository vitejs/vite, pull requests merged in 2022-03, with the labels that each got.

#7108 fix: throw Error when can't preload CSS
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: feat: css, p2-nice-to-have :cake:

#7136 fix: revert #7052, hmr style tag no support in html
  packages/playground/assets/__tests__/assets.spec.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: p3-downstream-blocker :hammer:

#7153 chore: fix typo in test description
  packages/playground/optimize-deps/__tests__/optimize-deps.spec.ts
Labels: p1-chore :broom:

#7005 fix(resolve): try .tsx extension for .js import from typescript module
  packages/playground/resolve/index.html
  packages/playground/resolve/ts-extension/hellojsx.tsx
  packages/playground/resolve/ts-extension/hellotsx.tsx
  packages/playground/resolve/ts-extension/index.ts
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/utils.ts
Labels: p2-to-be-discussed :cake:

#6352 fix(json): load json module error
  packages/playground/json/index.html
  packages/playground/json/json-module/index.json
  packages/playground/json/json-module/package.json
  packages/playground/json/package.json
  packages/vite/src/node/plugins/resolve.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#5466 fix(hmr): client pinging behind a proxy on websocket disconnect (fix #4501)
  packages/vite/src/client/client.ts
Labels: feat: hmr, p2-nice-to-have :cake:

#6340 fix: 🐛 define plugin not ignore file names
  packages/playground/define/__tests__/define.spec.ts
  packages/playground/define/index.html
  packages/playground/define/vite.config.js
  packages/vite/src/node/plugins/define.ts
Labels: p3-minor-bug :hammer:, inconsistency

#6995 fix: prevent loading env outside of root
  packages/playground/env-nested/.env
  packages/playground/env-nested/__tests__/env-nested.spec.ts
  packages/playground/env-nested/envs/.env.development
  packages/playground/env-nested/envs/.env.production
  packages/playground/env-nested/index.html
  packages/playground/env-nested/package.json
  packages/playground/env-nested/vite.config.js
  packages/vite/src/node/config.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#6629 feat: add `importedCss` and `importedAssets` properties to RenderedChunk type
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/manifest.ts
  packages/vite/src/node/plugins/metadata.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
Labels: p3-downstream-blocker :hammer:

#6624 feat(config): hmr add disable port config
  docs/config/index.md
  packages/vite/src/client/client.ts
  packages/vite/src/node/plugins/clientInjections.ts
  packages/vite/src/node/server/hmr.ts
Labels: feat: hmr, p2-nice-to-have :cake:

#7055 feat(perf): tsconfck perf improvement
  packages/vite/package.json
  packages/vite/src/node/plugins/esbuild.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#6855 fix: reoptimize deps on esbuild options change
  packages/vite/src/node/optimizer/index.ts
Labels: p3-minor-bug :hammer:

#6801 feat: optimize custom extensions
  packages/playground/optimize-deps/__tests__/optimize-deps.spec.ts
  packages/playground/optimize-deps/dep-not-js/foo.js
  packages/playground/optimize-deps/dep-not-js/index.notjs
  packages/playground/optimize-deps/dep-not-js/package.json
  packages/playground/optimize-deps/index.html
  packages/playground/optimize-deps/package.json
  packages/playground/optimize-deps/vite.config.js
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/scan.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:, YAO

#6574 fix(server): base middleware redirect with search and hash
  packages/vite/src/node/server/middlewares/base.ts
Labels: p2-nice-to-have :cake:

#6518 fix(server): ensure consistency for url to file mapping in importAnalysis and static middleware
  packages/playground/fs-serve/root/src/index.html
  packages/playground/fs-serve/root/src/subdir/safe.txt
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/utils.ts
Labels: p3-downstream-blocker :hammer:

#6758 feat: non-blocking pre bundling of dependencies
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/registerMissing.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p2-nice-to-have :cake:

#7099 fix: execute classic worker in dev mode
  .prettierignore
  packages/playground/worker/__tests__/worker.spec.ts
  packages/playground/worker/classic-worker.js
  packages/playground/worker/index.html
  packages/playground/worker/newUrl/classic-shared-worker.js
  packages/playground/worker/newUrl/classic-worker.js
  packages/playground/worker/public/classic.js
  packages/vite/src/node/importGlob.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:, feat: web workers

#7164 fix(ssr): bypass missing resolve error in SSR
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: feat: ssr

#6726 feat: show all prebundle deps when debug
  packages/vite/src/node/optimizer/index.ts
Labels: p2-nice-to-have :cake:

#6526 feat(glob): import.meta.glob support alias path
  packages/playground/glob-import/__tests__/glob-import.spec.ts
  packages/playground/glob-import/dir/alias.js
  packages/playground/glob-import/dir/index.js
  packages/playground/glob-import/vite.config.ts
  packages/vite/src/node/importGlob.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p2-nice-to-have :cake:

#6663 fix(html): build mode ignore html define transform
  packages/playground/define/__tests__/define.spec.ts
  packages/playground/define/index.html
  packages/vite/src/node/plugins/define.ts
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p3-minor-bug :hammer:, inconsistency

#6818 fix: reusing variable names in html module scripts (fix #6851)
  packages/playground/optimize-deps/__tests__/optimize-deps.spec.ts
  packages/playground/optimize-deps/index.html
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug :hammer:

#7180 docs: add config env var info
  docs/config/index.md
Labels: documentation

#7092 fix: allow `localhost` as a valid hostname
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:

#7187 docs: explain dep handling in dev and build
  docs/guide/dep-pre-bundling.md
Labels: documentation

#7193 docs: clarify rollup plugin order
  docs/guide/api-plugin.md
Labels: documentation

#7189 fix(optimizer): add missing keys to hash
  packages/vite/src/node/optimizer/index.ts
Labels: p3-minor-bug :hammer:

#7204 docs: glob support alias path
  docs/guide/features.md
Labels: documentation

#7202 fix: handle files with multiple comments
  packages/vite/src/node/__tests__/scan.spec.ts
  packages/vite/src/node/optimizer/scan.ts
Labels: bug, p3-minor-bug :hammer:

#7147 fix: import css in less/scss (fix 3293)
  packages/playground/css/__tests__/css.spec.ts
  packages/playground/css/index.html
  packages/playground/css/less.less
  packages/playground/css/nested/_index.scss
  packages/playground/css/nested/css-in-less-2.less
  packages/playground/css/nested/css-in-less.css
  packages/playground/css/nested/css-in-less.less
  packages/playground/css/nested/css-in-scss.css
  packages/playground/css/vite.config.js
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#6557 fix: replacing compression with modern version
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/http.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/middlewares/compression.ts
  packages/vite/types/shims.d.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#6599 feat(worker): bundle worker emit asset file
  packages/playground/wasm/__tests__/wasm.spec.ts
  packages/playground/wasm/add.wasm
  packages/playground/wasm/index.html
  packages/playground/wasm/vite.config.ts
  packages/playground/wasm/worker.js
  packages/playground/worker/__tests__/worker.spec.ts
  packages/playground/worker/index.html
  packages/playground/worker/sub-worker.js
  packages/playground/worker/vite.config.ts
  packages/playground/worker/worker-nested-worker.js
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
Labels: p2-nice-to-have :cake:, feat: web workers

#6746 chore: replace SourceMapConsumer with trace-mapping
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/plugins/esbuild.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/ssr/ssrStacktrace.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:, needs rebase

#7218 fix: optimizeDeps.include missing in known imports fallback
  packages/vite/src/node/build.ts
  packages/vite/src/node/optimizer/index.ts
Labels: p3-minor-bug :hammer:

#7233 docs(lib): show example entry file
  docs/guide/build.md
Labels: documentation

#7232 docs(vue): add transformAssetUrls example
  packages/plugin-vue/README.md
Labels: documentation

#7234 docs(vite-legacy): Note about using `regenerator-runtime` in Content Security Policy environment
  packages/plugin-legacy/README.md
Labels: documentation

#7254 fix: avoid caching transform result of invalidated module
  packages/vite/src/node/server/moduleGraph.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p4-important :exclamation:

#7253 docs(build): fix chunking strategy info
  docs/guide/build.md
Labels: documentation

#7256 chore: clarify writableEnded guard comment
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p1-chore :broom:

#7091 feat: expose ssrRewriteStacktrace
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:, feat: ssr

#7280 docs: clarify preprocessor options extension
  docs/config/index.md
Labels: documentation

#7265 docs: clarify postcss-load-config
  docs/config/index.md
Labels: documentation

#7290 docs: remove vite client script
  docs/guide/backend-integration.md
Labels: documentation

#7294 fix: dont replace define in json
  packages/playground/define/__tests__/define.spec.ts
  packages/playground/define/data.json
  packages/playground/define/index.html
  packages/vite/src/node/plugins/define.ts
Labels: p2-nice-to-have :cake:

#7299 fix: use relative paths in _metadata.json
  packages/vite/src/node/optimizer/index.ts
Labels: p3-minor-bug :hammer:

#7302 docs: clarify deprecated exports key end with `/`
  docs/config/index.md
Labels: documentation

#6165 docs(vue-ts): update note on vue type support in ts
  packages/create-vite/template-vue-ts/README.md
Labels: documentation

#7306 feat(asset): allow non-existent url
  packages/playground/assets/__tests__/assets.spec.ts
  packages/playground/assets/index.html
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
Labels: p2-nice-to-have :cake:

#7308 chore: new line for non-existent url
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
Labels: documentation

#7262 fix(hmr): hmr style tag no support in html
  packages/playground/assets/__tests__/assets.spec.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: feat: hmr

#7282 fix: use hmr port if specified
  docs/config/index.md
  packages/vite/src/node/server/ws.ts
Labels: bug, feat: hmr, p3-minor-bug :hammer:

#7154 fix: `ssrExternal` should not skip nested dependencies
  packages/vite/src/node/ssr/__tests__/ssrExternal.spec.ts
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: bug, p3-downstream-blocker :hammer:, feat: ssr

#7319 docs: note esbuild picomatch pattern
  docs/config/index.md
Labels: documentation

#7320 fix: update to esbuild 0.14.27, fix #6994
  package.json
  packages/vite/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#7345 fix: unhandled exception on eager transformRequest
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p4-important :exclamation:

#7350 fix: add version to optimized chunks, fix #7323
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p3-minor-bug :hammer:

#7357 chore: update es-module-lexer
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
  pnpm-lock.yaml
Labels: dependencies

#7380 fix: do not warn (about not being able to bundle non module scripts) when src is an external url
  packages/vite/src/node/plugins/html.ts
Labels: p2-nice-to-have :cake:

#7161 docs: vite only replace `__dirname`, `__filename`, `import.meta.url` in cjs
  docs/config/index.md
Labels: documentation

#7378 fix: browser cache of newly discovered deps
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/registerMissing.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug :hammer:

#6535 fix(plugin-legacy): always fallback legacy build when CSP
  packages/plugin-legacy/README.md
  packages/plugin-legacy/index.js
Labels: plugin: legacy

#7389 docs: clarify required build before test
  CONTRIBUTING.md
Labels: documentation

#7397 fix: avoid mangling code from incorrect magic-string usage
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/define.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: bug, p3-minor-bug :hammer:

#7173 feat: css sourcemap support during dev
  packages/playground/css-sourcemap/__tests__/build.spec.ts
  packages/playground/css-sourcemap/__tests__/serve.spec.ts
  packages/playground/css-sourcemap/be-imported.css
  packages/playground/css-sourcemap/imported-with-import.css
  packages/playground/css-sourcemap/imported.css
  packages/playground/css-sourcemap/imported.less
  packages/playground/css-sourcemap/imported.module.sass
  packages/playground/css-sourcemap/imported.sass
  packages/playground/css-sourcemap/imported.styl
  packages/playground/css-sourcemap/index.html
  packages/playground/css-sourcemap/linked-with-import.css
  packages/playground/css-sourcemap/linked.css
  packages/playground/css-sourcemap/package.json
  packages/playground/css-sourcemap/vite.config.js
  packages/playground/vue-sourcemap/Css.vue
  packages/playground/vue-sourcemap/Less.vue
  packages/playground/vue-sourcemap/Main.vue
  packages/playground/vue-sourcemap/Sass.vue
  packages/playground/vue-sourcemap/SassWithImport.vue
  packages/playground/vue-sourcemap/__tests__/build.spec.ts
  packages/playground/vue-sourcemap/__tests__/serve.spec.ts
  packages/playground/vue-sourcemap/index.html
  packages/playground/vue-sourcemap/package.json
  packages/playground/vue-sourcemap/sassWithImportImported.sass
  packages/playground/vue-sourcemap/src-import/SrcImport.vue
  packages/playground/vue-sourcemap/src-import/src-import-imported.sass
  packages/playground/vue-sourcemap/src-import/src-import.css
  packages/playground/vue-sourcemap/src-import/src-import.sass
  packages/playground/vue-sourcemap/vite.config.js
  packages/plugin-vue/src/index.ts
  packages/plugin-vue/src/style.ts
  packages/vite/package.json
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/server/send.ts
  packages/vite/src/node/server/sourcemap.ts
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
  scripts/jestPerTestSetup.ts
Labels: feat: css, p2-nice-to-have :cake:

#7379 feat: non-blocking scanning of dependencies
  packages/playground/cli-module/__tests__/serve.js
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/registerMissing.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: p2-nice-to-have :cake:

#7318 fix: consider undefined port when checking port
  packages/vite/src/node/server/ws.ts
Labels: p3-minor-bug :hammer:

#7424 fix: update tsconfck to 1.2.1
  packages/vite/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#4984 fix(plugin-vue): respect __VUE_PROD_DEVTOOLS__ setting
  packages/plugin-vue/src/index.ts
  packages/plugin-vue/src/main.ts
Labels: plugin: vue, p3-minor-bug :hammer:

#7438 fix(resolve): skip `module` field when the importer is a `require` call
  packages/playground/resolve/__tests__/resolve.spec.ts
  packages/playground/resolve/index.html
  packages/playground/resolve/package.json
  packages/playground/resolve/require-pkg-with-module-field/dep.cjs
  packages/playground/resolve/require-pkg-with-module-field/index.cjs
  packages/playground/resolve/require-pkg-with-module-field/package.json
  packages/playground/resolve/vite.config.js
  packages/vite/src/node/plugins/resolve.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#7088 feat(plugin-react): adding jsxPure option
  packages/plugin-react/src/index.ts
Labels: p2-nice-to-have :cake:, plugin: react

#5796 feat: support importing css with ?raw
  packages/playground/assets/__tests__/assets.spec.ts
  packages/playground/assets/index.html
  packages/playground/css/__tests__/css.spec.ts
  packages/playground/css/index.html
  packages/playground/css/main.js
  packages/playground/css/raw-imported.css
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-nice-to-have :cake:

#7437 feat(dev): expose APIs for client-server communication
  docs/guide/api-hmr.md
  docs/guide/api-plugin.md
  packages/playground/hmr/__tests__/hmr.spec.ts
  packages/playground/hmr/hmr.js
  packages/playground/hmr/index.html
  packages/playground/hmr/vite.config.js
  packages/vite/src/client/client.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/server/ws.ts
  packages/vite/types/importMeta.d.ts
Labels: feat: hmr, p2-nice-to-have :cake:

#7435 chore: also run CI on `fix/*` and `perf/*` branches
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#7469 fix: optimizeDeps.entries default ignore paths
  docs/config/index.md
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-downstream-blocker :hammer:

#7464 fix: import.meta.url in worker
  packages/playground/worker/__tests__/worker.spec.ts
  packages/playground/worker/sub-worker.js
  packages/playground/worker/url-worker.js
  packages/vite/src/node/plugins/define.ts
Labels: p3-minor-bug :hammer:, feat: web workers

#7371 fix: handle relative path glob raw import, fix #7307
  packages/playground/glob-import/__tests__/glob-import.spec.ts
  packages/playground/glob-import/index.html
  packages/vite/src/node/importGlob.ts
Labels: p3-minor-bug :hammer:

#7463 fix: infer client port from page location
  docs/config/index.md
  packages/vite/src/client/client.ts
  packages/vite/src/node/plugins/clientInjections.ts
  packages/vite/src/node/server/hmr.ts
Labels: p3-minor-bug :hammer:

#7508 docs: note url string must be static
  docs/guide/assets.md
Labels: documentation

#7098 fix: import with query with exports/browser field
  packages/playground/resolve/__tests__/resolve.spec.ts
  packages/playground/resolve/index.html
  packages/vite/src/node/plugins/resolve.ts
Labels: p2-nice-to-have :cake:

#7511 docs: declare the scope of define expressions
  docs/config/index.md
Labels: documentation

#7468 fix: import url worker two times
  packages/playground/worker/__tests__/es/es-worker.spec.ts
  packages/playground/worker/emit-chunk-nested-worker.js
  packages/playground/worker/emit-chunk-sub-worker.js
  packages/playground/worker/index.html
  packages/playground/worker/module-and-worker.js
  packages/playground/worker/worker/main-format-es.js
  packages/playground/worker/worker/main-module.js
  packages/vite/src/node/plugins/define.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
Labels: p3-minor-bug :hammer:, feat: web workers

#5417 feat(worker): Add sourcemap support for worker bundles
  packages/playground/worker/__tests__/sourcemap-hidden/sourcemap-hidden-worker.spec.ts
  packages/playground/worker/__tests__/sourcemap-hidden/vite.config.js
  packages/playground/worker/__tests__/sourcemap-inline/sourcemap-inline-worker.spec.ts
  packages/playground/worker/__tests__/sourcemap-inline/vite.config.js
  packages/playground/worker/__tests__/sourcemap/sourcemap-worker.spec.ts
  packages/playground/worker/__tests__/sourcemap/vite.config.js
  packages/playground/worker/__tests__/worker.spec.ts
  packages/playground/worker/vite.config-sourcemap.js
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
Labels: p2-nice-to-have :cake:, needs rebase, feat: web workers

#7518 fix: test error in worker test
  packages/playground/testUtils.ts
  packages/playground/worker/__tests__/iife/vite.config.js
  packages/playground/worker/__tests__/iife/worker.spec.ts
  packages/playground/worker/package.json
  packages/playground/worker/vite.config-sourcemap.js
Labels: p1-chore :broom:, feat: web workers

#7533 fix: dynamic import warning with @vite-ignore
  packages/playground/dynamic-import/__tests__/dynamic-import.spec.ts
  packages/playground/dynamic-import/nested/index.js
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p3-minor-bug :hammer:

#7540 docs(changelog): fix raw glob imports syntax
  packages/vite/CHANGELOG.md
Labels: documentation
