Repository vitejs/vite, pull requests merged in 2022-05, with the labels that each got.

#7974 fix: inline css hash
  packages/playground/html/inline/shared_a.html
  packages/playground/html/vite.config.js
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
Labels: feat: css, p3-minor-bug :hammer:

#7982 fix(css): sourcemap crash with postcss (fix #7978)
  packages/playground/vue-sourcemap/Css.vue
  packages/playground/vue-sourcemap/__tests__/serve.spec.ts
  packages/playground/vue-sourcemap/package.json
  packages/playground/vue-sourcemap/postcss.config.js
  packages/vite/src/node/plugins/css.ts
  pnpm-lock.yaml
Labels: feat: css, p3-minor-bug :hammer:

#7969 fix(css): dynamic import css in package fetches removed js (fixes #7955, #6823)
  packages/playground/dynamic-import/__tests__/dynamic-import.spec.ts
  packages/playground/dynamic-import/index.html
  packages/playground/dynamic-import/nested/deps.js
  packages/playground/dynamic-import/nested/index.js
  packages/playground/dynamic-import/package.json
  packages/playground/dynamic-import/pkg/index.js
  packages/playground/dynamic-import/pkg/package.json
  packages/playground/dynamic-import/pkg/pkg.css
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  pnpm-lock.yaml
Labels: feat: css, p3-minor-bug :hammer:

#7807 fix(css): inline css module when ssr, minify issue (fix #5471)
  packages/playground/css/__tests__/css.spec.ts
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:, feat: ssr

#6838 fix(plugin-react): React is not defined when component name is lowercase
  packages/plugin-react/src/jsx-runtime/restore-jsx.spec.ts
  packages/plugin-react/src/jsx-runtime/restore-jsx.ts
Labels: plugin: react

#7921 fix(css): var in image-set
  packages/playground/assets/__tests__/assets.spec.ts
  packages/playground/assets/css/css-url.css
  packages/playground/assets/index.html
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/utils.ts
Labels: feat: css, p3-minor-bug :hammer:

#6939 chore: fix ts checking on used-before-assigned
  scripts/jestPerTestSetup.ts
Labels: p1-chore :broom:

#8003 fix: only handle merge ssr.noExternal
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#7997 refactor(plugin-vue): remove querystring import
  packages/plugin-vue/src/main.ts
  packages/plugin-vue/src/utils/query.ts
Labels: plugin: vue, p1-chore :broom:

#7827 fix(css): do not clean id when passing to postcss (fix #7822)
  packages/playground/css/__tests__/css.spec.ts
  packages/playground/css/index.html
  packages/playground/css/main.js
  packages/playground/css/postcss-source-input.css
  packages/playground/css/postcss.config.js
  packages/vite/src/node/plugins/css.ts
Labels: feat: css

#8005 fix(ssr): allow ssrTransform to parse hashbang
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p2-nice-to-have :cake:, feat: ssr

#8010 chore: remove maybeVirtualHtmlSet
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/sourcemap.ts
Labels: p1-chore :broom:

#8013 test(css): fix postcss cleanid test
  packages/playground/css/postcss.config.js
Labels: test

#7998 feat: import ts with .js in vue
  packages/playground/vue-jsx/TsImport.vue
  packages/playground/vue-jsx/TsImportFile.ts
  packages/playground/vue-jsx/__tests__/vue-jsx.spec.ts
  packages/playground/vue-jsx/main.jsx
  packages/playground/vue/Main.vue
  packages/playground/vue/TsImport.vue
  packages/playground/vue/TsImportFile.ts
  packages/playground/vue/__tests__/vue.spec.ts
  packages/plugin-vue/src/main.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/utils.ts
Labels: plugin: vue, p2-nice-to-have :cake:

#8006 fix: handle optimize failure
  packages/vite/src/node/optimizer/registerMissing.ts
Labels: p2-nice-to-have :cake:

#7911 fix: warn for unresolved css in html
  packages/playground/html/index.html
  packages/vite/src/node/plugins/html.ts
Labels: p3-minor-bug :hammer:

#7332 docs: clarify code comments in `optimize-missing-deps`
  packages/playground/optimize-missing-deps/server.js
Labels: documentation, p1-chore :broom:

#8018 fix: client full reload
  packages/vite/src/client/client.ts
Labels: feat: hmr

#8025 test(optimize-missing-deps): rewrite deps in CJS
  packages/playground/optimize-missing-deps/missing-dep/index.js
  packages/playground/optimize-missing-deps/package.json
  pnpm-lock.yaml
Labels: test

#6827 fix(lib): use proper extension
  docs/config/index.md
  docs/guide/build.md
  packages/create-vite/template-lit-ts/package.json
  packages/create-vite/template-lit/package.json
  packages/playground/lib/index.dist.html
  packages/playground/lib/vite.config.js
  packages/playground/resolve-config/__tests__/resolve-config.spec.ts
  packages/playground/vue-lib/vite.config.lib.ts
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/__tests__/packages/module/package.json
  packages/vite/src/node/build.ts
  packages/vite/src/node/packages.ts
Labels: p3-minor-bug :hammer:, feat: library mode

#7877 fix: vite client types
  docs/guide/env-and-mode.md
  packages/vite/client.d.ts
Labels: p2-nice-to-have :cake:

#5972 feat: allow any JS identifier in define, not ASCII-only
  docs/config/index.md
  packages/playground/define/__tests__/define.spec.ts
  packages/playground/define/index.html
  packages/playground/define/vite.config.js
  packages/vite/src/node/plugins/define.ts
Labels: p2-nice-to-have :cake:

#8022 fix(css): hoist external @import for non-split css
  packages/playground/lib/__tests__/lib.spec.ts
  packages/playground/lib/__tests__/serve.js
  packages/playground/lib/src/dynamic.css
  packages/playground/lib/src/index.css
  packages/playground/lib/src/main2.js
  packages/playground/lib/vite.dyimport.config.js
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-nice-to-have :cake:

#6779 fix(plugin-vue): allow overwriting template.transformAssetUrls.includeAbsolute (fix #4836)
  packages/plugin-vue/src/template.ts
Labels: plugin: vue, p3-downstream-blocker :hammer:

#7658 feat: new hook `configurePreviewServer`
  docs/guide/api-plugin.md
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/preview.ts
Labels: p3-downstream-blocker :hammer:

#8046 refactor: use optional chaining in config `define` of vue-jsx
  packages/plugin-vue-jsx/index.js
Labels: plugin: vue-jsx, p1-chore :broom:

#7537 feat!: rework `import.meta.glob`
  docs/guide/features.md
  packages/playground/assets/__tests__/assets.spec.ts
  packages/playground/css/main.js
  packages/playground/glob-import/__tests__/glob-import.spec.ts
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/__tests__/plugins/importGlob/__snapshots__/fixture.test.ts.snap
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-a/.gitignore
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-a/index.ts
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-a/modules/a.ts
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-a/modules/b.ts
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-a/modules/index.ts
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-a/node_modules/framework/pages/hello.page.js
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-a/sibling.ts
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-b/a.ts
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-b/b.ts
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-b/index.ts
  packages/vite/src/node/__tests__/plugins/importGlob/fixture.test.ts
  packages/vite/src/node/__tests__/plugins/importGlob/parse.test.ts
  packages/vite/src/node/__tests__/plugins/importGlob/utils.test.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/importGlob.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
  packages/vite/types/chokidar.d.ts
  packages/vite/types/importGlob.d.ts
  packages/vite/types/importMeta.d.ts
  packages/vite/types/shims.d.ts
  pnpm-lock.yaml
Labels: enhancement

#7746 fix(css): preserve dynamic import css code (fix #5348)
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/css-codesplit/__tests__/css-codesplit.spec.ts
  playground/css-codesplit/async.css
  playground/css-codesplit/index.html
  playground/css-codesplit/inline.css
  playground/css-codesplit/main.js
  playground/css-codesplit/mod.module.css
Labels: feat: css, p3-minor-bug :hammer:

#8083 chore(plugin-react): add vite peer dep
  packages/plugin-react/package.json
Labels: p1-chore :broom:, plugin: react

#6207 fix(dev): increase default session memory limit in HTTPS dev server to prevent disconnections on large projects.
  packages/vite/src/node/http.ts
Labels: bug, p3-minor-bug :hammer:

#7846 docs(config-file): update tip note about string replace
  docs/config/index.md
Labels: documentation

#6674 docs: precautions of `define`
  docs/config/index.md
Labels: documentation, needs rebase

#8086 chore(plugin-vue-jsx): add peer deps
  packages/plugin-vue-jsx/package.json
Labels: plugin: vue-jsx, p1-chore :broom:

#8035 fix: image-set with base64 images (fix #8028)
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/utils.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/css/css-url.css
  playground/assets/index.html
Labels: feat: css, p3-minor-bug :hammer:

#4408 fix(build): use crossorigin for module preloaded
  packages/vite/src/node/plugins/html.ts
Labels: feat: html

#7756 feat: rework `dynamic-import-vars`
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/__snapshots__/parse.test.ts.snap
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/mods/hello.js
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/mods/hi.js
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/parse.test.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/dynamicImportVars.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/utils.ts
  packages/vite/types/shims.d.ts
  playground/dynamic-import/__tests__/dynamic-import.spec.ts
  playground/dynamic-import/alias/hello.js
  playground/dynamic-import/alias/hi.js
  playground/dynamic-import/index.html
  playground/dynamic-import/nested/hello.js
  playground/dynamic-import/nested/index.js
  playground/dynamic-import/vite.config.js
Labels: enhancement, p3-minor-bug :hammer:

#5902 fix: allow css to be written for systemjs output
  packages/vite/src/node/plugins/css.ts
  playground/legacy/__tests__/legacy.spec.ts
  playground/legacy/dynamic.css
  playground/legacy/index.html
  playground/legacy/main.js
  playground/legacy/package.json
  playground/legacy/vite.config-dynamic-css.js
Labels: feat: css, p2-nice-to-have :cake:

#7641 chore: use isScannable in optimizer scan
  packages/vite/src/node/optimizer/scan.ts
Labels: p1-chore :broom:

#6739 feat(create-vite): supports nested directory (closes #6638)
  packages/create-vite/index.js
Labels: p2-nice-to-have :cake:

#7909 fix(plugin-vue): don't inline ts scripts during build
  packages/plugin-vue/src/main.ts
Labels: plugin: vue

#7517 test: update define expression
  playground/define/__tests__/define.spec.ts
  playground/define/index.html
  playground/define/vite.config.js
Labels: p1-chore :broom:, test

#6597 fix(ssr): avoid transforming json file in ssrTransform
  packages/playground/json/index.ssr.html
  packages/playground/json/server.js
  packages/vite/src/node/plugins/json.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  playground/json/package.json
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:, feat: ssr

#5188 docs: mention middlewares in server.proxy config
  docs/config/index.md
Labels: documentation

#6294 chore: remove noop watch close
  packages/vite/src/node/build.ts
Labels: p3-minor-bug :hammer:

#3682 fix(glob): wrap glob compile output in function invocation
  packages/playground/glob-import/side-effect/writetodom.js
  packages/vite/src/node/__tests__/plugins/importGlob/__snapshots__/fixture.test.ts.snap
  packages/vite/src/node/plugins/importMetaGlob.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/glob-import/index.html
  playground/glob-import/side-effect/writedom.js
Labels: needs rebase

#8110 fix(lib): reduce backtrack when injecting esbuild helpers (fixes #8099)
  packages/vite/src/node/plugins/esbuild.ts
Labels: p3-minor-bug :hammer:, feat: library mode

#8108 test: fix flaky lib test
  playground/lib/__tests__/lib.spec.ts
Labels: test

#8094 fix: add direct query to html-proxy css (fixes #8091)
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/css-sourcemap/__tests__/serve.spec.ts
Labels: feat: css, p3-minor-bug :hammer:, possible regression

#8059 fix(vue): same src file request same key
  packages/plugin-vue/src/main.ts
  packages/plugin-vue/src/utils/descriptorCache.ts
  packages/plugin-vue/src/utils/query.ts
  playground/vue/src-import/css.module.css
  playground/vue/src-import/script.ts
  playground/vue/src-import/srcImportModuleStyle.vue
  playground/vue/src-import/srcImportModuleStyle2.vue
  playground/vue/src-import/template.html
Labels: plugin: vue, possible regression

#7171 fix(plugin-vue): user defined transformAssetUrls ignored in production build
  packages/plugin-vue/src/template.ts
Labels: plugin: vue

#7190 fix: add hash to lib chunk names
  packages/vite/src/node/build.ts
  playground/lib/__tests__/lib.spec.ts
Labels: feat: library mode

#6852 chore: using Unicode instead of unicode in doc and tests
  docs/guide/env-and-mode.md
  packages/vite/CHANGELOG.md
  packages/vite/src/node/__tests__/utils.spec.ts
  playground/assets/テスト-測試-white space.js
  playground/html/__tests__/html.spec.ts
  playground/html/unicode-path/中文-にほんご-한글-🌕🌖🌗/index.html
Labels: p1-chore :broom:, needs rebase

#8127 docs: explain dynamic import
  docs/config/index.md
  docs/guide/features.md
Labels: documentation

#7975 refactor: use node hash
  packages/plugin-vue-jsx/index.js
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue/package.json
  packages/plugin-vue/src/utils/descriptorCache.ts
  packages/vite/src/node/__tests__/asset.spec.ts
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/registerMissing.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
Labels: p1-chore :broom:

#8126 fix(lib): enable inlineDynamicImports for umd and iife
  packages/vite/src/node/build.ts
  playground/lib/__tests__/lib.spec.ts
  playground/lib/vite.dyimport.config.js
Labels: p2-nice-to-have :cake:, feat: library mode

#8138 chore: remove patch file deps hack
  CONTRIBUTING.md
  playground/alias/package.json
  playground/dynamic-import/package.json
  playground/optimize-deps/nested-exclude/package.json
  playground/optimize-deps/nested-include/index.js
  playground/optimize-deps/nested-include/package.json
  playground/optimize-deps/package.json
  playground/optimize-missing-deps/package.json
  playground/ssr-deps/forwarded-export/package.json
  playground/ssr-deps/package.json
  pnpm-lock.yaml
  scripts/patchFileDeps.ts
Labels: p1-chore :broom:

#7707 chore: stabilize experimental api
  packages/vite/src/node/config.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
Labels: p1-chore :broom:

#8107 fix(lib)!: remove format prefixes for cjs and esm
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/build.ts
  playground/lib/index.dist.html
  playground/resolve-config/__tests__/resolve-config.spec.ts
  playground/vue-lib/src-consumer/index.ts
Labels: feat: library mode

#8144 chore(deps): update tsconfck to 2.0.0 built for node14+
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#8122 fix: relative path html
  packages/vite/src/node/plugins/resolve.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/asset/main.js
  playground/assets/asset/style.css
  playground/assets/index.html
  playground/html/__tests__/html.spec.ts
  playground/html/nested/asset/main.js
  playground/html/nested/asset/style.css
  playground/html/nested/index.html
Labels: feat: html, p2-nice-to-have :cake:

#7804 feat: worker emit fileName with config
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/worker.ts
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/vite.config-es.js
Labels: p2-nice-to-have :cake:, feat: web workers

#6987 fix(plugin-vue): trigger css hmr on custom template languages
  packages/plugin-vue/src/handleHotUpdate.ts
  playground/tailwind/__test__/tailwind.spec.ts
  playground/tailwind/src/components/PugTemplate.vue
  playground/tailwind/src/views/Page.vue
Labels: feat: hmr, plugin: vue, p3-minor-bug :hammer:

#8151 feat: treat Astro file scripts as TS
  packages/vite/src/node/optimizer/scan.ts
  playground/optimize-deps/index.astro
  playground/optimize-deps/index.html
  playground/optimize-deps/vite.config.js
Labels: p3-downstream-blocker :hammer:

#8154 chore(plugin-vue): change @rollup/pluginutils to dep from devDep
  packages/plugin-vue/package.json
  pnpm-lock.yaml
Labels: dependencies

#8153 chore: fix repeated error message
  packages/vite/src/node/plugins/resolve.ts
Labels: p1-chore :broom:

#4181 fix: Vite cannot load configuration files in the link directory (#4180)
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#8155 chore(plugin-vue): replace source-map with gen/trace-mapping
  packages/plugin-vue/package.json
  packages/plugin-vue/src/main.ts
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#8077 fix(plugin-vue): use server.origin when building base for transformAssetUrls
  packages/plugin-vue/src/template.ts
  playground/vue-server-origin/Main.vue
  playground/vue-server-origin/__tests__/vue-server-origin.spec.ts
  playground/vue-server-origin/assets/asset.png
  playground/vue-server-origin/env.d.ts
  playground/vue-server-origin/index.html
  playground/vue-server-origin/package.json
  playground/vue-server-origin/vite.config.ts
  pnpm-lock.yaml
Labels: plugin: vue, p3-minor-bug :hammer:

#8185 chore: fix incorrect test
  playground/vue-server-origin/__tests__/vue-server-origin.spec.ts
Labels: p1-chore :broom:

#8184 docs(plugin-vue): clarify asset url handling
  packages/plugin-vue/README.md
Labels: documentation, plugin: vue

#5250 fix(plugin-legacy): fail to get the fileName
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p3-minor-bug :hammer:

#8190 docs: use latest core-js unpkg link
  packages/plugin-legacy/README.md
Labels: documentation

#8183 feat(css): warn if url rewrite has no importer
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-nice-to-have :cake:

#8197 test: fix server hmr port conflict
  playground/optimize-missing-deps/__test__/serve.ts
  playground/optimize-missing-deps/server.js
  playground/ssr-deps/__tests__/serve.ts
  playground/ssr-deps/server.js
  playground/ssr-html/__tests__/serve.ts
  playground/ssr-html/server.js
  playground/ssr-pug/__tests__/serve.ts
  playground/ssr-pug/server.js
  playground/ssr-react/__tests__/serve.ts
  playground/ssr-react/server.js
  playground/ssr-vue/__tests__/serve.ts
  playground/ssr-vue/server.js
  playground/test-utils.ts
Labels: p1-chore :broom:

#7644 feat!: relative base
  packages/plugin-legacy/src/index.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/utils.ts
  playground/assets/__tests__/relative-base/relative-base-assets.spec.ts
  playground/assets/__tests__/relative-base/vite.config.js
  playground/assets/nested/テスト-測試-white space.png
  playground/assets/package.json
  playground/assets/vite.config-relative-base.js
  playground/assets/vite.config.js
  playground/css/vite.config.js
  playground/html/vite.config.js
  playground/legacy/vite.config.js
  playground/preload/__tests__/preload.spec.ts
  playground/test-utils.ts
  playground/vitestSetup.ts
  playground/worker/__tests__/relative-base/relative-base-worker.spec.ts
  playground/worker/__tests__/relative-base/vite.config.js
  playground/worker/classic-shared-worker.js
  playground/worker/classic-worker.js
  playground/worker/package.json
  playground/worker/vite.config-relative-base.js
Labels: p3-downstream-blocker :hammer:

#8209 chore: show ws port conflict error
  packages/vite/src/node/server/ws.ts
Labels: p1-chore :broom:

#7111 fix(hmr): catch thrown errors when connecting to hmr websocket
  packages/vite/src/client/client.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#7989 fix(plugin-vue): regenerate scoped css in build watch, fix #7980
  packages/plugin-vue/src/main.ts
Labels: plugin: vue, p3-minor-bug :hammer:

#8227 fix: rewrite CJS specific funcs/vars in plugins
  .eslintrc.cjs
  packages/plugin-legacy/src/index.ts
  packages/plugin-legacy/tsconfig.json
  packages/plugin-react/src/fast-refresh.ts
  packages/plugin-react/tsconfig.json
  packages/plugin-vue-jsx/src/index.ts
  packages/plugin-vue-jsx/tsconfig.json
  packages/plugin-vue/src/compiler.ts
  packages/plugin-vue/tsconfig.json
Labels: plugin: vue-jsx, plugin: vue, plugin: legacy, p4-important :exclamation:, possible regression, plugin: react

#7733 feat: vite connected logs changed to console.debug
  packages/vite/src/client/client.ts
Labels: p2-to-be-discussed :cake:

#8223 docs: update for default target change
  docs/config/index.md
  docs/guide/assets.md
  docs/guide/build.md
  docs/guide/index.md
Labels: documentation

#8230 docs: note api run in same process
  docs/guide/api-javascript.md
  docs/guide/ssr.md
Labels: documentation

#8219 feat(wasm): new wasm plugin (`.wasm?init`)
  docs/guide/features.md
  packages/vite/client.d.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/wasm.ts
  playground/wasm/__tests__/wasm.spec.ts
  playground/wasm/index.html
  playground/wasm/worker.js
Labels: feat: wasm, breaking change, p3-significant 🔨

#8248 docs: remove experimental from stabilized apis
  docs/config/index.md
  docs/guide/api-javascript.md
Labels: documentation

#8247 fix(plugin-legacy): respect `entryFileNames` for polyfill chunks
  packages/plugin-legacy/src/index.ts
  packages/vite/src/node/plugins/manifest.ts
  playground/legacy/__tests__/legacy.spec.ts
  playground/legacy/vite.config-custom-filename.js
  playground/legacy/vite.config.js
Labels: plugin: legacy, p3-minor-bug :hammer:

#8244 fix(plugin-legacy): disable babel.compact when minify is disabled
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p3-minor-bug :hammer:

#6238 feat(plugin-react): allow options.babel to be a function
  packages/plugin-react/src/index.ts
Labels: p3-downstream-blocker :hammer:, plugin: react

#8178 feat!: migrate to ESM
  .eslintrc.cjs
  package.json
  packages/plugin-vue-jsx/src/index.ts
  packages/plugin-vue/src/style.ts
  packages/vite/LICENSE.md
  packages/vite/bin/vite.js
  packages/vite/index.cjs
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/scripts/patchTypes.ts
  packages/vite/scripts/tsconfig.json
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/parse.test.ts
  packages/vite/src/node/__tests__/plugins/importGlob/fixture.test.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/splitVendorChunk.ts
  packages/vite/src/node/plugins/ssrRequireHook.ts
  packages/vite/src/node/plugins/terser.ts
  packages/vite/src/node/publicUtils.ts
  packages/vite/src/node/server/__tests__/search-root.spec.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/server/openBrowser.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/ssr/__tests__/ssrModuleLoader.spec.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/tsconfig.json
  packages/vite/src/node/utils.ts
  packages/vite/tsconfig.base.json
  playground/vitestSetup.ts
  playground/vue-sourcemap/__tests__/serve.spec.ts
  pnpm-lock.yaml
Labels: breaking change, p3-significant 🔨

#7914 feat: worker support query url
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/iife/worker.spec.ts
  playground/worker/__tests__/sourcemap-hidden/sourcemap-hidden-worker.spec.ts
  playground/worker/__tests__/sourcemap-inline/sourcemap-inline-worker.spec.ts
  playground/worker/__tests__/sourcemap/sourcemap-worker.spec.ts
  playground/worker/index.html
  playground/worker/simple-worker.js
  playground/worker/worker/main-url.js
  playground/worker/worker/main.js
Labels: p2-nice-to-have :cake:, feat: web workers

#8235 fix: EPERM error on Windows when processing dependencies
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/utils.ts
Labels: windows only, p2-nice-to-have :cake:

#8278 fix(css): remove `?used` hack (fixes #6421, #8245)
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  playground/css/__tests__/css.spec.ts
Labels: feat: css, p3-minor-bug :hammer:

#8254 chore: use 'new URL' instead of 'url.parse'
  packages/vite/src/node/server/middlewares/base.ts
Labels: p1-chore :broom:

#8255 fix(plugin-react): broken optimized deps dir check
  docs/guide/features.md
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/jsx-runtime/restore-jsx.ts
  packages/vite/src/node/__tests__/plugins/import.spec.ts
Labels: plugin: react

#7995 chore: do not fixStacktrace
  packages/vite/src/node/ssr/__tests__/ssrModuleLoader.spec.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p2-nice-to-have :cake:, feat: ssr

#8217 feat: spa option, `preview` and `dev` for MPA and SSR apps
  docs/config/index.md
  docs/guide/ssr.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
Labels: p3-downstream-blocker :hammer:

#8285 fix(plugin-legacy): prevent failed to load module
  packages/plugin-legacy/README.md
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p2-nice-to-have :cake:

#8283 fix: correctly replace process.env.NODE_ENV
  packages/vite/src/node/plugins/clientInjections.ts
  playground/define/__tests__/define.spec.ts
  playground/define/index.html
  playground/define/vite.config.js
  playground/env/__tests__/env.spec.ts
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/iife/worker.spec.ts
  playground/worker/__tests__/relative-base/relative-base-worker.spec.ts
Labels: p3-minor-bug :hammer:

#8268 chore: remove unneeded worker context param
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  playground/worker/worker/main-url.js
Labels: feat: web workers

#8239 chore: cleanup now that we've dropped Node 12
  packages/create-vite/index.js
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/utils.ts
Labels: p1-chore :broom:

#8162 chore: use `esno` to replace `ts-node`
  .github/renovate.json5
  .npmrc
  package.json
  packages/plugin-legacy/package.json
  packages/plugin-react/package.json
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue/package.json
  packages/vite/scripts/patchTypes.ts
  pnpm-lock.yaml
  scripts/patchCJS.ts
Labels: p1-chore :broom:

#6997 refactor(cli): improve output aesthetics
  packages/vite/src/node/cli.ts
  packages/vite/src/node/logger.ts
Labels: p2-nice-to-have :cake:

#7568 feat: non-blocking needs interop
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/registerMissing.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/ssr-vue/__tests__/ssr-vue.spec.ts
Labels: p3-significant 🔨

#8280 feat: non-blocking esbuild optimization at build time
  packages/plugin-react/src/index.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/transform.ts
  playground/nested-deps/__tests__/nested-deps.spec.ts
  playground/nested-deps/index.html
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/worker/vite.config-es.js
Labels: inconsistency, p3-significant 🔨

#8346 chore: remove unused dts from dist
  packages/vite/rollup.config.ts
Labels: p1-chore :broom:

#8343 fix(optimizer): transpile before calling `transformGlobImport`
  packages/vite/src/node/optimizer/scan.ts
  playground/optimize-deps/index.astro
Labels: p3-minor-bug :hammer:

#8319 feat: scan free dev server
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
Labels: p3-significant 🔨

#8355 refactor: `ExportData.imports` to `ExportData.hasImports`
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/types/es-module-lexer.d.ts
Labels: p1-chore :broom:

#8370 fix: enable ESLint for `__tests__` dir
  package.json
  packages/create-vite/__tests__/cli.spec.ts
Labels: p1-chore :broom:

#8372 chore: enable `@typescript-eslint/explicit-module-boundary-types`
  .eslintrc.cjs
  packages/plugin-legacy/src/index.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/plugins/splitVendorChunk.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/sourcemap.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/utils.ts
  playground/legacy/__tests__/ssr/serve.ts
  scripts/releaseUtils.ts
Labels: p1-chore :broom:

#8371 fix: ssr-manifest no base
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
  playground/ssr-vue/__tests__/serve.ts
  playground/ssr-vue/__tests__/ssr-vue.spec.ts
  playground/ssr-vue/server.js
  playground/ssr-vue/src/entry-server.js
  playground/ssr-vue/src/main.js
  playground/ssr-vue/src/router.js
  playground/ssr-vue/vite.config.js
Labels: p3-minor-bug :hammer:

#8367 fix: fix return type of `handleHMRUpdate`
  packages/vite/src/node/server/hmr.ts
Labels: p1-chore :broom:

#6812 feat: add ssr.format to force esm output for ssr
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:, feat: ssr, YAO

#8348 feat: default esm SSR build, simplified externalization
  docs/config/ssr-options.md
  docs/vite.config.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/ssrRequireHook.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  playground/ssr-deps/__tests__/serve.ts
  playground/ssr-deps/package.json
  playground/ssr-deps/server.js
  playground/ssr-html/__tests__/serve.ts
  playground/ssr-html/package.json
  playground/ssr-html/server.js
  playground/ssr-pug/__tests__/serve.ts
  playground/ssr-pug/package.json
  playground/ssr-pug/server.js
  playground/ssr-react/__tests__/serve.ts
  playground/ssr-react/package.json
  playground/ssr-react/prerender.js
  playground/ssr-react/server.js
  playground/ssr-react/vite.config.js
  playground/ssr-vue/__tests__/serve.ts
  playground/ssr-vue/__tests__/ssr-vue.spec.ts
  playground/ssr-vue/package.json
  playground/ssr-vue/prerender.js
  playground/ssr-vue/server.js
  playground/ssr-vue/vite.config.js
  playground/ssr-webworker/__tests__/serve.ts
  playground/ssr-webworker/package.json
  playground/ssr-webworker/vite.config.js
  playground/ssr-webworker/worker.js
Labels: enhancement, feat: ssr, p3-significant 🔨

#6738 fix: improve warning message
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p2-nice-to-have :cake:

#8384 chore: enable reportUnusedDisableDirectives
  .eslintrc.cjs
  packages/plugin-vue/src/template.ts
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-a/index.ts
  packages/vite/src/node/__tests__/plugins/importGlob/parse.test.ts
  packages/vite/src/node/plugins/css.ts
Labels: p1-chore :broom:

#8381 chore: improve jsdoc of library options
  packages/vite/src/node/build.ts
Labels: p1-chore :broom:

#8388 chore: set node/no-unsupported-features version
  .eslintrc.cjs
  playground/dynamic-import/nested/index.js
  playground/worker/__tests__/sourcemap/sourcemap-worker.spec.ts
Labels: p1-chore :broom:

#8387 fix(plugin-legacy): empty base makes import fail (fixes #4212)
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p2-has-workaround :cake:

#8403 feat: ssr build using optimized deps
  packages/vite/src/node/build.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/index.ts
Labels: feat: ssr, breaking change, p3-significant 🔨

#8390 docs: migration from v2 guide
  docs/.vitepress/config.ts
  docs/guide/migration.md
Labels: documentation

#8417 docs: improve migration from v2 guide
  docs/guide/migration.md
Labels: documentation

#8415 fix: make array `acornInjectPlugins` work (fixes #8410)
  packages/vite/src/node/server/pluginContainer.ts
Labels: p2-has-workaround :cake:
