Repository vitejs/vite, pull requests merged in 2022-01, with the labels that each got.

#6326 docs(react): document opting out of automatic JSX runtime
  packages/plugin-react/README.md
Labels: documentation, plugin: react

#6233 fix: strip query when resolving entry
  packages/playground/vue/ExternalStyleCss.vue
  packages/playground/vue/Main.vue
  packages/playground/vue/package.json
  packages/vite/src/node/plugins/resolve.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#5467 feat(server): trace `error.loc` back to original source
  packages/vite/src/node/server/pluginContainer.ts
Labels: p2-nice-to-have :cake:, needs rebase

#6385 build: fix `declarationDir` for development builds
  packages/vite/rollup.config.js
Labels: p5-urgent :fire:

#6320 fix(plugin-react): check for import React statement in .js files
  packages/plugin-react/src/index.ts
Labels: feat: hmr, plugin: react

#5454 feat(plugin-react): check for `api.reactBabel` on other plugins
  packages/plugin-react/src/index.ts
Labels: p3-downstream-blocker :hammer:, plugin: react

#6390 fix: strip NULL_BYTE_PLACEHOLDER before transform
  packages/playground/ssr-vue/__tests__/ssr-vue.spec.ts
  packages/playground/ssr-vue/src/pages/Home.vue
  packages/playground/ssr-vue/vite.config.js
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-minor-bug :hammer:

#5602 feat: support .cjs config file
  packages/playground/resolve-config/__tests__/resolve-config.spec.ts
  packages/playground/resolve-config/__tests__/serve.js
  packages/playground/resolve-config/package.json
  packages/playground/resolve-config/root/index.js
  packages/playground/resolve-config/root/vite.config.js
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#5705 feat(ssr): support preload dynamic css file in html head
  packages/playground/ssr-vue/__tests__/ssr-vue.spec.ts
  packages/playground/ssr-vue/src/assets/button.css
  packages/playground/ssr-vue/src/components/button.js
  packages/playground/ssr-vue/src/entry-server.js
  packages/playground/ssr-vue/src/pages/About.vue
  packages/playground/ssr-vue/src/pages/Home.vue
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
Labels: p2-nice-to-have :cake:, feat: ssr

#6219 workflow: switch to simple-git-hooks
  package.json
  pnpm-lock.yaml
  scripts/verifyCommit.ts
Labels: enhancement

#6400 chore: add translation contribution guide.
  CONTRIBUTING.md
Labels: documentation

#6344 fix: improve array config merging
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#6433 fix(types): add missing options parameter to importMeta
  packages/vite/types/importMeta.d.ts
Labels: p2-nice-to-have :cake:

#5342 fix: only run build-html plugin on bundler inputs (closes #4067)
  packages/playground/html/__tests__/html.spec.ts
  packages/playground/html/importAsString.html
  packages/playground/html/main.js
  packages/playground/html/vite.config.js
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p3-minor-bug :hammer:

#5876 feat: add customResolver option to resolve.alias
  docs/config/index.md
  packages/playground/alias/__tests__/alias.spec.ts
  packages/playground/alias/customResolver.js
  packages/playground/alias/index.html
  packages/playground/alias/vite.config.js
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#6056 feat: allow globs in node_modules when pattern is explicit
  .gitignore
  packages/playground/glob-import/__tests__/glob-import.spec.ts
  packages/playground/glob-import/dir/node_modules/hoge.js
  packages/playground/glob-import/index.html
  packages/vite/src/node/importGlob.ts
Labels: p2-nice-to-have :cake:

#6489 fix(ssr): handle nameless descture in function args
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#6497 fix: improve alias merging
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#6499 fix(config): merge array correctly
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#6488 fix(ssr): avoid using `tryNodeResolve` on absolute paths
  packages/playground/ssr-deps/package.json
  packages/playground/ssr-deps/require-absolute/foo.js
  packages/playground/ssr-deps/require-absolute/index.js
  packages/playground/ssr-deps/require-absolute/package.json
  packages/playground/ssr-deps/src/app.js
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, feat: ssr

#6514 docs: fix typo in plugin API guide
  docs/guide/api-plugin.md
Labels: documentation

#6505 fix: merge debug params instead of overwrite (#6504)
  packages/vite/bin/vite.js
Labels: p3-minor-bug :hammer:

#6470 fix(ssr): fix resolution for nested ssr externals on windows (#6080)
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-minor-bug :hammer:, feat: ssr, needs test

#6330 fix: update preview port
  docs/config/index.md
  packages/vite/src/node/preview.ts
  scripts/jestPerTestSetup.ts
Labels: p2-nice-to-have :cake:

#6265 feat(import): Add TXT file format to assets
  packages/vite/client.d.ts
  packages/vite/src/node/constants.ts
Labels: p2-nice-to-have :cake:

#6324 feat(create-vite): tsconfig support vite.config.ts
  packages/create-vite/template-lit-ts/tsconfig.json
  packages/create-vite/template-lit-ts/tsconfig.node.json
  packages/create-vite/template-preact-ts/tsconfig.json
  packages/create-vite/template-preact-ts/tsconfig.node.json
  packages/create-vite/template-react-ts/tsconfig.json
  packages/create-vite/template-react-ts/tsconfig.node.json
  packages/create-vite/template-svelte-ts/tsconfig.json
  packages/create-vite/template-svelte-ts/tsconfig.node.json
  packages/create-vite/template-svelte-ts/vite.config.ts
  packages/create-vite/template-vanilla-ts/tsconfig.json
  packages/create-vite/template-vue-ts/tsconfig.json
  packages/create-vite/template-vue-ts/tsconfig.node.json
Labels: p2-nice-to-have :cake:

#6131 fix(create-vite): use `reset` for prompts for white bg color shell
  packages/create-vite/index.js
Labels: p2-nice-to-have :cake:

#6548 fix(ssr): should correctly transfrom identifier in ssr
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#6527 refactor: bundle json5
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/importGlob.ts
  pnpm-lock.yaml
Labels: p1-chore :broom:

#6551 docs(config): notes vite.config replace __dirname/__filename
  docs/config/index.md
Labels: documentation

#6532 chore: update postcss config loader
  packages/vite/package.json
  packages/vite/rollup.config.js
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#6556 chore: replace source-map with source-map-js
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/ssr/ssrStacktrace.ts
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#6566 fix(plugin-vue): compiler is `null` on rollup
  packages/plugin-vue/src/index.ts
Labels: plugin: vue

#6571 docs: fix typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#6353 fix(plugin-vue): make cssm code tree shakeable
  packages/playground/vue-lib/__tests__/serve.js
  packages/playground/vue-lib/__tests__/vue-lib.spec.ts
  packages/playground/vue-lib/index.html
  packages/playground/vue-lib/package.json
  packages/playground/vue-lib/src-consumer/index.ts
  packages/playground/vue-lib/src-lib/CompA.vue
  packages/playground/vue-lib/src-lib/CompB.vue
  packages/playground/vue-lib/src-lib/index.ts
  packages/playground/vue-lib/vite.config.consumer.ts
  packages/playground/vue-lib/vite.config.lib.ts
  packages/plugin-vue/src/main.ts
  pnpm-lock.yaml
Labels: feat: css, plugin: vue

#6590 chore: add homepage url and keywords to package.json
  package.json
Labels: p1-chore :broom:

#6589 fix(dev): Prevent stripping query params from CSS in HMR
  packages/playground/hmr/__tests__/hmr.spec.ts
  packages/playground/hmr/global.css
  packages/playground/hmr/hmr.js
  packages/playground/hmr/index.html
  packages/vite/src/client/client.ts
Labels: feat: hmr

#6270 feat: add lerna workspace support to `searchForWorkspaceRoot`
  docs/config/index.md
  packages/vite/src/node/server/__tests__/fixtures/lerna/lerna.json
  packages/vite/src/node/server/__tests__/fixtures/lerna/nested/package.json
  packages/vite/src/node/server/__tests__/search-root.spec.ts
  packages/vite/src/node/server/searchRoot.ts
Labels: p2-nice-to-have :cake:

#6492 fix: update SSR externals only when SSR is enabled (fix #6478)
  packages/vite/src/node/optimizer/registerMissing.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#6463 docs(contributing): re-create flow charts and provide sources
  .github/issue-workflow.excalidraw
  .github/issue-workflow.png
  .github/pr-workflow.excalidraw
  .github/pr-workflow.png
Labels: documentation, p1-chore :broom:

#6611 docs: delegate error handling to express’s error handler
  docs/guide/ssr.md
Labels: documentation

#6541 docs: reorder virtual modules convention
  docs/guide/api-plugin.md
Labels: documentation

#6584 fix(legacy): fix conflict with the modern build on css emitting
  packages/playground/legacy/__tests__/legacy.spec.ts
  packages/playground/legacy/main.js
  packages/playground/legacy/style.css
  packages/playground/legacy/vite.config.js
  packages/plugin-legacy/index.js
  packages/vite/src/node/plugins/css.ts
Labels: plugin: legacy

#6426 chore: avoid ts-node use tsconfig.json in ancestor's directory (fix #6409)
  scripts/tsconfig.json
Labels: p1-chore :broom:

#6680 fix: revert #5601 #6025, don't resolve rollupOptions.input
  packages/playground/backend-integration/vite.config.js
  packages/vite/LICENSE.md
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
Labels: p4-important :exclamation:

#6702 chore(deps): update esbuild to 0.14.14 in vite package
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#6701 chore(deps): update chokidar
  packages/vite/package.json
  packages/vite/src/node/index.ts
  packages/vite/types/chokidar.d.ts
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#6703 chore(deps): update dotenv-expand
  packages/vite/package.json
  packages/vite/src/node/config.ts
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:
