Repository vitejs/vite, pull requests merged in 2022-09, with the labels that each got.

#9773 fix(hmr): duplicated modules because of query params mismatch (fixes #2255)
  packages/vite/src/client/client.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/types/hmrPayload.d.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/hmr/importing-updated/a.js
  playground/hmr/importing-updated/b.js
  playground/hmr/importing-updated/index.js
  playground/hmr/index.html
Labels: feat: hmr, p4-important :exclamation:

#9941 refactor(create-vite): migrate to TypeScript
  package.json
  packages/create-vite/src/index.ts
  packages/create-vite/tsconfig.json
  pnpm-lock.yaml
Labels: p1-chore :broom:

#9976 fix(preview): send configured headers
  docs/config/preview-options.md
  packages/vite/src/node/preview.ts
  playground/fs-serve/__tests__/fs-serve.spec.ts
  playground/fs-serve/package.json
  playground/fs-serve/root/vite.config.js
Labels: p3-minor-bug :hammer:

#9971 fix: prevent error overlay style being overridden (fixes #9969)
  packages/vite/src/client/overlay.ts
Labels: p3-minor-bug :hammer:

#10045 fix: proxy to secured websocket server
  packages/vite/src/node/server/middlewares/proxy.ts
Labels: p3-minor-bug :hammer:

#10056 chore: cleanup old changelogs
  packages/vite/CHANGELOG.md
Labels: p1-chore :broom:

#10117 fix: no quote on attrs
  packages/vite/src/node/plugins/html.ts
  playground/html/__tests__/html.spec.ts
  playground/html/valid.html
  playground/html/valid.js
Labels: feat: html, p4-important :exclamation:

#10155 docs: remove heroku instructions
  docs/guide/static-deploy.md
Labels: documentation, p1-chore :broom:

#10154 fix: esbuildOutputFromId for symlinked root
  packages/vite/src/node/optimizer/index.ts
Labels: p3-minor-bug :hammer:

#10150 chore(create-vite): remove sourcemap, move --noEmit to tsconfig
  packages/create-vite/template-vanilla-ts/tsconfig.json
  packages/create-vite/template-vue-ts/package.json
  packages/create-vite/template-vue-ts/tsconfig.json
Labels: p1-chore :broom:

#10072 fix(plugin-legacy): force set `build.target`
  packages/plugin-legacy/build.config.ts
  packages/plugin-legacy/package.json
  packages/plugin-legacy/src/index.ts
  pnpm-lock.yaml
Labels: plugin: legacy, p4-important :exclamation:

#10158 docs(plugin-legacy): fix Vite default target
  packages/plugin-legacy/README.md
Labels: documentation

#10116 fix(lib): respect `rollupOptions.input` in lib mode
  packages/vite/src/node/build.ts
Labels: p4-important :exclamation:, feat: library mode

#10144 fix(hmr): dedupe virtual modules in module graph
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/utils.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/hmr/importedVirtual.js
  playground/hmr/index.html
  playground/hmr/vite.config.ts
  playground/ssr-html/__tests__/ssr-html.spec.ts
  playground/ssr-html/index.html
  playground/ssr-html/server.js
  playground/ssr-html/src/app.js
  playground/ssr-html/src/importedVirtual.js
Labels: feat: hmr, p3-downstream-blocker :hammer:

#9989 fix(build): fix resolution algorithm when `build.ssr` is true
  packages/vite/src/node/plugins/resolve.ts
  playground/ssr-resolve/__tests__/ssr-resolve.spec.ts
  playground/ssr-resolve/entries/dir/index.js
  playground/ssr-resolve/entries/file.js
  playground/ssr-resolve/entries/package.json
  playground/ssr-resolve/main.js
  playground/ssr-resolve/package.json
  playground/ssr-resolve/pkg-exports/entry.js
  playground/ssr-resolve/pkg-exports/index.js
  playground/ssr-resolve/pkg-exports/package.json
  playground/ssr-resolve/vite.config.js
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, feat: ssr

#10145 chore: remove duplicated logic in vanilla template
  packages/create-vite/template-vanilla-ts/src/counter.ts
  packages/create-vite/template-vanilla/counter.js
Labels: p1-chore :broom:

#9928 feat: include duplicate assets in the manifest
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/manifest.ts
Labels: p3-downstream-blocker :hammer:

#9949 fix: css order problem in async chunk
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/css/__tests__/css.spec.ts
  playground/css/async/async-1.css
  playground/css/async/async-1.js
  playground/css/async/async-2.css
  playground/css/async/async-2.js
  playground/css/async/async-3.js
  playground/css/async/async-3.module.css
  playground/css/async/base.css
  playground/css/async/base.js
  playground/css/async/index.js
  playground/css/main.js
Labels: feat: css, p4-important :exclamation:

#10044 perf: cache compiled glob for `server.fs.deny`
  docs/config/server-options.md
  package.json
  packages/vite/package.json
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/static.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#9860 fix: respect resolve.conditions, when resolving browser/require field
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-downstream-blocker :hammer:

#10200 fix(create-vite): remove baseUrl from Svelte configs
  packages/create-vite/template-svelte-ts/README.md
  packages/create-vite/template-svelte-ts/tsconfig.json
  packages/create-vite/template-svelte/README.md
  packages/create-vite/template-svelte/jsconfig.json
Labels: p3-minor-bug :hammer:

#10207 fix(esbuild): transpile with esnext in dev
  packages/plugin-vue/src/main.ts
  packages/vite/package.json
  packages/vite/src/node/plugins/esbuild.ts
  playground/vue/tsconfig.json
  pnpm-lock.yaml
Labels: p4-important :exclamation:

#10215 fix(esbuild): transpile with esnext in dev
  packages/vite/src/node/plugins/esbuild.ts
Labels: p4-important :exclamation:

#10071 fix: respect `mainFields` when resolving browser/module field (fixes #8659)
  docs/config/shared-options.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/ssrRequireHook.ts
  packages/vite/src/node/ssr/index.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-downstream-blocker :hammer:

#9970 fix: don't duplicate styles with dynamic import (fix #9967)
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/css-dynamic-import/__tests__/css-dynamic-import.spec.ts
  playground/css-dynamic-import/__tests__/serve.ts
  playground/css-dynamic-import/dynamic.css
  playground/css-dynamic-import/dynamic.js
  playground/css-dynamic-import/index.html
  playground/css-dynamic-import/index.js
  playground/css-dynamic-import/static.css
  playground/css-dynamic-import/static.js
  playground/test-utils.ts
Labels: feat: css, p3-minor-bug :hammer:

#8261 feat: dynamic import support ?url and ?worker
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/__snapshots__/parse.test.ts.snap
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/parse.test.ts
  packages/vite/src/node/plugins/dynamicImportVars.ts
  playground/dynamic-import/__tests__/dynamic-import.spec.ts
  playground/dynamic-import/alias/url.js
  playground/dynamic-import/alias/worker.js
  playground/dynamic-import/index.html
  playground/dynamic-import/nested/index.js
  playground/worker/worker/main-module.js
Labels: p2-nice-to-have :cake:

#10222 test: fix flaky tests
  playground/ssr-vue/__tests__/ssr-vue.spec.ts
Labels: test

#10220 fix(legacy): don't force set `build.target` when `renderLegacyChunks=false` (fixes #10201)
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy

#7837 feat(assets): allow `new URL` to resolve package assets
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
  playground/worker/index.html
  playground/worker/vite.config-es.js
  playground/worker/vite.config-iife.js
  playground/worker/vite.config-relative-base.js
  playground/worker/vite.config-sourcemap.js
  playground/worker/worker/main-module.js
Labels: p2-nice-to-have :cake:

#10230 docs: place `.nojekyll` when deploying to GitHub Pages
  docs/guide/static-deploy.md
Labels: documentation

#9938 feat: build.modulePreload options
  docs/config/build-options.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/worker.ts
  playground/preload/__tests__/preload-disabled/preload-disabled.spec.ts
  playground/preload/__tests__/preload-disabled/vite.config.js
  playground/preload/__tests__/resolve-deps/preload-resolve-deps.spec.ts
  playground/preload/__tests__/resolve-deps/vite.config.js
  playground/preload/package.json
  playground/preload/public/preloaded.js
  playground/preload/vite.config-preload-disabled.ts
  playground/preload/vite.config-resolve-deps.ts
Labels: p3-downstream-blocker :hammer:

#10231 docs: add trouble shooting section about file protocol
  docs/guide/troubleshooting.md
Labels: documentation

#10248 test: skip favicon log in debug serve
  playground/vitestSetup.ts
Labels: p1-chore :broom:, test

#10233 refactor(vue-jsx): remove `@babel/plugin-syntax-import-meta`
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue-jsx/src/index.ts
  pnpm-lock.yaml
Labels: plugin: vue-jsx, p1-chore :broom:

#10273 fix: isFromTsImporter flag in worker virtual model
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/worker.ts
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/modules/workerImport.ts
  playground/worker/my-worker.ts
  playground/worker/url-shared-worker.js
  playground/worker/worker/main-module.js
Labels: p3-significant 🔨

#10234 feat: customize ErrorOverlay
  packages/vite/src/client/overlay.ts
Labels: p2-nice-to-have :cake:

#10244 feat: support import.meta.hot.invalidate
  docs/guide/api-hmr.md
  packages/vite/src/client-types.d.ts
  packages/vite/src/client/client.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/types/customEvent.d.ts
  packages/vite/types/customEvent.d.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/hmr/index.html
  playground/hmr/invalidation/child.js
  playground/hmr/invalidation/parent.js
Labels: feat: hmr, p3-significant 🔨

#10243 refactor(types): simplify type exports
  .eslintignore
  .eslintrc.cjs
  .gitignore
  .prettierignore
  CONTRIBUTING.md
  docs/guide/api-plugin.md
  packages/vite/api-extractor.client.json
  packages/vite/client.d.ts
  packages/vite/import-meta.d.ts
  packages/vite/package.json
  packages/vite/scripts/patchTypes.ts
  packages/vite/scripts/postPatchTypes.ts
  packages/vite/scripts/prePatchTypes.ts
  packages/vite/scripts/util.ts
  packages/vite/src/client-types.d.ts
  packages/vite/src/dep-types/package.json
  packages/vite/src/node/__tests__/plugins/importGlob/__snapshots__/fixture.test.ts.snap
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-a/index.ts
  packages/vite/src/types/alias.d.ts
  packages/vite/src/types/anymatch.d.ts
  packages/vite/src/types/chokidar.d.ts
  packages/vite/src/types/commonjs.d.ts
  packages/vite/src/types/connect.d.ts
  packages/vite/src/types/customEvent.d.ts
  packages/vite/src/types/dynamicImportVars.d.ts
  packages/vite/src/types/hmrPayload.d.ts
  packages/vite/src/types/hot.d.ts
  packages/vite/src/types/http-proxy.d.ts
  packages/vite/src/types/importGlob.d.ts
  packages/vite/src/types/importMeta.d.ts
  packages/vite/src/types/shims.d.ts
  packages/vite/src/types/terser.d.ts
  packages/vite/src/types/ws.d.ts
  packages/vite/types/customEvent.d.ts
  packages/vite/types/hmrPayload.d.ts
  packages/vite/types/hot.d.ts
  packages/vite/types/importGlob.d.ts
  packages/vite/types/importMeta.d.ts
  playground/hmr/event.d.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#6705 feat: support postcss sugarss
  packages/vite/package.json
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/index.html
  playground/css/main.js
  playground/css/nested/nested.sss
  playground/css/package.json
  playground/css/sugarss.sss
  pnpm-lock.yaml
Labels: feat: css, p2-nice-to-have :cake:

#9748 fix: support process each out dir when there are two or more
  packages/vite/src/node/build.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#10298 fix(deps): update rollup to `^2.79.1`
  package.json
  packages/plugin-vue/package.json
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies

#9571 feat: add `throwIfNamespace` option for custom JSX runtime
  packages/plugin-react/src/index.ts
Labels: enhancement, p2-nice-to-have :cake:, plugin: react
