Repository vitejs/vite, pull requests merged in 2022-12, with the labels that each got.

#10242 fix: cacheDir should be ignored from watch
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/watch.ts
Labels: p3-minor-bug :hammer:

#11152 fix: add type for function localsConvention value
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-has-workaround :cake:

#11144 fix: Revert "fix: missing js sourcemaps with rewritten imports broke debugging (#7767) (#9476)"
  packages/vite/src/node/server/transformRequest.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
  playground/js-sourcemap/qux.js
Labels: possible regression

#11165 chore(deps): update to rollup 3.5
  package.json
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies

#11036 chore(client)!: remove never implemented hot.decline
  docs/guide/api-hmr.md
  packages/vite/src/client/client.ts
  packages/vite/types/hot.d.ts
Labels: feat: hmr, p1-chore :broom:

#11173 test: fix `css-dynamic-import` playground flakiness
  playground/css-dynamic-import/__tests__/css-dynamic-import.spec.ts
  playground/css-dynamic-import/package.json
Labels: p1-chore :broom:, test

#11174 test: improve `css-dynamic-import` playground test code
  playground/css-dynamic-import/__tests__/css-dynamic-import.spec.ts
Labels: p1-chore :broom:, test

#11176 test: migrate file-delete-restore playground test to hmr playground
  playground/file-delete-restore/App.jsx
  playground/file-delete-restore/Child.jsx
  playground/file-delete-restore/__tests__/file-delete-restore.spec.ts
  playground/file-delete-restore/index.html
  playground/file-delete-restore/package.json
  playground/file-delete-restore/vite.config.js
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/file-delete-restore/child.js
  playground/hmr/file-delete-restore/index.js
  playground/hmr/file-delete-restore/parent.js
  playground/hmr/file-delete-restore/runtime.js
  playground/hmr/hmr.ts
  playground/hmr/index.html
  pnpm-lock.yaml
Labels: p1-chore :broom:, test

#11195 chore: update @types/node to v18
  CONTRIBUTING.md
  package.json
  packages/vite/package.json
  packages/vite/scripts/checkBuiltTypes.ts
  packages/vite/tsconfig.check.json
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#11196 docs: add link to v3 docs
  docs/.vitepress/config.ts
Labels: documentation

#11177 test: remove jsx plugin from worker playground
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/modules/test-plugin.js
  playground/worker/modules/test-plugin.tsx
  playground/worker/package.json
  playground/worker/vite.config-es.js
  playground/worker/vite.config-iife.js
  playground/worker/vite.config-relative-base.js
  playground/worker/vite.config-sourcemap.js
  playground/worker/worker-plugin-test-plugin.js
  pnpm-lock.yaml
Labels: p1-chore :broom:, test

#11141 feat: improve the error message of `expand`
  packages/vite/src/node/env.ts
Labels: p2-nice-to-have :cake:

#11212 chore: add .git-blame-ignore-revs
  .git-blame-ignore-revs
  CONTRIBUTING.md
Labels: p1-chore :broom:

#11220 fix(config): resolve dynamic import as esm
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#11213 fix(env): prevent env expand on process.env
  package.json
  packages/vite/src/node/env.ts
  patches/dotenv-expand@9.0.0.patch
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#11237 fix(css): fix css lang regex
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/splitVendorChunk.ts
Labels: p4-important :exclamation:

#11239 test: skip multiple-entrypoint playground for now
  playground/multiple-entrypoints/__tests__/multiple-entrypoints.spec.ts
Labels: p1-chore :broom:, test

#11234 fix(resolve): ensure exports has precedence over mainFields
  packages/vite/src/node/plugins/resolve.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/exports-with-module/import.mjs
  playground/resolve/exports-with-module/module.mjs
  playground/resolve/exports-with-module/package.json
  playground/resolve/index.html
  playground/resolve/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#11250 fix(optimizer): escape entrypoints when running scanner
  packages/vite/src/node/optimizer/scan.ts
Labels: windows only, p4-important :exclamation:, feat: deps optimizer

#11251 refactor(optimizer): await depsOptimizer.scanProcessing
  packages/vite/src/node/optimizer/optimizer.ts
Labels: p1-chore :broom:

#11253 test: fix postcss-caching test flakiness
  playground/css/postcss-caching/css.spec.ts
Labels: p1-chore :broom:, test

#11252 test: fix preload flakiness
  playground/preload/vite.config-preload-disabled.ts
  playground/preload/vite.config-resolve-deps.ts
  playground/preload/vite.config.ts
Labels: p1-chore :broom:, test

#11254 ci: fix playwright cache
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#11255 ci: use node18 for windows/mac
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#11257 docs: remove ViteConf banner
  docs/.vitepress/theme/components/AsideSponsors.vue
Labels: documentation

#11070 fix(ssr): skip rewriting stack trace if it's already rewritten (fixes #11037)
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/ssr/__tests__/fixtures/modules/has-error.js
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
  packages/vite/src/node/ssr/__tests__/ssrStacktrace.spec.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/ssr/ssrStacktrace.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#11265 chore: update esbuild to 0.16.2
  packages/vite/package.json
  packages/vite/src/node/plugins/esbuild.ts
  pnpm-lock.yaml
Labels: p1-chore :broom:, breaking change

#11261 chore: add `\0` to virtual files id
  packages/vite/src/node/plugins/dynamicImportVars.ts
  packages/vite/src/node/plugins/modulePreloadPolyfill.ts
  packages/vite/src/node/plugins/wasm.ts
Labels: p2-nice-to-have :cake:

#11267 chore(esbuild): add test for configuration overrides
  packages/vite/src/node/__tests__/plugins/esbuild.spec.ts
Labels: p1-chore :broom:, test

#10564 fix: check if build exists so preview doesn't show 404s due to nonexistent build
  packages/vite/src/node/preview.ts
Labels: p2-nice-to-have :cake:

#11311 chore: fix format
  packages/vite/src/node/preview.ts
Labels: p1-chore :broom:

#11301 fix: derive `useDefineForClassFields` value from `tsconfig.compilerOptions.target` (fixes #10296)
  docs/guide/features.md
  packages/vite/src/node/__tests__/plugins/esbuild.spec.ts
  packages/vite/src/node/plugins/esbuild.ts
Labels: p4-important :exclamation:

#11310 docs(migration): add section for build node env
  docs/guide/migration.md
Labels: documentation

#11305 docs: add client types hint in static assets guide
  docs/guide/assets.md
Labels: documentation

#11315 test: run preview.headers test
  playground/fs-serve/__tests__/fs-serve.spec.ts
Labels: p1-chore :broom:, test

#11316 test: fix custom serve teardown
  playground/vitestSetup.ts
Labels: p1-chore :broom:, test

#11319 feat: show server url by pressing `u`
  packages/vite/src/node/shortcuts.ts
Labels: p2-nice-to-have :cake:

#11326 chore: enable `@typescript-eslint/ban-ts-comment`
  .eslintrc.cjs
  packages/plugin-legacy/src/index.ts
  packages/vite/src/node/__tests__/plugins/css.spec.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/esbuild.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/terser.ts
  packages/vite/src/node/plugins/wasm.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/server/__tests__/pluginContainer.spec.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/compression.ts
  packages/vite/src/node/server/middlewares/time.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/utils.ts
  packages/vite/src/types/shims.d.ts
  playground/hmr/hmr.ts
  playground/hmr/modules.d.ts
  playground/legacy/vite.config.js
  playground/ssr-noexternal/server.js
  playground/vitestSetup.ts
  playground/worker/my-shared-worker.ts
Labels: p1-chore :broom:

#11309 fix(env): test NODE_ENV override before expand
  packages/vite/src/node/__tests__/env.spec.ts
  packages/vite/src/node/__tests__/env/.env.testing
  packages/vite/src/node/env.ts
Labels: p4-important :exclamation:

#11312 fix: preview fallback
  package.json
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/utils.ts
  patches/sirv@2.0.2.patch
  playground/assets/__tests__/assets.spec.ts
  playground/assets/static/bar
  pnpm-lock.yaml
Labels: p4-important :exclamation:, possible regression

#11337 fix: respect base when using `/__open-in-editor`
  packages/vite/src/client/overlay.ts
  packages/vite/src/node/plugins/clientInjections.ts
Labels: p3-minor-bug :hammer:

#11290 fix: wrongly resolve to optimized doppelganger
  packages/vite/src/node/plugins/resolve.ts
  playground/resolve-optimized-dup-deps/__tests__/resolve-optimized-dup-deps.spec.ts
  playground/resolve-optimized-dup-deps/index.html
  playground/resolve-optimized-dup-deps/package-a/index.js
  playground/resolve-optimized-dup-deps/package-a/package.json
  playground/resolve-optimized-dup-deps/package-b-v1/index.js
  playground/resolve-optimized-dup-deps/package-b-v1/package.json
  playground/resolve-optimized-dup-deps/package-b-v2/index.js
  playground/resolve-optimized-dup-deps/package-b-v2/package.json
  playground/resolve-optimized-dup-deps/package.json
  playground/resolve-optimized-dup-deps/vite.config.js
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, feat: deps optimizer

#11347 fix: ?inline warning for .css.js file
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/css/__tests__/css.spec.ts
  playground/css/index.html
  playground/css/jsfile.css.js
  playground/css/main.js
Labels: p4-important :exclamation:

#11334 feat(html): clickable error position for html parse error
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: feat: html, p2-nice-to-have :cake:

#11367 fix: fix the error message in the `toOutputFilePathWithoutRuntime` function
  packages/vite/src/node/build.ts
Labels: p1-chore :broom:

#11369 test(css): improve test around deprecated default/named import
  playground/css/__tests__/css.spec.ts
  playground/css/imported-inline.css
  playground/css/main.js
  playground/css/vite.config.js
Labels: p1-chore :broom:, test

#11260 docs: specify that 'worker' means 'web worker'
  docs/config/worker-options.md
Labels: documentation

#11415 docs: fix typo succeful
  docs/guide/api-hmr.md
Labels: documentation

#8944 feat: allow import.meta.hot define override
  packages/vite/src/node/__tests__/plugins/define.spec.ts
  packages/vite/src/node/plugins/define.ts
Labels: feat: hmr, p2-nice-to-have :cake:

#11409 fix(ssr): ignore module exports condition
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  playground/ssr-deps/__tests__/ssr-deps.spec.ts
  playground/ssr-deps/module-condition/import.mjs
  playground/ssr-deps/module-condition/module.js
  playground/ssr-deps/module-condition/package.json
  playground/ssr-deps/package.json
  playground/ssr-deps/src/app.js
  pnpm-lock.yaml
Labels: p4-important :exclamation:, feat: ssr

#11452 test: remove vue plugin from optimize-deps playground
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  playground/optimize-deps/vite.config.js
  pnpm-lock.yaml
Labels: p1-chore :broom:, test

#11451 test: remove vue plugin from preload playground
  playground/preload/__tests__/preload-disabled/preload-disabled.spec.ts
  playground/preload/__tests__/preload.spec.ts
  playground/preload/__tests__/resolve-deps/preload-resolve-deps.spec.ts
  playground/preload/index.html
  playground/preload/package.json
  playground/preload/router.js
  playground/preload/src/App.vue
  playground/preload/src/about.js
  playground/preload/src/components/About.vue
  playground/preload/src/components/Hello.vue
  playground/preload/src/components/Home.vue
  playground/preload/src/hello.js
  playground/preload/src/hello.module.css
  playground/preload/src/main.js
  playground/preload/vite.config-preload-disabled.ts
  playground/preload/vite.config-resolve-deps.ts
  playground/preload/vite.config.ts
  pnpm-lock.yaml
Labels: p1-chore :broom:, test

#11145 fix: stop considering parent URLs as public file
  packages/vite/src/node/plugins/asset.ts
Labels: p3-minor-bug :hammer:

#11476 chore: update license
  packages/vite/LICENSE.md
Labels: p1-chore :broom:

#11475 fix(build): invalidate chunk hash when css changed
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/__tests__/packages/build-project/index.html
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:, feat: build

#11477 chore(docs): workaround netlify pnpm build issue
  netlify.toml
Labels: p1-chore :broom:

#11343 fix(ssr): emit js sourcemaps for ssr builds
  packages/vite/src/node/plugins/asset.ts
Labels: p4-important :exclamation:, feat: ssr
