Repository vitejs/vite, pull requests merged in 2022-04, with the labels that each got.

#7596 docs(legacy): note works in build only
  packages/plugin-legacy/README.md
Labels: documentation

#7595 fix: detect env hmr
  packages/vite/src/node/server/hmr.ts
Labels: p3-minor-bug :hammer:

#7605 fix: update ws types
  packages/vite/src/node/server/ws.ts
Labels: p3-minor-bug :hammer:

#7604 fix: use correct proxy config in preview
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/proxy.ts
Labels: p3-minor-bug :hammer:

#7561 fix: fix HMR propagation when imports not analyzed
  packages/playground/hmr/__tests__/hmr.spec.ts
  packages/playground/hmr/dynamic-import/dep.ts
  packages/playground/hmr/dynamic-import/index.html
  packages/playground/hmr/dynamic-import/index.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/moduleGraph.ts
Labels: feat: hmr, p3-downstream-blocker :hammer:

#7523 test: fix server port conflict
  packages/playground/cli-module/__tests__/serve.js
  packages/playground/cli/__tests__/serve.js
  packages/playground/css/__tests__/postcss-plugins-different-dir.spec.ts
  packages/playground/css/postcss-caching/css.spec.ts
  packages/playground/legacy/__tests__/ssr/serve.js
  packages/playground/lib/__tests__/serve.js
  packages/playground/optimize-missing-deps/__test__/serve.js
  packages/playground/ssr-deps/__tests__/serve.js
  packages/playground/ssr-html/__tests__/serve.js
  packages/playground/ssr-pug/__tests__/serve.js
  packages/playground/ssr-react/__tests__/serve.js
  packages/playground/ssr-vue/__tests__/serve.js
  packages/playground/ssr-webworker/__tests__/serve.js
  packages/playground/testUtils.ts
Labels: p1-chore :broom:

#7400 fix(less): handles rewriting relative paths passed Less's `data-uri` function.
  packages/playground/css/__tests__/css.spec.ts
  packages/playground/css/index.html
  packages/playground/css/less.less
  packages/playground/css/less/components/form.less
  packages/playground/css/less/images/backgrounds/form-select.svg
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#7612 fix: EACCES permission denied due to resolve new paths default
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#7655 chore: update @types/react version
  packages/create-vite/template-react-ts/package.json
  packages/create-vite/template-react/package.json
Labels: p1-chore :broom:, plugin: react

#7650 fix: nested comments and strings, new regexp utils
  CONTRIBUTING.md
  packages/vite/src/node/__tests__/cleanString.spec.ts
  packages/vite/src/node/cleanString.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#7678 fix(css): hoist charset
  packages/playground/css/__tests__/css.spec.ts
  packages/playground/css/charset.css
  packages/playground/css/index.html
  packages/playground/css/main.js
  packages/vite/src/node/plugins/css.ts
Labels: p2-nice-to-have :cake:

#7132 fix: update watch mode
  packages/playground/assets/__tests__/assets.spec.ts
  packages/playground/assets/css/foo.module.css
  packages/playground/assets/index.html
  packages/playground/assets/static/foo.txt
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/ensureWatch.ts
  packages/vite/src/node/plugins/index.ts
  scripts/jestPerTestSetup.ts
Labels: p3-minor-bug :hammer:

#7667 feat: clean string module lex string template
  packages/vite/src/node/__tests__/cleanString.spec.ts
  packages/vite/src/node/cleanString.ts
Labels: p3-minor-bug :hammer:

#7665 fix: `$ vite preview` 404 handling
  packages/vite/src/node/preview.ts
Labels: p2-to-be-discussed :cake:

#7702 chore: type unknown env as any
  docs/guide/env-and-mode.md
  packages/vite/types/importMeta.d.ts
Labels: p1-chore :broom:

#6876 feat: explicit the word boundary
  packages/playground/assets/__tests__/assets.spec.ts
  packages/playground/assets/index.html
  packages/vite/src/node/plugins/html.ts
Labels: p2-nice-to-have :cake:

#7646 feat: optimizeDeps.disabled
  packages/playground/vue-jsx/vite.config.js
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/server/index.ts
Labels: p3-downstream-blocker :hammer:

#7705 fix(ssr): properly transform export default with expressions
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#7757 fix(ssr): rewrite dynamic class method name (fix #7751)
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-downstream-blocker :hammer:, feat: ssr

#7759 refactor(legacy): remove unneeded dynamic import var init code
  packages/plugin-legacy/README.md
  packages/plugin-legacy/index.js
Labels: plugin: legacy, p1-chore :broom:

#7771 test: fix properly use terser for preload test
  packages/playground/preload/vite.config.js
Labels: p1-chore :broom:, test

#6840 feat: enable optimizeDeps.esbuildOptions.loader
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/scan.ts
Labels: p2-nice-to-have :cake:

#7726 chore(create-vite): set skipLibCheck true
  packages/create-vite/template-lit-ts/tsconfig.json
  packages/create-vite/template-preact-ts/tsconfig.json
  packages/create-vite/template-react-ts/tsconfig.json
  packages/create-vite/template-vanilla-ts/tsconfig.json
  packages/create-vite/template-vue-ts/tsconfig.json
Labels: p1-chore :broom:

#7785 docs: explain skipLibCheck
  docs/guide/features.md
Labels: documentation

#7794 docs: import.meta.url is replaced even if ESM
  docs/config/index.md
Labels: documentation

#7792 fix: correctly replace import.meta.url in config
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#7793 docs: add link to "Using Plugins" from Plugins section
  docs/plugins/index.md
Labels: documentation

#7805 chore: worker sourcemap output style
  packages/vite/src/node/plugins/reporter.ts
Labels: feat: web workers

#7826 ci: use action-semantic-pull-request
  .github/workflows/semantic-pull-request.yml
Labels: p1-chore :broom:

#7816 fix: modulepreload polyfill only during build (fix #4786)
  packages/playground/backend-integration/__tests__/backend-integration.spec.ts
  packages/playground/backend-integration/frontend/entrypoints/main.ts
  packages/vite/src/node/plugins/modulePreloadPolyfill.ts
  scripts/jestPerTestSetup.ts
Labels: p4-important :exclamation:

#7710 docs: declaration test env different with production
  CONTRIBUTING.md
  scripts/jestPerTestSetup.ts
Labels: documentation

#7813 fix: ssr.noExternal with boolean values
  packages/playground/ssr-webworker/vite.config.js
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#7834 fix: escape character in string regexp match
  packages/vite/src/node/__tests__/cleanString.spec.ts
  packages/vite/src/node/cleanString.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
Labels: p3-minor-bug :hammer:

#7787 docs(api-hmr): update hmr hot type
  docs/guide/api-hmr.md
Labels: documentation

#7825 fix: update sourcemap in importAnalysisBuild
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/server/sourcemap.ts
  packages/vite/src/node/utils.ts
Labels: bug, p3-minor-bug :hammer:

#7786 fix: style use string instead of js import
  packages/playground/worker/__tests__/es/es-worker.spec.ts
  packages/playground/worker/__tests__/iife/worker.spec.ts
  packages/playground/worker/__tests__/sourcemap-hidden/sourcemap-hidden-worker.spec.ts
  packages/playground/worker/__tests__/sourcemap-inline/sourcemap-inline-worker.spec.ts
  packages/playground/worker/__tests__/sourcemap/sourcemap-worker.spec.ts
  packages/vite/src/node/plugins/html.ts
Labels: feat: css

#7812 build: add node v18 support
  .github/workflows/ci.yml
  package.json
  packages/vite/package.json
  packages/vite/src/node/logger.ts
  pnpm-lock.yaml
Labels: enhancement, p2-nice-to-have :cake:, on hold

#7871 fix: clean string regexp
  packages/vite/src/node/__tests__/cleanString.spec.ts
  packages/vite/src/node/cleanString.ts
Labels: p3-minor-bug :hammer:

#7895 fix: HMR propagation of HTML changes (fix #7870)
  packages/playground/hmr/__tests__/hmr.spec.ts
  packages/playground/hmr/counter/dep.ts
  packages/playground/hmr/counter/index.html
  packages/playground/hmr/counter/index.ts
  packages/vite/src/node/server/moduleGraph.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#7885 docs: update link to postcss-nesting
  docs/guide/features.md
Labels: documentation

#7706 fix(worker): import.meta.*
  packages/playground/worker/__tests__/es/es-worker.spec.ts
  packages/playground/worker/__tests__/iife/worker.spec.ts
  packages/playground/worker/__tests__/sourcemap-hidden/sourcemap-hidden-worker.spec.ts
  packages/playground/worker/__tests__/sourcemap-inline/sourcemap-inline-worker.spec.ts
  packages/playground/worker/__tests__/sourcemap/sourcemap-worker.spec.ts
  packages/playground/worker/classic-shared-worker.js
  packages/playground/worker/classic-worker.js
  packages/playground/worker/emit-chunk-dynamic-import-worker.js
  packages/playground/worker/emit-chunk-nested-worker.js
  packages/playground/worker/emit-chunk-sub-worker.js
  packages/playground/worker/importMetaGlob.worker.js
  packages/playground/worker/importMetaGlobEager.worker.js
  packages/playground/worker/index.html
  packages/playground/worker/module-and-worker.js
  packages/playground/worker/modules/module0.js
  packages/playground/worker/modules/module2.js
  packages/playground/worker/modules/module3.js
  packages/playground/worker/my-shared-worker.ts
  packages/playground/worker/my-worker.ts
  packages/playground/worker/possible-ts-output-worker.mjs
  packages/playground/worker/sub-worker.js
  packages/playground/worker/url-shared-worker.js
  packages/playground/worker/url-worker.js
  packages/playground/worker/worker-nested-worker.js
  packages/playground/worker/worker/main-format-es.js
  packages/playground/worker/worker/main-module.js
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/worker.ts
Labels: p3-minor-bug :hammer:, feat: web workers

#7865 docs: `server.origin` config trailing slash (fix #6622)
  docs/config/index.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/server/index.ts
Labels: documentation

#7924 fix(css): clean comments before hoist at rules
  packages/vite/src/node/__tests__/plugins/css.spec.ts
  packages/vite/src/node/cleanString.ts
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#7872 docs: clarify loadEnv
  docs/config/index.md
Labels: documentation

#7673 fix: use NODE_ENV in optimizer
  packages/playground/optimize-deps/.env
  packages/playground/optimize-deps/__tests__/optimize-deps.spec.ts
  packages/playground/optimize-deps/dep-node-env/index.js
  packages/playground/optimize-deps/dep-node-env/package.json
  packages/playground/optimize-deps/index.html
  packages/playground/optimize-deps/package.json
  packages/vite/src/node/optimizer/index.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, plugin: react

#7934 chore(css): catch postcss config error (fix #2793)
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p1-chore :broom:

#7935 fix(css): support postcss.config.ts
  packages/playground/tailwind/package.json
  packages/playground/tailwind/postcss.config.ts
  packages/vite/rollup.config.js
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#7962 chore: add core.symlinks description to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: p1-chore :broom:

#7948 fix: inject esbuild helpers in IIFE and UMD wrappers
  packages/playground/lib/__tests__/lib.spec.ts
  packages/playground/lib/src/main.js
  packages/vite/src/node/plugins/esbuild.ts
Labels: p3-minor-bug :hammer:, feat: library mode

#7869 fix: style hmr reduce replace style code
  packages/playground/assets/__tests__/assets.spec.ts
  packages/playground/assets/index.html
  packages/playground/css-sourcemap/__tests__/serve.spec.ts
  packages/playground/hmr/__tests__/hmr.spec.ts
  packages/playground/hmr/icon.png
  packages/playground/hmr/index.html
  packages/playground/ssr-html/index.html
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: feat: css, feat: hmr, p2-has-workaround :cake:

#7177 fix(ssr): failed ssrLoadModule call throws same error
  packages/vite/src/node/server/moduleGraph.ts
  packages/vite/src/node/ssr/__tests__/fixtures/ssrModuleLoader-bad.js
  packages/vite/src/node/ssr/__tests__/ssrModuleLoader.spec.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#7971 feat(create-vite): scaffold directory with only .git
  packages/create-vite/index.js
Labels: p2-nice-to-have :cake:
