Repository vitejs/vite, pull requests merged in 2022-02, with the labels that each got.

#6750 feat(plugin-react): ensure `overrides` array exists before `api.reactBabel` hooks are called
  packages/plugin-react/src/index.ts
Labels: plugin: react

#6764 fix(ssr): skip vite resolve for windows absolute path
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#6788 chore: prefer using weakmap over writing field on nodes
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p1-chore :broom:

#6785 chore: ensure local package private
  packages/create-vite/template-lit-ts/package.json
  packages/create-vite/template-lit/package.json
  packages/create-vite/template-preact-ts/package.json
  packages/create-vite/template-preact/package.json
  packages/create-vite/template-react-ts/package.json
  packages/create-vite/template-react/package.json
  packages/create-vite/template-svelte-ts/package.json
  packages/create-vite/template-svelte/package.json
  packages/create-vite/template-vanilla-ts/package.json
  packages/create-vite/template-vanilla/package.json
  packages/create-vite/template-vue-ts/package.json
  packages/create-vite/template-vue/package.json
  packages/playground/css/css-dep/package.json
  packages/playground/css/pkg-dep/package.json
  packages/playground/nested-deps/test-package-a/package.json
  packages/playground/nested-deps/test-package-b/package.json
  packages/playground/nested-deps/test-package-c/package.json
  packages/playground/nested-deps/test-package-d/package.json
  packages/playground/nested-deps/test-package-d/test-package-d-nested/package.json
  packages/playground/nested-deps/test-package-e/package.json
  packages/playground/nested-deps/test-package-e/test-package-e-excluded/package.json
  packages/playground/nested-deps/test-package-e/test-package-e-included/package.json
  packages/playground/optimize-deps/dep-cjs-compiled-from-cjs/package.json
  packages/playground/optimize-deps/dep-cjs-compiled-from-esm/package.json
  packages/playground/optimize-deps/dep-esbuild-plugin-transform/package.json
  packages/playground/optimize-deps/dep-linked-include/package.json
  packages/playground/optimize-deps/dep-linked/package.json
  packages/playground/optimize-deps/nested-exclude/nested-include/package.json
  packages/playground/optimize-deps/nested-exclude/package.json
  packages/playground/optimize-missing-deps/missing-dep/package.json
  packages/playground/optimize-missing-deps/multi-entry-dep/package.json
  packages/playground/package.json
  packages/playground/preserve-symlinks/moduleA/package.json
  packages/playground/preserve-symlinks/package.json
  packages/playground/resolve-config/package.json
  packages/playground/resolve-linked/package.json
  packages/playground/resolve/browser-field/package.json
  packages/playground/resolve/custom-condition/package.json
  packages/playground/resolve/custom-main-field/package.json
  packages/playground/resolve/exports-env/package.json
  packages/playground/resolve/exports-path/package.json
  packages/playground/resolve/inline-package/package.json
  packages/playground/ssr-deps/define-properties-exports/package.json
  packages/playground/ssr-deps/define-property-exports/package.json
  packages/playground/ssr-deps/forwarded-export/package.json
  packages/playground/ssr-deps/object-assigned-exports/package.json
  packages/playground/ssr-deps/only-object-assigned-exports/package.json
  packages/playground/ssr-deps/primitive-export/package.json
  packages/playground/ssr-deps/read-file-content/package.json
  packages/playground/ssr-deps/require-absolute/package.json
  packages/playground/ssr-deps/ts-transpiled-exports/package.json
  packages/playground/ssr-vue/dep-import-type/package.json
Labels: p1-chore :broom:

#6826 docs(static-deploy): update preview port
  docs/guide/static-deploy.md
Labels: documentation

#6854 docs: correct wording
  docs/guide/env-and-mode.md
Labels: p1-chore :broom:

#6843 chore: add timeouts to ci job to avoid dangling runs for 6 hours
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#6844 docs: change worker config to object instead of array
  packages/vite/CHANGELOG.md
Labels: documentation

#6857 docs: Rename empty git repo from master to main
  docs/guide/static-deploy.md
Labels: documentation

#6781 chore: remove cancelled sponsor img
  docs/public/finclip.png
Labels: p1-chore :broom:

#6669 chore: release action
  .github/workflows/release.yml
  scripts/release.ts
Labels: p1-chore :broom:

#6869 fix(plugin-legacy): require Vite 2.8.0 (#6272)
  packages/plugin-legacy/package.json
Labels: plugin: legacy

#5073 feat: Make `import.meta.glob` and `import.meta.globEager` generic
  packages/vite/types/importMeta.d.ts
Labels: p2-nice-to-have :cake:

#6868 perf: improve isFileReadable performance
  packages/vite/src/node/utils.ts
Labels: p4-important :exclamation:

#6667 feat: custom manifest file name
  docs/config/index.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/plugins/manifest.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
Labels: p2-nice-to-have :cake:

#6786 chore(types): correct typing in jestPerTestSetup
  scripts/jestPerTestSetup.ts
  scripts/tsconfig.json
Labels: p1-chore :broom:

#6934 fix: revert update dotenv-expand #6703, fix #6858
  packages/vite/package.json
  packages/vite/src/node/config.ts
  pnpm-lock.yaml
Labels: p4-important :exclamation:

#6936 chore(deps): avoid updating dotenv-expand to v6+
  .github/renovate.json5
Labels: dependencies, p1-chore :broom:

#6945 docs: add backticks
  docs/config/index.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
Labels: documentation

#6959 fix: normalize postcss dependency messages
  packages/playground/tailwind/__test__/tailwind.spec.ts
  packages/playground/tailwind/src/App.vue
  packages/playground/tailwind/tailwind.config.js
  packages/vite/src/node/plugins/css.ts
Labels: feat: css

#6991 docs(cli): add command descriptions
  packages/vite/src/node/cli.ts
Labels: p1-chore :broom:

#6895 fix: recycle serve to avoid preventing Node self-exit
  packages/vite/src/node/plugins/esbuild.ts
Labels: p3-minor-bug :hammer:

#7006 fix: prebundle dep with colon
  packages/playground/optimize-deps/__tests__/optimize-deps.spec.ts
  packages/playground/optimize-deps/index.html
  packages/playground/optimize-deps/package.json
  packages/playground/optimize-deps/vite.config.js
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#6949 fix(glob): css imports injecting a ?used query to export the css string
  packages/playground/css/__tests__/css.spec.ts
  packages/playground/css/glob-import/bar.css
  packages/playground/css/glob-import/foo.css
  packages/playground/css/index.html
  packages/playground/css/main.js
  packages/vite/src/node/importGlob.ts
Labels: feat: css

#7008 docs: update pre-bundling guide
  docs/guide/dep-pre-bundling.md
Labels: documentation, p1-chore :broom:

#6983 fix: allow optional trailing comma in asset `import.meta.url`
  packages/playground/assets/index.html
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
Labels: p3-minor-bug :hammer:

#7034 fix: don't override user config
  packages/vite/src/node/http.ts
Labels: p3-minor-bug :hammer:

#7031 fix: resolve @import of the proxied <style>
  packages/playground/assets/index.html
  packages/playground/assets/static/foo.css
  packages/vite/src/node/plugins/css.ts
Labels: p3-minor-bug :hammer:, possible regression

#6568 fix(plugin-vue): setup jsx script no hmr
  packages/playground/vue-jsx/__tests__/vue-jsx.spec.ts
  packages/playground/vue-jsx/main.jsx
  packages/playground/vue-jsx/setup-syntax-jsx.vue
  packages/plugin-vue/src/handleHotUpdate.ts
Labels: feat: hmr, plugin: vue

#7052 fix(hmr): hmr style tag no support in html
  packages/playground/assets/__tests__/assets.spec.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: feat: hmr, feat: html

#7073 fix: import with query with exports field
  packages/playground/resolve/__tests__/resolve.spec.ts
  packages/playground/resolve/exports-path/deep.json
  packages/playground/resolve/exports-path/package.json
  packages/playground/resolve/index.html
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug :hammer:

#7048 feat: add fixStacktrace option to ssrLoadModule
  docs/guide/api-javascript.md
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-downstream-blocker :hammer:, feat: ssr

#7093 fix: `?html-proxy` with trailing `=` added by some servers
  packages/vite/src/node/plugins/html.ts
Labels: p3-minor-bug :hammer:

#6407 fix(ssrTransform): continuous exports parsing error
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#7121 fix(vue-jsx): support jsx imports with queries
  packages/playground/vue-jsx/Query.jsx
  packages/playground/vue-jsx/__tests__/vue-jsx.spec.ts
  packages/playground/vue-jsx/main.jsx
  packages/playground/vue-jsx/vite.config.js
  packages/plugin-vue-jsx/index.js
Labels: plugin: vue-jsx, p3-downstream-blocker :hammer:
