Repository vitejs/vite, pull requests merged in 2022-08, with the labels that each got.

#9457 fix: ignore tsconfig target when bundling config
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#9473 fix(config): use file url for import path (fixes #9471)
  packages/vite/src/node/config.ts
Labels: bug, windows only, p3-minor-bug :hammer:

#9468 chore: tidy up eslint config
  .eslintrc.cjs
  package.json
  packages/create-vite/template-lit-ts/src/my-element.ts
  packages/create-vite/template-lit/src/my-element.js
  packages/vite/rollup.config.ts
  playground/css/main.js
  playground/css/postcss.config.js
  playground/json/server.js
  playground/resolve/browser-field/relative.js
  playground/tailwind/__test__/tailwind.spec.ts
  playground/tailwind/src/router.ts
  playground/wasm/worker.js
  playground/worker/my-worker.ts
  pnpm-lock.yaml
Labels: p1-chore :broom:

#9480 chore: remove unused deps
  package.json
  playground/package.json
  pnpm-lock.yaml
Labels: p1-chore :broom:

#9489 fix: update dep types (fixes #9475)
  packages/vite/types/commonjs.d.ts
  packages/vite/types/connect.d.ts
  packages/vite/types/http-proxy.d.ts
  packages/vite/types/terser.d.ts
Labels: p2-has-workaround :cake:

#9488 docs: override `vite/client` type
  docs/guide/features.md
Labels: documentation

#9514 chore: node prefix lint
  .eslintrc.cjs
  packages/vite/bin/vite.js
  packages/vite/src/node/http.ts
  packages/vite/src/node/logger.ts
  packages/vite/src/node/plugins/ssrRequireHook.ts
  packages/vite/types/ws.d.ts
  playground/alias/vite.config.js
  playground/assets/vite.config-runtime-base.js
  playground/assets/vite.config.js
  playground/backend-integration/vite.config.js
  playground/css-codesplit-cjs/vite.config.js
  playground/css-codesplit/vite.config.js
  playground/css/postcss.config.js
  playground/css/vite.config.js
  playground/dynamic-import/vite.config.js
  playground/fs-serve/root/vite.config.js
  playground/html/vite.config.js
  playground/json/server.js
  playground/legacy/vite.config.js
  playground/lib/vite.config.js
  playground/lib/vite.dyimport.config.js
  playground/multiple-entrypoints/vite.config.js
  playground/optimize-deps/dep-with-builtin-module-cjs/index.js
  playground/optimize-deps/dep-with-builtin-module-esm/index.js
  playground/optimize-deps/vite.config.js
  playground/optimize-missing-deps/multi-entry-dep/index.js
  playground/optimize-missing-deps/server.js
  playground/resolve/browser-field/multiple.dot.path.js
  playground/resolve/browser-field/not-browser.js
  playground/ssr-deps/import-builtin-cjs/index.js
  playground/ssr-deps/read-file-content/index.js
  playground/ssr-deps/require-absolute/index.js
  playground/ssr-deps/server.js
  playground/ssr-html/server.js
  playground/ssr-pug/server.js
  playground/ssr-react/prerender.js
  playground/ssr-react/server.js
  playground/ssr-vue/server.js
  playground/ssr-vue/vite.config.js
  playground/ssr-webworker/worker.js
  playground/worker/vite.config-relative-base.js
Labels: p1-chore :broom:

#9577 fix(config): try catch unlink after load
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#9560 docs: miscellaneous fixes
  docs/guide/build.md
  docs/guide/features.md
  docs/guide/ssr.md
  docs/guide/troubleshooting.md
Labels: documentation

#9526 docs: add git option for netlify deployment
  docs/guide/static-deploy.md
Labels: documentation

#9554 fix(ssr): use appendRight for import
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#9517 docs: add Render deployment instructions
  docs/guide/static-deploy.md
Labels: documentation

#9547 fix: allow tree-shake glob eager css in js
  packages/vite/src/node/__tests__/plugins/importGlob/__snapshots__/fixture.test.ts.snap
  packages/vite/src/node/plugins/importMetaGlob.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/glob-import/index.html
  playground/glob-import/no-tree-shake.css
  playground/glob-import/tree-shake.css
Labels: p2-nice-to-have :cake:

#9516 test: refactor test a bit
  playground/ssr-deps/read-file-content/index.js
  playground/ssr-webworker/package.json
  playground/ssr-webworker/src/entry-worker.jsx
  pnpm-lock.yaml
Labels: p1-chore :broom:

#9494 fix(ssr): check root import extension for external
  packages/vite/src/node/plugins/resolve.ts
  playground/ssr-deps/__tests__/ssr-deps.spec.ts
  playground/ssr-deps/css-lib/index.css
  playground/ssr-deps/css-lib/package.json
  playground/ssr-deps/index.html
  playground/ssr-deps/package.json
  playground/ssr-deps/src/app.js
  pnpm-lock.yaml
Labels: feat: ssr, p3-significant 🔨

#9381 fix: avoid using `import.meta.url` for relative assets if output is not ESM (fixes #9297)
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/worker.ts
  playground/legacy/__tests__/legacy.spec.ts
  playground/legacy/index.html
  playground/legacy/main.js
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
  playground/worker/__tests__/relative-base/relative-base-worker.spec.ts
  playground/worker/__tests__/sourcemap-hidden/sourcemap-hidden-worker.spec.ts
  playground/worker/__tests__/sourcemap-inline/sourcemap-inline-worker.spec.ts
  playground/worker/__tests__/sourcemap/sourcemap-worker.spec.ts
  playground/worker/index.html
  playground/worker/my-worker.ts
  playground/worker/vite.svg
  playground/worker/worker/main-module.js
Labels: p4-important :exclamation:

#9500 fix: legacy no emit worker
  packages/vite/src/node/plugins/worker.ts
  playground/legacy/__tests__/legacy.spec.ts
  playground/legacy/index.html
  playground/legacy/main.js
  playground/legacy/module.js
  playground/legacy/worker.js
Labels: plugin: legacy, p4-important :exclamation:, feat: web workers

#9509 fix(optimizer): ignore EACCES errors while scanner (fixes #8916)
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug :hammer:

#9459 fix: use browser field if it is not likely UMD or CJS (fixes #9445)
  packages/vite/src/node/plugins/resolve.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/browser-module-field1/index.js
  playground/resolve/browser-module-field1/index.web.js
  playground/resolve/browser-module-field1/package.json
  playground/resolve/browser-module-field2/index.js
  playground/resolve/browser-module-field2/index.web.js
  playground/resolve/browser-module-field2/package.json
  playground/resolve/index.html
  playground/resolve/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#9324 feat: show warning on 431 response
  docs/guide/troubleshooting.md
  packages/vite/src/node/http.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
Labels: enhancement, p2-nice-to-have :cake:

#8887 fix: don't count class declarations as react fast refresh boundry (fixes #3675)
  packages/plugin-react/src/fast-refresh.ts
Labels: p3-minor-bug :hammer:, plugin: react

#9635 fix(legacy): skip esbuild transform for systemjs
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p5-urgent :fire:

#9640 refactor(legacy): remove code for Vite 2
  packages/plugin-legacy/src/index.ts
Labels: p1-chore :broom:

#9642 fix(config): don't use file url for external files with cjs output
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:, possible regression

#9595 fix(ssr-manifest): check name before saving to ssrManifest
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#9654 fix: fs serve only edit pathname (fixes #9148)
  packages/playground/fs-serve/__tests__/fs-serve.spec.ts
  packages/playground/fs-serve/root/src/index.html
  packages/vite/src/node/server/middlewares/static.ts
Labels: p3-minor-bug :hammer:, possible regression

#9653 fix: use browser field if likely esm (fixes #9652)
  packages/vite/src/node/plugins/resolve.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/browser-module-field3/index.js
  playground/resolve/browser-module-field3/index.web.js
  playground/resolve/browser-module-field3/package.json
  playground/resolve/index.html
  playground/resolve/package.json
  pnpm-lock.yaml
Labels: p2-has-workaround :cake:, possible regression

#9561 fix(vite/client): allow ping to http from https website
  packages/vite/src/client/client.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#8939 docs: update WSL2 watch limitation explanation
  docs/config/build-options.md
  docs/config/server-options.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/watch.ts
Labels: documentation, windows only, feat: hmr, p1-chore :broom:

#9659 feat: skip `.git` when emptying dir
  packages/create-vite/index.js
Labels: enhancement, p2-nice-to-have :cake:

#9658 chore: publish under previous tag if not latest
  scripts/publishCI.ts
  scripts/releaseUtils.ts
Labels: p1-chore :broom:

#9687 perf(plugin-vue-jsx): hoist variables
  packages/plugin-vue-jsx/src/index.ts
Labels: plugin: vue-jsx, p2-nice-to-have :cake:

#9697 fix(hmr): duplicate link tags
  packages/vite/src/client/client.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#9708 docs(ssr): note linked deps no external
  docs/guide/ssr.md
Labels: documentation, feat: ssr

#9709 docs: update import.meta.glob jsdocs
  packages/vite/types/importGlob.d.ts
Labels: documentation

#9350 fix: dynamic import path contain ../ and its own directory
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/__snapshots__/parse.test.ts.snap
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/parse.test.ts
  packages/vite/src/node/plugins/dynamicImportVars.ts
  playground/dynamic-import/__tests__/dynamic-import.spec.ts
  playground/dynamic-import/index.html
  playground/dynamic-import/nested/index.js
  playground/dynamic-import/nested/nested/self.js
  playground/dynamic-import/nested/self.js
Labels: p2-has-workaround :cake:

#9711 docs: fix typos in comments and documentation
  docs/guide/troubleshooting.md
  packages/vite/CHANGELOG.md
  packages/vite/src/node/server/ws.ts
  packages/vite/types/http-proxy.d.ts
Labels: documentation, p1-chore :broom:

#9729 fix(import-analysis): escape quotes
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/glob-import/dir/quote'.js
Labels: p3-minor-bug :hammer:

#9507 fix: legacy no resolve asset urls
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/completeSystemWrap.ts
  packages/vite/src/node/plugins/css.ts
  playground/vitestSetup.ts
  playground/vue-legacy/Main.vue
  playground/vue-legacy/__tests__/vue-legacy.spec.ts
  playground/vue-legacy/assets/asset.png
  playground/vue-legacy/env.d.ts
  playground/vue-legacy/index.html
  playground/vue-legacy/inline.css
  playground/vue-legacy/module.vue
  playground/vue-legacy/package.json
  playground/vue-legacy/vite.config.ts
  pnpm-lock.yaml
Labels: plugin: legacy, p4-important :exclamation:

#9738 feat(ssr): warn if cant analyze dynamic import
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p2-nice-to-have :cake:, feat: ssr

#9737 fix: sanitize asset filenames
  packages/vite/src/node/plugins/asset.ts
  playground/assets-sanitize/+circle.svg
  playground/assets-sanitize/__tests__/assets-sanitize.spec.ts
  playground/assets-sanitize/_circle.svg
  playground/assets-sanitize/index.html
  playground/assets-sanitize/index.js
  playground/assets-sanitize/package.json
  playground/assets-sanitize/vite.config.js
Labels: bug, p3-downstream-blocker :hammer:

#9321 fix: handle resolve optional peer deps
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/utils.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-with-optional-peer-dep/index.js
  playground/optimize-deps/dep-with-optional-peer-dep/package.json
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  pnpm-lock.yaml
Labels: p3-significant 🔨

#9056 fix: add `react` to `optimizeDeps`
  packages/plugin-react/src/index.ts
Labels: p2-nice-to-have :cake:

#9639 refactor(legacy): build polyfill chunk
  packages/plugin-legacy/src/index.ts
Labels: p1-chore :broom:

#9759 fix: module graph ensureEntryFromUrl based on id
  packages/vite/src/node/server/__tests__/moduleGraph.spec.ts
  packages/vite/src/node/server/moduleGraph.ts
Labels: p3-downstream-blocker :hammer:

#9762 test: refactor config load
  playground/vitestSetup.ts
Labels: p1-chore :broom:

#9392 fix(html): move importmap before module scripts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/external/__tests__/external.spec.ts
  playground/html/__tests__/html.spec.ts
  playground/html/vite.config.js
Labels: feat: html, p3-minor-bug :hammer:

#9768 chore: output tsconfck debug log
  packages/vite/src/node/plugins/esbuild.ts
Labels: p1-chore :broom:

#9634 feat: support object style hooks
  package.json
  packages/plugin-vue/package.json
  packages/vite/package.json
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/pluginContainer.ts
  playground/lib/__tests__/lib.spec.ts
  playground/object-hooks/__tests__/object-hooks.spec.ts
  playground/object-hooks/index.html
  playground/object-hooks/main.ts
  playground/object-hooks/package.json
  playground/object-hooks/vite.config.ts
  pnpm-lock.yaml
Labels: p3-significant 🔨

#9795 fix: Skip inlining Git LFS placeholders (fix #9714)
  docs/config/build-options.md
  docs/guide/assets.md
  packages/vite/src/node/plugins/asset.ts
Labels: enhancement

#9678 refactor: migrate from vue/compiler-dom to parse5
  .prettierignore
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/html/valid.html
  playground/html/vite.config.js
  pnpm-lock.yaml
Labels: feat: html, p3-significant 🔨

#9816 fix: close socket when client error handled
  packages/vite/src/node/http.ts
Labels: p3-minor-bug :hammer:

#9741 fix(plugin-legacy): prevent global process.env.NODE_ENV mutation
  packages/plugin-legacy/src/index.ts
  playground/legacy/__tests__/client-and-ssr/client-legacy-ssr-sequential-builds.spec.ts
  playground/legacy/__tests__/client-and-ssr/serve.ts
  playground/legacy/entry-server-sequential.js
  playground/test-utils.ts
Labels: plugin: legacy, p3-minor-bug :hammer:

#9760 fix: `injectQuery` break relative path
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#9821 fix: `completeSystemWrapPlugin` captures `function ()` (fixes #9807)
  packages/vite/src/node/plugins/completeSystemWrap.ts
Labels: p4-important :exclamation:

#9837 feat: relax dep browser externals as warning
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
Labels: p3-significant 🔨

#8855 feat(client): use debug channel on hot updates
  packages/vite/src/client/client.ts
Labels: p2-to-be-discussed :cake:

#9406 feat(create-vite): add support for custom init commands (`create-vue`, Nuxt, and SvelteKit)
  packages/create-vite/index.js
  packages/create-vite/package.json
  pnpm-lock.yaml
Labels: p3-significant 🔨

#9793 fix(build): build project path error
  packages/vite/src/node/plugins/html.ts
Labels: windows only, p2-has-workaround :cake:

#9848 fix: ensure version query for direct node_modules imports
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-non-optimized/index.js
  playground/optimize-deps/dep-non-optimized/package.json
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  playground/optimize-deps/vite.config.js
  pnpm-lock.yaml
Labels: p4-important :exclamation:

#9842 fix: escape glob path
  packages/vite/src/node/plugins/importMetaGlob.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/glob-import/escape/(parenthesis)/glob.js
  playground/glob-import/escape/(parenthesis)/mod/index.js
  playground/glob-import/escape/[brackets]/glob.js
  playground/glob-import/escape/[brackets]/mod/index.js
  playground/glob-import/escape/{curlies}/glob.js
  playground/glob-import/escape/{curlies}/mod/index.js
  playground/glob-import/index.html
  playground/glob-import/vite.config.ts
Labels: p3-downstream-blocker :hammer:

#9881 refactor(hmr): simplify fetchUpdate
  packages/vite/src/client/client.ts
Labels: p1-chore :broom:

#9897 chore: fix internal plugins publish
  scripts/releaseUtils.ts
Labels: p1-chore :broom:

#9034 perf: bundle create-vite
  .eslintrc.cjs
  package.json
  packages/create-vite/LICENSE
  packages/create-vite/build.config.ts
  packages/create-vite/index.js
  packages/create-vite/package.json
  packages/create-vite/src/index.js
  packages/vite/package.json
  packages/vite/rollup.config.ts
  pnpm-lock.yaml
  scripts/rollupLicensePlugin.mjs
Labels: p2-nice-to-have :cake:

#9914 fix(css): remove css-post plugin sourcemap
  packages/vite/src/node/plugins/css.ts
  playground/css-sourcemap/__tests__/css-sourcemap.spec.ts
Labels: feat: css, p3-minor-bug :hammer:

#9909 feat(css): format error
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/utils.ts
Labels: feat: css, p2-nice-to-have :cake:

#9887 chore: trigger ecosystem-ci by comment
  .github/workflows/ecosystem-ci-trigger.yml
Labels: p1-chore :broom:

#9934 chore!: bump esbuild to 0.15.6
  packages/vite/package.json
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  pnpm-lock.yaml
Labels: dependencies
