Repository vitejs/vite, pull requests merged in 2022-07, with the labels that each got.

#8875 test: fix flaky glob test
  playground/glob-import/__tests__/glob-import.spec.ts
Labels: p1-chore :broom:, test

#8871 docs: simplify Snowpack comparison
  docs/guide/comparisons.md
Labels: documentation, p1-chore :broom:

#8863 feat: ssrBuild flag in config env
  docs/config/index.md
  packages/vite/src/node/config.ts
  playground/ssr-vue/vite.config.js
Labels: p3-significant 🔨

#8892 fix: ensure define overrides import.meta in build
  packages/vite/src/node/plugins/define.ts
  playground/env/.env
  playground/env/__tests__/env.spec.ts
  playground/env/index.html
  playground/env/vite.config.js
Labels: p3-minor-bug :hammer:

#8898 fix(hmr): set isSelfAccepting unless it is delayed
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/moduleGraph.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#8900 refactor: remove ?used inject in glob plugin
  packages/vite/src/node/plugins/importMetaGlob.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/glob-import/dir/foo.css
  playground/glob-import/index.html
  playground/test-utils.ts
Labels: p1-chore :broom:

#8917 feat: ssr.optimizeDeps
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/ssr/index.ts
  packages/vite/src/node/utils.ts
Labels: feat: ssr, p3-significant 🔨, feat: deps optimizer

#8938 docs: fix `build.chunkSizeWarningLimit` heading level
  docs/config/build-options.md
Labels: documentation

#8937 feat: support import assertions
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/import-assertion/__tests__/import-assertion.spec.ts
  playground/import-assertion/data.json
  playground/import-assertion/import-assertion-dep/data.json
  playground/import-assertion/import-assertion-dep/index.js
  playground/import-assertion/import-assertion-dep/package.json
  playground/import-assertion/index.html
  playground/import-assertion/package.json
  pnpm-lock.yaml
Labels: p3-significant 🔨

#8927 docs: add Cloudflare Pages to deploy options
  docs/guide/static-deploy.md
Labels: documentation

#8953 fix: cjs interop export names local clash, fix #8950
  packages/vite/src/node/__tests__/plugins/import.spec.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/alias/index.html
  playground/optimize-deps/cjs.js
Labels: p3-minor-bug :hammer:

#8961 refactor!: move basic ssl setup to external plugin, fix #8532
  docs/config/server-options.md
  docs/guide/migration.md
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/certificate.ts
  packages/vite/src/node/http.ts
  pnpm-lock.yaml
Labels: p3-significant 🔨

#8977 fix(css): backport #8936
  packages/playground/css/__tests__/css.spec.ts
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:, possible regression

#8979 fix: re-encode url to prevent fs.allow bypass (fixes #8498)
  packages/vite/src/node/server/middlewares/static.ts
  playground/fs-serve/__tests__/fs-serve.spec.ts
  playground/fs-serve/root/src/index.html
Labels: bug, p5-urgent :fire:, security

#8965 refactor: opt-in optimizeDeps during build and SSR
  docs/guide/migration.md
  package.json
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/ssr/index.ts
  playground/import-assertion/vite.config.js
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/vite.config.js
  playground/ssr-deps/server.js
Labels: p3-significant 🔨

#8990 fix: backport #8979, re-encode url to prevent fs.allow bypass (fixes #8498)
  packages/playground/fs-serve/__tests__/fs-serve.spec.ts
  packages/playground/fs-serve/root/src/index.html
  packages/vite/src/node/server/middlewares/static.ts
Labels: bug, p5-urgent :fire:, security

#8988 chore: use vite-env.d.ts convention
  packages/create-vite/template-vue-ts/src/vite-env.d.ts
Labels: p1-chore :broom:

#8999 docs: update api-javascript
  docs/guide/api-javascript.md
  packages/vite/src/node/optimizer/index.ts
Labels: documentation

#9007 feat: show ws connection error and don't reload if ws connection did not success
  packages/vite/src/client/client.ts
  packages/vite/src/node/plugins/clientInjections.ts
Labels: p2-nice-to-have :cake:

#9006 fix(react): sourcemap incorrect warning and classic runtime sourcemap
  packages/plugin-react/package.json
  packages/plugin-react/src/index.ts
  playground/react-sourcemap/App.jsx
  playground/react-sourcemap/__tests__/react-sourcemap.spec.ts
  playground/react-sourcemap/index.html
  playground/react-sourcemap/main.jsx
  playground/react-sourcemap/package.json
  playground/react-sourcemap/vite.config.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, plugin: react

#8997 fix(ssr): fix sourcemap content (fixes #8657)
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: has workaround, p3-downstream-blocker :hammer:, feat: ssr

#9011 fix(vue): handle undefined on import.meta.hot.accept (fixes #8625)
  packages/plugin-vue/src/main.ts
Labels: plugin: vue, p2-nice-to-have :cake:

#9004 chore: fix test optimizeDeps at build time flag
  packages/vite/src/node/config.ts
Labels: p1-chore :broom:

#8720 docs: add team page
  docs/.vitepress/config.ts
  docs/_data/team.js
  docs/team.md
Labels: documentation

#8986 feat: expose server resolved urls
  docs/guide/migration.md
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/logger.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:

#9040 fix: reload on restart with middleware mode (fixes #9038)
  packages/vite/src/client/client.ts
Labels: bug, feat: hmr, possible regression

#9041 fix: remove ws is already closed error
  packages/vite/src/client/client.ts
Labels: p2-nice-to-have :cake:

#9053 chore: include 2.9.13-2.9.14 changelog in main
  packages/vite/CHANGELOG.md
Labels: p1-chore :broom:

#9030 docs: improve server.host desc in migration guide
  docs/config/server-options.md
  docs/guide/migration.md
Labels: documentation

#9069 docs: version toggle label
  docs/.vitepress/config.ts
Labels: documentation

#9084 docs(guide): fix library mode example import
  docs/guide/build.md
Labels: documentation

#9079 docs: tweak ogp tags
  docs/.vitepress/config.ts
  docs/blog/announcing-vite3.md
Labels: documentation

#9090 chore: remove note about v3
  README.md
Labels: p1-chore :broom:

#9106 fix: check server after tsconfig reload
  packages/vite/src/node/plugins/esbuild.ts
Labels: p2-nice-to-have :cake:

#9130 docs: note library mode process.env.* replacement
  docs/guide/build.md
Labels: documentation

#8994 refactor(vue): limit passable compilerOptions
  packages/plugin-vue/README.md
  packages/plugin-vue/src/index.ts
Labels: plugin: vue, p1-chore :broom:

#9128 fix(vue): remove ssr.external config
  packages/plugin-vue/src/index.ts
Labels: plugin: vue, p2-has-workaround :cake:

#9105 fix(esbuild): always support dynamic import and import meta
  packages/vite/src/node/__tests__/plugins/esbuild.spec.ts
  packages/vite/src/node/plugins/esbuild.ts
  playground/build-old/__tests__/build-old.spec.ts
  playground/build-old/dynamic.js
  playground/build-old/index.html
  playground/build-old/package.json
  playground/build-old/vite.config.js
Labels: p3-minor-bug :hammer:

#9064 fix: avoid errors when loading the overlay code in workers
  packages/vite/src/client/overlay.ts
Labels: p3-minor-bug :hammer:, feat: web workers

#9140 fix: externalize workspace relative import when bundle config
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#9146 fix: ssr.external/noExternal should apply to packageName
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: p4-important :exclamation:

#9154 feat: allow declaring `__dirname` in config
  docs/config/index.md
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#9161 docs: fix broken link to envPrefix config option
  docs/guide/env-and-mode.md
Labels: documentation

#9166 fix: disable keepNames in `vite:esbuild` (fixes #9164)
  packages/vite/src/node/plugins/esbuild.ts
Labels: p3-minor-bug :hammer:

#9175 fix: return 500 on proxy error only if possible (fixes #9172)
  packages/vite/src/node/server/middlewares/proxy.ts
Labels: p3-minor-bug :hammer:

#9173 fix: fs serve only edit pathname (fixes #9148)
  packages/vite/src/node/server/middlewares/static.ts
  playground/fs-serve/__tests__/fs-serve.spec.ts
  playground/fs-serve/root/src/index.html
Labels: p3-minor-bug :hammer:, possible regression

#9187 fix(dev): build.ssr is set during dev, fix #9134
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/index.ts
Labels: p4-important :exclamation:, feat: ssr

#9193 fix: return 500 on proxy error only if possible (fixes #9172)
  packages/vite/src/node/server/middlewares/proxy.ts
Labels: p3-minor-bug :hammer:

#9210 feat(css): use esbuild.log* options when minifying (fixes #9196)
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/main.js
  playground/css/unsupported.css
  playground/css/vite.config.js
Labels: feat: css, p2-nice-to-have :cake:

#9212 feat: worker config call config hook
  packages/vite/src/node/config.ts
  playground/worker/__tests__/iife/vite.config.js
  playground/worker/package.json
  playground/worker/vite.config-iife.js
Labels: feat: web workers

#9199 fix: ssrLoadModule executes code in non-strict mode, fixes #9197
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#9262 fix: don't modify config
  packages/vite/src/node/config.ts
Labels: bug

#9281 fix(glob): handle glob prop access
  packages/vite/src/node/plugins/importMetaGlob.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/glob-import/index.html
Labels: p3-minor-bug :hammer:

#9282 fix(scan): handle .ts import as .js alias
  packages/vite/src/node/optimizer/scan.ts
  playground/vue/TsImport.vue
  playground/vue/__tests__/vue.spec.ts
  playground/vue/vite.config.ts
Labels: p3-minor-bug :hammer:, feat: deps optimizer

#9263 docs: show deployed version
  docs/.vitepress/config.ts
Labels: documentation

#9290 docs: fix deploy type var
  docs/.vitepress/config.ts
Labels: documentation

#9286 fix: entries in ssr.external
  packages/vite/src/node/ssr/ssrExternal.ts
  playground/ssr-deps/__tests__/ssr-deps.spec.ts
  playground/ssr-deps/external-entry/entry.js
  playground/ssr-deps/external-entry/index.js
  playground/ssr-deps/external-entry/package.json
  playground/ssr-deps/external-using-external-entry/index.js
  playground/ssr-deps/external-using-external-entry/package.json
  playground/ssr-deps/package.json
  playground/ssr-deps/server.js
  playground/ssr-deps/src/app.js
  pnpm-lock.yaml
Labels: p4-important :exclamation:, feat: ssr

#9268 feat: supports cts and mts files
  packages/vite/src/node/constants.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/esbuild.ts
  packages/vite/src/node/utils.ts
  playground/resolve/index.html
  playground/resolve/ts-extension/hellocjs.cts
  playground/resolve/ts-extension/hellomjs.mts
  playground/resolve/ts-extension/index.ts
Labels: enhancement, p2-nice-to-have :cake:

#9296 fix(ssr): no external symlink package
  packages/vite/src/node/plugins/resolve.ts
  playground/ssr-deps/__tests__/ssr-deps.spec.ts
  playground/ssr-deps/linked-no-external/index.js
  playground/ssr-deps/linked-no-external/package.json
  playground/ssr-deps/package.json
  playground/ssr-deps/src/app.js
  pnpm-lock.yaml
Labels: feat: ssr, p3-significant 🔨

#9315 fix: support vite client in safari 13
  packages/vite/src/client/tsconfig.json
Labels: p3-minor-bug :hammer:

#9316 docs: update browser baseline features
  docs/config/build-options.md
  docs/guide/build.md
  docs/guide/index.md
  docs/guide/migration.md
  packages/vite/src/node/constants.ts
Labels: documentation

#9314 fix: support multiline dynamic imports
  packages/vite/src/node/plugins/dynamicImportVars.ts
  packages/vite/src/node/utils.ts
  playground/dynamic-import/__tests__/dynamic-import.spec.ts
  playground/dynamic-import/nested/index.js
Labels: p3-minor-bug :hammer:

#9336 docs: fix highlight lines
  docs/guide/ssr.md
  docs/guide/static-deploy.md
Labels: documentation

#9346 fix: externalize explicitly configured linked packages
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: p4-important :exclamation:

#9353 fix: normalise css paths in manifest on windows (fixes #9295)
  packages/vite/src/node/plugins/css.ts
  playground/backend-integration/__tests__/backend-integration.spec.ts
  playground/backend-integration/dir/foo.css
  playground/backend-integration/vite.config.js
Labels: windows only, feat: css, p3-downstream-blocker :hammer:

#6751 fix: support stylesheets with link tag and media/disable prop
  packages/vite/src/node/plugins/html.ts
  playground/html/__tests__/html.spec.ts
  playground/html/link-props/index.html
  playground/html/link-props/print.css
  playground/html/link-props/screen.css
  playground/html/vite.config.js
Labels: p3-minor-bug :hammer:

#9352 fix(glob): support static template literals
  packages/vite/src/node/__tests__/plugins/importGlob/parse.test.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
Labels: p2-has-workaround :cake:

#9373 docs: update broken link for import.meta
  docs/blog/announcing-vite3.md
  docs/config/build-options.md
  docs/guide/build.md
  docs/guide/index.md
  docs/guide/migration.md
Labels: documentation

#9380 docs: mention create-vite-extra for repro
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation

#9388 test: refactor some regexp, remove `{1}`
  playground/assets/__tests__/assets.spec.ts
  playground/assets/__tests__/relative-base/relative-base-assets.spec.ts
  playground/assets/__tests__/runtime-base/runtime-base-assets.spec.ts
Labels: p1-chore :broom:

#9390 docs: add overflow to Vite CLI code block
  docs/blog/announcing-vite3.md
Labels: documentation

#9399 fix: url constructor import asset no as url
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
  playground/assets/nested/test.js
Labels: bug

#9401 fix: inline dynamic imports for ssr-webworker (fixes #9385)
  packages/vite/src/node/build.ts
  playground/ssr-vue/vite.config.js
  playground/ssr-webworker/__tests__/ssr-webworker.spec.ts
  playground/ssr-webworker/src/dynamic.js
  playground/ssr-webworker/src/entry-worker.jsx
  playground/test-utils.ts
Labels: p4-important :exclamation:, possible regression

#9379 docs: add troubleshooting page
  docs/.vitepress/config.ts
  docs/config/server-options.md
  docs/guide/troubleshooting.md
Labels: documentation

#9425 fix(glob): server perf when globbing huge dirs
  packages/vite/src/node/plugins/importMetaGlob.ts
Labels: bug, OS specific

#9405 fix(ssr): allow virtual paths on node modules
  packages/vite/src/node/ssr/ssrExternal.ts
  playground/ssr-deps/__tests__/ssr-deps.spec.ts
  playground/ssr-deps/package.json
  playground/ssr-deps/pkg-exports/index.js
  playground/ssr-deps/pkg-exports/package.json
  playground/ssr-deps/server.js
  playground/ssr-deps/src/app.js
  pnpm-lock.yaml
Labels: feat: ssr

#9247 fix: __VITE_PUBLIC_ASSET__hash__ in HTML
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/html.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: p3-minor-bug :hammer:

#9432 feat(ssr): debug failed node resolve
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: p2-nice-to-have :cake:, feat: ssr

#9454 docs: ESM is always strict mode
  docs/guide/troubleshooting.md
Labels: documentation

#9467 chore: fix docs-check.sh lint
  package.json
Labels: p1-chore :broom:
