Repository vitejs/vite, pull requests merged in 2022-10, with the labels that each got.

#10300 fix(ssr): correctly track scope
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#10303 test: add sugarss sourcemap test
  playground/css-sourcemap/__tests__/css-sourcemap.spec.ts
  playground/css-sourcemap/imported.sss
  playground/css-sourcemap/index.html
  playground/css-sourcemap/package.json
  pnpm-lock.yaml
Labels: feat: css, p1-chore :broom:, test

#10299 fix: add module types
  packages/vite/client.d.ts
Labels: p2-has-workaround :cake:

#10324 fix(hmr): handle virtual module update
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/hmr.ts
Labels: feat: hmr, p3-downstream-blocker :hammer:

#10113 fix: env variables override
  packages/vite/src/node/__tests__/env.spec.ts
  packages/vite/src/node/__tests__/env/.env
  packages/vite/src/node/__tests__/env/.env.development
  packages/vite/src/node/__tests__/env/.env.production
  packages/vite/src/node/env.ts
Labels: p3-minor-bug :hammer:

#10336 fix(server): handle appType mpa html fallback
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/htmlFallback.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: feat: html, p3-minor-bug :hammer:

#10314 fix(optimizer): browser field bare import (fix #7599)
  packages/vite/src/node/plugins/resolve.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-cjs-browser-field-bare/events-shim.js
  playground/optimize-deps/dep-cjs-browser-field-bare/index.js
  playground/optimize-deps/dep-cjs-browser-field-bare/internal.js
  playground/optimize-deps/dep-cjs-browser-field-bare/package.json
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#10239 fix(react): conditionally self-accept fast-refresh HMR
  packages/plugin-react/src/fast-refresh.ts
  playground/react/App.jsx
  playground/react/__tests__/react.spec.ts
  playground/react/context/ContextButton.jsx
  playground/react/context/CountProvider.jsx
  playground/react/hmr/no-exported-comp.jsx
  playground/react/hmr/parent.jsx
Labels: feat: hmr, p4-important :exclamation:, plugin: react

#10347 fix(config): don't resolve by module field
  packages/vite/src/node/config.ts
Labels: p4-important :exclamation:

#10353 chore: make reproduction field a textarea
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: p1-chore :broom:

#10325 docs: update `git checkout -b main` as `git checkout -B main`
  docs/guide/static-deploy.md
Labels: documentation

#10381 fix(html): handle attrs with prefix (fixes #10337)
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/html/public/sprite.svg
  playground/html/valid.html
Labels: feat: html, p3-minor-bug :hammer:

#10388 fix(ssr): track var as function scope
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-downstream-blocker :hammer:, feat: ssr

#10315 feat(lib): cjs instead of umd as default format for multiple entries
  docs/config/build-options.md
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/build.ts
Labels: p2-nice-to-have :cake:, feat: library mode

#10399 chore: fix vue-ssr test warning
  playground/ssr-vue/src/pages/Store.vue
Labels: p1-chore :broom:

#10401 fix(ssr): handle parallel hookNodeResolve
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#10414 docs: add missing binding in asset import example
  packages/plugin-vue/README.md
Labels: documentation, plugin: vue

#10420 fix(config): skip resolve builtin modules
  packages/vite/src/node/config.ts
  playground/cli-module/package.json
  playground/cli-module/vite.config.js
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#10371 fix: prefer exports when resolving
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/exports-legacy-fallback/dir/index.js
  playground/resolve/exports-legacy-fallback/dir/index.mjs
  playground/resolve/exports-legacy-fallback/dir/package.json
  playground/resolve/exports-legacy-fallback/index.js
  playground/resolve/exports-legacy-fallback/package.json
  playground/resolve/index.html
  playground/resolve/package.json
  pnpm-lock.yaml
Labels: p3-downstream-blocker :hammer:

#10446 fix(config): partial deno support
  packages/vite/src/node/config.ts
Labels: p3-downstream-blocker :hammer:

#10333 feat(server): invalidate module with hmr
  docs/guide/api-javascript.md
  packages/vite/src/node/server/index.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/hmr/index.html
  playground/hmr/vite.config.ts
Labels: feat: hmr, p3-significant 🔨

#10454 docs: fix git hooks link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: p1-chore :broom:

#10214 feat(create-vite): support create-vite-extra
  packages/create-vite/src/index.ts
Labels: p2-nice-to-have :cake:

#10374 feat: update esbuild compilation affecting fields
  docs/guide/features.md
  packages/vite/src/node/plugins/esbuild.ts
Labels: p2-nice-to-have :cake:

#10478 fix(html): allow self closing on non-void elements
  packages/vite/src/node/plugins/html.ts
  playground/html/valid.html
Labels: feat: html, p3-minor-bug :hammer:

#10479 fix(plugin-react): update `package.json`
  packages/plugin-react/package.json
Labels: p1-chore :broom:, plugin: react

#10496 fix(legacy): restore entry chunk CSS inlining, reverts #9761
  packages/vite/src/node/plugins/css.ts
Labels: plugin: legacy, p3-minor-bug :hammer:, possible regression

#10485 feat: reuse opening tab in chromium browsers when start dev server
  packages/vite/bin/openChrome.applescript
  packages/vite/src/node/server/openBrowser.ts
Labels: p2-nice-to-have :cake:

#10196 fix: expose server as Http2SecureServer type
  docs/guide/api-javascript.md
  docs/guide/api-plugin.md
  packages/vite/src/node/http.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/proxy.ts
  packages/vite/src/node/server/ws.ts
Labels: p2-nice-to-have :cake:

#10528 fix(config): don't use module condition (`import.meta.resolve`) (fixes #10430)
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/config.ts
  playground/config/__tests__/load.spec.ts
  playground/config/packages/entry/package.json
  playground/config/packages/entry/vite.config.ts
  playground/config/packages/plugin-module-condition/index.cjs
  playground/config/packages/plugin-module-condition/index.d.ts
  playground/config/packages/plugin-module-condition/index.mjs
  playground/config/packages/plugin-module-condition/module.mjs
  playground/config/packages/plugin-module-condition/package.json
  pnpm-lock.yaml
Labels: p4-important :exclamation:

#10545 chore: update netlify configuration
  netlify.toml
Labels: p1-chore :broom:

#10514 fix(css): remove `?direct` in id for postcss process
  packages/vite/src/node/__tests__/plugins/css.spec.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/utils.ts
Labels: feat: css, p3-minor-bug :hammer:

#10529 feat: include line and column in error format
  packages/vite/src/node/server/middlewares/error.ts
Labels: p2-nice-to-have :cake:

#10569 fix(ssr): resolve with isRequire true
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-downstream-blocker :hammer:

#10577 fix(css): strip BOM (fixes #10043)
  packages/vite/src/node/plugins/css.ts
Labels: p2-has-workaround :cake:

#10614 fix: revert es-module-lexer version
  packages/vite/package.json
  pnpm-lock.yaml
Labels: possible regression

#10331 fix: add a warning if css urls not exist during build time (fix #9800)
  packages/vite/src/node/plugins/css.ts
Labels: p2-nice-to-have :cake:

#10602 fix(hmr): cannot reload after missing import on server startup (#9534)
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/missing-import/a.js
  playground/hmr/missing-import/index.html
  playground/hmr/missing-import/main.js
Labels: feat: hmr, p3-minor-bug :hammer:, feat: deps optimizer

#10550 feat(build): add copyPublicDir option
  docs/config/build-options.md
  packages/vite/src/node/build.ts
Labels: feat: ssr, YAO, p2-to-be-discussed :cake:, feat: build

#10429 feat(css): export preprocessCSS API
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-significant 🔨

#10645 fix(config): resolve build options with fallback
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
Labels: p3-downstream-blocker :hammer:

#10678 fix: remove picomatch type import (fixes #10656)
  packages/vite/scripts/postPatchTypes.ts
  packages/vite/scripts/util.ts
  packages/vite/tsconfig.check.json
Labels: bug, p3-downstream-blocker :hammer:, possible regression

#10684 fix: prioritize existing env over .env (fixes #10676)
  packages/vite/src/node/__tests__/env.spec.ts
  packages/vite/src/node/__tests__/env/.env.existing
  packages/vite/src/node/env.ts
Labels: p4-important :exclamation:, possible regression

#10683 fix(config): resolve externalized specifier with internal resolver
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/resolve.ts
  pnpm-lock.yaml
Labels: p4-important :exclamation:, possible regression

#10704 test: remove console.log
  playground/hmr/vite.config.ts
Labels: p1-chore :broom:, test

#10705 fix: remove loaded input sourcemap (fixes #8411)
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/server/transformRequest.ts
  playground/css-sourcemap/index.html
  playground/css-sourcemap/input-map.css
  playground/css-sourcemap/input-map.css.map
  playground/css-sourcemap/input-map.src.css
Labels: p2-has-workaround :cake:

#10714 fix: tsconfig `jsx` overrides esbuild options, reverts #10374
  docs/guide/features.md
  packages/vite/src/node/plugins/esbuild.ts
Labels: p4-important :exclamation:, possible regression

#10738 chore: remove non used type definitions
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/types/shims.d.ts
Labels: p1-chore :broom:

#10740 chore: fix dev build replacing undefined
  packages/vite/src/node/server/transformRequest.ts
Labels: bug, p1-chore :broom:
