Repository vitejs/vite, pull requests merged in 2022-06, with the labels that each got.

#8423 chore: reapply #5930
  packages/vite/src/node/build.ts
Labels: p1-chore :broom:

#8421 fix: SSR deep imports externalization (fixes #8420)
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: p3-downstream-blocker :hammer:, feat: ssr

#8422 docs: add advanced section to migration from v2 guide
  docs/guide/migration.md
Labels: documentation

#8050 docs: CSS `?inline` query parameter
  docs/guide/features.md
Labels: documentation

#8312 refactor(plugin-legacy): improve default polyfill
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p2-nice-to-have :cake:

#7910 docs: update Heroku deployment instructions
  docs/guide/static-deploy.md
Labels: documentation

#8455 chore: resolve ssr options
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/ssr/index.ts
Labels: p3-downstream-blocker :hammer:

#8451 perf: disable postcss sourcemap when unused
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-nice-to-have :cake:

#8453 chore: generate vite sourcemap when not production
  packages/vite/rollup.config.ts
Labels: p1-chore :broom:

#8459 fix(optimizer): external require-import conversion (fixes #2492, #3409)
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-cjs-with-assets/foo.css
  playground/optimize-deps/dep-cjs-with-assets/index.js
  playground/optimize-deps/dep-cjs-with-assets/package.json
  playground/optimize-deps/dep-linked-include/test.css
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#8338 feat: handle named imports of builtin modules
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/resolve.ts
  playground/optimize-deps/.env
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-with-builtin-module-cjs/index.js
  playground/optimize-deps/dep-with-builtin-module-cjs/package.json
  playground/optimize-deps/dep-with-builtin-module-esm/index.js
  playground/optimize-deps/dep-with-builtin-module-esm/package.json
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  playground/optimize-deps/vite.config.js
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#8090 feat: preserve process env vars in lib build
  packages/vite/src/node/plugins/define.ts
  playground/lib/__tests__/lib.spec.ts
  playground/lib/index.dist.html
  playground/lib/src/main.js
Labels: feat: library mode

#8481 fix: respect server.headers in static middlewares
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/static.ts
Labels: p3-downstream-blocker :hammer:

#8049 chore: make terser an optional dependency
  docs/config/build-options.md
  packages/plugin-legacy/README.md
  packages/plugin-legacy/package.json
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/terser.ts
  packages/vite/src/node/utils.ts
  playground/legacy/package.json
  playground/preload/package.json
  playground/vitestSetup.ts
  pnpm-lock.yaml
Labels: p2-to-be-discussed :cake:, breaking change

#8496 docs(plugin-vue-jsx): update the options
  packages/plugin-vue-jsx/README.md
Labels: documentation, plugin: vue-jsx

#8491 refactor: remove hooks ssr param support
  packages/plugin-react/src/index.ts
  packages/plugin-vue-jsx/src/index.ts
  packages/plugin-vue/src/index.ts
Labels: p1-chore :broom:

#8442 feat: better config `__dirname` support
  docs/config/index.md
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#8489 fix: respect optimize deps entries
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  playground/optimize-deps/added-in-entries/index.js
  playground/optimize-deps/added-in-entries/package.json
  playground/optimize-deps/entry.js
  playground/optimize-deps/package.json
  playground/optimize-deps/vite.config.js
  pnpm-lock.yaml
Labels: p3-significant 🔨

#8501 chore(create-vite): add current directory description
  packages/create-vite/README.md
  packages/create-vite/__tests__/cli.spec.ts
  packages/create-vite/index.js
Labels: p2-nice-to-have :cake:

#8495 fix(dev): avoid FOUC when swapping out link tag (fix #7973)
  packages/vite/src/client/client.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/hmr/index.html
Labels: feat: hmr, p2-nice-to-have :cake:

#8511 fix: deps optimizer idle logic for workers (fix #8479)
  packages/vite/src/node/optimizer/optimizer.ts
  playground/worker/dep-to-optimize/index.js
  playground/worker/dep-to-optimize/package.json
  playground/worker/my-worker.ts
  playground/worker/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#8535 chore: include 2.9.10-2.9.12 changelog in main
  packages/vite/CHANGELOG.md
Labels: p1-chore :broom:

#8538 test: fix style link after HMR
  playground/backend-integration/__tests__/backend-integration.spec.ts
Labels: p1-chore :broom:

#8544 chore: refactor interop named imports
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p1-chore :broom:

#8545 chore: remove unused timestamp option
  packages/vite/src/node/optimizer/optimizer.ts
Labels: p1-chore :broom:

#8546 fix(plugin-react): apply manual runtime interop
  packages/plugin-react/package.json
  packages/plugin-react/src/index.ts
  playground/react/App.jsx
  playground/react/jsx-entry/Button.jsx
  playground/react/jsx-entry/package.json
  playground/react/package.json
  playground/react/vite.config.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, plugin: react

#5313 fix(plugin-react): support import namespace in `parseReactAlias`
  packages/plugin-react/src/jsx-runtime/restore-jsx.spec.ts
  packages/plugin-react/src/jsx-runtime/restore-jsx.ts
Labels: p3-minor-bug :hammer:, plugin: react

#8550 fix: dont handle sigterm in middleware mode
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:

#8556 fix(config): only rewrite .js loader in `loadConfigFromBundledFile`
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#8568 fix: mime missing extensions
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/asset.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
  playground/assets/nested/foo.unknown
  playground/assets/vite.config.js
Labels: p3-minor-bug :hammer:

#8569 chore: remove rollup `namespaceToStringTag`
  packages/vite/src/node/build.ts
Labels: p1-chore :broom:

#8541 fix: objurl for type module, and concurrent tests
  packages/vite/src/node/plugins/worker.ts
  playground/assets/__tests__/relative-base/relative-base-assets.spec.ts
  playground/assets/vite.config-relative-base.js
  playground/assets/vite.config.js
  playground/test-utils.ts
  playground/vitestGlobalSetup.ts
  playground/vitestSetup.ts
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
  playground/worker/__tests__/relative-base/relative-base-worker.spec.ts
  playground/worker/__tests__/sourcemap/__snapshots__/sourcemap-worker.spec.ts.snap
  playground/worker/index.html
  playground/worker/my-shared-worker.ts
  playground/worker/my-worker.ts
  playground/worker/possible-ts-output-worker.mjs
  playground/worker/vite.config-es.js
  playground/worker/vite.config-relative-base.js
  playground/worker/vite.config-sourcemap.js
  playground/worker/vite.config.js
  playground/worker/worker/main-module.js
Labels: feat: web workers

#8572 chore: update major deps
  .eslintrc.cjs
  .github/renovate.json5
  package.json
  packages/create-vite/__tests__/cli.spec.ts
  packages/plugin-legacy/package.json
  packages/plugin-react/package.json
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue/package.json
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  playground/cli-module/__tests__/serve.ts
  playground/cli/__tests__/serve.ts
  playground/resolve-config/__tests__/resolve-config.spec.ts
  playground/ssr-react/package.json
  playground/test-utils.ts
  pnpm-lock.yaml
  scripts/releaseUtils.ts
Labels: dependencies, p1-chore :broom:

#8543 fix: default host to `localhost` instead of `127.0.0.1`
  docs/config/server-options.md
  docs/guide/migration.md
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/http.ts
  packages/vite/src/node/logger.ts
  packages/vite/src/node/utils.ts
  playground/css/postcss-caching/css.spec.ts
Labels: p3-downstream-blocker :hammer:, breaking change

#8554 docs: worker related notes
  docs/config/worker-options.md
  docs/guide/features.md
  packages/vite/src/node/config.ts
Labels: documentation

#6902 fix(plugin-legacy): don't include SystemJS in modern polyfills
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p2-nice-to-have :cake:

#8585 chore: enable eslint and prettier cache
  .gitignore
  package.json
  packages/vite/package.json
Labels: p1-chore :broom:

#8590 docs: update config jsdoc style
  docs/config/index.md
Labels: documentation

#8591 docs: add some changes to "Migration from v2"
  docs/guide/migration.md
Labels: documentation

#8589 ci: only install chromium for playwright
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#7081 fix(css): escape pattern chars from base path in postcss dir-dependency messages
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/glob-dep/nested (dir)/baz.css
  playground/css/index.html
  playground/css/postcss.config.js
Labels: feat: css, p3-minor-bug :hammer:

#8561 fix(asset): respect assetFileNames if rollupOptions.output is an array
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/asset.ts
  playground/legacy/main.js
  playground/legacy/package.json
  playground/legacy/vite.config-multiple-output.js
  playground/legacy/vite.svg
Labels: p3-minor-bug :hammer:

#8587 chore: upgrade playground deps
  .github/renovate.json5
  playground/backend-integration/package.json
  playground/backend-integration/tailwind.config.js
  playground/file-delete-restore/index.html
  playground/file-delete-restore/package.json
  playground/optimize-deps/cjs-dynamic.js
  playground/optimize-deps/cjs.js
  playground/optimize-deps/dedupe.js
  playground/optimize-deps/dep-linked-include/package.json
  playground/optimize-deps/package.json
  playground/react-emotion/index.html
  playground/react-emotion/package.json
  playground/react/index.html
  playground/react/package.json
  playground/ssr-react/package.json
  playground/ssr-react/src/App.jsx
  playground/ssr-react/src/entry-client.jsx
  playground/ssr-react/src/entry-server.jsx
  playground/ssr-webworker/package.json
  playground/tailwind/package.json
  playground/tailwind/tailwind.config.js
  pnpm-lock.yaml
Labels: dependencies

#8599 ci: cache playwright binary correctly
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#8606 fix: avoid replacing defines and NODE_ENV in optimized deps (fix #8593)
  packages/vite/src/node/optimizer/index.ts
  playground/define/__tests__/define.spec.ts
  playground/define/commonjs-dep/index.js
  playground/define/commonjs-dep/package.json
  playground/define/index.html
  playground/define/package.json
  playground/define/vite.config.js
  pnpm-lock.yaml
Labels: bug, p4-important :exclamation:

#8604 fix(plugin-vue): fix sourcemap when no script block in sfc (close #8601)
  packages/plugin-vue/src/main.ts
  playground/vue-sourcemap/Main.vue
  playground/vue-sourcemap/NoScript.vue
  playground/vue-sourcemap/NoTemplate.vue
  playground/vue-sourcemap/__tests__/serve.spec.ts
Labels: plugin: vue, p3-minor-bug :hammer:

#6493 fix(optimizer): browser mapping for yarn pnp
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
Labels: p3-minor-bug :hammer:

#8630 fix(optimizer): use simple browser external shim in prod
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
Labels: p2-nice-to-have :cake:

#8628 fix: json plugin add judgment and filtering of BOM tags
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/json.ts
  packages/vite/src/node/utils.ts
  playground/json/index.html
  playground/json/json-bom/has-bom.json
Labels: p2-has-workaround :cake:

#8622 fix(wasm): support inlined WASM in Node < v16 (fix #8620)
  packages/vite/src/node/plugins/wasm.ts
Labels: p3-minor-bug :hammer:, feat: wasm

#8418 refactor: rename `force` to `optimizeDeps.force`
  docs/config/dep-optimization-options.md
  docs/config/server-options.md
  docs/guide/migration.md
  packages/vite/src/node/cli.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
Labels: documentation, p3-significant 🔨

#8623 feat: legacy options to revert to v2 strategies
  docs/guide/migration.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: p3-significant 🔨

#8430 feat: support cjs noExternal in SSR dev, fix #2579
  packages/vite/src/node/build.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/index.ts
  playground/ssr-deps/__tests__/ssr-deps.spec.ts
  playground/ssr-deps/no-external-cjs/index.js
  playground/ssr-deps/no-external-cjs/package.json
  playground/ssr-deps/package.json
  playground/ssr-deps/server.js
  playground/ssr-deps/src/app.js
  pnpm-lock.yaml
Labels: feat: ssr, p3-significant 🔨

#8638 feat: cleaner default dev output
  packages/vite/src/node/logger.ts
Labels: p2-nice-to-have :cake:

#8452 feat!: appType (spa, mpa, custom), boolean middlewareMode
  docs/config/server-options.md
  docs/config/shared-options.md
  docs/guide/ssr.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  playground/json/server.js
  playground/optimize-missing-deps/server.js
  playground/ssr-deps/server.js
  playground/ssr-html/server.js
  playground/ssr-pug/server.js
  playground/ssr-react/server.js
  playground/ssr-vue/server.js
Labels: p3-downstream-blocker :hammer:, breaking change

#8574 feat: support async plugins
  docs/config/shared-options.md
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/utils.ts
Labels: p3-significant 🔨

#8649 docs: update root resolve
  docs/config/shared-options.md
Labels: documentation

#8634 docs: improve wildcard host note
  docs/config/preview-options.md
  docs/config/server-options.md
  packages/vite/src/node/logger.ts
Labels: documentation

#8654 fix: revert #5902, fix #8243
  packages/vite/src/node/plugins/css.ts
  playground/legacy/__tests__/legacy.spec.ts
  playground/legacy/package.json
  playground/legacy/vite.config-dynamic-css.js
Labels: feat: css, p3-minor-bug :hammer:, possible regression

#6649 feat(dev): added assets to manifest
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/manifest.ts
  playground/backend-integration/__tests__/backend-integration.spec.ts
Labels: p3-downstream-blocker :hammer:

#8655 docs: fix broken links
  docs/config/build-options.md
  docs/config/preview-options.md
  docs/config/server-options.md
  docs/config/shared-options.md
  docs/guide/assets.md
  docs/guide/backend-integration.md
  docs/guide/build.md
  docs/guide/dep-pre-bundling.md
  docs/guide/env-and-mode.md
  docs/guide/features.md
  docs/guide/migration.md
  docs/guide/static-deploy.md
Labels: documentation

#8658 docs: tweak `voice.svg`
  docs/guide/index.md
  docs/public/voice.svg
  docs/vite.config.ts
Labels: documentation

#8641 fix: disable inlineDynamicImports for ssr.target = node
  docs/guide/migration.md
  packages/vite/src/node/build.ts
Labels: feat: ssr, p2-has-workaround :cake:, breaking change

#8660 fix(plugin-legacy): prevent esbuild injecting arrow function (fixes #8651)
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p4-important :exclamation:

#8647 feat: print resolved address for localhost
  docs/config/server-options.md
  docs/guide/migration.md
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/logger.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/utils.ts
  playground/cli-module/__tests__/serve.ts
  playground/cli/__tests__/serve.ts
Labels: p2-nice-to-have :cake:, breaking change

#8626 refactor: type client maps
  docs/guide/api-hmr.md
  packages/vite/src/client/client.ts
  packages/vite/types/hot.d.ts
Labels: documentation, p1-chore :broom:

#8672 docs: fix node version in "Migration from v2"
  docs/guide/migration.md
Labels: documentation

#7324 feat(hmr): experimental.hmrPartialAccept
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/client/client.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/moduleGraph.ts
  packages/vite/types/hot.d.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/accept-exports/dynamic-imports/deps-all-accepted.ts
  playground/hmr/accept-exports/dynamic-imports/deps-some-accepted.ts
  playground/hmr/accept-exports/dynamic-imports/dynamic-imports.ts
  playground/hmr/accept-exports/dynamic-imports/index.html
  playground/hmr/accept-exports/export-from/depA.ts
  playground/hmr/accept-exports/export-from/export-from.ts
  playground/hmr/accept-exports/export-from/hub.ts
  playground/hmr/accept-exports/export-from/index.html
  playground/hmr/accept-exports/main-accepted/callback.ts
  playground/hmr/accept-exports/main-accepted/dep.ts
  playground/hmr/accept-exports/main-accepted/index.html
  playground/hmr/accept-exports/main-accepted/main-accepted.ts
  playground/hmr/accept-exports/main-accepted/target.ts
  playground/hmr/accept-exports/main-non-accepted/default.ts
  playground/hmr/accept-exports/main-non-accepted/dep.ts
  playground/hmr/accept-exports/main-non-accepted/index.html
  playground/hmr/accept-exports/main-non-accepted/main-non-accepted.ts
  playground/hmr/accept-exports/main-non-accepted/named.ts
  playground/hmr/accept-exports/reexports.bak/accept-named.ts
  playground/hmr/accept-exports/reexports.bak/index.html
  playground/hmr/accept-exports/reexports.bak/reexports.ts
  playground/hmr/accept-exports/reexports.bak/source.ts
  playground/hmr/accept-exports/side-effects/index.html
  playground/hmr/accept-exports/side-effects/side-effects.ts
  playground/hmr/accept-exports/star-imports/deps-all-accepted.ts
  playground/hmr/accept-exports/star-imports/deps-some-accepted.ts
  playground/hmr/accept-exports/star-imports/index.html
  playground/hmr/accept-exports/star-imports/star-imports.ts
  playground/hmr/accept-exports/unused-exports/index.html
  playground/hmr/accept-exports/unused-exports/index.ts
  playground/hmr/accept-exports/unused-exports/unused.ts
  playground/hmr/accept-exports/unused-exports/used.ts
  playground/hmr/vite.config.ts
  playground/test-utils.ts
  pnpm-lock.yaml
Labels: enhancement, feat: hmr, p2-nice-to-have :cake:

#8675 feat: export esbuildVersion and rollupVersion
  packages/vite/src/node/publicUtils.ts
Labels: p2-nice-to-have :cake:

#8450 feat: experimental.buildAdvancedBaseOptions
  docs/guide/build.md
  packages/plugin-legacy/src/index.ts
  packages/plugin-react/src/index.ts
  packages/plugin-vue/src/template.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/logger.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/clientInjections.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/base.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
  packages/vite/src/node/utils.ts
  playground/assets/__tests__/runtime-base/runtime-base-assets.spec.ts
  playground/assets/__tests__/runtime-base/vite.config.js
  playground/assets/package.json
  playground/assets/vite.config-runtime-base.js
  playground/legacy/nested/index.html
  playground/legacy/vite.config.js
  playground/lib/__tests__/serve.ts
  playground/vitestSetup.ts
Labels: p3-downstream-blocker :hammer:

#8650 fix: infer hmr ws target by client location
  docs/config/server-options.md
  packages/vite/src/client/client.ts
  packages/vite/src/node/plugins/clientInjections.ts
Labels: feat: hmr, p3-downstream-blocker :hammer:

#8694 chore: fix "remove pending triage label" action
  .github/workflows/issue-labeled.yml
Labels: p1-chore :broom:

#8698 docs: add #8626 to migration guide
  docs/guide/migration.md
Labels: documentation

#8699 chore: improve issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: p1-chore :broom:

#8714 fix: use esbuild platform browser/node instead of neutral
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/define.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-relative-to-main/entry.js
  playground/optimize-deps/dep-relative-to-main/lib/main.js
  playground/optimize-deps/dep-relative-to-main/package.json
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  pnpm-lock.yaml
Labels: p4-important :exclamation:

#8737 feat: enable tree-shaking for lib es
  packages/vite/src/node/plugins/esbuild.ts
Labels: p2-nice-to-have :cake:, feat: library mode

#8748 fix: optimizeDeps.entries transformRequest url (fix #8719)
  packages/vite/src/node/optimizer/optimizer.ts
Labels: feat: hmr, p3-minor-bug :hammer:, feat: deps optimizer

#8751 docs: link to es translation
  docs/.vitepress/config.ts
Labels: documentation

#8755 chore: prevent unnecessary netlify builds
  netlify.toml
Labels: p1-chore :broom:

#8761 fix(hmr): __HMR_PORT__ should not be `'undefined'`
  packages/vite/src/client/client.ts
  packages/vite/src/node/plugins/clientInjections.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#8729 feat: supports cts and mts config
  packages/vite/src/node/config.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/utils.ts
  playground/resolve-config/__tests__/resolve-config.spec.ts
  playground/resolve-config/__tests__/serve.ts
  playground/resolve-config/root/vite.config.ts
Labels: enhancement, p2-nice-to-have :cake:

#8754 feat: respect esbuild minify config
  docs/config/build-options.md
  docs/config/shared-options.md
  packages/vite/src/node/__tests__/plugins/esbuild.spec.ts
  packages/vite/src/node/__tests__/plugins/importGlob/__snapshots__/fixture.test.ts.snap
  packages/vite/src/node/plugins/esbuild.ts
Labels: p2-nice-to-have :cake:

#8782 fix: always remove temp config
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#8773 chore: use `tsx` directly instead of indirect `esno`
  package.json
  packages/plugin-legacy/package.json
  packages/plugin-react/package.json
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue/package.json
  packages/vite/package.json
  pnpm-lock.yaml
Labels: p1-chore :broom:

#8795 fix(optimizer): only run require-import conversion if require'd
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
Labels: p4-important :exclamation:, feat: deps optimizer

#8785 fix: remove buildTimeImportMetaUrl
  packages/vite/rollup.config.ts
  packages/vite/src/node/constants.ts
Labels: p5-urgent :fire:

#8798 chore: add dark theme images
  .github/issue-workflow-dark.png
  .github/pr-workflow-dark.png
  CONTRIBUTING.md
Labels: p1-chore :broom:

#8796 perf: avoid sourcemap chains during dev
  packages/vite/src/node/__tests__/plugins/importGlob/__snapshots__/fixture.test.ts.snap
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/define.ts
  packages/vite/src/node/plugins/dynamicImportVars.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  packages/vite/src/node/utils.ts
  playground/vue-sourcemap/__tests__/__snapshots__/serve.spec.ts.snap
  playground/vue-sourcemap/__tests__/serve.spec.ts
  playground/worker/__tests__/sourcemap/__snapshots__/sourcemap-worker.spec.ts.snap
  playground/worker/__tests__/sourcemap/sourcemap-worker.spec.ts
Labels: p4-important :exclamation:

#8790 chore: set local packages private
  playground/external/dep-that-imports-vue/package.json
  playground/external/dep-that-requires-vue/package.json
Labels: p1-chore :broom:

#8775 fix: ensure deps optimizer first run, fixes #8750
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
Labels: p3-downstream-blocker :hammer:, feat: deps optimizer

#8804 fix: /@fs/ dir traversal with escaped chars (fixes #8498)
  packages/vite/src/node/server/middlewares/static.ts
  playground/fs-serve/__tests__/fs-serve.spec.ts
  playground/fs-serve/root/src/index.html
Labels: bug, p5-urgent :fire:, security

#8808 fix: incorrectly resolving `knownJsSrcRE` files from root (fixes #4161)
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/utils.ts
Labels: bug, p3-downstream-blocker :hammer:

#8665 feat: use esbuild supported feature
  package.json
  packages/vite/package.json
  packages/vite/src/node/build.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/optimizer/index.ts
  playground/lib/vite.config.js
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#8831 test: fix tailwind playground `server.origin`
  playground/tailwind/vite.config.ts
Labels: p1-chore :broom:

#8815 chore: use tsconfig for client build
  packages/vite/rollup.config.ts
  packages/vite/src/client/tsconfig.json
  packages/vite/src/node/tsconfig.json
Labels: p1-chore :broom:

#8846 fix(worker): dont throw on `import.meta.url` in ssr
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
Labels: feat: web workers

#8778 fix: ignore Playwright test results directory
  packages/vite/src/node/server/index.ts
Labels: p3-downstream-blocker :hammer:

#8809 fix(plugin-react): pass correct context to runPluginOverrides
  packages/plugin-react/src/index.ts
Labels: plugin: react
