Repository vitejs/vite, pull requests merged in 2023-10, with the labels that each got.

#14489 fix(resolve): support submodules of optional peer deps
  packages/vite/src/node/plugins/resolve.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-with-optional-peer-dep-submodule/index.js
  playground/optimize-deps/dep-with-optional-peer-dep-submodule/package.json
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#14475 test: cleanup `testConfig.baseRoute` and use `testConfig.previewBase`
  playground/assets/__tests__/relative-base/relative-base-assets.spec.ts
  playground/assets/__tests__/url-base/url-base-assets.spec.ts
  playground/assets/vite.config-relative-base.js
  playground/assets/vite.config-url-base.js
  playground/css/vite.config-relative-base.js
  playground/legacy/vite.config-no-polyfills-no-systemjs.js
  playground/legacy/vite.config-no-polyfills.js
  playground/vitestSetup.ts
  playground/worker/vite.config-relative-base-iife.js
  playground/worker/vite.config-relative-base.js
Labels: p1-chore :broom:, test

#14522 test: fix flaky legacy structuredClone fail
  playground/legacy/vite.config-no-polyfills-no-systemjs.js
  playground/legacy/vite.config-no-polyfills.js
Labels: p1-chore :broom:, test

#14530 refactor!: remove `server.force`
  packages/vite/src/node/config.ts
  packages/vite/src/node/server/index.ts
Labels: p1-chore :broom:, breaking change

#14498 feat(ssr): support for ssr.resolve.conditions and ssr.resolve.externalConditions options
  docs/config/ssr-options.md
  docs/guide/ssr.md
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/index.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  playground/ssr-conditions/__tests__/serve.ts
  playground/ssr-conditions/__tests__/ssr-conditions.spec.ts
  playground/ssr-conditions/external/browser.js
  playground/ssr-conditions/external/default.js
  playground/ssr-conditions/external/edge.js
  playground/ssr-conditions/external/node.js
  playground/ssr-conditions/external/node.unbundled.js
  playground/ssr-conditions/external/package.json
  playground/ssr-conditions/index.html
  playground/ssr-conditions/no-external/browser.js
  playground/ssr-conditions/no-external/default.js
  playground/ssr-conditions/no-external/edge.js
  playground/ssr-conditions/no-external/node.js
  playground/ssr-conditions/no-external/node.unbundled.js
  playground/ssr-conditions/no-external/package.json
  playground/ssr-conditions/package.json
  playground/ssr-conditions/server.js
  playground/ssr-conditions/src/app.js
  playground/ssr-conditions/vite.config.js
  playground/ssr-webworker/__tests__/ssr-webworker.spec.ts
  playground/ssr-webworker/browser-exports/browser.js
  playground/ssr-webworker/browser-exports/node.js
  playground/ssr-webworker/browser-exports/package.json
  playground/ssr-webworker/package.json
  playground/ssr-webworker/src/entry-worker.jsx
  playground/ssr-webworker/vite.config.js
  playground/ssr-webworker/worker-exports/browser.js
  playground/ssr-webworker/worker-exports/node.js
  playground/ssr-webworker/worker-exports/package.json
  playground/ssr-webworker/worker-exports/worker.js
  playground/test-utils.ts
  pnpm-lock.yaml
Labels: p3-downstream-blocker :hammer:, feat: ssr

#11599 fix(legacy)!: should rename `x.[hash].js` to `x-legacy.[hash].js`
  packages/plugin-legacy/src/index.ts
  playground/legacy/__tests__/legacy.spec.ts
  playground/legacy/custom0.js
  playground/legacy/custom1.js
  playground/legacy/custom2.js
  playground/legacy/main.js
  playground/legacy/vite.config.js
Labels: plugin: legacy, p2-nice-to-have :cake:, breaking change

#14543 feat(optimizer): check optimizeDeps.extensions for scannable files
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-downstream-blocker :hammer:

#14539 fix(lib): esbuild helper functions injection not working with named exports
  packages/vite/src/node/plugins/esbuild.ts
  playground/lib/__tests__/lib.spec.ts
  playground/lib/__tests__/serve.ts
  playground/lib/src/main-named.js
  playground/lib/vite.named-exports.config.js
Labels: p3-minor-bug :hammer:, regression

#14557 refactor: remove unused record flatIdToExports
  packages/vite/src/node/optimizer/index.ts
Labels: p1-chore :broom:

#14274 refactor: ensure HTML is stripped of generated blank lines
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p2-nice-to-have :cake:

#14562 docs: fix resolveDependencies signature
  docs/config/build-options.md
Labels: documentation

#14139 fix: update transform error message
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: p2-nice-to-have :cake:

#13639 perf: move up external url check before fs path checks
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p2-nice-to-have :cake:

#14566 chore: use `npm-run-all2`
  package.json
  pnpm-lock.yaml
Labels: p1-chore :broom:

#14550 perf: reduce preload marker markup size
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
Labels: p3-significant 🔨, feat: build, performance

#14561 fix(optimizer): limit bundled file name length to 170 characters
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/index.html
  playground/optimize-deps/long-file-name.js
  playground/optimize-deps/longfilename/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.js
  playground/optimize-deps/longfilename/package.json
  playground/optimize-deps/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#14528 refactor(css): make `getEmptyChunkReplacer` for unit test
  packages/vite/src/node/__tests__/plugins/css.spec.ts
  packages/vite/src/node/plugins/css.ts
Labels: p1-chore :broom:

#14571 build: use rollup-plugin-dts
  package.json
  packages/vite/api-extractor.json
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/rollup.dts.config.ts
  packages/vite/scripts/api-extractor.ts
  packages/vite/scripts/checkBuiltTypes.ts
  packages/vite/scripts/postPatchTypes.ts
  packages/vite/scripts/prePatchTypes.ts
  packages/vite/scripts/util.ts
  packages/vite/src/node/tsconfig.json
  packages/vite/tsconfig.json
  pnpm-lock.yaml
Labels: p1-chore :broom:

#14586 docs(prebundling): remove uncertain warning
  docs/guide/dep-pre-bundling.md
Labels: documentation

#14518 feat: add off method to ViteHotContext (issue #14185)
  docs/guide/api-hmr.md
  packages/vite/src/client/client.ts
  packages/vite/types/hot.d.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/hmr/index.html
  playground/hmr/vite.config.ts
Labels: p2-nice-to-have :cake:

#14591 fix(html): relative paths without leading dot wasn't rewritten
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/vite.config.js
Labels: feat: html, p3-minor-bug :hammer:

#14589 fix: off-by-one bug in HTML whitespace removal
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p3-downstream-blocker :hammer:

#14582 build: clean generated type file
  packages/vite/rollup.dts.config.ts
Labels: p1-chore :broom:

#14592 fix(html): inline style attribute not working in dev
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/assets/__tests__/assets.spec.ts
Labels: feat: html, p3-minor-bug :hammer:

#14595 fix(html): import expression in classic script for dev
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/vitestSetup.ts
Labels: feat: html, p3-minor-bug :hammer:

#14600 feat: show better parse error in build
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p2-nice-to-have :cake:

#5657 fix!: return 404 for resources requests outside the base path
  docs/guide/migration.md
  packages/vite/src/node/server/middlewares/base.ts
  playground/assets/__tests__/assets.spec.ts
Labels: p3-minor-bug :hammer:

#14584 refactor!: remove `resolvePackageEntry` and `resolvePackageData` APIs
  docs/guide/migration.md
  packages/vite/index.cjs
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
Labels: breaking change

#14583 refactor!: remove exporting internal APIs
  docs/guide/migration.md
  packages/vite/src/node/cli.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/preview.ts
Labels: breaking change

#14597 test: update test for inline sourcemap
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
  playground/js-sourcemap/foo-with-sourcemap-plugin.ts
  playground/js-sourcemap/foo-with-sourcemap.js
  playground/js-sourcemap/vite.config.js
Labels: p1-chore :broom:, test

#14622 docs: change https://polyfill.io/v3/ to https://polyfill.io/
  docs/guide/build.md
Labels: documentation, plugin: legacy

#14615 feat: add import-meta.d.ts
  packages/vite/types/import-meta.d.ts
Labels: p2-nice-to-have :cake:

#14624 docs(create-vite): add qwik and qwik-ts to the list
  packages/create-vite/README.md
Labels: hacktoberfest-accepted

#14630 docs(ssr): update example projects
  docs/guide/ssr.md
Labels: documentation

#14560 feat: add mdx as known js source
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:

#14645 test(hmr): improve #3033 fix description
  packages/vite/src/node/server/moduleGraph.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/issue-3033/index.html
  playground/hmr/self-accept-within-circular/a.js
  playground/hmr/self-accept-within-circular/b.js
  playground/hmr/self-accept-within-circular/c.js
  playground/hmr/self-accept-within-circular/index.html
  playground/hmr/self-accept-within-circular/index.js
Labels: p1-chore :broom:, test

#14650 fix(esbuild): handle tsconfck cache undefined
  packages/vite/src/node/plugins/esbuild.ts
Labels: p3-minor-bug :hammer:

#14291 feat: add server.warmup option
  docs/config/server-options.md
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/warmup.ts
  playground/html/__tests__/html.spec.ts
  playground/html/vite.config.js
  playground/html/warmup/warm.js
Labels: p2-nice-to-have :cake:

#12809 perf: pre transform requests while opening the browser
  packages/vite/src/node/server/index.ts
Labels: p4-important :exclamation:, performance

#14459 fix(dynamic-import-vars): preserve custom query string
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/__snapshots__/parse.spec.ts.snap
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/parse.spec.ts
  packages/vite/src/node/plugins/dynamicImportVars.ts
Labels: p3-minor-bug :hammer:

#14662 test: reduce ssr-conditions test flakiness
  playground/ssr-conditions/__tests__/ssr-conditions.spec.ts
Labels: p1-chore :broom:, test

#14663 fix(html): srcset pointing image in public dir wasn't working during dev
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/utils.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: feat: html, p3-minor-bug :hammer:

#14666 fix: avoid --open optimization if preTransformRequests is disabled
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#13371 fix(hmr): add timestamp for assets in dev
  packages/vite/src/node/plugins/asset.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/__tests__/relative-base/relative-base-assets.spec.ts
  playground/assets/__tests__/runtime-base/runtime-base-assets.spec.ts
  playground/assets/__tests__/url-base/url-base-assets.spec.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/hmr/index.html
  playground/hmr/logo.svg
Labels: feat: hmr, p3-minor-bug :hammer:

#14508 feat!: rollup v4
  docs/guide/migration.md
  package.json
  packages/create-vite/build.config.ts
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/ensureWatch.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/loadFallback.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/server/sourcemap.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  packages/vite/tsconfig.base.json
  playground/assets/__tests__/assets.spec.ts
  playground/assets/__tests__/relative-base/relative-base-assets.spec.ts
  playground/assets/__tests__/runtime-base/runtime-base-assets.spec.ts
  playground/assets/__tests__/url-base/url-base-assets.spec.ts
  playground/backend-integration/__tests__/backend-integration.spec.ts
  playground/css-lightningcss/__tests__/lightningcss.spec.ts
  playground/css/__tests__/css.spec.ts
  playground/css/__tests__/no-css-minify/no-css-minify.spec.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/legacy/__tests__/legacy.spec.ts
  playground/lib/__tests__/lib.spec.ts
  playground/preload/__tests__/preload-disabled/preload-disabled.spec.ts
  playground/preload/__tests__/preload.spec.ts
  playground/preload/__tests__/resolve-deps/preload-resolve-deps.spec.ts
  playground/ssr-webworker/__tests__/ssr-webworker.spec.ts
  playground/worker/__tests__/sourcemap-hidden/sourcemap-hidden-worker.spec.ts
  playground/worker/__tests__/sourcemap-inline/sourcemap-inline-worker.spec.ts
  playground/worker/__tests__/sourcemap/sourcemap-worker.spec.ts
  pnpm-lock.yaml
Labels: breaking change, p3-significant 🔨

#14657 fix(manifest): include assets referenced in html
  packages/vite/src/node/plugins/html.ts
  playground/assets/index.html
  playground/assets/nested/html-only-asset.jpg
Labels: p3-minor-bug :hammer:

#14680 docs(migration): fix troubleshooting link
  docs/guide/migration.md
Labels: documentation

#12991 fix(build): add crossorigin attribute to `link[rel="stylesheet"]`
  packages/vite/src/node/plugins/html.ts
Labels: feat: css, p3-minor-bug :hammer:, feat: build

#14670 feat: backport mdx as known js source (#14560)
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:

#14669 feat: scan .marko files
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-downstream-blocker :hammer:

#14675 fix(assets): make timestamp invalidation lazy
  packages/vite/src/node/plugins/asset.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/__tests__/relative-base/relative-base-assets.spec.ts
  playground/assets/__tests__/runtime-base/runtime-base-assets.spec.ts
  playground/assets/__tests__/url-base/url-base-assets.spec.ts
Labels: p3-minor-bug :hammer:

#14681 refactor!: remove https flag
  docs/guide/cli.md
  docs/guide/index.md
  docs/guide/migration.md
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/http.ts
Labels: p1-chore :broom:, breaking change

#14684 chore: reduce test flakiness
  .prettierignore
  playground/external/index.html
  playground/external/package.json
  playground/external/public/slash@3.0.0.js
  playground/external/vite.config.js
  playground/hmr/__tests__/hmr.spec.ts
  playground/lib/__tests__/lib.spec.ts
  playground/proxy-hmr/__tests__/proxy-hmr.spec.ts
  pnpm-lock.yaml
Labels: p1-chore :broom:, test

#14660 feat: postcss config `.cts` support
  docs/guide/troubleshooting.md
  package.json
  patches/postcss-load-config@4.0.1.patch
  pnpm-lock.yaml
Labels: feat: css, p3-significant 🔨

#14643 feat(build)!: inline SVGs
  packages/vite/src/node/plugins/asset.ts
  playground/assets/__tests__/assets.spec.ts
  playground/legacy/vite.config.js
  playground/worker/vite.config-es.js
  playground/worker/vite.config-iife.js
  playground/worker/vite.config-relative-base-iife.js
  playground/worker/vite.config-relative-base.js
  playground/worker/worker-sourcemap-config.js
Labels: p3-significant 🔨

#14685 fix!: worker.plugins is a function
  docs/config/worker-options.md
  docs/guide/migration.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/utils.ts
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
  playground/worker/__tests__/sourcemap-hidden/sourcemap-hidden-worker.spec.ts
  playground/worker/__tests__/sourcemap-inline/sourcemap-inline-worker.spec.ts
  playground/worker/__tests__/sourcemap/sourcemap-worker.spec.ts
  playground/worker/deeply-nested-second-worker.js
  playground/worker/deeply-nested-third-worker.js
  playground/worker/deeply-nested-worker.js
  playground/worker/index.html
  playground/worker/vite.config-es.js
  playground/worker/vite.config-iife.js
  playground/worker/vite.config-relative-base-iife.js
  playground/worker/vite.config-relative-base.js
  playground/worker/worker-sourcemap-config.js
  playground/worker/worker/main-deeply-nested.js
  playground/worker/worker/main.js
Labels: breaking change, p3-significant 🔨

#14711 refactor(ssr): remove unused metadata code
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p2-nice-to-have :cake:, feat: ssr

#14714 fix(assets): fix svg inline in css url
  packages/vite/src/node/plugins/css.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/css/css-url.css
  playground/assets/index.html
Labels: p4-important :exclamation:

#14732 docs: port 4.4.10 to 4.5 changelog to main
  packages/vite/CHANGELOG.md
Labels: p1-chore :broom:

#14626 fix(resolve): make directory package.json check best effort
  packages/vite/src/node/plugins/resolve.ts
  playground/resolve/__tests__/resolve.spec.ts
Labels: p3-minor-bug :hammer:

#14723 fix(resolve)!: remove special .mjs handling
  docs/guide/migration.md
  packages/vite/src/node/plugins/resolve.ts
Labels: breaking change, p3-significant 🔨

#14693 docs: add performance page
  docs/.vitepress/config.ts
  docs/config/server-options.md
  docs/guide/performance.md
Labels: documentation

#14740 docs(static-deploy): bump gh-pages action to v2
  docs/guide/static-deploy.md
Labels: documentation

#14733 feat(resolve)!: remove `resolve.browserField`
  docs/config/shared-options.md
  docs/guide/migration.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  playground/resolve/vite.config.js
Labels: p2-nice-to-have :cake:, breaking change

#14654 perf(hmr): implement soft invalidation
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/moduleGraph.ts
  packages/vite/src/node/server/transformRequest.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/hmr/index.html
  playground/hmr/soft-invalidation/child.js
  playground/hmr/soft-invalidation/index.js
  playground/hmr/vite.config.ts
Labels: feat: hmr, p3-significant 🔨, performance

#14749 refactor(shortcuts)!: tweak shortcuts api
  packages/vite/src/node/cli.ts
  packages/vite/src/node/shortcuts.ts
Labels: breaking change

#11151 feat(define): handle replacement with esbuild
  docs/config/shared-options.md
  docs/guide/migration.md
  packages/vite/src/node/__tests__/plugins/define.spec.ts
  packages/vite/src/node/plugins/clientInjections.ts
  packages/vite/src/node/plugins/define.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/utils.ts
  playground/define/__tests__/define.spec.ts
  playground/define/commonjs-dep/index.js
  playground/define/index.html
  playground/define/vite.config.js
  playground/env/__tests__/env.spec.ts
  playground/env/index.html
  playground/html/__tests__/html.spec.ts
  playground/html/env.html
  playground/html/vite.config.js
  playground/react/components/DefineVariables.jsx
  playground/vue/DefineVariable.vue
Labels: breaking change, p3-significant 🔨

#8746 refactor!: move side effect of restart server to the caller
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/shortcuts.ts
Labels: p2-to-be-discussed :cake:, breaking change

#14679 ci: run CI on new Node LTS version (20)
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#14517 fix(css): ensure code is valid after empty css chunk imports are removed (fix #14515)
  packages/vite/src/node/__tests__/plugins/css.spec.ts
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#14790 chore: update license
  packages/vite/LICENSE.md
Labels: p1-chore :broom:

#14791 feat: add a runtime warning for the old object type transformIndexHtml hook
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: p2-nice-to-have :cake:

#14792 refactor!: remove non boolean middleware mode
  docs/guide/migration.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/server/index.ts
Labels: p1-chore :broom:, breaking change

#14756 fix(html)!: align html serving between dev and preview
  docs/guide/migration.md
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/htmlFallback.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/middlewares/notFound.ts
  packages/vite/src/node/shortcuts.ts
  packages/vite/src/node/utils.ts
  packages/vite/src/types/shims.d.ts
  playground/assets/__tests__/assets.spec.ts
  playground/html/__tests__/html.spec.ts
  playground/html/index.html
  playground/html/serve/both.html
  playground/html/serve/both/index.html
  playground/html/serve/file.html
  playground/html/serve/folder/index.html
  playground/html/vite.config.js
  playground/legacy/__tests__/legacy.spec.ts
  pnpm-lock.yaml
Labels: breaking change, p3-significant 🔨

#14804 refactor(esbuild)!: remove esbuild 0.17 -> 0.18 compat
  docs/guide/features.md
  docs/guide/migration.md
  packages/vite/src/node/__tests__/plugins/esbuild.spec.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/esbuild.ts
  playground/tsconfig-json/__tests__/tsconfig-json.spec.ts
  playground/tsconfig-json/tsconfig.json
Labels: breaking change

#14788 perf(define): create simple regex for checks
  packages/vite/src/node/__tests__/plugins/define.spec.ts
  packages/vite/src/node/plugins/define.ts
Labels: p2-nice-to-have :cake:, performance

#14821 feat: upgrade rollup to 4.2.0 and use parseAstAsync
  package.json
  packages/vite/package.json
  packages/vite/src/node/ssr/ssrTransform.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#14827 chore: revert "feat: show warning to discourage putting process/global to `define` option (#14447)"
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#14830 docs: add links to migration guide
  docs/guide/migration.md
Labels: documentation

#14832 docs: remove boolean from `server.https`
  docs/config/server-options.md
Labels: documentation
