Repository vitejs/vite, pull requests merged in 2023-03, with the labels that each got.

#11910 fix(build-import-analysis): should not append ?used when css request has ?url or ?raw
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/assets/__tests__/relative-base/relative-base-assets.spec.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#12174 feat: add `sourcemapIgnoreList` configuration option
  docs/config/server-options.md
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p3-significant 🔨

#12197 feat: don't override `build.target` if terser is 5.16.0+
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#11219 fix: resolve browser mapping using bare imports (fix #11208)
  packages/vite/src/node/plugins/resolve.ts
  playground/resolve/browser-field-bare-import-fail/main.js
  playground/resolve/browser-field-bare-import-fail/module.js
  playground/resolve/browser-field-bare-import-fail/package.json
  playground/resolve/browser-field-bare-import-success/main.js
  playground/resolve/browser-field-bare-import-success/module.js
  playground/resolve/browser-field-bare-import-success/package.json
  playground/resolve/browser-field/bare-import.js
  playground/resolve/browser-field/package.json
  playground/resolve/index.html
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#12263 fix: configure proxy before subscribing to error events
  packages/vite/src/node/server/middlewares/proxy.ts
Labels: p2-nice-to-have :cake:

#7770 feat: support ESM subpath imports
  packages/vite/src/node/packages.ts
  packages/vite/src/node/plugins/resolve.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/imports-path/nested-path.js
  playground/resolve/imports-path/other-pkg/nest/index.js
  playground/resolve/imports-path/other-pkg/package.json
  playground/resolve/imports-path/slash/index.js
  playground/resolve/imports-path/star/index.js
  playground/resolve/imports-path/top-level.js
  playground/resolve/index.html
  playground/resolve/package.json
  pnpm-lock.yaml
Labels: enhancement, p3-downstream-blocker :hammer:

#7227 feat(css): add preprocessor option to define stylus vars & funcs
  docs/config/shared-options.md
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/index.html
  playground/css/stylus.styl
  playground/css/vite.config.js
Labels: feat: css, p2-nice-to-have :cake:

#12309 fix: enforce absolute path for server.sourcemapIgnoreList
  docs/config/server-options.md
  packages/vite/src/node/server/transformRequest.ts
Labels: p3-minor-bug :hammer:

#7817 feat(css): support resolving stylesheets from exports map
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/css-dep-exports/index.js
  playground/css/css-dep-exports/package.json
  playground/css/css-dep-exports/style.css
  playground/css/css-dep-exports/style.scss
  playground/css/dep.css
  playground/css/index.html
  playground/css/package.json
  playground/css/sass.scss
  pnpm-lock.yaml
Labels: feat: css, p3-significant 🔨

#12202 feat(html): support env replacement
  docs/guide/env-and-mode.md
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/html/.env
  playground/html/__tests__/html.spec.ts
  playground/html/env.html
  playground/html/vite.config.js
Labels: feat: html, p2-nice-to-have :cake:

#12321 fix(config): watch config even outside of root
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#12207 feat(css): add build.cssMinify
  docs/config/build-options.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/no-css-minify/no-css-minify.spec.ts
  playground/css/__tests__/no-css-minify/vite.config.js
  playground/css/package.json
  playground/css/vite.config-no-css-minify.js
Labels: feat: css, p3-significant 🔨

#12204 fix(define): correctly replace SSR in dev
  packages/vite/src/node/plugins/define.ts
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p3-minor-bug :hammer:

#12346 fix(types): avoid resolve.exports types for bundling
  packages/vite/src/node/packages.ts
Labels: p4-important :exclamation:

#12358 fix(optimizer): suppress esbuild cancel error
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/scan.ts
Labels: p2-nice-to-have :cake:

#12347 docs: add note about using define in envPrefix config
  docs/config/shared-options.md
Labels: documentation, p1-chore :broom:

#12349 fix(config): watch envDir even outside of root
  packages/vite/src/node/config.ts
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#12105 chore: add `português` to locales in `.vitepress/config.ts`
  docs/.vitepress/config.ts
Labels: documentation, p2-nice-to-have :cake:

#12261 fix: print urls when dns order change
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#12316 feat(types): export Rollup namespace
  packages/vite/src/node/index.ts
Labels: p2-nice-to-have :cake:

#12378 ci: should exit when build-types-check failed
  packages/vite/scripts/checkBuiltTypes.ts
Labels: p1-chore :broom:

#12343 fix(optimizer): transform css require to import directly
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
Labels: feat: css, p3-minor-bug :hammer:, feat: deps optimizer

#12324 fix: throw ssr import error directly (fix #12322)
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-minor-bug :hammer:, feat: ssr, possible regression

#11919 fix(worker): force rollup to build worker module under watch mode
  packages/vite/src/node/plugins/worker.ts
Labels: p3-minor-bug :hammer:, feat: web workers

#12108 fix(reporter): build.assetsDir should not impact output when in lib mode
  packages/vite/src/node/plugins/reporter.ts
Labels: p2-nice-to-have :cake:

#12391 chore: remove build warn filter
  packages/vite/rollup.config.ts
Labels: p1-chore :broom:

#12392 chore: fix test misc
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/__snapshots__/parse.test.ts.snap
  packages/vite/src/node/__tests__/plugins/importGlob/__snapshots__/fixture.test.ts.snap
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
  packages/vite/src/node/ssr/__tests__/ssrStacktrace.spec.ts
  playground/optimize-deps/vite.config.js
  playground/tailwind-sourcemap/postcss.config.js
Labels: p1-chore :broom:

#12382 chore: remove issue comment for help labels
  .github/workflows/issue-labeled.yml
Labels: p1-chore :broom:

#12381 refactor(resolve): remove deep import syntax handling
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:

#12379 fix(server): should close server after create new server
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#12415 fix(optimizer): # symbol in deps id stripped by browser
  packages/vite/src/node/utils.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/index.html
Labels: p3-minor-bug :hammer:, feat: deps optimizer

#12435 feat: add status message for 504 caused by optimizer
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p2-nice-to-have :cake:

#12390 feat(create-vite): support create-electron-vite
  packages/create-vite/src/index.ts
Labels: p2-nice-to-have :cake:

#12488 fix: simplify prettyUrl
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:

#12486 fix: escape replacements in clientInjections
  packages/vite/src/node/plugins/clientInjections.ts
Labels: p4-important :exclamation:, performance

#12484 perf(css): improve postcss config resolve
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p4-important :exclamation:, performance

#12461 perf(resolve): refactor package.json handling for deep imports
  packages/vite/src/node/plugins/resolve.ts
Labels: p4-important :exclamation:, performance

#12476 perf(resolve): skip absolute paths in root as url checks
  packages/vite/src/node/plugins/resolve.ts
Labels: p4-important :exclamation:, performance

#12441 perf(resolve): improve package.json resolve speed
  packages/vite/package.json
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/packages.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
Labels: p4-important :exclamation:, performance

#12493 refactor: esbuild plugin config logic
  packages/vite/src/node/plugins/esbuild.ts
Labels: p1-chore :broom:

#12274 fix(ssr): hoist import statements to the top
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#12516 fix: esbuild complains with extra fields
  packages/vite/src/node/plugins/esbuild.ts
Labels: p3-downstream-blocker :hammer:

#12512 perf: improve package cache usage
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/packages.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: p4-important :exclamation:, performance

#12502 perf: remove regex in ImportMetaURL plugins
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
Labels: performance

#12530 fix(ssr): hoist re-exports with imports
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#12520 perf: more regex improvements
  packages/vite/scripts/util.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/clientInjections.ts
  packages/vite/src/node/plugins/define.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/__tests__/pluginContainer.spec.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/utils.ts
Labels: performance

#12528 test: move ssr tests from plugin-react
  playground/ssr/__tests__/serve.ts
  playground/ssr/__tests__/ssr.spec.ts
  playground/ssr/index.html
  playground/ssr/package.json
  playground/ssr/server.js
  playground/ssr/src/app.js
  playground/ssr/src/circular-dep-init/README.md
  playground/ssr/src/circular-dep-init/circular-dep-init.js
  playground/ssr/src/circular-dep-init/module-a.js
  playground/ssr/src/circular-dep-init/module-b.js
  playground/ssr/src/forked-deadlock/README.md
  playground/ssr/src/forked-deadlock/common-module.js
  playground/ssr/src/forked-deadlock/deadlock-fuse-module.js
  playground/ssr/src/forked-deadlock/fuse-stuck-bridge-module.js
  playground/ssr/src/forked-deadlock/middle-module.js
  playground/ssr/src/forked-deadlock/stuck-module.js
  playground/ssr/src/utils.js
  playground/test-utils.ts
  pnpm-lock.yaml
Labels: p1-chore :broom:

#11870 fix(html): public asset urls always being treated as paths (fix #11857)
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/utils.ts
  playground/assets/__tests__/url-base/url-base-assets.spec.ts
  playground/assets/__tests__/url-base/vite.config.js
  playground/assets/package.json
  playground/assets/vite.config-url-base.js
Labels: p3-minor-bug :hammer:

#12522 perf: extract vite:resolve internal functions
  packages/vite/src/node/plugins/resolve.ts
Labels: performance

#12542 perf(resolve): refactor tryFsResolve and tryResolveFile
  packages/vite/src/node/plugins/resolve.ts
Labels: p4-important :exclamation:, performance

#12550 perf(resolve): fix browser mapping nearest package.json check
  packages/vite/src/node/plugins/resolve.ts
Labels: p4-important :exclamation:, performance

#12551 perf: use `safeRealpath` in `getRealpath`
  packages/vite/src/node/plugins/resolve.ts
Labels: performance

#12548 perf(esbuild): make tsconfck non-blocking
  packages/vite/src/node/plugins/esbuild.ts
  packages/vite/src/node/plugins/index.ts
Labels: performance

#12485 feat(reporter): show gzip info for all compressible files (fix #11288)
  packages/vite/src/node/plugins/reporter.ts
Labels: p2-nice-to-have :cake:

#12564 refactor: remove `idToPkgMap`
  packages/vite/src/node/plugins/resolve.ts
Labels: p1-chore :broom:

#12560 fix: throw error on build optimizeDeps issue
  packages/vite/src/node/plugins/optimizedDeps.ts
Labels: p3-minor-bug :hammer:, feat: deps optimizer

#12553 perf: use fsp in more cases
  packages/vite/src/node/config.ts
  packages/vite/src/node/http.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: p2-nice-to-have :cake:, performance

#12573 perf: improve cleanUrl util
  packages/vite/src/node/utils.ts
Labels: performance

#12574 chore: disable reactivityTransform in vitepress
  docs/.vitepress/config.ts
Labels: p1-chore :broom:

#12571 perf(resolve): avoid isWorkerRequest and clean up .ts imported a .js
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/utils.ts
Labels: performance

#12576 perf(resolve): findNearestMainPackageData instead of lookupFile
  packages/vite/src/node/packages.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/utils.ts
Labels: performance

#11647 feat: use preview server parameter in preview server hook
  docs/guide/api-javascript.md
  docs/guide/api-plugin.md
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/preview.ts
Labels: p2-nice-to-have :cake:

#12578 refactor: improve scanner logs
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/optimizer/scan.ts
Labels: p2-nice-to-have :cake:

#12580 perf: try using realpathSync.native in Windows
  packages/vite/src/node/utils.ts
Labels: performance

#12577 refactor: use findNearestPackageData in more places
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
Labels: p1-chore :broom:

#12582 fix: avoid temporal optimize deps dirs
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/utils.ts
Labels: p3-significant 🔨

#12588 refactor: isInNodeModules util
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/splitVendorChunk.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/utils.ts
Labels: p1-chore :broom:

#12601 perf: cache `depsCacheDirPrefix` value for `isOptimizedDepFile`
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: performance

#12593 perf(optimizer): start optimizer early
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
  packages/vite/src/node/ssr/__tests__/ssrStacktrace.spec.ts
  vitest.config.ts
Labels: performance

#12572 fix: splitFileAndPostfix works as cleanUrl
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug :hammer:

#12599 perf(html): apply preTransformRequest for html scripts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: feat: html, performance

#12609 perf(optimizer): bulk optimizer delay
  packages/vite/src/node/optimizer/optimizer.ts
Labels: performance

#12624 fix: call `buildStart` only once when using next port
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:, possible regression

#12625 test: don't share cacheDir among different configs
  playground/assets/vite.config-relative-base.js
  playground/assets/vite.config-runtime-base.js
  playground/assets/vite.config-url-base.js
  playground/css/vite.config-no-css-minify.js
  playground/css/vite.config-relative-base.js
  playground/lib/vite.dyimport.config.js
  playground/lib/vite.nominify.config.js
  playground/preload/vite.config-preload-disabled.ts
  playground/preload/vite.config-resolve-deps.ts
  playground/worker/vite.config-es.js
  playground/worker/vite.config-iife.js
  playground/worker/vite.config-relative-base.js
  playground/worker/vite.config-sourcemap.js
Labels: p1-chore :broom:

#12626 test: fix flaky assets/url-base test fail
  playground/assets/__tests__/url-base/url-base-assets.spec.ts
  playground/assets/vite.config-url-base.js
  playground/test-utils.ts
Labels: p1-chore :broom:

#12622 perf: back to temporal optimizer dirs
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p4-important :exclamation:, performance

#12650 fix(html): dont pretransform public scripts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: feat: html, p3-minor-bug :hammer:

#12633 fix: sourcemapIgnoreList for optimizedDeps
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/sourcemap.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p3-minor-bug :hammer:

#12638 perf(resolve): skip for virtual files
  packages/vite/src/node/plugins/resolve.ts
Labels: performance

#12654 perf: avoid new URL() in hot path
  packages/vite/src/node/server/moduleGraph.ts
Labels: performance

#12619 perf(moduleGraph): resolve dep urls in parallel
  packages/vite/src/node/server/moduleGraph.ts
Labels: performance

#12642 fix: output combined sourcemap in importAnalysisBuild plugin
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
  playground/js-sourcemap/after-preload-dynamic.js
  playground/js-sourcemap/dynamic/dynamic-foo.css
  playground/js-sourcemap/dynamic/dynamic-foo.js
  playground/js-sourcemap/index.html
  playground/js-sourcemap/vite.config.js
Labels: p3-minor-bug :hammer:

#12614 perf: reduce runOptimizerIfIdleAfterMs time
  packages/vite/src/node/optimizer/optimizer.ts
Labels: performance

#12621 docs: show vite sponsors
  docs/.vitepress/theme/components/HomeSponsors.vue
  docs/.vitepress/theme/composables/sponsor.ts
Labels: documentation

#12661 fix(worker): disable manifest plugins in worker build
  packages/vite/src/node/build.ts
Labels: p3-downstream-blocker :hammer:, feat: web workers

#12635 perf: module graph url shortcuts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/moduleGraph.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: performance

#11731 fix: throws error when plugin tries to resolve ID to external URL
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p3-minor-bug :hammer:

#12672 refactor: clean up preTransformRequest
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: p1-chore :broom:
