Repository vitejs/vite, pull requests merged in 2023-06, with the labels that each got.

#13384 docs(legacy): add test case to ensure correct csp hashes in readme.md
  packages/plugin-legacy/README.md
  packages/plugin-legacy/src/__tests__/readme.spec.ts
Labels: documentation, plugin: legacy

#13412 fix: only show the listened IP when host is specified
  packages/vite/src/node/utils.ts
Labels: p2-has-workaround :cake:

#13413 test: rewrite `waitForNavigation` to `waitForEvent('load')`
  playground/assets/__tests__/assets.spec.ts
  playground/css/postcss-caching/css.spec.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/ssr-html/__tests__/ssr-html.spec.ts
Labels: p1-chore :broom:, test

#13402 fix(create-vite): support bun as a script runner
  packages/create-vite/src/index.ts
Labels: p2-nice-to-have :cake:

#13150 docs: add special sponsors section
  docs/.vitepress/theme/composables/sponsor.ts
  docs/public/astro.svg
  docs/public/nuxtlabs.svg
  docs/public/stackblitz.svg
  package.json
  pnpm-lock.yaml
Labels: documentation

#13427 refactor(config): replace `fs.promises` with `fsp`
  packages/vite/src/node/config.ts
Labels: p1-chore :broom:

#12467 feat(importMetaGlob): support sub imports pattern
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/resolve.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/glob-import/imports-path/bar.js
  playground/glob-import/imports-path/foo.js
  playground/glob-import/index.html
  playground/glob-import/package.json
Labels: p2-nice-to-have :cake:

#13073 fix: use consistent virtual module ID in module graph
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#13135 fix(mergeConfig): don't accept callback config
  docs/guide/api-javascript.md
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#13283 feat(config): friendly ESM file require error
  docs/guide/troubleshooting.md
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#12863 feat: support files for `fs.allow`
  docs/config/server-options.md
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:

#8400 feat(css): support at import preprocessed styles
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/types/shims.d.ts
  playground/css/__tests__/css.spec.ts
  playground/css/imported.scss
  playground/css/index.html
Labels: feat: css, p2-nice-to-have :cake:

#13431 docs(chunkSplitting): add `manualChunks` object form syntax warning when it is used with the `splitVendorChunk` plugin
  docs/guide/build.md
  packages/vite/src/node/plugins/splitVendorChunk.ts
Labels: documentation

#13438 fix: show network URLs when `--host 0.0.0.0`
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:, regression

#13381 fix: remove extra path shorten when resolving from a dir
  packages/vite/src/node/optimizer/index.ts
Labels: p3-minor-bug :hammer:

#12414 feat(optimizer): support glob includes
  docs/config/dep-optimization-options.md
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/resolve.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/utils.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-optimize-exports-with-glob/glob/bar.js
  playground/optimize-deps/dep-optimize-exports-with-glob/glob/foo.js
  playground/optimize-deps/dep-optimize-exports-with-glob/glob/nested/baz.js
  playground/optimize-deps/dep-optimize-exports-with-glob/index.js
  playground/optimize-deps/dep-optimize-exports-with-glob/named.js
  playground/optimize-deps/dep-optimize-exports-with-glob/package.json
  playground/optimize-deps/dep-optimize-with-glob/glob/bar.js
  playground/optimize-deps/dep-optimize-with-glob/glob/foo.js
  playground/optimize-deps/dep-optimize-with-glob/glob/nested/baz.js
  playground/optimize-deps/dep-optimize-with-glob/index.js
  playground/optimize-deps/dep-optimize-with-glob/named.js
  playground/optimize-deps/dep-optimize-with-glob/package.json
  playground/optimize-deps/package.json
  playground/optimize-deps/vite.config.js
  playground/test-utils.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:, feat: deps optimizer

#13057 fix(deps): update sirv to 2.0.3
  package.json
  packages/vite/package.json
  packages/vite/src/node/server/middlewares/static.ts
  patches/sirv@2.0.3.patch
  playground/fs-serve/__tests__/fs-serve.spec.ts
  playground/lib/package.json
  playground/package.json
  pnpm-lock.yaml
Labels: dependencies, p3-minor-bug :hammer:

#12924 fix(build): make output warning message clearer
  packages/vite/src/node/build.ts
Labels: p2-nice-to-have :cake:

#13262 fix: await requests to before server restart
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p3-significant 🔨

#13472 docs: link to the config and using plugin sections from getting started
  docs/guide/index.md
Labels: documentation

#13473 feat(html): support image set in inline style
  packages/vite/src/node/plugins/html.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: feat: css, p2-nice-to-have :cake:

#13437 docs: reword docs/config/Async Config
  docs/config/index.md
Labels: documentation

#13269 fix: unexpected temporary file
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:, on hold

#12850 feat(build): warn dynamic import module with a static import alongside
  packages/vite/src/node/plugins/reporter.ts
  playground/dynamic-import/__tests__/dynamic-import.spec.ts
Labels: p2-nice-to-have :cake:, feat: build

#13447 refactor(build): type rollup output
  packages/vite/src/node/build.ts
Labels: p1-chore :broom:

#9763 fix(ssr): fix crash when a pnpm/Yarn workspace depends on a CJS package
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  playground/ssr-deps/nested-external-cjs/index.js
  playground/ssr-deps/nested-external-cjs/package.json
  playground/ssr-deps/non-optimized-with-nested-external/index.js
  playground/ssr-deps/non-optimized-with-nested-external/package.json
  playground/ssr-deps/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, feat: ssr

#13516 docs: using loadEnv for define should use `JSON.stringify`
  docs/config/index.md
Labels: documentation

#13519 fix(optimizer): include exports for css modules
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-css-require/mod.cjs
  playground/optimize-deps/dep-css-require/mod.module.css
  playground/optimize-deps/index.html
Labels: p3-minor-bug :hammer:, regression, feat: deps optimizer

#11973 fix: keep track of ssr version of imported modules separately
  packages/vite/src/node/server/moduleGraph.ts
  playground/ssr-deps/__tests__/ssr-deps.spec.ts
  playground/ssr-deps/index.html
  playground/ssr-deps/server.js
  playground/ssr-deps/src/app.js
  playground/ssr-deps/src/isomorphic-module-browser.js
  playground/ssr-deps/src/isomorphic-module-server.js
Labels: p3-minor-bug :hammer:, feat: ssr

#12084 feat: emit event to handle chunk load errors
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
Labels: p3-downstream-blocker :hammer:

#13334 feat(client): add WebSocket connections events
  docs/guide/api-hmr.md
  packages/vite/src/client/client.ts
  packages/vite/types/customEvent.d.ts
Labels: feat: hmr, p2-nice-to-have :cake:

#13525 feat!: update esbuild to 0.18.2
  packages/vite/package.json
  packages/vite/src/node/plugins/esbuild.ts
  pnpm-lock.yaml
Labels: breaking change, p3-significant 🔨

#12807 feat(css): add support for Lightning CSS
  .eslintrc.cjs
  packages/vite/api-extractor.json
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/scripts/api-extractor.ts
  packages/vite/src/node/__tests__/plugins/css.spec.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/types/lightningcss.d.ts
  playground/css-lightningcss/__tests__/lightningcss.spec.ts
  playground/css-lightningcss/composed.module.css
  playground/css-lightningcss/composes-path-resolving.module.css
  playground/css-lightningcss/imported-at-import.css
  playground/css-lightningcss/imported.css
  playground/css-lightningcss/index.html
  playground/css-lightningcss/inline.module.css
  playground/css-lightningcss/inlined.css
  playground/css-lightningcss/linked-at-import.css
  playground/css-lightningcss/linked.css
  playground/css-lightningcss/main.js
  playground/css-lightningcss/minify.css
  playground/css-lightningcss/mod.module.css
  playground/css-lightningcss/ok.png
  playground/css-lightningcss/package.json
  playground/css-lightningcss/vite.config.js
  pnpm-lock.yaml
Labels: feat: css, p3-significant 🔨

#13545 feat(client): add debounce on page reload
  packages/vite/src/client/client.ts
Labels: p3-minor-bug :hammer:

#13566 fix: clean up changelog, downgrade conventional-changelog-cli to v2
  package.json
  packages/vite/CHANGELOG.md
  pnpm-lock.yaml
Labels: p1-chore :broom:

#13578 fix(proxy): forward SSE close event
  packages/vite/src/node/server/middlewares/proxy.ts
Labels: p3-minor-bug :hammer:

#13577 feat: update esbuild to 0.18.6
  packages/vite/package.json
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#13579 fix: the shortcut fails to open browser when set the host
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#13585 chore: add funding field
  packages/create-vite/package.json
  packages/plugin-legacy/package.json
  packages/vite/package.json
Labels: p1-chore :broom:

#13024 fix(hmr): only invalidate `lastHMRTimestamp` of importers if the invalidated module is not a HMR boundary
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/moduleGraph.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/issue-3033/a.js
  playground/hmr/issue-3033/b.js
  playground/hmr/issue-3033/c.js
  playground/hmr/issue-3033/index.html
  playground/hmr/issue-3033/index.js
Labels: feat: hmr

#13581 fix(indexHtml): decode html URI
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/html/__tests__/html.spec.ts
  playground/html/a á.html
  playground/html/vite.config.js
Labels: p3-minor-bug :hammer:

#13623 chore: show error position
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
Labels: p2-nice-to-have :cake:

#13635 fix(ssr): transform superclass identifier
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#13644 feat: update esbuild to 0.18.10
  packages/vite/package.json
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#12968 feat: preview mode add keyboard shortcuts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/shortcuts.ts
Labels: p2-nice-to-have :cake:, p2-to-be-discussed :cake:

#13661 fix(css): use esbuild legalComments config when minifying CSS
  packages/vite/src/node/plugins/css.ts
  playground/minify/__tests__/minify.spec.ts
  playground/minify/dir/module/index.css
  playground/minify/dir/module/index.js
  playground/minify/dir/module/package.json
  playground/minify/main.js
  playground/minify/package.json
  playground/minify/test.css
  playground/minify/vite.config.js
  pnpm-lock.yaml
Labels: feat: css, p3-minor-bug :hammer:
