Repository vitejs/vite, pull requests merged in 2023-04, with the labels that each got.

#12690 refactor: remove `ensureVolumeInPath`
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/utils.ts
Labels: p1-chore :broom:

#12688 fix(import-analysis): escape quotes correctly
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-minor-bug :hammer:

#12694 docs: update x_google_ignoreList documentation url
  docs/config/server-options.md
Labels: documentation

#12695 fix: take in relative assets path fixes from rollup
  packages/vite/src/node/build.ts
Labels: p3-minor-bug :hammer:

#12629 fix(worker): worker import.meta.url should not depends on document in iife mode
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/worker.ts
  playground/test-utils.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
  playground/worker/url-worker.js
Labels: p3-minor-bug :hammer:, feat: web workers

#12696 refactor: `import.meta.url` condition from renderChunk hook of worker plugin
  packages/vite/src/node/plugins/worker.ts
Labels: p1-chore :broom:

#10549 fix: leave fully dynamic import.meta.url asset (fixes #10306)
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  playground/assets/index.html
Labels: p2-has-workaround :cake:

#12716 docs: add a note about duplicate style by `additionalData`
  docs/config/shared-options.md
Labels: documentation

#12719 fix: ignore pnp resolve error
  packages/vite/src/node/packages.ts
Labels: p3-minor-bug :hammer:, possible regression

#12698 feat: skip pinging the server when the tab is not shown
  packages/vite/src/client/client.ts
Labels: p2-nice-to-have :cake:

#12722 fix: avoid clean up while committing deps folder
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
Labels: p3-minor-bug :hammer:

#12721 perf(css): cache lazy import
  packages/vite/src/node/plugins/css.ts
Labels: p2-nice-to-have :cake:, performance

#12732 perf: skip es-module-lexer if have no dynamic imports
  packages/vite/src/node/plugins/dynamicImportVars.ts
Labels: performance

#12700 fix(optimizer): load the correct lock file
  packages/vite/src/node/optimizer/index.ts
Labels: p3-minor-bug :hammer:, feat: deps optimizer

#12740 refactor: remove unused exports data props
  packages/vite/src/node/optimizer/index.ts
Labels: p1-chore :broom:

#12687 refactor: make debugger nullable
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/esbuild.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/middlewares/proxy.ts
  packages/vite/src/node/server/middlewares/time.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/server/sourcemap.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/utils.ts
Labels: p1-chore :broom:

#12744 perf: use package cache for one off resolve
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
Labels: performance

#12746 chore: fix resolve debug log timing
  packages/vite/src/node/server/pluginContainer.ts
Labels: p1-chore :broom:

#12658 perf(hmr): keep track of already traversed modules when propagating update
  packages/vite/src/node/server/hmr.ts
Labels: feat: hmr, performance

#12678 feat: reuse existing style elements in dev
  packages/vite/src/client/client.ts
Labels: feat: css, p2-nice-to-have :cake:, feat: ssr

#12558 fix(css): css file emit synchronously
  package.json
  packages/vite/package.json
  packages/vite/src/node/plugins/css.ts
  pnpm-lock.yaml
Labels: feat: css, p3-downstream-blocker :hammer:

#12682 chore: use @vitejs/release-scripts
  package.json
  packages/create-vite/package.json
  playground/css/__tests__/no-css-minify/vite.config.js
  pnpm-lock.yaml
  scripts/publishCI.ts
  scripts/release.ts
  scripts/releaseUtils.ts
  scripts/tsconfig.json
Labels: p1-chore :broom:

#12757 fix: allow onwarn to override vite default warning handling
  packages/vite/src/node/build.ts
Labels: p2-nice-to-have :cake:

#12754 perf: parallelize imports processing in import analysis plugin
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: performance

#12763 chore: improve debug log filtering
  packages/vite/src/node/utils.ts
Labels: p1-chore :broom:

#12772 fix: update package cache watcher
  packages/vite/src/node/build.ts
  packages/vite/src/node/packages.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#12770 refactor: use simpler resolve for nested optimized deps
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:, feat: deps optimizer

#12450 perf(resolve): avoid tryFsResolve for /@fs/ paths
  packages/vite/src/node/plugins/resolve.ts
Labels: p4-important :exclamation:, performance

#12471 perf(resolve): reduce vite client path checks
  packages/vite/src/node/config.ts
Labels: on hold, performance

#12057 feat(create-vite): move TypeScript ones up
  packages/create-vite/src/index.ts
Labels: p2-nice-to-have :cake:

#12697 fix(worker): asset in iife worker and relative base
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/worker.ts
  playground/worker/__tests__/relative-base-iife/relative-base-worker.spec.ts
  playground/worker/__tests__/relative-base-iife/vite.config.js
  playground/worker/package.json
  playground/worker/vite.config-relative-base-iife.js
Labels: p3-minor-bug :hammer:, feat: web workers

#12616 fix: warn on build when bundling code that uses nodejs built in module
  packages/vite/src/node/plugins/resolve.ts
Labels: p2-nice-to-have :cake:

#12786 fix: ignore sideEffects for scripts imported from html
  packages/vite/src/node/plugins/resolve.ts
  playground/html/__tests__/html.spec.ts
  playground/html/side-effects/index.html
  playground/html/side-effects/package.json
  playground/html/side-effects/sideEffects.js
  playground/html/vite.config.js
Labels: p4-important :exclamation:, feat: build

#12790 docs: yarn link and outdated dependencies
  docs/guide/troubleshooting.md
Labels: documentation

#12796 fix(css): resolve at import from dependency basedir
  packages/vite/rollup.config.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/resolve.ts
  playground/css/__tests__/css.spec.ts
  playground/css/css-proxy-dep-nested/index.css
  playground/css/css-proxy-dep-nested/package.json
  playground/css/css-proxy-dep/index.css
  playground/css/css-proxy-dep/package.json
  playground/css/dep.css
  playground/css/index.html
  playground/css/package.json
  pnpm-lock.yaml
Labels: feat: css, p3-minor-bug :hammer:

#12797 fix(worker): return null for shouldTransformCachedModule
  packages/vite/src/node/plugins/reporter.ts
  packages/vite/src/node/plugins/worker.ts
Labels: p4-important :exclamation:, feat: web workers, feat: build

#5495 test: resolve using absolute dep path
  playground/nested-deps/__tests__/nested-deps.spec.ts
  playground/nested-deps/index.html
  playground/nested-deps/package.json
  playground/nested-deps/test-package-f/index.js
  playground/nested-deps/test-package-f/package.json
  playground/nested-deps/vite.config.js
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, needs rebase

#12815 fix(resolve): use different importer check for css imports
  packages/vite/src/node/plugins/resolve.ts
Labels: feat: css, p4-important :exclamation:

#12808 fix: handle try-catch for fs promise when resolve https config
  packages/vite/src/node/http.ts
Labels: p4-important :exclamation:

#12831 fix(build): correctly handle warning ignore list
  packages/vite/src/node/build.ts
Labels: p3-minor-bug :hammer:

#12833 fix: correct vite config temporary name
  packages/vite/src/node/config.ts
Labels: p1-chore :broom:

#12799 fix(importAnalysis): warning on ExportAllDeclaration
  packages/vite/src/node/__tests__/plugins/import.spec.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-minor-bug :hammer:

#12851 fix: build time deps optimization, and ensure single crawl end call
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/plugins/preAlias.ts
  playground/worker/classic-shared-worker.js
  playground/worker/classic-worker.js
Labels: p4-important :exclamation:, feat: deps optimizer

#12869 perf: parallelize await exportsData from depsInfo
  packages/vite/src/node/optimizer/index.ts
Labels: performance

#12868 refactor: simplify crawlEndFinder
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
Labels: p3-significant 🔨, feat: deps optimizer

#12903 fix: yarn pnp considerBuiltins
  packages/vite/src/node/packages.ts
Labels: p3-minor-bug :hammer:, possible regression

#12907 docs: correct glob import as example
  docs/guide/features.md
Labels: documentation

#10917 refactor: resolveExports
  packages/vite/src/node/plugins/resolve.ts
Labels: p1-chore :broom:

#12940 chore: build time message setting color
  packages/vite/src/node/plugins/reporter.ts
Labels: p2-nice-to-have :cake:

#12985 fix(ssr): hoist statements after hashbang
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#12996 test(dynamic-import): fix multiline test
  playground/dynamic-import/__tests__/dynamic-import.spec.ts
  playground/dynamic-import/index.html
Labels: p1-chore :broom:, test

#12777 test(server): vite server restart flow
  playground/cli/__tests__/cli.spec.ts
  playground/cli/__tests__/serve.ts
  playground/ssr/__tests__/serve.ts
  playground/ssr/__tests__/ssr.spec.ts
  playground/ssr/server.js
  playground/ssr/vite.config.ts
  playground/vitestSetup.ts
Labels: p1-chore :broom:, test

#13005 fix: address file path mismatch when loading Vite config file on Windows (fix #12923)
  packages/vite/src/node/config.ts
Labels: p4-important :exclamation:

#13000 feat: optimize deps option to turn off auto discovery
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  playground/optimize-deps-no-discovery/__tests__/optimize-deps.spec.ts
  playground/optimize-deps-no-discovery/dep-no-discovery/index.js
  playground/optimize-deps-no-discovery/dep-no-discovery/package.json
  playground/optimize-deps-no-discovery/index.html
  playground/optimize-deps-no-discovery/package.json
  playground/optimize-deps-no-discovery/vite.config.js
  pnpm-lock.yaml
Labels: p3-downstream-blocker :hammer:, feat: deps optimizer

#13021 fix(ssr): track for statements as block scope
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p4-important :exclamation:, feat: ssr

#13022 test(resolve): ssr deep import resolve
  playground/ssr-resolve/__tests__/ssr-resolve.spec.ts
  playground/ssr-resolve/deep-import/bar/package.json
  playground/ssr-resolve/deep-import/foo/index.js
  playground/ssr-resolve/deep-import/foo/package.json
  playground/ssr-resolve/deep-import/index.js
  playground/ssr-resolve/deep-import/package.json
  playground/ssr-resolve/deep-import/utils/bar.js
  playground/ssr-resolve/main.js
  playground/ssr-resolve/package.json
  pnpm-lock.yaml
Labels: test
