Repository vitejs/vite, pull requests merged in 2023-01, with the labels that each got.

#11492 fix: importmap should insert before module preload link
  packages/vite/src/node/plugins/html.ts
  playground/html/__tests__/html.spec.ts
  playground/html/importmapOrder.html
  playground/html/vite.config.js
Labels: feat: html, p3-minor-bug :hammer:

#11543 test: use default import for fs-extra
  packages/create-vite/__tests__/cli.spec.ts
Labels: p1-chore :broom:

#11436 perf(resolve): improve file existence check
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-significant 🔨

#11460 refactor(build): close rollup bundle directly
  packages/vite/src/node/build.ts
Labels: p2-nice-to-have :cake:

#11502 fix: remove moment from force interop packages
  packages/vite/src/node/optimizer/index.ts
Labels: p2-nice-to-have :cake:

#11542 feat: reproducible manifest
  package.json
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/src/node/plugins/manifest.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#11259 fix(resolve): use only root package.json as exports source
  packages/vite/src/node/plugins/resolve.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/exports-and-nested-scope/index.js
  playground/resolve/exports-and-nested-scope/nested-scope/file.js
  playground/resolve/exports-and-nested-scope/nested-scope/package.json
  playground/resolve/exports-and-nested-scope/package.json
  playground/resolve/exports-from-root/file.js
  playground/resolve/exports-from-root/index.js
  playground/resolve/exports-from-root/nested/file.js
  playground/resolve/exports-from-root/nested/package.json
  playground/resolve/exports-from-root/package.json
  playground/resolve/index.html
  playground/resolve/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#11513 feat: support BROWSER and BROWSER_ARGS in env file
  docs/config/preview-options.md
  docs/config/server-options.md
  packages/vite/src/node/env.ts
  packages/vite/src/node/server/openBrowser.ts
Labels: p2-nice-to-have :cake:

#11506 fix(css): fix stale css when reloading with hmr disabled (#10270)
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/moduleGraph.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#11454 perf(build): disable rollup cache for builds
  packages/vite/src/node/build.ts
Labels: p3-significant 🔨

#11494 feat(cli): clear console by pressing c (#11493)
  packages/vite/src/node/shortcuts.ts
Labels: p2-nice-to-have :cake:

#11497 fix(hmr): base default protocol on client source location
  packages/vite/src/client/client.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#11595 fix(resolve): ensure exports has precedence over mainFields (cherry pick #11234)
  packages/vite/src/node/plugins/resolve.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/exports-with-module/import.mjs
  playground/resolve/exports-with-module/module.mjs
  playground/resolve/exports-with-module/package.json
  playground/resolve/index.html
  playground/resolve/package.json
  pnpm-lock.yaml
Labels: p4-important :exclamation:

#11673 chore: fix type warning during building vite
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/parse.test.ts
Labels: p1-chore :broom:

#11674 docs: fix build-options default
  docs/config/build-options.md
Labels: documentation

#11689 chore: StackBlitz startCommand
  package.json
Labels: p1-chore :broom:

#11669 chore: extract DEFAULT_DEV_PORT and DEFAULT_PREVIEW_PORT
  packages/vite/src/node/constants.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:

#11712 refactor: upgrade resolve.exports
  packages/vite/package.json
  packages/vite/src/node/plugins/resolve.ts
  pnpm-lock.yaml
Labels: p1-chore :broom:

#11487 fix(hmr): hmr websocket failure for custom middleware mode with server.hmr.server
  packages/vite/src/node/plugins/clientInjections.ts
Labels: feat: hmr, p2-nice-to-have :cake:

#11411 feat: add experimental option to skip SSR transform
  packages/vite/src/node/config.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: feat: ssr, p3-significant 🔨

#11747 fix(esbuild): check server before reload tsconfig
  packages/vite/src/node/plugins/esbuild.ts
Labels: p3-minor-bug :hammer:

#11759 chore: revert "chore(docs): workaround netlify pnpm build issue (#11477)"
  netlify.toml
  playground/ssr-resolve/__tests__/ssr-resolve.spec.ts
  playground/ssr-resolve/main.js
  playground/ssr-resolve/package.json
  playground/ssr-resolve/pkg-exports/package.json
  pnpm-lock.yaml
Labels: p1-chore :broom:

#11765 chore: clear netlify cache
  docs/.vitepress/config.ts
  netlify.toml
Labels: p1-chore :broom:

#11766 chore: revert "chore: clear netlify cache (#11765)"
  docs/.vitepress/config.ts
  netlify.toml
Labels: p1-chore :broom:

#11767 docs: ssr manifest can be used for 103 early hints
  docs/guide/ssr.md
Labels: documentation

#11811 fix: scope tracking for shadowing variables in blocks (#11806)
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: feat: ssr, p2-has-workaround :cake:

#11763 fix(css): insert styles in the same position
  packages/vite/src/client/client.ts
  playground/css-codesplit/__tests__/css-codesplit.spec.ts
  playground/css-codesplit/index.html
  playground/css-codesplit/main.js
  playground/css-codesplit/order/base.css
  playground/css-codesplit/order/dynamic.css
  playground/css-codesplit/order/index.js
  playground/css-codesplit/order/insert.js
Labels: feat: css, p3-minor-bug :hammer:, inconsistency

#11814 docs: change cors options object link
  docs/config/preview-options.md
  docs/config/server-options.md
Labels: documentation

#11430 fix: emit assets from SSR build
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/asset.ts
Labels: feat: ssr, p3-significant 🔨

#11602 fix: duplicated sourceMappingURL for worker bundles (fix #11601)
  packages/vite/src/node/plugins/worker.ts
Labels: p3-minor-bug :hammer:

#11720 docs: update vitepress
  .gitignore
  docs/.vitepress/theme/styles/vars.css
  pnpm-lock.yaml
Labels: documentation

#11819 docs: restore locale links
  docs/.vitepress/config.ts
Labels: documentation

#11317 fix: replace import.meta.hot with undefined in the production
  packages/vite/src/node/__tests__/plugins/define.spec.ts
  packages/vite/src/node/plugins/define.ts
  playground/hmr/counter/dep.ts
Labels: p2-nice-to-have :cake:

#11768 fix: make viteMetadata property of RenderedChunk optional
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/manifest.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
  packages/vite/types/metadata.d.ts
Labels: bug, possible regression

#11841 fix(plugin-legacy): legacy sourcemap not generate (fix #11693)
  packages/plugin-legacy/src/index.ts
  playground/legacy/__tests__/legacy.spec.ts
  playground/legacy/vite.config.js
Labels: plugin: legacy, p4-important :exclamation:, possible regression
