Repository vitejs/vite, pull requests merged in 2023-08, with the labels that each got.

#13970 fix(build): silence warn dynamic import module when inlineDynamicImports true
  packages/vite/src/node/plugins/reporter.ts
  playground/dynamic-import-inline/__tests__/dynamic-import-inline.spec.ts
  playground/dynamic-import-inline/index.html
  playground/dynamic-import-inline/package.json
  playground/dynamic-import-inline/src/foo.js
  playground/dynamic-import-inline/src/index.js
  playground/dynamic-import-inline/vite.config.js
Labels: p3-minor-bug :hammer:, feat: build

#14049 feat(deps): upgrade rollup to 3.28.0
  package.json
  packages/vite/package.json
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#14075 docs: viteconf 23 link
  docs/.vitepress/theme/components/AsideSponsors.vue
  docs/index.md
  docs/public/viteconf.svg
Labels: documentation

#14079 docs(cli): include `--profile` option
  docs/guide/cli.md
  docs/guide/troubleshooting.md
Labels: documentation

#14073 test: remove plugin-vue from tailwind playground
  playground/css/__tests__/postcss-plugins-different-dir/postcss-plugins-different-dir.spec.ts
  playground/tailwind/__test__/tailwind.spec.ts
  playground/tailwind/index.html
  playground/tailwind/src/App.vue
  playground/tailwind/src/assets/logo.png
  playground/tailwind/src/components/HelloWorld.vue
  playground/tailwind/src/components/PugTemplate.vue
  playground/tailwind/src/components/component1.js
  playground/tailwind/src/main.js
  playground/tailwind/src/router.ts
  playground/tailwind/src/utils.ts
  playground/tailwind/src/views/Page.vue
  playground/tailwind/src/views/view1.js
  playground/tailwind/tailwind.config.js
  playground/tailwind/vite.config.ts
  playground/test-utils.ts
Labels: p1-chore :broom:

#14030 feat!: bump minimum node version to 18
  .eslintrc.cjs
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  docs/guide/index.md
  netlify.toml
  package.json
  packages/create-vite/README.md
  packages/create-vite/build.config.ts
  packages/create-vite/package.json
  packages/create-vite/tsconfig.json
  packages/plugin-legacy/build.config.ts
  packages/plugin-legacy/package.json
  packages/vite/package.json
  packages/vite/src/node/config.ts
  packages/vite/tsconfig.base.json
  playground/tsconfig.json
  scripts/tsconfig.json
  vitest.config.e2e.ts
  vitest.config.ts
Labels: breaking change, p3-significant 🔨

#13893 fix(css): trim esbuild's minified css
  packages/vite/src/node/plugins/css.ts
  playground/glob-import/__tests__/glob-import.spec.ts
Labels: p2-to-be-discussed :cake:

#14098 fix!: avoid rewriting this (reverts #5312)
  packages/vite/src/node/build.ts
Labels: breaking change, p3-significant 🔨

#14119 refactor!: merge `PreviewServerForHook` into `PreviewServer` type
  docs/guide/api-javascript.md
  docs/guide/api-plugin.md
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/shortcuts.ts
Labels: p1-chore :broom:, breaking change

#14124 docs: clarify when `import.meta.env.PROD` is `true`
  docs/guide/env-and-mode.md
Labels: documentation

#14117 fix(glob): trigger HMR for glob in a package
  packages/vite/src/node/plugins/importMetaGlob.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/glob-import/import-meta-glob-pkg/index.js
  playground/glob-import/import-meta-glob-pkg/package.json
  playground/glob-import/index.html
  playground/glob-import/package.json
  playground/glob-import/pkg-pages/foo.js
  pnpm-lock.yaml
Labels: has workaround, p3-downstream-blocker :hammer:

#14127 fix: ws never connects after restarting server if server.hmr.server is set
  packages/vite/src/node/server/ws.ts
Labels: p3-downstream-blocker :hammer:

#14154 docs: update esbuild link
  docs/config/shared-options.md
Labels: documentation

#14144 docs: add example for mergeConfig with a config in callback form
  docs/guide/api-javascript.md
Labels: documentation

#14152 fix: initWasm options should be optional
  packages/vite/client.d.ts
Labels: p2-has-workaround :cake:, feat: wasm

#14072 docs: fix typo in cli.md
  docs/guide/cli.md
Labels: documentation

#11578 feat(css): build assets with the entry name when it is an entry point
  packages/vite/src/node/plugins/css.ts
  playground/backend-integration/__tests__/backend-integration.spec.ts
  playground/backend-integration/dir/foo.css
  playground/backend-integration/frontend/dynamic/foo.css
  playground/backend-integration/frontend/dynamic/foo.ts
  playground/backend-integration/frontend/entrypoints/main.ts
  playground/backend-integration/vite.config.js
Labels: feat: css, p2-nice-to-have :cake:

#14061 chore: use "kB" everywhere with the correct definition
  docs/config/build-options.md
  docs/guide/build.md
  packages/vite/rollup.config.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/reporter.ts
  playground/assets/vite.config.js
Labels: p1-chore :broom:

#14118 refactor(glob)!: remove `import.meta.globEager`
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/types/importGlob.d.ts
  packages/vite/types/importMeta.d.ts
Labels: p1-chore :broom:, breaking change

#14107 chore(deps): update miniflare to v3
  .github/renovate.json5
  playground/ssr-webworker/__tests__/serve.ts
  playground/ssr-webworker/package.json
  playground/ssr-webworker/worker.js
  pnpm-lock.yaml
Labels: dependencies, p1-chore :broom:

#14160 fix(client): correctly display the config file name
  packages/vite/src/client/overlay.ts
  packages/vite/src/node/plugins/clientInjections.ts
Labels: p2-nice-to-have :cake:

#14013 fix: if host is specified check whether it is valid
  packages/vite/src/node/cli.ts
Labels: p3-minor-bug :hammer:

#13514 fix: breakpoints in JS not working
  packages/vite/rollup.config.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/server/send.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  playground/css-sourcemap/__tests__/css-sourcemap.spec.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#14032 feat(worker): support a way to name the worker
  packages/vite/client.d.ts
  packages/vite/src/node/plugins/worker.ts
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
  playground/worker/__tests__/relative-base/relative-base-worker.spec.ts
  playground/worker/index.html
  playground/worker/worker/main-module.js
Labels: enhancement, p2-nice-to-have :cake:, feat: web workers

#14142 feat!: allow path containing . to fallback to index.html
  packages/vite/src/node/server/middlewares/htmlFallback.ts
  playground/assets/__tests__/assets.spec.ts
  playground/legacy/__tests__/legacy.spec.ts
  playground/legacy/immutable-chunk.js
  playground/legacy/index.html
Labels: p2-to-be-discussed :cake:, breaking change

#14168 docs(library-mode): add advanced usage warning
  docs/guide/build.md
Labels: documentation, feat: library mode

#14094 fix: use string manipulation instead of regex to inject esbuild helpers
  packages/vite/src/node/plugins/esbuild.ts
  playground/lib/__tests__/lib.spec.ts
  playground/lib/src/main.js
  playground/lib/vite.config.js
Labels: p3-significant 🔨

#14232 fix: handle sourcemap correctly when multiple line import exists
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
  playground/js-sourcemap/importee-pkg/index.js
  playground/js-sourcemap/importee-pkg/package.json
  playground/js-sourcemap/index.html
  playground/js-sourcemap/package.json
  playground/js-sourcemap/with-multiline-import.ts
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, feat: sourcemap

#14240 docs: remove npm@6 commands
  docs/guide/index.md
  packages/create-vite/README.md
Labels: documentation
