Repository vitejs/vite, pull requests merged in 2023-09, with the labels that each got.

#14017 docs: detect Bun package manager in `create-vite`
  docs/guide/index.md
  packages/create-vite/README.md
Labels: documentation

#14241 fix(vite): precisely check if files are in dirs
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/reporter.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/middlewares/base.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#13675 feat: export `server.bindCLIShortcuts`
  docs/guide/api-javascript.md
  packages/vite/src/node/cli.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/shortcuts.ts
Labels: p2-nice-to-have :cake:

#14256 fix(create-vite): remove redundant tsconfig include configuration
  packages/create-vite/template-svelte-ts/tsconfig.json
  packages/create-vite/template-vue-ts/tsconfig.json
Labels: p2-nice-to-have :cake:

#14296 fix: include `vite/types/*` in exports field
  packages/vite/package.json
Labels: p3-minor-bug :hammer:

#14285 fix(optimizer): define crawlDeps after scanProcessing and optimizationResult are complete (fix #14284)
  packages/vite/src/node/optimizer/optimizer.ts
Labels: p4-important :exclamation:, feat: deps optimizer

#14310 chore: remove unused packages
  package.json
  playground/multiple-entrypoints/package.json
  playground/tailwind/package.json
  pnpm-lock.yaml
Labels: p1-chore :broom:

#14326 fix(css): reset render cache on renderStart
  packages/vite/src/node/plugins/css.ts
  playground/lib/__tests__/serve.ts
  playground/lib/src/main-multiple-output.js
  playground/lib/src/sub-multiple-output.js
  playground/lib/vite.multiple-output.config.js
Labels: feat: css, p3-minor-bug :hammer:

#14331 chore: reduce one if judgment
  packages/vite/src/node/config.ts
Labels: p1-chore :broom:

#14297 fix(manifest): preserve pure css chunk assets
  packages/vite/src/node/plugins/css.ts
Labels: p3-downstream-blocker :hammer:

#14247 fix: use relative path for sources field
  packages/vite/src/node/server/send.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
Labels: p3-minor-bug :hammer:, feat: sourcemap

#14282 chore(docs): `api-plugin` and `features` apply outline deep
  docs/guide/api-plugin.md
  docs/guide/features.md
Labels: documentation, p2-nice-to-have :cake:

#13879 fix: omit 'plugins' since it has no effect
  packages/vite/src/node/plugin.ts
Labels: p3-minor-bug :hammer:

#14231 feat!: add extension to internal virtual modules
  packages/vite/src/node/plugins/dynamicImportVars.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/modulePreloadPolyfill.ts
  packages/vite/src/node/plugins/wasm.ts
Labels: rollup plugin compat, p2-nice-to-have :cake:, breaking change

#14307 fix(worker): inline es worker does not work in build mode
  packages/vite/src/node/plugins/worker.ts
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
  playground/worker/__tests__/relative-base/relative-base-worker.spec.ts
  playground/worker/index.html
  playground/worker/my-worker.ts
  playground/worker/worker/main-module.js
Labels: p3-minor-bug :hammer:, feat: web workers

#14377 feat: use `import.meta.url` instead of `self.location`
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  playground/assets/index.html
Labels: p3-minor-bug :hammer:

#14202 feat: ssrTransform support import assertion by default
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:, feat: ssr

#14188 feat: warn if # in project root
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#14055 feat: build.ssrEmitAssets out of experimental
  docs/config/build-options.md
  packages/vite/src/node/build.ts
Labels: feat: ssr, p3-significant 🔨

#13944 refactor: remove CJS ssr output format
  docs/config/ssr-options.md
  docs/guide/ssr.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/ssr/__tests__/ssrExternal.spec.ts
  packages/vite/src/node/ssr/index.ts
  packages/vite/src/node/ssr/ssrExternal.ts
Labels: feat: ssr, p3-significant 🔨

#14391 fix(deps): update dependency dotenv-expand to v10
  package.json
  packages/vite/package.json
  packages/vite/rollup.config.ts
  patches/dotenv-expand@10.0.0.patch
  patches/dotenv-expand@9.0.0.patch
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:

#14403 docs: use extends instead of spreading default theme
  docs/.vitepress/theme/index.ts
Labels: documentation

#14230 fix!: put manifest files in .vite directory by default
  docs/config/build-options.md
  docs/guide/backend-integration.md
  docs/guide/ssr.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/manifest.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
  playground/test-utils.ts
Labels: p2-has-workaround :cake:, breaking change

#14238 feat: add generic type for plugin api
  package.json
  packages/vite/package.json
  packages/vite/src/node/plugin.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#14394 fix: handle errors during `hasWorkspacePackageJSON` function
  packages/vite/src/node/server/searchRoot.ts
Labels: p3-minor-bug :hammer:

#14208 feat: allow passing down "null" to disable server watcher
  docs/config/server-options.md
  docs/guide/api-javascript.md
  packages/vite/src/node/server/__tests__/watcher.spec.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/watch.ts
Labels: p3-downstream-blocker :hammer:

#12858 chore(optimizer): debug info on cache dir handle process
  packages/vite/src/node/optimizer/index.ts
Labels: p2-nice-to-have :cake:

#13719 fix(legacy): add guard to modern polyfill chunk
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p3-minor-bug :hammer:

#13892 fix(plugin-legacy): ensure correct typing for node esm
  package.json
  packages/plugin-legacy/package.json
  pnpm-lock.yaml
Labels: plugin: legacy, p2-nice-to-have :cake:

#14419 chore: ensure create-vite has unbuild dev dep
  packages/create-vite/package.json
  pnpm-lock.yaml
Labels: p1-chore :broom:

#14342 feat(shortcuts)!: remove setRawMode
  packages/vite/src/node/shortcuts.ts
Labels: p3-significant 🔨

#14425 fix(legacy): suppress babel warning during polyfill scan
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p2-nice-to-have :cake:

#14428 fix(legacy): modern polyfill autodetection was injecting more polyfills than needed
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p3-minor-bug :hammer:

#11671 fix: unify css collecting order
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#14430 chore: update manually bumped deps
  package.json
  packages/create-vite/template-lit-ts/package.json
  packages/create-vite/template-preact-ts/package.json
  packages/create-vite/template-qwik-ts/package.json
  packages/create-vite/template-qwik/package.json
  packages/create-vite/template-react-ts/package.json
  packages/create-vite/template-solid-ts/package.json
  packages/create-vite/template-svelte-ts/package.json
  packages/create-vite/template-vanilla-ts/package.json
  packages/create-vite/template-vue-ts/package.json
  packages/vite/package.json
  packages/vite/src/node/__tests__/plugins/importGlob/__snapshots__/fixture.spec.ts.snap
  packages/vite/src/node/__tests__/plugins/importGlob/fixture.spec.ts
  packages/vite/src/node/__tests__/plugins/importGlob/parse.spec.ts
  packages/vite/src/node/__tests__/plugins/importGlob/utils.spec.ts
  pnpm-lock.yaml
Labels: dependencies, test

#14429 refactor(legacy)!: remove `ignoreBrowserslistConfig` option
  packages/plugin-legacy/README.md
  packages/plugin-legacy/src/index.ts
  packages/plugin-legacy/src/types.ts
Labels: plugin: legacy, p1-chore :broom:, breaking change

#14452 test: tweak lib helpers inject to test "use strict"
  playground/lib/__tests__/lib.spec.ts
Labels: p1-chore :broom:, test

#14461 refactor: replace duplicate code with tryStatSync
  packages/vite/src/node/packages.ts
  packages/vite/src/node/utils.ts
Labels: p1-chore :broom:

#14469 docs: update server.watch info
  docs/config/server-options.md
Labels: documentation

#14346 fix(legacy): fix broken build when renderModernChunks=false & polyfills=false (fix #14324)
  packages/plugin-legacy/src/index.ts
  playground/legacy/__tests__/no-polyfills-no-systemjs/no-polyfills-no-systemjs.spec.ts
  playground/legacy/__tests__/no-polyfills/no-polyfills.spec.ts
  playground/legacy/no-polyfills-no-systemjs.html
  playground/legacy/no-polyfills-no-systemjs.js
  playground/legacy/no-polyfills.html
  playground/legacy/no-polyfills.js
  playground/legacy/package.json
  playground/legacy/vite.config-no-polyfills-no-systemjs.js
  playground/legacy/vite.config-no-polyfills.js
Labels: plugin: legacy, p3-minor-bug :hammer:

#14447 feat: show warning to discourage putting process/global to `define` option
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#14465 fix(import-analysis): preserve importedUrls import order
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/module-graph/__tests__/module-graph.spec.ts
  playground/module-graph/empty.js
  playground/module-graph/imported-urls-order.js
  playground/module-graph/index.html
  playground/module-graph/package.json
  playground/module-graph/vite.config.ts
  pnpm-lock.yaml
Labels: p3-downstream-blocker :hammer:

#14487 fix: handle fs.realpath.native MAX_PATH issue for Node.js <18.10
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#13858 feat(terser): add `maxWorkers` option for terserOptions
  docs/config/build-options.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/terser.ts
Labels: p2-nice-to-have :cake:, feat: build

#14426 fix(hmr): dev mode reduce unnecessary restart
  packages/vite/src/node/env.ts
  packages/vite/src/node/server/hmr.ts
Labels: feat: hmr, p2-nice-to-have :cake:

#14458 fix(analysis): warnings for dynamic imports that use static template literals
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/dynamic-import/index.html
  playground/dynamic-import/nested/index.js
  playground/dynamic-import/nested/static.js
Labels: p3-minor-bug :hammer:

#14343 docs: v4 to v5 migration guide
  docs/.vitepress/config.ts
  docs/guide/migration.md
Labels: documentation

#14507 ci: use Node 18.17 for Windows due to a bug in Node
  .github/workflows/ci.yml
Labels: p1-chore :broom:, test
