Repository vitejs/vite, pull requests merged in 2023-02, with the labels that each got.

#11873 fix: await bundle closing
  packages/vite/src/node/build.ts
Labels: bug, p3-downstream-blocker :hammer:

#11834 docs: distinguish plugins config used for workers in build and serve
  docs/config/worker-options.md
Labels: documentation

#11865 fix(client): serve client sources next to deployed scripts
  packages/vite/rollup.config.ts
Labels: p3-significant 🔨

#11877 docs: add troubleshooting for browser compat
  docs/guide/troubleshooting.md
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/plugins/resolve.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
Labels: documentation

#11684 docs: add documentation about import.meta.hot magic
  docs/guide/api-hmr.md
Labels: documentation

#11879 docs: remove wrong vite command description
  docs/guide/cli.md
Labels: documentation

#11876 docs: tweak wording
  docs/config/index.md
  docs/config/shared-options.md
Labels: documentation

#11630 fix: two folders are created when the project name contains spaces
  packages/create-vite/src/index.ts
Labels: p3-minor-bug :hammer:

#11318 fix(plugin-legacy)!: support browserslist and update default target
  packages/plugin-legacy/README.md
  packages/plugin-legacy/package.json
  packages/plugin-legacy/src/index.ts
  pnpm-lock.yaml
Labels: plugin: legacy, p4-important :exclamation:, breaking change

#11896 feat(legacy)!: bump modern target to support async generator
  packages/plugin-legacy/README.md
  packages/plugin-legacy/package.json
  packages/plugin-legacy/src/__tests__/snippets.spec.ts
  packages/plugin-legacy/src/index.ts
  packages/plugin-legacy/src/snippets.ts
  playground/legacy/__tests__/legacy.spec.ts
  playground/legacy/index.html
  playground/legacy/main.js
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:, breaking change

#11899 fix(legacy): fix browserslist import, close https://github.com/vitejs/vite/issues/11898
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p5-urgent :fire:, possible regression

#11907 fix: catch statSync error
  packages/vite/src/node/plugins/resolve.ts
Labels: p4-important :exclamation:

#11909 test: reduce flaky fails
  playground/css-dynamic-import/__tests__/css-dynamic-import.spec.ts
  playground/css/__tests__/postcss-plugins-different-dir/postcss-plugins-different-dir.spec.ts
Labels: p1-chore :broom:, test

#12033 docs: fix migration guide link in vite v3 news
  docs/blog/announcing-vite3.md
Labels: documentation, p1-chore :broom:

#11906 fix(create-vite): add final newline for package.json
  packages/create-vite/src/index.ts
Labels: p2-nice-to-have :cake:

#12023 fix: correct access to `crossOrigin` attribute
  packages/vite/src/node/plugins/modulePreloadPolyfill.ts
Labels: bug, p3-minor-bug :hammer:

#12021 fix: narrow defineConfig return type
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#11959 docs(troubleshooting): add network stalled solution for ubuntu linux (fixes #11468)
  docs/guide/troubleshooting.md
Labels: documentation, p2-nice-to-have :cake:

#12045 chore: add issue template for docs
  .github/ISSUE_TEMPLATE/docs.yml
Labels: p1-chore :broom:

#12061 chore: patch sirv/build.js as well
  patches/sirv@2.0.2.patch
  pnpm-lock.yaml
Labels: p1-chore :broom:

#12035 docs: update GitHub Pages documentation
  docs/guide/static-deploy.md
Labels: documentation

#11828 docs: provider additional server proxy options
  docs/config/server-options.md
Labels: documentation

#12053 feat: support `import.meta.hot?.accept`
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/hmr/index.html
  playground/hmr/optional-chaining/child.js
  playground/hmr/optional-chaining/parent.js
Labels: p2-nice-to-have :cake:

#12078 docs: fix svg type override
  docs/guide/features.md
Labels: documentation

#12060 fix(ssr): print file url in `ssrTransform` parse error
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p2-nice-to-have :cake:, feat: ssr

#11988 fix(esbuild): umd helper insert into wrong position in lib mode
  packages/vite/src/node/plugins/esbuild.ts
  playground/lib/__tests__/lib.spec.ts
  playground/lib/src/main.js
Labels: p3-minor-bug :hammer:, feat: library mode

#12020 docs: precise plugin-react-swc build when using plugins
  docs/plugins/index.md
Labels: documentation

#11606 feat(ssr): add importer path to error msg when invalid url import occur
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
Labels: p2-nice-to-have :cake:, feat: ssr

#11764 fix(html): rewrite assets url in `<noscript>`
  packages/vite/src/node/plugins/html.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: feat: html, p3-minor-bug :hammer:

#12096 feat(preview): improve error when build output missing
  packages/vite/src/node/preview.ts
Labels: p2-nice-to-have :cake:

#12007 fix: catch and handle websocket error (#11991)
  packages/vite/src/node/server/ws.ts
Labels: p3-minor-bug :hammer:

#12091 fix(css): handle pure css chunk heuristic with special queries
  packages/vite/src/node/plugins/css.ts
  playground/css-codesplit/__tests__/css-codesplit.spec.ts
  playground/css-codesplit/chunk.css
  playground/css-codesplit/index.html
  playground/css-codesplit/main.js
  playground/css-codesplit/other.js
  playground/css-codesplit/vite.config.js
Labels: feat: css, p3-downstream-blocker :hammer:

#11961 fix: do not append version query param when scanning for dependencies
  packages/vite/src/node/plugins/resolve.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-alias-using-absolute-path/index.js
  playground/optimize-deps/dep-alias-using-absolute-path/package.json
  playground/optimize-deps/dynamic-use-dep-alias-using-absolute-path.js
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  playground/optimize-deps/unused-split-entry.js
  playground/optimize-deps/vite.config.js
  pnpm-lock.yaml
Labels: p3-minor-bug :hammer:, feat: deps optimizer

#12111 fix(html): respect disable modulepreload
  packages/vite/src/node/plugins/html.ts
  playground/preload/index.html
  playground/preload/src/chunk.js
  playground/preload/src/main.js
  playground/preload/vite.config-preload-disabled.ts
  playground/preload/vite.config-resolve-deps.ts
  playground/preload/vite.config.ts
Labels: feat: html, p3-minor-bug :hammer:

#11818 refactor: remove constructed sheet type style injection
  packages/vite/src/client/client.ts
Labels: p1-chore :broom:

#12100 feat(reporter): report built time
  packages/vite/src/node/plugins/reporter.ts
Labels: p2-nice-to-have :cake:

#11977 fix(optimizer): log esbuild error when scanning deps
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/optimizer/scan.ts
Labels: p2-nice-to-have :cake:, feat: deps optimizer

#11908 feat: esbuild 0.17
  package.json
  packages/vite/package.json
  pnpm-lock.yaml
Labels: p3-significant 🔨

#11505 feat(cli): allow to specify sourcemap mode via --sourcemap build's option
  docs/guide/cli.md
  packages/vite/src/node/cli.ts
Labels: p2-nice-to-have :cake:

#11830 refactor: customize ErrorOverlay (part 2)
  packages/vite/src/client/overlay.ts
Labels: p2-nice-to-have :cake:

#11469 feat: support rollup plugin this.load in plugin container context
  packages/vite/src/node/server/__tests__/pluginContainer.spec.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: rollup plugin compat, p2-nice-to-have :cake:

#11974 fix(cli): after setting server.open, the default open is inconsistent…
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/shortcuts.ts
Labels: p3-minor-bug :hammer:

#12066 docs(dep-optimization): add disabled API
  docs/config/dep-optimization-options.md
Labels: documentation

#12182 docs(api-plugin): update server-to-client exampel
  docs/guide/api-plugin.md
Labels: documentation

#12183 docs(build): note chunkSizeWarningLimit compare with uncompressed size
  docs/config/build-options.md
Labels: documentation

#10108 docs: added custom logger info
  docs/config/shared-options.md
Labels: documentation

#12184 docs(api-hmr): note intellisense for import.meta.hot
  docs/guide/api-hmr.md
Labels: documentation

#12179 docs(prebundling): update latest options and behaviour
  docs/config/dep-optimization-options.md
  docs/guide/dep-pre-bundling.md
Labels: documentation

#12192 chore: allow context comment for ecosystem-ci run in PR
  .github/workflows/ecosystem-ci-trigger.yml
Labels: p1-chore :broom:

#12195 fix(css): should not rebase http url for less (fix: #12155)
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#12154 refactor(importAnalysis): cache injected env string
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p2-nice-to-have :cake:

#12181 docs(api-plugin): note plugin options extended properties
  docs/guide/api-plugin.md
Labels: documentation

#12230 chore(deps): update es-module-lexer
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies

#12131 refactor(playground): move to ESM module and add type check for config
  playground/alias/vite.config.js
  playground/assets-sanitize/vite.config.js
  playground/assets/__tests__/relative-base/vite.config.js
  playground/assets/__tests__/runtime-base/vite.config.js
  playground/assets/vite.config-relative-base.js
  playground/assets/vite.config-runtime-base.js
  playground/assets/vite.config.js
  playground/backend-integration/vite.config.js
  playground/cli/vite.config.js
  playground/css-codesplit-cjs/vite.config.js
  playground/css-codesplit/vite.config.js
  playground/css-sourcemap/vite.config.js
  playground/css/vite.config-relative-base.js
  playground/css/vite.config.js
  playground/define/vite.config.js
  playground/dynamic-import/vite.config.js
  playground/env-nested/vite.config.js
  playground/env/vite.config.js
  playground/extensions/vite.config.js
  playground/fs-serve/root/vite.config.js
  playground/hmr/optional-chaining/parent.js
  playground/html/vite.config.js
  playground/js-sourcemap/vite.config.js
  playground/legacy/vite.config-custom-filename.js
  playground/legacy/vite.config-multiple-output.js
  playground/legacy/vite.config.js
  playground/lib/vite.config.js
  playground/lib/vite.dyimport.config.js
  playground/lib/vite.nominify.config.js
  playground/multiple-entrypoints/vite.config.js
  playground/nested-deps/vite.config.js
  playground/optimize-deps/vite.config.js
  playground/preload/__tests__/preload-disabled/vite.config.js
  playground/preload/__tests__/resolve-deps/vite.config.js
  playground/resolve-config/root/vite.config.ts
  playground/resolve/vite.config.js
  playground/ssr-noexternal/vite.config.js
  playground/ssr-webworker/vite.config.js
  playground/tailwind-sourcemap/vite.config.js
  playground/transform-plugin/vite.config.js
  playground/tsconfig.json
  playground/vitestSetup.ts
  playground/worker/__tests__/es/vite.config.js
  playground/worker/__tests__/iife/vite.config.js
  playground/worker/__tests__/relative-base/vite.config.js
  playground/worker/__tests__/sourcemap-hidden/vite.config.js
  playground/worker/__tests__/sourcemap-inline/vite.config.js
  playground/worker/__tests__/sourcemap/vite.config.js
  playground/worker/vite.config-es.js
  playground/worker/vite.config-iife.js
  playground/worker/vite.config-relative-base.js
  playground/worker/vite.config-sourcemap.js
Labels: p1-chore :broom:, test
