Repository vitejs/vite, pull requests merged in 2023-11, with the labels that each got.

#14831 docs: update stale `define` docs
  docs/guide/env-and-mode.md
Labels: documentation

#14833 feat: expose parseAst and parseAstAsync from rollup
  packages/vite/rollup.dts.config.ts
  packages/vite/src/node/index.ts
  packages/vite/tsconfig.check.json
Labels: p3-downstream-blocker :hammer:

#14787 feat(server): add warmupRequest api
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/server/warmup.ts
Labels: p2-nice-to-have :cake:

#14817 docs: explain intended usage of `import.meta.hot.data`
  docs/guide/api-hmr.md
Labels: documentation

#14828 docs: avoid importing large deps
  docs/guide/performance.md
Labels: documentation

#14829 refactor: simplify build optimizer node_env handling
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/define.ts
  playground/define/__tests__/define.spec.ts
  playground/define/index.html
Labels: p2-nice-to-have :cake:

#14822 feat(pluginContainer): implement watchChange hook
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: rollup plugin compat, p2-nice-to-have :cake:

#14648 feat: implement AsyncDisposable
  packages/vite/src/node/constants.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/server/ws.ts
Labels: p2-nice-to-have :cake:

#14847 fix: use correct publicDir in ERR_LOAD_PUBLIC_URL
  packages/vite/src/node/server/transformRequest.ts
Labels: p2-nice-to-have :cake:

#14845 chore: add `PluginWithRequiredHook` type & extract `getHookHandler` function
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: p1-chore :broom:

#14834 fix(types)!: expose httpServer with Http2SecureServer union
  packages/vite/src/node/http.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/proxy.ts
  packages/vite/src/node/server/ws.ts
Labels: p2-nice-to-have :cake:, breaking change

#14862 chore: fix git tag log
  scripts/releaseUtils.ts
Labels: p1-chore :broom:

#14871 fix(css): fix sourcemap warning in build with lightningCSS
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#14872 fix(css): initialize lightningCSS targets when not using options
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-has-workaround :cake:

#14876 docs(migration): tweak wordings
  docs/guide/migration.md
Labels: documentation

#14878 test: use `isPreview` instead of `previewBase`
  playground/assets/vite.config-relative-base.js
  playground/css/vite.config-relative-base.js
  playground/legacy/vite.config-no-polyfills-no-systemjs.js
  playground/legacy/vite.config-no-polyfills.js
  playground/vitestSetup.ts
  playground/worker/vite.config-relative-base-iife.js
  playground/worker/vite.config-relative-base.js
Labels: p1-chore :broom:, test

#14879 fix: file link in overlay with custom backend
  packages/vite/src/client/overlay.ts
Labels: p3-minor-bug :hammer:

#14870 fix: processNodeUrl for srcset
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: feat: html, p3-minor-bug :hammer:

#14889 docs: add #14834 to migration guide
  docs/guide/migration.md
Labels: documentation

#14892 fix: use latest module graph in transform middleware
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#14890 fix: resovedUrls is null after server restart
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/cli/__tests__/cli.spec.ts
Labels: p3-minor-bug :hammer:

#14888 fix(build): mixed external and transpiled srcset
  packages/vite/src/node/plugins/html.ts
  playground/assets/__tests__/assets.spec.ts
Labels: feat: html, p3-minor-bug :hammer:

#14867 feat(hmr): improve circular import updates
  docs/guide/troubleshooting.md
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/moduleGraph.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/circular/index.js
  playground/hmr/circular/mod-a.js
  playground/hmr/circular/mod-b.js
  playground/hmr/circular/mod-c.js
  playground/hmr/hmr.ts
  playground/hmr/index.html
Labels: feat: hmr, p2-nice-to-have :cake:

#14905 fix: `server.headers` after restart in middleware mode
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/middlewares/static.ts
Labels: p3-minor-bug :hammer:

#14906 chore: add documentation update checkbox in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: p1-chore :broom:

#14907 docs: clarify origin part of `base` is not used in dev
  docs/config/shared-options.md
Labels: documentation

#14418 fix(server): the server restart port should remain unchanged
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#14909 feat: add invalid `rollupOptions` warnings
  packages/vite/src/node/build.ts
Labels: p2-nice-to-have :cake:

#14910 fix: injectQuery check with double slash in the url
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/dynamic-import/__tests__/dynamic-import.spec.ts
  playground/dynamic-import/index.html
  playground/dynamic-import/nested/index.js
Labels: p3-minor-bug :hammer:

#14918 fix(worker): prevent inject esm in classic workers
  .prettierignore
  packages/vite/src/client/client.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
  playground/worker/__tests__/relative-base/relative-base-worker.spec.ts
  playground/worker/classic-esm.js
  playground/worker/classic-worker.js
  playground/worker/index.html
  playground/worker/worker/main-classic.js
Labels: p3-minor-bug :hammer:, feat: web workers

#14933 feat(legacy): export `Options`
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p2-nice-to-have :cake:

#14932 docs: note skipLibCheck
  docs/guide/features.md
Labels: documentation

#14935 docs: update library mode env var tip
  docs/guide/build.md
Labels: documentation

#14937 refactor: update es-module-lexer to 1.4.0
  packages/vite/package.json
  packages/vite/src/node/plugins/dynamicImportVars.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
Labels: p1-chore :broom:

#14761 fix(build): make build error message clearer
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/reporter.ts
Labels: p2-nice-to-have :cake:

#14936 feat: skip initial clear screen if has logs
  packages/vite/index.cjs
  packages/vite/src/node/cli.ts
Labels: p2-nice-to-have :cake:

#14938 fix: add watch in fallback file load
  packages/vite/src/node/server/pluginContainer.ts
  playground/hmr-root/__tests__/hmr-root.spec.ts
  playground/hmr-root/foo.js
  playground/hmr-root/root/index.html
  playground/hmr-root/vite.config.ts
Labels: p4-important :exclamation:

#14940 docs: add mastodon link to sapphi-red
  docs/_data/team.js
Labels: documentation

#14939 docs: add v4.vitejs.dev link to nav bar
  docs/.vitepress/config.ts
Labels: documentation

#14874 docs(performance): use lesser or native tooling section
  docs/guide/performance.md
Labels: documentation

#14945 fix(css): correctly set manifest source name and emit CSS file
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/manifest.ts
  playground/backend-integration/__tests__/backend-integration.spec.ts
  playground/backend-integration/dir/foo.css
  playground/backend-integration/frontend/dynamic/foo.css
  playground/backend-integration/frontend/dynamic/foo.ts
  playground/backend-integration/frontend/entrypoints/foo.pcss
  playground/backend-integration/frontend/entrypoints/main.ts
  playground/css/__tests__/css.spec.ts
  playground/css/main.js
  playground/css/manual-chunk.css
  playground/css/vite.config.js
Labels: feat: css, p3-minor-bug :hammer:

#14953 fix: don't watch SPA fallback paths
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p3-minor-bug :hammer:, regression

#14955 fix: preload marker duplicate deps
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: bug, p2-nice-to-have :cake:

#14969 build: dont strip single line comments
  packages/vite/rollup.dts.config.ts
Labels: p1-chore :broom:

#14972 docs: add back link to ViteConf replay
  docs/.vitepress/theme/components/AsideSponsors.vue
  docs/index.md
Labels: documentation

#14970 docs: link to ViteConf replay
  docs/.vitepress/theme/components/AsideSponsors.vue
  docs/index.md
Labels: documentation

#14973 feat: error when failed to resolve aliased import
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/index.ts
Labels: p2-nice-to-have :cake:

#14965 fix(pluginContainer): run transform in this.load
  packages/vite/src/node/server/__tests__/pluginContainer.spec.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: p2-nice-to-have :cake:

#14968 fix(plugin-legacy): add invoke to modern detector to avoid terser treeshaking
  packages/plugin-legacy/README.md
  packages/plugin-legacy/src/snippets.ts
Labels: plugin: legacy, p3-minor-bug :hammer:

#14967 fix: handle addWatchFile in load hooks
  packages/vite/src/node/server/pluginContainer.ts
  playground/transform-plugin/__tests__/transform-plugin.spec.ts
  playground/transform-plugin/plugin-dep-load.js
  playground/transform-plugin/vite.config.js
Labels: p3-minor-bug :hammer:

#14979 fix: relax overlay frame regex
  packages/vite/src/client/overlay.ts
Labels: p2-nice-to-have :cake:

#14978 docs: explain node_env and modes
  docs/guide/env-and-mode.md
Labels: documentation

#14951 docs: update static-deploy.md to support custom domains with GitHub Pages
  docs/guide/static-deploy.md
Labels: documentation

#14701 style(client): overlay frame show scrollbar
  packages/vite/src/client/overlay.ts
Labels: p2-nice-to-have :cake:

#14984 fix: caret position was incorrect
  packages/vite/src/node/__tests__/__snapshots__/utils.spec.ts.snap
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/esbuild.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#14986 fix: code frame was not generated for postcss errors
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: feat: css, p3-minor-bug :hammer:

#14988 fix(ssr): skip esm proxy guard for namespace imports
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-downstream-blocker :hammer:, feat: ssr

#14995 fix: don't append `/@fs/` for bare imports
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p3-minor-bug :hammer:

#14993 fix: server.preTransformRequests https error (#14991)
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#14632 feat: allow providing parent httpServer on middleware mode
  docs/guide/api-javascript.md
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#14996 ci(publish): workaround provenance bug
  scripts/publishCI.ts
Labels: p1-chore :broom:

#14998 docs: improve why not bundle with esbuild
  docs/guide/why.md
Labels: documentation

#14860 docs: vite 5 announcement blog post
  docs/blog/announcing-vite4.md
  docs/blog/announcing-vite5.md
  docs/public/og-image-announcing-vite5.png
Labels: documentation

#14997 docs: dev vs build target
  docs/guide/dep-pre-bundling.md
  docs/guide/index.md
Labels: documentation

#15008 docs: remove Vite 5 feedback discussion note
  docs/releases.md
Labels: documentation

#15017 docs(troubleshooting): note config mts extension
  docs/guide/migration.md
  docs/guide/troubleshooting.md
Labels: documentation

#14987 fix: update type CSSModulesOptions interface
  docs/config/shared-options.md
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-nice-to-have :cake:

#15020 docs: indirect use vite.middlewares in example
  docs/guide/api-javascript.md
Labels: documentation

#15023 docs: add a note about `moduleResolution` for rollup 4
  docs/guide/migration.md
Labels: documentation

#15025 fix: run htmlFallbackMiddleware for no accept header requests
  packages/vite/src/node/server/middlewares/htmlFallback.ts
Labels: p3-minor-bug :hammer:

#15040 chore: add comment about crossorigin attribute for script module
  packages/vite/src/node/plugins/html.ts
Labels: p1-chore :broom:

#14450 fix(legacy): error in build with --watch and manifest enabled
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/manifest.ts
  playground/legacy/__tests__/watch/styles-only-entry-watch.spec.ts
  playground/legacy/package.json
  playground/legacy/style-only-entry.css
  playground/legacy/vite.config-watch.js
Labels: plugin: legacy, p3-minor-bug :hammer:

#15034 perf(hmr): skip traversed modules when checking circular imports
  packages/vite/src/node/server/hmr.ts
Labels: feat: hmr, p3-minor-bug :hammer:, performance

#14884 test: avoid read check when running as root
  packages/vite/src/node/__tests__/utils.spec.ts
Labels: test

#15026 chore(deps): update eslint-define-config
  .eslintrc.cjs
  .gitignore
  package.json
  pnpm-lock.yaml
Labels: dependencies

#15021 fix(legacy): preserve async generator function invocation
  packages/plugin-legacy/README.md
  packages/plugin-legacy/src/snippets.ts
  playground/legacy/__tests__/legacy.spec.ts
Labels: plugin: legacy, p3-minor-bug :hammer:

#15058 chore: fix order of commits since in release script
  package.json
  pnpm-lock.yaml
  scripts/releaseUtils.ts
Labels: p1-chore :broom:

#15057 docs(legacy): clarify that csp hashes could change between minors
  packages/plugin-legacy/README.md
Labels: documentation, plugin: legacy

#15095 fix(plugin-legacy): syntax error in variable `detectModernBrowserCode`
  packages/plugin-legacy/README.md
  packages/plugin-legacy/src/snippets.ts
Labels: plugin: legacy, p5-urgent :fire:

#15098 test(legacy): add a test to checks all inline snippets are valid JS
  packages/plugin-legacy/src/__tests__/snippets.spec.ts
Labels: plugin: legacy, p1-chore :broom:, test

#15096 test: skip unicode test on windows instead of lowering the Node version
  .github/workflows/ci.yml
  playground/hasWindowsUnicodeFsBug.js
  playground/hmr/__tests__/hmr.spec.ts
  playground/html/__tests__/html.spec.ts
  playground/html/vite.config.js
  playground/vitestGlobalSetup.ts
Labels: p1-chore :broom:

#15093 fix: `generateCodeFrame` infinite loop
  packages/vite/src/node/__tests__/__snapshots__/utils.spec.ts.snap
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: p4-important :exclamation:

#15135 fix: js fallback sourcemap content should be using original content
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/send.ts
  packages/vite/src/node/server/sourcemap.ts
Labels: p3-minor-bug :hammer:, feat: sourcemap

#15154 fix(css): render correct asset url when CSS chunk name is nested
  packages/vite/src/node/plugins/css.ts
  playground/assets/__tests__/relative-base/relative-base-assets.spec.ts
  playground/assets/css/manual-chunks.css
  playground/assets/index.html
  playground/assets/vite.config-relative-base.js
Labels: feat: css, p3-downstream-blocker :hammer:

#15133 docs: improve community templates section
  docs/guide/index.md
Labels: documentation

#15165 docs: reflect changes to manifest.json in migration.md
  docs/guide/migration.md
Labels: documentation

#15115 feat(legacy): build file name optimization
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p2-nice-to-have :cake:

#15155 fix(css): use non-nested chunk name if facadeModule is not CSS file
  packages/vite/src/node/plugins/css.ts
  playground/backend-integration/__tests__/backend-integration.spec.ts
  playground/backend-integration/frontend/entrypoints/index.html
  playground/backend-integration/frontend/entrypoints/nested/sub.ts
  playground/backend-integration/frontend/styles/imported.css
Labels: feat: css, p3-minor-bug :hammer:

#15162 fix: bindCLIShortcuts to proper server
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#15171 refactor: align with Promise.withResolvers()
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/utils.ts
  playground/test-utils.ts
Labels: p1-chore :broom:

#15173 fix(define): allow define process.env
  packages/vite/src/node/plugins/define.ts
  playground/define/__tests__/define.spec.ts
  playground/define/index.html
  playground/define/vite.config.js
Labels: p3-minor-bug :hammer:

#15168 test: avoid magic number on cli playground spec
  playground/cli/__tests__/cli.spec.ts
Labels: p1-chore :broom:, test

#15178 fix: revert "fix: js fallback sourcemap content should be using original content (#15135)"
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/send.ts
  packages/vite/src/node/server/sourcemap.ts
Labels: p3-significant 🔨

#15186 docs: verify Mastodon account
  docs/.vitepress/config.ts
Labels: documentation
