Repository vitejs/vite, pull requests merged in 2023-05, with the labels that each got.

#13040 fix(server): should respect hmr port when middlewareMode=false
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:, possible regression

#13063 docs: update Vue 2 plugins
  docs/guide/features.md
  docs/plugins/index.md
Labels: documentation

#12961 fix(legacy): import `@babel/preset-env`
  package.json
  packages/plugin-legacy/src/index.ts
  pnpm-lock.yaml
Labels: plugin: legacy, p3-minor-bug :hammer:

#13069 chore: cleanup hoist patterns
  .npmrc
Labels: p1-chore :broom:

#13083 fix: unwrapId and pass ssr flag when adding to moduleGraph in this.load
  packages/vite/src/node/server/pluginContainer.ts
Labels: p3-minor-bug :hammer:

#13099 fix(build): declare moduleSideEffects for vite:modulepreload-polyfill
  packages/vite/src/node/__tests__/plugins/modulePreloadPolyfill/__snapshots__/modulePreloadPolyfill.spec.ts.snap
  packages/vite/src/node/__tests__/plugins/modulePreloadPolyfill/modulePreloadPolyfill.spec.ts
  packages/vite/src/node/plugins/modulePreloadPolyfill.ts
Labels: p2-nice-to-have :cake:, feat: build

#13117 fix(server): intercept ping requests
  packages/vite/src/client/client.ts
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:

#13142 fix: call `tryFsResolve` for relative `new URL(foo, import.meta.url)`
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
  playground/worker/index.html
  playground/worker/worker/main-module.js
Labels: p3-minor-bug :hammer:, possible regression

#13193 docs: remove RFCs section
  docs/releases.md
Labels: documentation

#13160 fix: handle more yarn pnp load errors
  packages/vite/src/node/packages.ts
Labels: p3-minor-bug :hammer:, possible regression

#13162 perf: skip windows absolute paths for node resolve
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:, performance

#13190 fix(css): respect `esbuild.charset` when minify
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:

#13194 docs: tweak `build.cssCodeSplit` documentation
  docs/config/build-options.md
Labels: documentation

#12902 fix(ssr): stacktrace uses abs path with or without sourcemap
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/ssr/ssrStacktrace.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  playground/ssr-html/__tests__/ssr-html.spec.ts
  playground/ssr-html/src/error.ts
  playground/ssr-html/test-stacktrace.js
  playground/test-utils.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#13217 fix: revert only watch .env files in envDir (#12587)
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#13121 fix(assetImportMetaUrl): allow ternary operator in template literal urls
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: p4-important :exclamation:, possible regression

#13230 fix(ssr): skip updateCjsSsrExternals if legacy flag disabled
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:, feat: ssr

#13256 perf(ssr): calculate stacktrace offset lazily
  packages/vite/src/node/ssr/ssrStacktrace.ts
Labels: p2-nice-to-have :cake:, feat: ssr

#13273 test: respect commonjs options in playgrounds
  packages/vite/src/node/config.ts
Labels: p1-chore :broom:

#13266 fix(legacy): style insert order
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, plugin: legacy, p3-minor-bug :hammer:

#13274 fix: optimizeDeps during build and external ids
  packages/vite/src/node/plugins/optimizedDeps.ts
Labels: p3-minor-bug :hammer:, feat: deps optimizer

#13316 docs: preview not for production on CLI guide
  docs/guide/cli.md
Labels: documentation

#13323 docs: optimizeDeps.needsInterop
  docs/config/dep-optimization-options.md
  packages/vite/src/node/optimizer/index.ts
Labels: documentation

#13392 docs: cross drive links troubleshooting guide
  docs/guide/troubleshooting.md
Labels: documentation

#13389 docs: clarify html input entry name ignored for HTML files
  docs/guide/build.md
Labels: documentation

#13393 docs: accessing the server on WSL2 from your LAN
  docs/config/server-options.md
Labels: documentation
