Repository vitejs/vite, pull requests merged in 2023-12, with the labels that each got.

#15140 fix: esbuild glob import resolve error
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug :hammer:, feat: deps optimizer

#15203 fix: emit `vite:preloadError` for chunks without deps
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
Labels: p3-minor-bug :hammer:

#15204 perf: remove debug only prettifyUrl call
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: performance

#15218 feat(server): allow disabling built-in shortcuts
  packages/vite/src/node/shortcuts.ts
Labels: p2-nice-to-have :cake:

#15205 test: reduce optimize-deps playground flaky fail
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/test-utils.ts
Labels: p1-chore :broom:, test

#15207 perf: skip computing sourceRoot in injectSourcesContent
  packages/vite/src/node/server/sourcemap.ts
Labels: performance

#15222 docs: add about `vite:preloadError`
  docs/guide/build.md
Labels: documentation

#15223 fix: proxy html path should be encoded
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/ssr/__tests__/ssr.spec.ts
  playground/ssr/index.html
Labels: p3-minor-bug :hammer:

#15229 fix(hmr): don't consider CSS dep as a circular dep
  packages/vite/src/node/server/hmr.ts
Labels: feat: hmr, p3-minor-bug :hammer:

#15247 chore: remove unneccessary eslint-disable-next-line regexp/no-unused-capturing-group
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
Labels: p1-chore :broom:

#15245 perf: cache empty optimizer result
  packages/vite/src/node/optimizer/optimizer.ts
Labels: feat: deps optimizer, performance

#14958 fix(html): skip inlining icon and manifest links
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/html.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
  playground/assets/manifest.json
Labels: feat: html, p3-minor-bug :hammer:

#15264 fix: symbolic links in public dir
  packages/vite/src/node/publicDir.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:, regression

#15267 chore: remove unneeded condition in getRealPath
  packages/vite/src/node/plugins/resolve.ts
Labels: p1-chore :broom:

#15275 fix: suppress terser warning if minify disabled
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#15303 fix: missing warmupRequest in transformIndexHtml
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: performance

#15307 fix(ssr): check esm file with normal file path
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p3-minor-bug :hammer:, feat: ssr

#15317 fix: public files map will be updated on add/unlink in windows
  packages/vite/src/node/server/index.ts
Labels: windows only, p3-minor-bug :hammer:, regression

#15246 fix(build): decode urls in CSS files (fix #15109)
  packages/vite/src/node/plugins/css.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/css/css-url.css
  playground/assets/index.html
  playground/assets/nested/asset[small].png
Labels: feat: css, p3-minor-bug :hammer:

#15272 feat(cli): allow initializing non-empty directory
  packages/create-vite/src/index.ts
Labels: p2-nice-to-have :cake:

#15279 perf: cached fs utils
  packages/vite/src/node/config.ts
  packages/vite/src/node/fsUtils.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/htmlFallback.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/html/vite.config.js
Labels: performance

#15318 perf: avoid computing paths on each request
  packages/vite/src/node/server/middlewares/transform.ts
Labels: performance

#15321 fix(worker): replace `import.meta` correctly for IIFE worker
  packages/vite/src/node/plugins/worker.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
  playground/worker/url-worker.js
Labels: p3-minor-bug :hammer:, feat: web workers

#15299 perf: temporary hack to avoid fs checks for /@react-refresh
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: performance

#15329 chore: temporary typo
  packages/vite/src/node/optimizer/index.ts
Labels: p1-chore :broom:

#15301 fix: htmlFallbackMiddleware for favicon
  packages/vite/src/node/server/middlewares/htmlFallback.ts
Labels: p3-minor-bug :hammer:

#15271 fix(build): use base64 for inline SVG if it contains both single and double quotes
  packages/vite/src/node/plugins/asset.ts
  playground/data-uri/__tests__/data-uri.spec.ts
  playground/data-uri/double-quote-in-single-quotes.svg
  playground/data-uri/double-quotes-in-single-quotes.svg
  playground/data-uri/index.html
  playground/data-uri/main.js
  playground/data-uri/single-quote-in-double-quotes.svg
  playground/data-uri/single-quotes-in-double-quotes.svg
Labels: p3-minor-bug :hammer:, feat: build

#15361 fix: don't pretransform classic script links
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: p2-has-workaround :cake:, regression

#15422 fix(assets): avoid splitting `,` inside base64 value of `srcset` attribute
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:
