Repository vitejs/vite, pull requests merged in 2023-07, with the labels that each got.

#13662 fix(sourcemap): preserve original sourcesContent
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/sourcemap.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:, feat: sourcemap

#13708 fix(esbuild): use `useDefineForClassFields: false` when no `compilerOptions.target` is declared
  packages/vite/src/node/__tests__/plugins/esbuild.spec.ts
  packages/vite/src/node/plugins/esbuild.ts
Labels: p3-minor-bug :hammer:, regression

#10139 feat(plugin-legacy): add option to output only legacy builds
  packages/plugin-legacy/README.md
  packages/plugin-legacy/src/index.ts
  packages/plugin-legacy/src/types.ts
Labels: enhancement, plugin: legacy, p2-nice-to-have :cake:

#13722 fix(pluginContainer): drop previous sourcesContent
  packages/vite/src/node/server/pluginContainer.ts
Labels: p3-minor-bug :hammer:, regression

#13731 fix: revert import config module as data
  packages/vite/src/node/config.ts
Labels: p4-important :exclamation:

#13738 fix(css): use single postcss instance
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug :hammer:, regression

#13679 docs(static-deploy): added deployment instructions for AWS with Flightcontrol
  docs/guide/static-deploy.md
Labels: documentation

#13795 feat(client): close `vite-error-overlay` with Escape key
  packages/vite/src/client/overlay.ts
  playground/html/__tests__/html.spec.ts
Labels: feat: hmr, p2-nice-to-have :cake:

#13805 fix(esbuild): enable experimentalDecorators by default
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/esbuild.ts
  playground/tsconfig-json/__tests__/tsconfig-json.spec.ts
  playground/tsconfig-json/src/decorator.ts
  playground/tsconfig-json/src/main.ts
Labels: p3-minor-bug :hammer:, regression

#13827 chore: warning about ssr cjs format removal
  docs/config/ssr-options.md
  docs/guide/ssr.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/ssr/index.ts
Labels: feat: ssr, p3-significant 🔨

#13669 fix(build): style insert order for UMD builds (fix #13668)
  packages/vite/src/node/plugins/css.ts
Labels: plugin: legacy, p3-minor-bug :hammer:, regression

#13840 docs: fix build.cssMinify link
  docs/guide/features.md
  packages/vite/CHANGELOG.md
Labels: documentation

#13817 chore(deps): update `@typescript-eslint/*` dependencies to v6.0.0
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
Labels: dependencies

#13792 fix(types): narrow down the return type of `defineConfig`
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
  playground/assets/vite.config.js
  playground/css/vite.config.js
  playground/define/vite.config.js
  playground/lib/vite.config.js
Labels: p2-has-workaround :cake:, regression

#13655 fix: "EISDIR: illegal operation on a directory, realpath" error on RA…
  packages/vite/src/node/utils.ts
Labels: windows only, p2-to-be-discussed :cake:

#13884 fix(build): remove warning about ineffective dynamic import from node_modules
  packages/vite/src/node/plugins/reporter.ts
Labels: p2-nice-to-have :cake:

#13896 feat(client): add guide to press Esc for closing the overlay
  packages/vite/src/client/overlay.ts
Labels: p2-nice-to-have :cake:

#13918 test: restrict iife helpers injection
  playground/lib/__tests__/lib.spec.ts
  playground/lib/__tests__/serve.ts
  playground/lib/src/main-helpers-injection.js
  playground/lib/vite.helpers-injection.config.js
Labels: test

#13882 docs(static-deploy): add deployment instructions for AWS Amplify Hosting
  docs/guide/static-deploy.md
Labels: documentation

#13929 fix(proxy): handle error when proxy itself errors
  packages/vite/src/node/server/middlewares/proxy.ts
Labels: p2-nice-to-have :cake:

#13425 fix(html): support `import.meta.env` define replacement without quotes
  packages/vite/src/node/plugins/html.ts
  playground/html/__tests__/html.spec.ts
  playground/html/env.html
  playground/html/vite.config.js
Labels: p4-important :exclamation:

#13776 fix: lightningcss fails with html-proxy
  packages/vite/src/node/plugins/css.ts
  playground/css-lightningcss-proxy/__tests__/css-lightningcss-proxy.spec.ts
  playground/css-lightningcss-proxy/__tests__/serve.ts
  playground/css-lightningcss-proxy/index.html
  playground/css-lightningcss-proxy/package.json
  playground/css-lightningcss-proxy/server.js
  playground/test-utils.ts
  pnpm-lock.yaml
Labels: feat: css, p3-downstream-blocker :hammer:

#13949 perf: use Intl.NumberFormat instead of toLocaleString
  packages/vite/src/node/plugins/reporter.ts
Labels: performance

#13947 fix: use file extensions on type imports so they work with `moduleResolution: 'node16'`
  packages/vite/scripts/postPatchTypes.ts
Labels: p3-downstream-blocker :hammer:

#13951 perf: use Intl.DateTimeFormatter instead of toLocaleTimeString
  packages/vite/src/node/logger.ts
Labels: performance

#13865 fix(optimizer): avoid double-commit of optimized deps when discovery is disabled
  packages/vite/src/node/optimizer/optimizer.ts
Labels: p3-minor-bug :hammer:, feat: deps optimizer

#13962 fix: multiple entries with shared css and no JS
  packages/vite/src/node/plugins/html.ts
  playground/css-codesplit/__tests__/css-codesplit.spec.ts
  playground/css-codesplit/shared-css-empty-1.js
  playground/css-codesplit/shared-css-empty-2.js
  playground/css-codesplit/shared-css-main.js
  playground/css-codesplit/shared-css-no-js.html
  playground/css-codesplit/shared-css-theme.css
  playground/css-codesplit/shared-css-with-js.html
  playground/css-codesplit/vite.config.js
Labels: p3-minor-bug :hammer:

#13646 fix(importMetaGlob): avoid unnecessary hmr of negative glob
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/server/index.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/glob-import/dir/index.js
Labels: feat: hmr, p3-minor-bug :hammer:

#13981 fix(optimizer): enable experimentalDecorators by default
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug :hammer:, regression

#13971 perf: use magic-string hires boundary for sourcemaps
  packages/plugin-legacy/package.json
  packages/plugin-legacy/src/index.ts
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  packages/vite/src/node/utils.ts
  playground/css-sourcemap/__tests__/css-sourcemap.spec.ts
  playground/css-sourcemap/package.json
  playground/css-sourcemap/vite.config.js
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
  pnpm-lock.yaml
Labels: p4-important :exclamation:, feat: sourcemap

#11485 fix(css): enhance error message for missing preprocessor dependency
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/utils.ts
Labels: feat: css, p2-nice-to-have :cake:

#13973 fix: modulePreload false
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/index.ts
  playground/preload/__tests__/preload-disabled/preload-disabled.spec.ts
Labels: feat: css, p3-minor-bug :hammer:, feat: build
