Repository vitejs/vite, pull requests merged in 2024-05, with the labels that each got.

#16421 fix: scripts and styles were missing from built HTML on Windows
  packages/vite/src/node/plugins/html.ts
  playground/html/__tests__/html.spec.ts
  playground/html/relative-input.html
  playground/html/relative-input/main.js
  playground/html/vite.config.js
Labels: windows only, has workaround, p2-edge-case, regression, feat: build

#16565 chore(npmrc): set `package-manager-strict` to false
  .npmrc
Labels: p1-chore

#16441 docs(static-deploy): add xmit deployment guide
  docs/guide/static-deploy.md
Labels: documentation

#16568 docs(static-deploy): add criteria comment
  docs/guide/static-deploy.md
Labels: documentation

#16563 fix(ssr): handle function expression name scoping
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug, feat: ssr

#16569 fix(ssr): handle class declaration and expression name scoping
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug, feat: ssr

#16519 feat: improve dynamic import variable failure error message
  packages/vite/src/node/plugins/dynamicImportVars.ts
Labels: p2-nice-to-have

#16594 fix(sourcemap): improve sourcemap compatibility for vue2
  packages/vite/src/node/server/sourcemap.ts
Labels: p2-edge-case, feat: sourcemap

#16339 test: don't skip unicode related tests anymore
  playground/hasWindowsUnicodeFsBug.js
  playground/hmr-ssr/__tests__/hmr-ssr.spec.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/html/__tests__/html.spec.ts
  playground/html/vite.config.js
  playground/vitestGlobalSetup.ts
Labels: p1-chore, test

#16605 chore(create-vite): update IDE support instructions in helloworld components
  packages/create-vite/template-vue-ts/src/components/HelloWorld.vue
  packages/create-vite/template-vue/src/components/HelloWorld.vue
Labels: p1-chore, feat: create-vite

#16620 docs: update manifest example
  docs/guide/backend-integration.md
Labels: documentation

#16609 docs: add custom event types docs
  docs/guide/api-hmr.md
  docs/guide/api-plugin.md
Labels: documentation

#16581 fix(logger): truncate log over 5000 characters long
  packages/vite/src/node/logger.ts
  packages/vite/src/node/utils.ts
Labels: p2-edge-case

#16540 fix(error-logging): rollup errors weren't displaying id and codeframe
  packages/vite/src/node/build.ts
Labels: p3-minor-bug

#16633 fix(build): make SystemJSWrapRE match lazy
  packages/vite/src/node/plugins/completeSystemWrap.ts
Labels: p3-minor-bug

#16667 test: fix flaky test fail
  playground/hmr/__tests__/hmr.spec.ts
Labels: p1-chore

#16636 fix(hmr): trigger page reload when calling invalidate on root module
  packages/vite/src/node/server/hmr.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/hmr/index.html
  playground/hmr/invalidation/parent.js
  playground/hmr/invalidation/root.js
Labels: feat: hmr, p2-edge-case

#16078 fix(css): avoid generating empty JS files when JS files becomes empty but has CSS files imported
  packages/vite/src/node/plugins/css.ts
  playground/css-codesplit/__tests__/css-codesplit.spec.ts
  playground/css-codesplit/async-js.css
  playground/css-codesplit/async-js.js
  playground/css-codesplit/index.html
  playground/css-codesplit/main.js
  playground/css-no-codesplit/__tests__/css-no-codesplit.spec.ts
  playground/css-no-codesplit/async-js.css
  playground/css-no-codesplit/async-js.js
  playground/css-no-codesplit/index.html
  playground/css-no-codesplit/index.js
  playground/css-no-codesplit/package.json
  playground/css-no-codesplit/shared-linked.css
  playground/css-no-codesplit/sub.html
  playground/css-no-codesplit/vite.config.js
  pnpm-lock.yaml
Labels: feat: css, p2-nice-to-have

#16455 fix(css): page reload was not happening with .css?raw
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/css/__tests__/css.spec.ts
Labels: feat: css, feat: hmr, p3-minor-bug, regression

#16741 docs: deprecate server.hot
  docs/guide/api-plugin.md
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/server/index.ts
Labels: documentation, p1-chore

#14255 fix(hmr): normalize the path info
  packages/vite/src/node/server/hmr.ts
Labels: p2-nice-to-have

#17301 fix(css): handle lightningcss compiled css in Deno
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug

#16729 fix(optimizer): log dependencies added by plugins
  packages/vite/src/node/optimizer/index.ts
Labels: p2-nice-to-have

#16219 feat: add an option to not start a websocket server
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/ws.ts
Labels: p2-nice-to-have

#16590 feat(asset): support `/*@vite-ignore*/` for `new URL(, import.meta.url)`
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: p2-nice-to-have

#17288 refactor: plugin container
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/utils.ts
Labels: performance

#16562 refactor(build): remove quotes from preload marker
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-minor-bug, feat: build

#16558 fix(proxy): rewrite the origin header to match the target for ws proxy
  docs/config/server-options.md
  packages/vite/src/node/server/middlewares/proxy.ts
Labels: has workaround, p2-edge-case

#16566 fix(plugin-legacy): improve deterministic polyfills discovery
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p2-nice-to-have

#16738 fix: adjust import analysis behavior to match Node
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/runtime/runtime.ts
  packages/vite/src/shared/ssrTransform.ts
Labels: p3-minor-bug, feat: ssr

#16238 refactor: remove acorn
  package.json
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/__tests__/plugins/importGlob/parse.spec.ts
  packages/vite/src/node/plugins/dynamicImportVars.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  patches/acorn@8.11.3.patch
  pnpm-lock.yaml
Labels: p2-nice-to-have

#16242 fix(optimize-deps): don't externalize JS files imported with asset extensions
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-cjs-external-package-omit-js-suffix/index.js
  playground/optimize-deps/dep-cjs-external-package-omit-js-suffix/package.json
  playground/optimize-deps/dep-cjs-external-package-omit-js-suffix/test.astro.js
  playground/optimize-deps/dep-cjs-external-package-omit-js-suffix/test.okay.js
  playground/optimize-deps/dep-cjs-external-package-omit-js-suffix/test.scss.js
  playground/optimize-deps/dep-cjs-external-package-omit-js-suffix/test.tsx.js
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  playground/optimize-deps/vite.config.js
  pnpm-lock.yaml
Labels: p3-minor-bug, feat: deps optimizer

#16726 fix: prevent unhandledRejection if `--open` fails
  packages/vite/src/node/server/openBrowser.ts
Labels: p3-minor-bug
