Repository vitejs/vite, pull requests merged in 2024-12, with the labels that each got.

#18860 chore: fix duplicate attributes issue number in comment
  packages/vite/src/node/plugins/html.ts
Labels: p1-chore

#18844 fix: no permission to create vite config file
  packages/vite/src/node/config.ts
Labels: has workaround, p2-edge-case

#18851 fix: make result interfaces for `ModuleRunnerTransport#invoke` more explicit
  docs/guide/api-environment-runtimes.md
  packages/vite/src/shared/moduleRunnerTransport.ts
Labels: feat: environment API

#18857 fix: merge `environments.ssr.resolve` with root `ssr` config
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
Labels: p3-downstream-blocker

#18837 fix(module-runner): decode uri for file url passed to import
  packages/vite/src/module-runner/utils.ts
  packages/vite/src/node/ssr/__tests__/fixtures/file-url/test space.js
  packages/vite/src/node/ssr/__tests__/fixtures/file-url/test.js
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
Labels: p3-minor-bug, feat: ssr

#18856 docs(api-environment): remove outdated text content
  docs/guide/api-environment-frameworks.md
  docs/guide/api-environment-instances.md
  docs/guide/api-environment-plugins.md
  docs/guide/api-environment-runtimes.md
  docs/guide/api-environment.md
Labels: documentation

#18833 fix(config): make stacktrace path correct when sourcemap is enabled
  packages/vite/src/node/config.ts
Labels: p2-edge-case, trigger: preview

#18868 fix(css): rewrite url when image-set and url exist at the same time
  packages/vite/src/node/plugins/css.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: feat: css, p2-edge-case

#18877 docs: add SvelteKit to the Environment API story
  docs/blog/announcing-vite6.md
Labels: documentation

#18881 docs: tweak wordings in Environment API doc
  docs/guide/api-environment-frameworks.md
  docs/guide/api-environment-instances.md
  docs/guide/api-environment-plugins.md
  docs/guide/api-environment-runtimes.md
  docs/guide/api-environment.md
Labels: documentation

#18852 fix(html): allow unexpected question mark in tag name
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p3-downstream-blocker

#18887 fix(config): bundle files referenced with imports field
  packages/vite/src/node/config.ts
  playground/config/__tests__/config.spec.ts
  playground/config/packages/entry/imports-field.ts
  playground/config/packages/entry/package.json
  playground/config/packages/entry/vite.config.ts
Labels: p4-important, regression

#18886 fix: handle postcss load unhandled rejections
  packages/vite/bin/vite.js
  packages/vite/src/node/plugins/css.ts
Labels: p2-edge-case

#18885 fix: remove CSS import in CJS correctly in some cases
  packages/vite/src/node/__tests__/plugins/css.spec.ts
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-edge-case

#18891 refactor: fix logic errors found by no-unnecessary-condition rule
  packages/create-vite/src/index.ts
  packages/vite/src/client/overlay.ts
  packages/vite/src/module-runner/hmrHandler.ts
  packages/vite/src/module-runner/sourcemap/interceptor.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/external.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/esbuild.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/json.ts
  packages/vite/src/node/plugins/manifest.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/splitVendorChunk.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/environment.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/mixedModuleGraph.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/ssr/ssrStacktrace.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  packages/vite/src/node/utils.ts
  packages/vite/src/shared/hmr.ts
Labels: p1-chore

#18876 fix: make handleInvoke interface compatible with invoke
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/ws.ts
Labels: p4-important, feat: environment API

#18865 test: test `ModuleRunnerTransport` `invoke` API
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/worker.invoke.mjs
  packages/vite/src/node/ssr/runtime/__tests__/package.json
  packages/vite/src/node/ssr/runtime/__tests__/server-worker-runner.invoke.spec.ts
  pnpm-lock.yaml
Labels: test, feat: environment API

#18900 test: use `readDepOptimizationMetadata`
  playground/environment-react-ssr/__tests__/environment-react-ssr.spec.ts
  playground/optimize-deps-no-discovery/__tests__/optimize-deps-no-discovery.spec.ts
  playground/test-utils.ts
Labels: p1-chore, test

#18898 test: test output hash changes
  packages/vite/src/node/__tests__/build.spec.ts
Labels: p1-chore, test

#18890 refactor: simplify manifest plugin code
  packages/vite/src/node/plugins/manifest.ts
Labels: p1-chore

#18924 docs: bring back the UwU logo
  docs/.vitepress/theme/components/landing/1. hero-section/HeroDiagram.vue
Labels: documentation

#18926 ci: fix ecosystem-ci-trigger user permission check
  .github/workflows/ecosystem-ci-trigger.yml
Labels: p1-chore

#18927 ci: fix ecosystem ci trigger
  .github/workflows/ecosystem-ci-trigger.yml
Labels: p1-chore

#18929 ci: fix ecosystem-ci-trigger reaction id
  .github/workflows/ecosystem-ci-trigger.yml
Labels: p1-chore

#18930 ci: fix ecosystem-ci-trigger ignore skipped
  .github/workflows/ecosystem-ci-trigger.yml
Labels: p1-chore

#18931 ci: fix ecosystem-ci-trigger ignore skipped
  .github/workflows/ecosystem-ci-trigger.yml
Labels: p1-chore

#18903 fix: `this.resolve` skipSelf should not skip for different `id` or `import`
  packages/vite/src/node/index.ts
  packages/vite/src/node/server/__tests__/pluginContainer.spec.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: rollup plugin compat, p3-minor-bug

#18895 fix: merge client and ssr values for `pluginContainer.getModuleInfo`
  packages/vite/src/node/server/mixedModuleGraph.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: p3-downstream-blocker

#18942 ci: fix checkout pr in ecosystem ci
  .github/workflows/ecosystem-ci-trigger.yml
Labels: p1-chore, trigger: preview

#18948 chore: better validation error message for dts build
  packages/vite/rollup.dts.config.ts
Labels: p1-chore

#18969 test: don't use `__dirname` in tailwind config
  playground/backend-integration/tailwind.config.js
Labels: p1-chore

#18902 refactor: make internal invoke event to use the same interface with `handleInvoke`
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/shared/invokeMethods.ts
  packages/vite/src/shared/moduleRunnerTransport.ts
Labels: p1-chore, feat: environment API

#18973 fix(ssr): recreate ssrCompatModuleRunner on restart
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug, feat: ssr, regression

#18899 fix(optimizer): keep NODE_ENV as-is when keepProcessEnv is `true`
  packages/vite/src/node/optimizer/index.ts
  playground/environment-react-ssr/__tests__/environment-react-ssr.spec.ts
Labels: p3-minor-bug, inconsistency, feat: deps optimizer, feat: environment API

#18970 fix(css): skip non css in custom sass importer
  .prettierignore
  packages/vite/src/node/plugins/css.ts
  playground/css/nested/_index.scss
  playground/css/vite.config.js
  playground/css/weapp.wxss
Labels: feat: css, p3-minor-bug, trigger: preview

#18987 fix: fallback terser to main thread when function options are used
  packages/vite/package.json
  packages/vite/src/node/__tests__/plugins/terser.spec.ts
  packages/vite/src/node/plugins/terser.ts
  pnpm-lock.yaml
Labels: p3-minor-bug

#18999 test: fix "excluded dep in included dep" test
  playground/nested-deps/__tests__/nested-deps.spec.ts
  playground/nested-deps/index.html
  playground/nested-deps/test-package-e/test-package-e-included/index.js
  playground/nested-deps/test-package-e/test-package-e-included/package.json
  pnpm-lock.yaml
Labels: p1-chore, test

#18862 feat(create-vite): extend from @vue/tsconfig to simplify tsconfig.app.json
  packages/create-vite/template-vue-ts/package.json
  packages/create-vite/template-vue-ts/tsconfig.app.json
Labels: feat: create-vite

#19015 refactor(create-vite): remove tslib from svelte-ts template
  packages/create-vite/template-svelte-ts/package.json
Labels: p1-chore, feat: create-vite

#19014 fix(create-vite): svelte-ts typecheck command
  packages/create-vite/template-svelte-ts/package.json
Labels: p4-important, feat: create-vite

#19044 test(ssr): test virtual module with query
  packages/vite/src/node/ssr/runtime/__tests__/server-runtime.spec.ts
Labels: p1-chore, feat: ssr, test

#19048 ci: add additionalAllowedUsers to `ecosystem-ci-trigger` workflow
  .github/workflows/ecosystem-ci-trigger.yml
Labels: p1-chore

#19047 chore: update comment about `build.target`
  packages/vite/src/node/build.ts
Labels: p1-chore

#19043 revert: unpin esbuild version
  packages/vite/package.json
  pnpm-lock.yaml
Labels: trigger: preview

#18361 fix: replace runner-side path normalization with `fetchModule`-side resolve
  docs/guide/api-environment-runtimes.md
  packages/vite/src/module-runner/runner.ts
  packages/vite/src/module-runner/types.ts
  packages/vite/src/module-runner/utils.ts
  packages/vite/src/node/ssr/fetchModule.ts
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/dynamic-import.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/worker.invoke.mjs
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/worker.mjs
  packages/vite/src/node/ssr/runtime/__tests__/server-runtime.spec.ts
  packages/vite/src/node/ssr/runtime/__tests__/server-source-maps.spec.ts
  packages/vite/src/node/ssr/runtime/__tests__/utils.ts
Labels: p2-to-be-discussed, trigger: preview

#19000 fix(resolve): handle package.json with UTF-8 BOM
  packages/vite/src/node/packages.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/index.html
  playground/resolve/package.json
  playground/resolve/utf8-bom-package/index.mjs
  playground/resolve/utf8-bom-package/package.json
  pnpm-lock.yaml
Labels: p2-edge-case

#19004 fix(ssrTransform): preserve line offset when transforming imports
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: feat: ssr, trigger: preview

#19056 chore: bump TypeScript to ~5.7.2
  package.json
  packages/create-vite/template-lit-ts/package.json
  packages/create-vite/template-preact-ts/package.json
  packages/create-vite/template-qwik-ts/package.json
  packages/create-vite/template-react-ts/package.json
  packages/create-vite/template-solid-ts/package.json
  packages/create-vite/template-svelte-ts/package.json
  packages/create-vite/template-vanilla-ts/package.json
  packages/create-vite/template-vue-ts/package.json
  pnpm-lock.yaml
Labels: dependencies, p2-nice-to-have

#19001 fix(css): resolve style tags in HTML files correctly for lightningcss
  packages/vite/src/node/plugins/css.ts
  playground/css-lightningcss/__tests__/css-lightningcss.spec.ts
Labels: feat: css, p3-minor-bug

#19070 fix(css): show correct error when unknown placeholder is used for CSS modules pattern in lightningcss
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-edge-case

#19025 fix: fix `minify` when `builder.sharedPlugins: true`
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/__tests__/fixtures/shared-plugins/minify/entry.js
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/esbuild.ts
  pnpm-lock.yaml
Labels: p2-edge-case, feat: build

#19076 feat(css): show lightningcss warnings
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-nice-to-have

#19084 docs: fix canonical links
  docs/.vitepress/config.ts
Labels: documentation

#19062 fix(html): error while removing `vite-ignore` attribute for inline script
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/html/index.html
Labels: feat: html, p3-minor-bug
