Repository vitejs/vite, pull requests merged in 2024-07, with the labels that each got.

#17563 fix(proxy): replace changeOrigin changes in 5.3.0 with new rewriteWsOrigin option
  docs/config/server-options.md
  packages/vite/src/node/server/middlewares/proxy.ts
Labels: p4-important, regression

#17634 chore: move shinigami to team emeriti
  docs/_data/team.js
Labels: documentation

#17509 fix(worker): nested inlined worker always fallbacked to data URI worker instead of using blob worker
  packages/vite/src/node/plugins/worker.ts
  playground/worker/__tests__/es/worker-es.spec.ts
  playground/worker/__tests__/iife/worker-iife.spec.ts
  playground/worker/__tests__/relative-base/worker-relative-base.spec.ts
  playground/worker/__tests__/sourcemap-hidden/worker-sourcemap-hidden.spec.ts
  playground/worker/__tests__/sourcemap-inline/worker-sourcemap-inline.spec.ts
  playground/worker/__tests__/sourcemap/worker-sourcemap.spec.ts
Labels: p3-minor-bug, feat: web workers

#17649 chore: add `create-preact` recommendation to Preact templates
  packages/create-vite/template-preact-ts/src/app.tsx
  packages/create-vite/template-preact/src/app.jsx
Labels: p2-nice-to-have, feat: create-vite

#17669 fix: update Terser type definitions (fix #17668)
  packages/vite/src/types/terser.d.ts
Labels: p3-minor-bug

#17687 fix(build): skip preload treeshaking for nested braces
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/dynamic-import/nested/index.js
Labels: p4-important

#17620 refactor: replace includes with logical operations
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
Labels: p2-nice-to-have

#17623 fix(css): include `.css?url` in assets field of manifest
  packages/vite/src/node/plugins/css.ts
  playground/backend-integration/__tests__/backend-integration.spec.ts
  playground/backend-integration/frontend/entrypoints/main.ts
  playground/backend-integration/frontend/styles/url.css
Labels: feat: css, p3-minor-bug

#17643 docs: show usage with `satisfies` operator
  docs/config/index.md
Labels: documentation, p2-to-be-discussed

#17677 fix(ssrTransform): sourcemaps with multiple sources
  packages/vite/src/node/ssr/__tests__/fixtures/bundled-with-sourcemaps/bundle.js
  packages/vite/src/node/ssr/__tests__/fixtures/bundled-with-sourcemaps/bundle.js.map
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug, feat: sourcemap

#17419 fix: show error if vite client cannot be loaded
  packages/vite/src/node/server/middlewares/error.ts
Labels: p3-minor-bug

#17691 fix(css): resolve url aliases with fragments (fix: #17690)
  packages/vite/src/node/plugins/css.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/css/icons.css
  playground/assets/index.html
  playground/assets/vite.config.js
Labels: feat: css, p3-minor-bug

#17743 fix(importMetaGlob): handle alias that starts with hash
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/resolve.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/glob-import/index.html
  playground/glob-import/vite.config.ts
Labels: p3-minor-bug

#17745 docs: improve additional command line options by code-group
  docs/guide/index.md
Labels: documentation

#16331 refactor(asset): remove rollup 3 public file watch workaround
  packages/vite/src/node/plugins/asset.ts
Labels: p2-nice-to-have

#16263 docs: explicit EOL for previous releases
  docs/releases.md
Labels: documentation, p3-significant

#17782 chore: remove fs-extra dev dependency
  package.json
  packages/create-vite/__tests__/cli.spec.ts
  playground/resolve-config/__tests__/serve.ts
  playground/vitestGlobalSetup.ts
  playground/vitestSetup.ts
  pnpm-lock.yaml
  scripts/releaseUtils.ts
Labels: p2-nice-to-have, performance

#17648 fix(build): handle invalid JSON in import.meta.env
  packages/vite/src/node/__tests__/plugins/define.spec.ts
  packages/vite/src/node/plugins/define.ts
  playground/define/__tests__/define.spec.ts
  playground/define/index.html
  playground/define/vite.config.js
Labels: p3-minor-bug

#17307 fix: specify own Node version as target when bundling config files
  packages/vite/src/node/config.ts
  playground/config/__tests__/config.spec.ts
  playground/config/packages/entry/vite.config.import-attributes.ts
Labels: p3-minor-bug

#17615 feat(types): support custom VitePreloadErrorEvent
  packages/vite/client.d.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p2-nice-to-have

#17728 feat(css): support sass modern api
  docs/config/shared-options.md
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/sass-modern/sass-modern.spec.ts
  playground/css/vite.config-sass-modern.js
  playground/vitestGlobalSetup.ts
  playground/vitestSetup.ts
Labels: feat: css, p3-significant

#12860 feat(create-vite): add eslint.config.js to React templates
  packages/create-vite/template-react-ts/.eslintrc.cjs
  packages/create-vite/template-react-ts/README.md
  packages/create-vite/template-react-ts/eslint.config.js
  packages/create-vite/template-react-ts/package.json
  packages/create-vite/template-react/.eslintrc.cjs
  packages/create-vite/template-react/eslint.config.js
  packages/create-vite/template-react/package.json
Labels: p2-nice-to-have
