Repository vitejs/vite, pull requests merged in 2024-04, with the labels that each got.

#16338 ci: run lint in node 20
  .github/workflows/ci.yml
Labels: p1-chore

#16340 refactor: use types from sass instead of @types/sass
  package.json
  packages/vite/package.json
  packages/vite/src/node/plugins/css.ts
  pnpm-lock.yaml
Labels: p1-chore

#15805 fix: fix sourcemap when using object as `define` value
  packages/vite/src/node/plugins/define.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
  playground/js-sourcemap/index.html
  playground/js-sourcemap/test-ssr-dev.js
  playground/js-sourcemap/vite.config.js
  playground/js-sourcemap/with-define-object-ssr.ts
  playground/js-sourcemap/with-define-object.ts
Labels: p3-minor-bug, feat: sourcemap

#16318 fix: do not access document in `/@vite/client` when not defined
  packages/vite/src/client/client.ts
  packages/vite/src/client/overlay.ts
  playground/worker/__tests__/es/worker-es.spec.ts
  playground/worker/__tests__/relative-base/worker-relative-base.spec.ts
  playground/worker/emit-chunk-dynamic-import-worker.js
Labels: p3-minor-bug, regression

#16346 chore: `pnpm audit --fix`
  pnpm-lock.yaml
Labels: p1-chore

#16348 ci: run publish in node 20
  .github/workflows/publish.yml
Labels: p1-chore

#16184 perf: reduce size of injected __vite__mapDeps code
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
Labels: p2-nice-to-have, performance

#16367 fix(legacy): modern polyfill autodetection was not injecting enough polyfills
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p3-minor-bug

#16204 docs: update dep optimization options entries
  docs/config/dep-optimization-options.md
Labels: documentation

#16392 docs: add links to environment api
  docs/guide/api-vite-runtime.md
  docs/guide/ssr.md
Labels: documentation

#16393 fix: fix accumulated stacks in error overlay
  packages/vite/src/client/overlay.ts
  playground/html/__tests__/html.spec.ts
Labels: p3-minor-bug

#16415 fix(cspNonce): don't overwrite existing nonce values
  packages/vite/src/node/plugins/html.ts
  playground/csp/__tests__/csp.spec.ts
  playground/csp/index.html
Labels: feat: html, p3-minor-bug

#16436 fix: adjust esm syntax judgment logic
  packages/vite/src/node/optimizer/index.ts
Labels: p3-minor-bug, feat: deps optimizer

#16419 feat: write cspNonce to style tags
  docs/guide/features.md
  packages/vite/src/node/plugins/html.ts
  playground/csp/index.html
Labels: feat: html, p2-nice-to-have

#16442 fix: add base to virtual html
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: p3-minor-bug

#16454 feat: show warning if root is in build.outDir
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have

#16089 docs: environment API proposal
  docs/.vitepress/config.ts
  docs/blog/announcing-vite5-1.md
  docs/guide/api-vite-environment.md
  docs/guide/api-vite-runtime.md
  docs/images/vite-environments.svg
Labels: feat: hmr, p3-significant, feat: dev, feat: runtime

#16476 revert: perf: use workspace root for fs cache (#15712)
  packages/vite/src/node/fsUtils.ts
Labels: feat: hmr, p4-important

#16491 docs(legacy): update `modernTargets` option default value description
  packages/plugin-legacy/README.md
  packages/plugin-legacy/src/types.ts
Labels: documentation, plugin: legacy

#16502 fix(dev): watch publicDir explicitly to include it outside the root
  packages/vite/src/node/server/__tests__/watcher.spec.ts
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug, regression, feat: dev

#16518 fix: dynamic-import-vars plugin normalize path issue
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/__snapshots__/parse.spec.ts.snap
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/parse.spec.ts
  packages/vite/src/node/plugins/dynamicImportVars.ts
Labels: p3-minor-bug

#16553 docs(env): clarify env are statically replaced
  docs/guide/env-and-mode.md
Labels: documentation

#16514 feat(plugin-legacy): support `additionalModernPolyfills`
  packages/plugin-legacy/README.md
  packages/plugin-legacy/src/index.ts
  packages/plugin-legacy/src/types.ts
Labels: plugin: legacy, p2-nice-to-have

#16556 fix(preload): skip preload for non-static urls
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/dynamic-import/__tests__/dynamic-import.spec.ts
Labels: p2-edge-case
