Repository vitejs/vite, pull requests merged in 2024-09, with the labels that each got.

#17915 fix: allow getting URL of JS files in publicDir
  packages/vite/src/node/server/middlewares/static.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: p2-edge-case, inconsistency

#17982 fix: waitForRequestIdle locked
  packages/vite/src/node/server/index.ts
Labels: p3-downstream-blocker

#17916 fix: only remove entry assets handled by Vite core
  packages/vite/src/node/plugins/asset.ts
Labels: p2-edge-case, regression

#17988 fix(html): rewrite assets url in <template>
  packages/vite/src/node/plugins/html.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: feat: html, p3-minor-bug

#17930 fix(preload): add crossorigin attribute in CSS link tags
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: feat: css, p3-minor-bug

#18027 docs: `createNodeDevEnvironment` requires `hot` option
  docs/guide/api-environment.md
Labels: documentation

#18044 refactor: remove unnecessary escape
  eslint.config.js
  packages/vite/src/node/__tests__/plugins/importGlob/parse.spec.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/utils.ts
Labels: p1-chore

#18046 fix(preload): allow ignoring dep errors
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
Labels: p3-minor-bug

#18052 chore: silence unnecessary logs during test
  packages/vite/src/node/__tests__/build.spec.ts
  playground/environment-react-ssr/vite.config.ts
Labels: p1-chore

#18053 test: move glob test root to reduce snapshot change
  packages/vite/src/node/__tests__/plugins/importGlob/__snapshots__/fixture.spec.ts.snap
  packages/vite/src/node/__tests__/plugins/importGlob/fixture.spec.ts
Labels: p1-chore

#18041 refactor: remove custom resolveOptions from pre-alias plugin
  packages/vite/src/node/plugins/preAlias.ts
Labels: p1-chore

#18071 fix(css): fallback to mainthread if logger or pkgImporter option is set for sass
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug

#18067 fix(html): escape html attribute
  packages/vite/src/node/plugins/html.ts
  playground/html/__tests__/html.spec.ts
  playground/html/vite.config.js
Labels: feat: html, p3-minor-bug

#18063 fix: allow scanning exports from `script module` in svelte
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-downstream-blocker

#18057 fix(build): declare `preload-helper` has no side effects
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p2-nice-to-have

#18076 fix(preload): backport #18046, allow ignoring dep errors
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
Labels: p3-minor-bug

#18080 feat: expose `EnvironmentOptions` type
  packages/vite/src/node/index.ts
Labels: feat: environment API

#18087 test: remove not needed test
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
Labels: p1-chore, test

#18085 refactor(create-vite): use picocolors
  packages/create-vite/LICENSE
  packages/create-vite/package.json
  packages/create-vite/src/index.ts
  packages/vite/LICENSE.md
  pnpm-lock.yaml
Labels: p1-chore

#18083 chore: remove npm-run-all2
  package.json
  packages/vite/package.json
  pnpm-lock.yaml
Labels: p1-chore

#18075 test: refactor hmr-ssr tests
  playground/hmr-ssr/__tests__/hmr-ssr.spec.ts
  playground/hmr-ssr/file-delete-restore/child.js
  playground/test-utils.ts
  playground/vitestSetup.ts
Labels: p1-chore, test

#18089 docs: update Environment API guide after beta
  docs/guide/api-environment.md
Labels: documentation

#18126 chore: escape template tag in CHANGELOG.md
  packages/vite/CHANGELOG.md
Labels: p1-chore

#18081 fix(config): treat all files as ESM on deno
  packages/vite/src/node/config.ts
Labels: p3-downstream-blocker

#18138 docs(static-deploy): add `npm install` to render's build command
  docs/guide/static-deploy.md
Labels: documentation

#18132 docs: add `vitepress-plugin-group-icons`
  docs/.vitepress/config.ts
  docs/.vitepress/theme/index.ts
  docs/config/server-options.md
  docs/guide/api-javascript.md
  docs/guide/api-plugin.md
  docs/guide/backend-integration.md
  docs/guide/build.md
  docs/guide/dep-pre-bundling.md
  docs/guide/env-and-mode.md
  docs/guide/features.md
  docs/guide/index.md
  docs/guide/performance.md
  docs/guide/ssr.md
  docs/guide/static-deploy.md
  docs/guide/using-plugins.md
  docs/package.json
  pnpm-lock.yaml
Labels: documentation

#18142 feat: support `this.environment` in `options` and `onLog` hook
  packages/vite/src/node/build.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/typeUtils.ts
Labels: p2-nice-to-have, feat: environment API

#18140 fix: use `config.consumer` instead of `options?.ssr` / `config.build.ssr`
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/modulePreloadPolyfill.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/reporter.ts
Labels: p3-minor-bug, feat: environment API

#18113 fix(css): fix missing source file warning with sass modern api custom importer
  packages/vite/src/node/plugins/css.ts
  playground/css-sourcemap/__tests__/css-sourcemap.spec.ts
  playground/css-sourcemap/imported-nested.sass
  playground/css-sourcemap/imported.sass
Labels: feat: css, p3-minor-bug, feat: sourcemap

#18197 docs: correct variable name in `build.lib.fileName` option description
  docs/config/build-options.md
Labels: documentation

#18185 refactor: replace `parse` with `splitFileAndPostfix`
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/shared/utils.ts
Labels: p1-chore

#18200 test: misc fixes
  playground/alias/vite.config.js
  playground/css-lightningcss-proxy/__tests__/css-lightningcss-proxy.spec.ts
  playground/css/index.html
  playground/vitestSetup.ts
Labels: p1-chore, test

#18150 fix(ssr): fix source map remapping with multiple sources
  packages/vite/src/node/ssr/__tests__/fixtures/multi-source-sourcemaps/dist.js
  packages/vite/src/node/ssr/__tests__/fixtures/multi-source-sourcemaps/dist.js.map
  packages/vite/src/node/ssr/__tests__/fixtures/multi-source-sourcemaps/entrypoint.js
  packages/vite/src/node/ssr/__tests__/fixtures/multi-source-sourcemaps/nested-directory/nested-file.js
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-minor-bug, feat: ssr, feat: sourcemap

#18163 fix: asset import should skip handling data URIs
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: p2-edge-case

#18125 fix(css): fix lightningcss dep url resolution with custom root
  packages/vite/src/node/plugins/css.ts
  playground/css-lightningcss-root/__tests__/css-lightningcss-root.spec.ts
  playground/css-lightningcss-root/package.json
  playground/css-lightningcss-root/root/index.html
  playground/css-lightningcss-root/root/main.js
  playground/css-lightningcss-root/root/ok.png
  playground/css-lightningcss-root/root/url-dep.css
  playground/css-lightningcss-root/vite.config.js
  pnpm-lock.yaml
Labels: feat: css, p3-minor-bug, regression

#18207 refactor: remove `_onCrawlEnd`
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/server/environment.ts
Labels: p1-chore, feat: environment API

#18208 refactor: use `resolvePackageData` to get rollup version
  packages/vite/src/node/utils.ts
Labels: p1-chore

#18206 fix: close HotChannel on environment close
  packages/vite/src/node/server/environment.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/ws.ts
Labels: p3-minor-bug, feat: environment API

#18212 fix: call `this.hot.close` for non-ws HotChannel
  packages/vite/src/node/server/environment.ts
Labels: p3-minor-bug, feat: environment API

#18180 fix(deps): upgrade rollup 4.22.4+ to ensure avoiding XSS
  package.json
  packages/vite/package.json
  packages/vite/src/node/plugins/importAnalysis.ts
  pnpm-lock.yaml
Labels: dependencies

#18241 fix(data-uri): only match ids starting with `data:`
  packages/vite/src/node/plugins/dataUri.ts
  playground/data-uri/index.html
  playground/data-uri/vite.config.js
Labels: p3-minor-bug, feat: build

#18237 refactor: break circular dependencies to fix test-unit
  packages/vite/src/node/baseEnvironment.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/server/environment.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p1-chore
