Repository vitejs/vite, pull requests merged in 2024-11, with the labels that each got.

#18541 fix(json): don't `json.stringify` arrays
  packages/vite/src/node/__tests__/plugins/json.spec.ts
  packages/vite/src/node/plugins/json.ts
Labels: p4-important, regression

#18486 fix(css): `cssCodeSplit` uses the current environment configuration
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, feat: environment API

#18509 fix(config): write temporary vite config to node_modules
  packages/vite/src/node/config.ts
  packages/vite/src/node/packages.ts
Labels: trigger: preview

#18548 fix(client): detect ws close correctly
  packages/vite/src/client/client.ts
Labels: p3-minor-bug

#18549 fix: use `server.perEnvironmentStartEndDuringDev`
  packages/vite/src/node/server/pluginContainer.ts
Labels: p3-minor-bug, feat: environment API

#15454 feat(asset): add `?inline` and `?no-inline` queries to control inlining
  docs/guide/assets.md
  packages/vite/client.d.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: p2-to-be-discussed

#18567 docs: remove horizontal scrollbars in code blocks
  docs/config/index.md
  docs/config/server-options.md
  docs/guide/api-environment-frameworks.md
  docs/guide/api-environment-instances.md
  docs/guide/api-environment-plugins.md
  docs/guide/api-environment-runtimes.md
  docs/guide/build.md
Labels: documentation

#16490 fix(create-vite): improve project name inference from path
  packages/create-vite/__tests__/cli.spec.ts
  packages/create-vite/src/index.ts
Labels: p2-nice-to-have, feat: create-vite

#18573 docs(migration): add bundle size note about strictRequires true
  docs/guide/migration.md
Labels: documentation

#18577 docs(migration): add a note about using a CommonJS file as an entrypoint
  docs/guide/migration.md
Labels: documentation

#18575 fix: browser field should not be included by default for `consumer: 'server'`
  packages/vite/src/node/config.ts
Labels: p4-important, regression

#18537 chore: upgrade to express 5
  .github/renovate.json5
  docs/guide/ssr.md
  playground/css-lightningcss-proxy/package.json
  playground/css-lightningcss-proxy/server.js
  playground/json/package.json
  playground/json/server.js
  playground/legacy/package.json
  playground/optimize-missing-deps/package.json
  playground/optimize-missing-deps/server.js
  playground/ssr-conditions/package.json
  playground/ssr-conditions/server.js
  playground/ssr-deps/package.json
  playground/ssr-deps/server.js
  playground/ssr-html/package.json
  playground/ssr-html/server.js
  playground/ssr-noexternal/package.json
  playground/ssr-noexternal/server.js
  playground/ssr-pug/package.json
  playground/ssr-pug/server.js
  playground/ssr/package.json
  playground/ssr/server.js
  pnpm-lock.yaml
Labels: dependencies, p1-chore

#18589 chore: remove unneeded `slienceDeprecations`
  playground/css/vite.config.js
Labels: p1-chore

#18593 test: update filename regex
  packages/vite/src/node/__tests__/build.spec.ts
Labels: p1-chore, test

#18587 docs: clarify dynamic `new URL(foo, import.meta.url)` behavior
  docs/guide/assets.md
Labels: documentation

#18591 fix(resolve): run ensureVersionQuery for SSR
  packages/vite/src/node/plugins/resolve.ts
Labels: feat: ssr, p2-edge-case, feat: deps optimizer

#18594 chore: remove unused `ssr` variable
  packages/vite/src/node/plugins/resolve.ts
Labels: p1-chore

#18599 docs: remove X links in team page
  docs/_data/team.js
Labels: documentation

#18362 feat: use a single transport for fetchModule and HMR support
  docs/guide/api-environment-instances.md
  docs/guide/api-environment-runtimes.md
  packages/vite/rollup.config.ts
  packages/vite/src/client/client.ts
  packages/vite/src/module-runner/hmrHandler.ts
  packages/vite/src/module-runner/index.ts
  packages/vite/src/module-runner/runner.ts
  packages/vite/src/module-runner/runnerTransport.ts
  packages/vite/src/module-runner/types.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/server/__tests__/pluginContainer.spec.ts
  packages/vite/src/node/server/environment.ts
  packages/vite/src/node/server/environmentTransport.ts
  packages/vite/src/node/server/environments/runnableEnvironment.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/ws.ts
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/worker.mjs
  packages/vite/src/node/ssr/runtime/__tests__/server-worker-runner.spec.ts
  packages/vite/src/node/ssr/runtime/serverHmrConnector.ts
  packages/vite/src/node/ssr/runtime/serverModuleRunner.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/utils.ts
  packages/vite/src/shared/hmr.ts
  packages/vite/src/shared/invokeMethods.ts
  packages/vite/src/shared/moduleRunnerTransport.ts
  packages/vite/src/shared/utils.ts
  packages/vite/types/hmrPayload.d.ts
  playground/hmr-ssr/__tests__/hmr-ssr.spec.ts
  playground/ssr/__tests__/ssr.spec.ts
Labels: p3-significant, feat: environment API, trigger: preview

#18611 feat(optimizer): allow users to specify their esbuild `platform` option
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/optimizer/index.ts
Labels: p3-downstream-blocker, regression, feat: deps optimizer, feat: environment API

#18617 chore(deps): update dependencies of postcss-modules
  pnpm-lock.yaml
Labels: feat: css, dependencies, p3-minor-bug

#18622 chore: tweak build config
  packages/vite/rollup.config.ts
  packages/vite/rollup.dts.config.ts
Labels: p1-chore

#18618 fix(html): externalize `rollup.external` scripts correctly
  packages/vite/src/node/plugins/html.ts
  playground/html/__tests__/html.spec.ts
  playground/html/index.html
  playground/html/vite.config.js
Labels: feat: html, p3-downstream-blocker

#18630 perf: remove strip-ansi for a node built-in
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/server/middlewares/error.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have

#18633 docs: fix mobile menu background on light mode landing page
  docs/.vitepress/theme/styles/landing.css
Labels: documentation

#18626 fix(ssr): preserve fetchModule error details
  .prettierignore
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/ssr/__tests__/__snapshots__/ssrLoadModule.spec.ts.snap
  packages/vite/src/node/ssr/__tests__/fixtures/errors/syntax-error-dep.js
  packages/vite/src/node/ssr/__tests__/fixtures/errors/syntax-error-dep.ts
  packages/vite/src/node/ssr/__tests__/fixtures/errors/syntax-error.js
  packages/vite/src/node/ssr/__tests__/fixtures/errors/syntax-error.ts
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
  packages/vite/src/shared/moduleRunnerTransport.ts
Labels: p4-important, feat: ssr, trigger: preview

#18619 docs: expand description of `externalConditions`
  docs/config/ssr-options.md
Labels: documentation

#18550 refactor: introduce `mergeWithDefaults` and organize how default values for config options are set
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/__tests_dts__/utils.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/json.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/ssr/index.ts
  packages/vite/src/node/utils.ts
Labels: p1-chore, trigger: preview

#18646 feat: add `ssr.resolve.mainFields` option
  docs/config/ssr-options.md
  docs/guide/migration.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/ssr/index.ts
Labels: p3-downstream-blocker, feat: ssr

#18649 feat: show error when accessing variables not exposed in CJS build
  packages/vite/index.cjs
  packages/vite/rollup.config.ts
Labels: p3-minor-bug

#18544 feat: extended applyToEnvironment and perEnvironmentPlugin
  docs/changes/shared-plugins-during-build.md
  docs/guide/api-environment-plugins.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/environment.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/clientInjections.ts
  packages/vite/src/node/plugins/dynamicImportVars.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/manifest.ts
  packages/vite/src/node/plugins/reporter.ts
  packages/vite/src/node/server/environment.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
Labels: p2-to-be-discussed, feat: environment API

#18644 fix(ssr): format `ssrTransform` parse error
  packages/vite/src/node/ssr/__tests__/__snapshots__/ssrLoadModule.spec.ts.snap
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: feat: ssr, p2-edge-case

#18620 feat: add `isSsrTargetWebWorker` flag to `configEnvironment` hook
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugin.ts
Labels: feat: environment API

#18670 refactor(resolve): remove `allowLinkedExternal` parameter from `tryNodeResolve`
  packages/vite/src/node/external.ts
  packages/vite/src/node/plugins/resolve.ts
Labels: p1-chore

#18667 fix: include more modules to prefix-only module list
  packages/vite/src/module-runner/evaluatedModules.ts
Labels: p3-minor-bug, feat: ssr

#18648 feat: expose default mainFields/conditions
  docs/config/shared-options.md
  docs/config/ssr-options.md
  docs/guide/migration.md
  packages/vite/src/node/constants.ts
  packages/vite/src/node/publicUtils.ts
  packages/vite/src/node/utils.ts
  playground/resolve/vite.config.js
  playground/ssr-conditions/vite.config.js
  playground/ssr-webworker/vite.config.js
Labels: p2-to-be-discussed

#18673 fix: `createRunnableDevEnvironment` returns `RunnableDevEnvironment`, not `DevEnvironment`
  packages/vite/src/node/server/environments/runnableEnvironment.ts
Labels: has workaround, p2-edge-case, feat: environment API

#18694 test: skip ssr-html build tests
  playground/ssr-html/__tests__/ssr-html.spec.ts
Labels: p1-chore, test

#18560 fix(optimizer): detect npm / yarn / pnpm dependency changes correctly (#17336)
  packages/vite/src/node/optimizer/index.ts
Labels: p4-important, feat: deps optimizer

#18698 test: remove `runInBuild` flag from `withRetry`
  playground/cli/__tests__/cli.spec.ts
  playground/css/__tests__/css.spec.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/ssr-conditions/__tests__/ssr-conditions.spec.ts
  playground/ssr/__tests__/ssr.spec.ts
  playground/test-utils.ts
Labels: p1-chore, test

#18695 test: run ssr-conditions build test
  playground/ssr-conditions/__tests__/serve.ts
  playground/ssr-conditions/__tests__/ssr-conditions.spec.ts
  playground/ssr-conditions/package.json
  playground/ssr-conditions/server.js
  pnpm-lock.yaml
Labels: p1-chore, test

#18705 chore: add some comments about mimes
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/asset.ts
Labels: p1-chore

#18680 feat: add support for .cur type
  packages/vite/client.d.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/asset.ts
Labels: p2-nice-to-have

#18718 docs: rename `HotUpdateContext` to `HotUpdateOptions`
  docs/changes/hotupdate-hook.md
  docs/guide/api-environment-plugins.md
  packages/vite/src/node/server/hmr.ts
Labels: documentation

#18715 fix: `getModulesByFile` should return a `serverModule`
  packages/vite/src/node/server/mixedModuleGraph.ts
Labels: p3-downstream-blocker, feat: environment API

#18710 fix(create-vite): change create-app prompt to not remove existing files by default
  packages/create-vite/src/index.ts
Labels: p2-edge-case, feat: create-vite

#18727 test: change assets-runtime-base outDir to different one
  playground/assets/__tests__/runtime-base/assets-runtime-base.spec.ts
  playground/assets/vite.config-runtime-base.js
Labels: p1-chore, test

#18713 fix: catch error in full reload handler
  packages/vite/src/module-runner/hmrHandler.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/server/environment.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/shared/constants.ts
  packages/vite/src/shared/moduleRunnerTransport.ts
  playground/environment-react-ssr/__tests__/environment-react-ssr.spec.ts
  playground/environment-react-ssr/vite.config.ts
Labels: feat: hmr, p3-minor-bug, feat: ssr, feat: deps optimizer, feat: environment API

#18729 feat!: drop node 21 support in version ranges
  package.json
  packages/create-vite/package.json
  packages/plugin-legacy/package.json
  packages/vite/package.json
  packages/vite/src/node/ssr/runtime/__tests__/package.json
Labels: p1-chore, breaking change

#18733 fix(optimizer): trigger onCrawlEnd after manual included deps are registered
  packages/vite/src/node/optimizer/optimizer.ts
Labels: p2-edge-case, feat: deps optimizer

#18716 chore(create-vite): change directory structure of `template-vanilla` for consistency
  packages/create-vite/template-vanilla/index.html
  packages/create-vite/template-vanilla/src/counter.js
  packages/create-vite/template-vanilla/src/javascript.svg
  packages/create-vite/template-vanilla/src/main.js
  packages/create-vite/template-vanilla/src/style.css
Labels: p2-nice-to-have, feat: create-vite

#18741 fix: exit code on `SIGTERM`
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug

#18650 feat: support `module-sync` condition when loading config if enabled
  packages/vite/misc/false.d.ts
  packages/vite/misc/false.js
  packages/vite/misc/true.d.ts
  packages/vite/misc/true.js
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/rollup.dts.config.ts
  packages/vite/src/node/config.ts
  packages/vite/tsconfig.base.json
Labels: p2-nice-to-have

#18752 perf(worker): inline worker without base64
  packages/vite/src/node/plugins/worker.ts
  playground/worker/__tests__/es/worker-es.spec.ts
  playground/worker/__tests__/sourcemap-hidden/worker-sourcemap-hidden.spec.ts
  playground/worker/__tests__/sourcemap-inline/worker-sourcemap-inline.spec.ts
  playground/worker/__tests__/sourcemap/worker-sourcemap.spec.ts
Labels: p2-nice-to-have, feat: web workers

#18758 docs: changes ssr using module runner
  docs/changes/ssr-using-modulerunner.md
Labels: documentation

#18768 chore: add 5.4.x changelogs
  packages/vite/CHANGELOG.md
Labels: p1-chore

#18766 fix: expose missing `InterceptorOptions` type
  packages/vite/src/module-runner/index.ts
Labels: has workaround, p2-edge-case, feat: environment API

#18764 fix: display pre-transform error details
  packages/vite/src/node/server/environment.ts
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have

#18776 fix(manifest): do not override existing js manifest entry
  packages/vite/src/node/plugins/manifest.ts
Labels: p3-downstream-blocker

#18778 ci(ecosystem-ci): pass along commit of fork branch to use
  .github/workflows/ecosystem-ci-trigger.yml
Labels: p1-chore

#18784 fix(server): close _ssrCompatModuleRunner on server close
  packages/vite/src/node/server/index.ts
Labels: p3-downstream-blocker

#18792 feat(create-vite): bump vite-plugin-solid to `2.11.0`
  packages/create-vite/template-solid-ts/package.json
  packages/create-vite/template-solid/package.json
Labels: dependencies, p3-significant, feat: create-vite

#18795 docs: link correctly to vite 5/6 docs versions after vite 6 release
  docs/.vitepress/config.ts
Labels: documentation

#18788 fix: default empty server `proxy` prevents starting http2 server
  packages/vite/src/node/server/index.ts
Labels: p4-important, regression

#18793 fix(worker): fix `applyToEnvironment` hooks on worker build
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/worker.ts
  playground/worker/__tests__/es/worker-es.spec.ts
  playground/worker/__tests__/iife/worker-iife.spec.ts
  playground/worker/dep-cjs/index.cjs
  playground/worker/dep-cjs/package.json
  playground/worker/index.html
  playground/worker/my-worker.ts
  playground/worker/package.json
  playground/worker/worker/main-module.js
  pnpm-lock.yaml
Labels: trigger: preview

#18782 fix(server): skip hot channel client normalization for wsServer
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/ws.ts
Labels: p3-downstream-blocker, regression

#18802 chore: update broken links in changelog
  packages/vite/CHANGELOG.md
Labels: p1-chore

#18804 chore: update broken links in changelog
  packages/vite/CHANGELOG.md
Labels: p1-chore

#18796 refactor: make properties of ResolvedServerOptions and ResolvedPreviewOptions required
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/typeUtils.ts
Labels: p1-chore

#18820 fix(manifest): use `style.css` as a key for the style file for `cssCodesplit: false`
  docs/guide/backend-integration.md
  packages/vite/src/node/plugins/css.ts
Labels: p3-minor-bug, regression

#18818 feat(css): format lightningcss error
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-nice-to-have

#18805 docs: show old document warning
  docs/.vitepress/theme/components/OldDocument.vue
  docs/.vitepress/theme/index.ts
Labels: documentation

#18765 docs: clarify .env loading precedence / behavior
  docs/guide/env-and-mode.md
Labels: documentation

#18829 docs: v4 show old document warning (#18805)
  docs/.vitepress/theme/components/OldDocument.vue
  docs/.vitepress/theme/index.ts
Labels: documentation

#18830 docs: v3 show old document warning (#18805)
  docs/.vitepress/theme/components/OldDocument.vue
  docs/.vitepress/theme/index.ts
Labels: documentation

#18831 docs: v2 show old document warning (#18805)
  docs/.vitepress/theme/components/OldDocument.vue
  docs/.vitepress/theme/components/WrappedLayout.vue
  docs/.vitepress/theme/custom.css
  docs/.vitepress/theme/index.js
Labels: documentation

#18826 fix(optimizer): resolve all promises when cancelled
  packages/vite/src/node/optimizer/optimizer.ts
Labels: p3-minor-bug, regression, feat: deps optimizer

#18821 fix(resolve): don't set builtinModules to `external` by default
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug, feat: ssr, regression

#18827 fix(ssr): set `ssr.target: 'webworker'` defaults as fallback
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
Labels: p3-downstream-blocker, regression
