Repository vitejs/vite, pull requests merged in 2024-01, with the labels that each got.

#15435 fix(html): handle offset magic-string slice error
  packages/vite/src/node/plugins/html.ts
  playground/html/vite.config.js
  playground/html/write.html
Labels: feat: html, p3-minor-bug :hammer:

#15483 fix: inject `__vite__mapDeps` code before sourcemap file comment
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
Labels: p3-minor-bug :hammer:, feat: sourcemap

#14588 fix(sourcemap): sourcemap is incorrect when sourcemap has `sources: [null]`
  packages/vite/src/node/server/pluginContainer.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
  playground/js-sourcemap/index.html
  playground/js-sourcemap/package.json
  playground/js-sourcemap/plugin-foo.js
  playground/js-sourcemap/vite.config.js
  playground/js-sourcemap/zoo-with-sourcemap-plugin.ts
  playground/js-sourcemap/zoo.js
  pnpm-lock.yaml
Labels: rollup plugin compat, p3-minor-bug :hammer:, feat: sourcemap

#15519 fix(hmr): `package.json` change should trigger server restart
  packages/vite/src/node/server/hmr.ts
Labels: p2-nice-to-have :cake:

#15480 refactor: reuse existing node utils
  packages/vite/src/node/build.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/splitVendorChunk.ts
  packages/vite/src/node/utils.ts
  packages/vite/src/node/watch.ts
Labels: p1-chore :broom:

#15427 fix: update javascript mime type to text/javascript
  package.json
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/server/send.ts
  patches/sirv@2.0.4.patch
  playground/assets/__tests__/assets.spec.ts
  playground/dynamic-import/__tests__/dynamic-import.spec.ts
  playground/external/vite.config.js
  playground/legacy/__tests__/legacy.spec.ts
  playground/lib/package.json
  playground/worker/__tests__/es/es-worker.spec.ts
  playground/worker/__tests__/sourcemap-hidden/sourcemap-hidden-worker.spec.ts
  playground/worker/__tests__/sourcemap-inline/sourcemap-inline-worker.spec.ts
  playground/worker/__tests__/sourcemap/sourcemap-worker.spec.ts
  pnpm-lock.yaml
Labels: p3-downstream-blocker :hammer:

#15471 feat: add '*.m4a' to client.d.ts and constants
  packages/vite/client.d.ts
  packages/vite/src/node/constants.ts
Labels: p2-nice-to-have :cake:

#15118 feat(hmr): reload for circular imports only if error
  packages/vite/src/client/client.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/types/hmrPayload.d.ts
  playground/hmr/__tests__/hmr.spec.ts
Labels: feat: hmr, p2-nice-to-have :cake:

#15360 refactor: normalize publicDir when resolving config
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/publicDir.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p1-chore :broom:

#14420 feat(glob-import): deprecate as option
  docs/guide/features.md
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/__snapshots__/parse.spec.ts.snap
  packages/vite/src/node/__tests__/plugins/importGlob/__snapshots__/fixture.spec.ts.snap
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-a/index.ts
  packages/vite/src/node/__tests__/plugins/importGlob/parse.spec.ts
  packages/vite/src/node/plugins/dynamicImportVars.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/types/importGlob.d.ts
  playground/glob-import/index.html
  playground/worker/worker/main-module.js
Labels: p3-significant 🔨

#15000 fix(css): @import with .css in node_modules importing a different package failed to resolve
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/index.html
  playground/css/package.json
  playground/css/sass.scss
  playground/css/scss-proxy-dep-nested/index.css
  playground/css/scss-proxy-dep-nested/package.json
  playground/css/scss-proxy-dep/index.scss
  playground/css/scss-proxy-dep/package.json
  pnpm-lock.yaml
Labels: feat: css, p3-minor-bug :hammer:

#15326 fix(hmr): make watcher ignore build.outDir
  docs/config/server-options.md
  packages/vite/src/node/watch.ts
Labels: p2-nice-to-have :cake:

#15541 refactor: extract '_metadata.json' string to a constant
  packages/vite/src/node/constants.ts
  packages/vite/src/node/optimizer/index.ts
Labels: p1-chore :broom:

#15544 fix(css): skip url replace for function calls
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/index.html
  playground/css/nested/_index.scss
Labels: feat: css, p3-minor-bug :hammer:

#15450 fix: resolvedUrls is null in plugin's configureServer after server restart
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#15561 fix: init dev ssr optimizer on server init
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p3-downstream-blocker :hammer:, feat: ssr, feat: deps optimizer

#10939 feat(ssr): support external true
  docs/config/ssr-options.md
  packages/vite/src/node/ssr/__tests__/fixtures/cjs-ssr-dep/index.js
  packages/vite/src/node/ssr/__tests__/fixtures/cjs-ssr-dep/package.json
  packages/vite/src/node/ssr/__tests__/package.json
  packages/vite/src/node/ssr/__tests__/ssrExternal.spec.ts
  packages/vite/src/node/ssr/index.ts
  packages/vite/src/node/ssr/ssrExternal.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: feat: ssr, p2-to-be-discussed :cake:

#15562 test: ignore net:ERR_ABORTED on flacky html proxy encoded test
  playground/ssr/__tests__/ssr.spec.ts
Labels: test

#15554 fix(build): normalize html path
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p3-minor-bug :hammer:

#15574 perf: optimize logger
  packages/vite/src/node/logger.ts
Labels: performance

#15486 refactor(hmr): keep buffer implementation internal, expose queueUpdate
  packages/vite/src/client/client.ts
  packages/vite/src/shared/hmr.ts
Labels: p3-significant 🔨

#15571 refactor: remove json-stable-stringify
  package.json
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/src/node/plugins/manifest.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:

#15366 feat: `build.assetsInlineLimit` callback
  docs/config/build-options.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/asset.ts
  playground/worker/vite.config-es.js
  playground/worker/vite.config-iife.js
  playground/worker/vite.config-relative-base-iife.js
  playground/worker/vite.config-relative-base.js
  playground/worker/worker-sourcemap-config.js
Labels: p3-significant 🔨

#15580 test: fixed port for lib dev test
  playground/lib/__tests__/serve.ts
Labels: test

#15259 fix(css): `.css?url` support
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/utils.ts
  playground/assets/__tests__/assets.spec.ts
  playground/css/__tests__/css.spec.ts
  playground/css/index.html
  playground/css/main.js
  playground/css/raw-imported.css
  playground/css/url-imported.css
Labels: feat: css, p3-minor-bug :hammer:

#15184 refactor: remove build time pre-bundling
  docs/config/dep-optimization-options.md
  package.json
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
  packages/vite/src/node/ssr/__tests__/ssrStacktrace.spec.ts
  packages/vite/src/node/ssr/index.ts
  playground/optimize-deps-no-discovery/vite.config.js
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/vite.config.js
  playground/ssr-deps/server.js
  playground/ssr-noexternal/__tests__/ssr-noexternal.spec.ts
  playground/ssr-noexternal/vite.config.js
Labels: p2-nice-to-have :cake:, feat: deps optimizer, feat: build

#15606 fix(types): mark hmr update internal types optional
  packages/vite/types/hmrPayload.d.ts
Labels: p3-downstream-blocker :hammer:

#15599 fix(ssr): externalize network imports during `ssrLoadModule`
  .prettierignore
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  playground/ssr-html/__tests__/ssr-html.spec.ts
  playground/ssr-html/public/slash@3.0.0.js
  playground/ssr-html/src/network-imports.js
  playground/ssr-html/test-network-imports.js
Labels: p3-minor-bug :hammer:, feat: ssr

#15590 perf: simplify isHtmlProxy regex
  packages/vite/src/node/plugins/html.ts
Labels: performance

#15579 perf: don't recreate html hooks on each transform call
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: performance

#15617 perf: avoid parseRequest
  packages/vite/src/node/__tests__/plugins/dynamicImportVar/__snapshots__/parse.spec.ts.snap
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/dynamicImportVars.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  packages/vite/src/node/utils.ts
  playground/worker/__tests__/iife/iife-worker.spec.ts
Labels: p2-nice-to-have :cake:, performance

#15610 perf: do not bind plugin hook context functions
  packages/vite/src/node/server/__tests__/pluginContainer.spec.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: performance

#15608 fix(css): track dependencies from addWatchFile for HMR
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/index.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/css-deps/dep.js
  playground/hmr/css-deps/index.html
  playground/hmr/css-deps/main.css
  playground/hmr/vite.config.ts
Labels: feat: css, feat: hmr, p3-downstream-blocker :hammer:

#15340 feat: support multiple HMR clients on the server
  docs/guide/api-plugin.md
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/esbuild.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/error.ts
  packages/vite/src/node/server/ws.ts
  playground/hmr/vite.config.ts
  playground/vitestGlobalSetup.ts
  playground/vitestSetup.ts
Labels: p3-significant 🔨

#15506 feat(plugin-legacy): add `modernTargets` option
  packages/plugin-legacy/README.md
  packages/plugin-legacy/package.json
  packages/plugin-legacy/src/index.ts
  packages/plugin-legacy/src/types.ts
  pnpm-lock.yaml
Labels: plugin: legacy, p2-nice-to-have :cake:

#15630 feat: preview server add close method
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have :cake:

#15634 perf: avoid performance.now() call
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: performance

#15636 docs: `build.minify` defaults to `false` for SSR
  docs/config/build-options.md
Labels: documentation

#15619 fix: handle namespace import and dynamic import interop consistently
  packages/vite/src/node/__tests__/plugins/import.spec.ts
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p3-minor-bug :hammer:

#15605 fix: await `configResolved` hooks of worker plugins (#15597)
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:, regression

#15646 docs: changed bunx create-vite to bun create vite
  docs/guide/index.md
  packages/create-vite/README.md
Labels: documentation

#15624 perf: optimize getSortedPluginsByHook
  packages/vite/src/node/plugins/index.ts
Labels: performance

#15623 perf: don't recalculate path.dirname(mod.file)
  packages/vite/src/node/server/transformRequest.ts
Labels: performance

#15631 refactor(hmr): provide a separate logger interface
  packages/vite/src/shared/hmr.ts
Labels: feat: hmr

#15658 fix(ssr): mark builtin modules as side effect free
  packages/vite/src/node/plugins/resolve.ts
  playground/ssr-resolve/__tests__/ssr-resolve.spec.ts
  playground/ssr-resolve/main.js
  playground/ssr-resolve/util.js
Labels: p2-nice-to-have :cake:, feat: ssr

#15586 perf: middleware to short-circuit on 304
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/moduleGraph.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: performance

#15656 fix(ssr): support externalized builtins for webworker
  packages/vite/src/node/plugins/resolve.ts
  playground/ssr-webworker/__tests__/ssr-webworker.spec.ts
  playground/ssr-webworker/src/entry-worker.jsx
  playground/ssr-webworker/vite.config.js
  playground/ssr-webworker/worker.js
Labels: p3-downstream-blocker :hammer:, feat: ssr

#15647 refactor: append tags logic in applyHtmlTransforms
  packages/vite/src/node/plugins/html.ts
Labels: p1-chore :broom:

#15665 fix: default sideEffect option is delivered to rollup
  packages/vite/src/node/packages.ts
Labels: p3-minor-bug :hammer:

#13584 perf: use thread for preprocessors
  docs/config/shared-options.md
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/terser.ts
  playground/css/vite.config.js
  pnpm-lock.yaml
Labels: feat: css, p3-significant 🔨, performance

#15621 perf: lazy load rollup during dev
  packages/vite/src/node/publicUtils.ts
  packages/vite/src/node/server/pluginContainer.ts
  packages/vite/src/node/utils.ts
Labels: performance

#15244 feat(optimizer): holdUntilCrawlEnd option
  docs/config/dep-optimization-options.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
Labels: p3-significant 🔨, feat: deps optimizer, performance

#15664 fix(build): build error message output twice
  packages/vite/src/node/build.ts
  playground/tsconfig-json-load-error/__tests__/tsconfig-json-load-error.spec.ts
Labels: p3-significant 🔨

#15663 fix(node): remove timestamp query of `staticImportedUrls`
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/hmr/__tests__/hmr.spec.ts
Labels: p3-minor-bug :hammer:

#15704 feat: enable fs.cachedChecks by default
  packages/vite/src/node/fsUtils.ts
  packages/vite/src/node/server/index.ts
  playground/html/vite.config.js
Labels: p3-significant 🔨, performance

#15712 perf: use workspace root for fs cache
  packages/vite/src/node/fsUtils.ts
Labels: p3-significant 🔨, performance

#15716 test: fix proxy-bypass and proxy-hmr ports
  playground/proxy-bypass/index.html
  playground/proxy-bypass/vite.config.js
  playground/proxy-hmr/other-app/vite.config.js
  playground/proxy-hmr/vite.config.js
  playground/test-utils.ts
Labels: test

#15718 test: consolidate spec names in all playgrounds
  playground/assets/__tests__/relative-base/assets-relative-base.spec.ts
  playground/assets/__tests__/runtime-base/assets-runtime-base.spec.ts
  playground/assets/__tests__/url-base/assets-url-base.spec.ts
  playground/config/__tests__/config.spec.ts
  playground/css-codesplit-cjs/__tests__/css-codesplit-cjs.spec.ts
  playground/css-lightningcss/__tests__/css-lightningcss.spec.ts
  playground/css-sourcemap/__tests__/lib-entry/css-sourcemap-lib-entry.spec.ts
  playground/css/__tests__/no-css-minify/css-no-css-minify.spec.ts
  playground/css/__tests__/postcss-plugins-different-dir/css-postcss-plugins-different-dir.spec.ts
  playground/css/__tests__/same-file-name/css-same-file-name.spec.ts
  playground/json/__tests__/csr/json-csr.spec.ts
  playground/json/__tests__/ssr/json-ssr.spec.ts
  playground/legacy/__tests__/client-and-ssr/legacy-client-legacy-ssr-sequential-builds.spec.ts
  playground/legacy/__tests__/no-polyfills-no-systemjs/legacy-no-polyfills-no-systemjs.spec.ts
  playground/legacy/__tests__/no-polyfills/legacy-no-polyfills.spec.ts
  playground/legacy/__tests__/watch/legacy-styles-only-entry-watch.spec.ts
  playground/optimize-deps-no-discovery/__tests__/optimize-deps-no-discovery.spec.ts
  playground/proxy-bypass/__tests__/proxy-bypass.spec.ts
  playground/worker/__tests__/es/worker-es.spec.ts
  playground/worker/__tests__/iife/worker-iife.spec.ts
  playground/worker/__tests__/relative-base-iife/worker-relative-base-iife.spec.ts
  playground/worker/__tests__/relative-base/worker-relative-base.spec.ts
  playground/worker/__tests__/sourcemap-hidden/worker-sourcemap-hidden.spec.ts
  playground/worker/__tests__/sourcemap-inline/worker-sourcemap-inline.spec.ts
  playground/worker/__tests__/sourcemap/worker-sourcemap.spec.ts
Labels: test

#15724 perf: simplify explicit import mark in import analysis
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: performance
