Repository vitejs/vite, pull requests merged in 2024-03, with the labels that each got.

#16061 refactor(runtime): use functions from `pathe`
  packages/vite/package.json
  packages/vite/src/runtime/utils.ts
  pnpm-lock.yaml
Labels: p1-chore, feat: runtime

#16056 docs(hmr): document `hmr.protocol` setting
  docs/config/server-options.md
Labels: documentation

#16062 fix: upgrade esbuild to 0.20.x
  packages/vite/package.json
  playground/legacy/__tests__/watch/legacy-styles-only-entry-watch.spec.ts
  playground/legacy/style-only-entry.css
  pnpm-lock.yaml
Labels: dependencies, p3-minor-bug

#15534 docs(assets): add note to inlining SVG through url()
  docs/guide/assets.md
Labels: documentation

#16085 fix: import with query with imports field
  packages/vite/src/node/plugins/resolve.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/imports-path/query.json
  playground/resolve/index.html
  playground/resolve/package.json
Labels: p3-minor-bug

#15469 fix: analysing build chunk without dependencies
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-minor-bug

#16060 fix: escape single quote when relative base is used
  packages/vite/src/node/build.ts
  playground/assets/index.html
  playground/assets/nested/with-single'quote.png
Labels: p3-minor-bug

#16063 refactor(runtime): share more code between runtime and main bundle
  packages/vite/src/node/ssr/fetchModule.ts
  packages/vite/src/node/ssr/ssrFetchModule.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  packages/vite/src/runtime/esmRunner.ts
  packages/vite/src/runtime/moduleCache.ts
  packages/vite/src/runtime/runtime.ts
  packages/vite/src/runtime/sourcemap/interceptor.ts
  packages/vite/src/runtime/types.ts
  packages/vite/src/shared/constants.ts
  packages/vite/src/shared/ssrTransform.ts
  packages/vite/src/shared/utils.ts
Labels: p1-chore, feat: runtime

#16094 fix(worker): hide "The emitted file overwrites" warning if the content is same
  packages/vite/src/node/plugins/worker.ts
Labels: p2-nice-to-have, feat: web workers

#16103 fix(worker): throw error when circular worker import is detected and support self referencing worker
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  playground/worker/__tests__/es/worker-es.spec.ts
  playground/worker/__tests__/iife/worker-iife.spec.ts
  playground/worker/__tests__/relative-base/worker-relative-base.spec.ts
  playground/worker/__tests__/sourcemap-hidden/worker-sourcemap-hidden.spec.ts
  playground/worker/__tests__/sourcemap-inline/worker-sourcemap-inline.spec.ts
  playground/worker/__tests__/sourcemap/worker-sourcemap.spec.ts
  playground/worker/index.html
  playground/worker/self-reference-url-worker.js
  playground/worker/self-reference-worker.js
  playground/worker/worker/main-module.js
Labels: p3-minor-bug, inconsistency, feat: web workers

#15789 fix(plugin-legacy): respect modernTargets option if renderLegacyChunks disabled
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p3-significant

#16113 fix: handle function property extension in namespace import
  packages/vite/src/node/__tests__/plugins/import.spec.ts
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p3-minor-bug

#16046 fix: check for publicDir before checking if it is a parent directory
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
Labels: p3-minor-bug, regression

#16122 fix: server middleware mode resolve
  packages/vite/src/node/server/index.ts
Labels: p3-significant

#15773 docs(static-deploy): update workflow
  docs/guide/static-deploy.md
Labels: documentation

#16145 docs: add docs about `vite serve` alias
  docs/config/index.md
  docs/guide/cli.md
Labels: documentation

#16144 docs: replace `DEBUG="vite:foo"` with `--debug foo`
  docs/guide/performance.md
Labels: documentation

#16079 fix: upgrade esbuild to 0.20.x
  packages/vite/package.json
  playground/legacy/__tests__/watch/legacy-styles-only-entry-watch.spec.ts
  playground/legacy/style-only-entry.css
  pnpm-lock.yaml
Labels: dependencies, p3-minor-bug

#16146 chore: use `@polka/compression`
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/middlewares/compression.ts
  pnpm-lock.yaml
Labels: p1-chore

#15760 style: update overlay style on mobile
  packages/vite/src/client/overlay.ts
Labels: p2-nice-to-have

#16068 feat: support for self-referencing
  packages/vite/src/node/plugins/resolve.ts
  playground/nested-deps/__tests__/nested-deps.spec.ts
  playground/nested-deps/index.html
  playground/nested-deps/package.json
  playground/self-referencing/index.js
  playground/self-referencing/package.json
  playground/self-referencing/test/index.js
  pnpm-lock.yaml
Labels: p3-minor-bug

#16087 feat: accept assets to be specified as input
  packages/vite/src/node/plugins/asset.ts
  playground/backend-integration/__tests__/backend-integration.spec.ts
  playground/backend-integration/frontend/entrypoints/icon.png
Labels: p2-to-be-discussed

#15888 feat(config): `import.meta.filename`/`dirname` support
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have

#15852 feat: convert overlay template to DOM
  packages/vite/src/client/overlay.ts
Labels: p2-to-be-discussed

#16019 feat(resolve): auto externalize node builtins for `noExternal: true` in node
  docs/config/ssr-options.md
  packages/vite/src/node/plugins/resolve.ts
Labels: p2-nice-to-have, feat: ssr

#15782 fix(hmr): call dispose before prune
  packages/vite/src/client/client.ts
  packages/vite/src/runtime/hmrHandler.ts
  packages/vite/src/shared/hmr.ts
  playground/hmr-ssr/__tests__/hmr-ssr.spec.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/file-delete-restore/child.js
Labels: feat: hmr, p3-minor-bug

#15311 fix: encode URLs correctly (fix #15298)
  docs/guide/build.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/utils.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
  playground/assets/nested/テスト-測試-white space%.png
  playground/assets/テスト-測試-white space%.js
Labels: p3-minor-bug

#15887 feat(ssr): `import.meta.filename`/`dirname` support
  packages/vite/src/node/ssr/__tests__/fixtures/modules/import-meta.js
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p2-nice-to-have, feat: ssr

#14441 fix(ssr): crash on circular import
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  playground/ssr/__tests__/ssr.spec.ts
  playground/ssr/src/app.js
  playground/ssr/src/circular-import/a.js
  playground/ssr/src/circular-import/b.js
  playground/ssr/src/circular-import/index.js
Labels: p3-minor-bug, feat: ssr

#16151 fix(esbuild): preserve import.meta even if esbuild.target is set to lower versions
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/esbuild.ts
Labels: has workaround, p2-edge-case

#16152 fix: `sideEffects: []` should work as `sideEffects: false`
  packages/vite/src/node/packages.ts
Labels: p3-minor-bug

#16052 feat: csp nonce support
  docs/config/shared-options.md
  docs/guide/features.md
  packages/vite/src/client/client.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/csp/__tests__/csp.spec.ts
  playground/csp/dynamic.css
  playground/csp/dynamic.js
  playground/csp/from-js.css
  playground/csp/index.html
  playground/csp/index.js
  playground/csp/linked.css
  playground/csp/package.json
  playground/csp/vite.config.js
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
  pnpm-lock.yaml
Labels: enhancement, p2-to-be-discussed

#16080 feat(optimizer): show a friendly warning with 404 instead of 504 outdated optimize dep
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/server/middlewares/transform.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-incompatible/index.js
  playground/optimize-deps/dep-incompatible/package.json
  playground/optimize-deps/dep-incompatible/sub.js
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  pnpm-lock.yaml
Labels: p2-nice-to-have, feat: deps optimizer

#16086 docs: backend integration clarify tags to include in production HTML
  docs/guide/backend-integration.md
Labels: documentation

#16135 feat: formalize waitForRequestsIdle (experimental)
  docs/guide/api-javascript.md
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/transformRequest.ts
  playground/tailwind/vite.config.ts
Labels: p3-downstream-blocker, feat: dev

#16168 docs: add `@shikiji/vitepress-twoslash`
  docs/.vitepress/config.ts
  docs/.vitepress/theme/index.ts
  docs/.vitepress/tsconfig.json
  docs/config/build-options.md
  docs/config/dep-optimization-options.md
  docs/config/index.md
  docs/config/server-options.md
  docs/config/shared-options.md
  docs/guide/api-hmr.md
  docs/guide/api-javascript.md
  docs/guide/api-plugin.md
  docs/guide/assets.md
  docs/guide/backend-integration.md
  docs/guide/build.md
  docs/guide/dep-pre-bundling.md
  docs/guide/features.md
  docs/guide/ssr.md
  docs/guide/using-plugins.md
  docs/package.json
  package.json
  packages/vite/src/node/config.ts
  packages/vite/types/customEvent.d.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: documentation

#16081 fix(assets): avoid splitting `,` inside query parameter of image URI in srcset property
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: feat: html, p3-minor-bug

#16170 perf(transformRequest): fast-path watch and sourcemap handling
  packages/vite/src/node/server/sourcemap.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p2-nice-to-have

#16182 fix: update client.ts@cleanUrl to accomodate blob protocol
  packages/vite/src/client/client.ts
Labels: feat: hmr, p2-edge-case

#16223 fix: handle warmup request error correctly
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug, feat: dev

#16220 fix(runtime): fix sourcemap with `prepareStackTrace`
  packages/vite/rollup.config.ts
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/has-error-deep.ts
  packages/vite/src/node/ssr/runtime/__tests__/server-source-maps.spec.ts
  playground/ssr-html/__tests__/ssr-html.spec.ts
  playground/ssr-html/src/has-error-deep.ts
  playground/ssr-html/test-stacktrace-runtime.js
Labels: p3-minor-bug, regression, feat: sourcemap

#16232 chore: `utf8` replaced with `utf-8`
  packages/vite/rollupLicensePlugin.ts
  packages/vite/src/node/config.ts
  playground/csp/vite.config.js
  playground/json/server.js
  playground/resolve-config/__tests__/resolve-config.spec.ts
  playground/resolve-config/__tests__/serve.ts
Labels: p1-chore

#16230 fix(optimizer): fix `optimizeDeps.include` glob syntax for `./*` exports
  packages/vite/src/node/optimizer/resolve.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-optimize-exports-with-root-glob/dir/file2.js
  playground/optimize-deps/dep-optimize-exports-with-root-glob/file1.js
  playground/optimize-deps/dep-optimize-exports-with-root-glob/index.js
  playground/optimize-deps/dep-optimize-exports-with-root-glob/package.json
  playground/optimize-deps/package.json
  playground/optimize-deps/vite.config.js
  pnpm-lock.yaml
Labels: p3-minor-bug

#16233 fix: skip encode if is data uri
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/utils.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
  playground/assets/nested/inlined.svg
Labels: p4-important

#16244 fix: dont resolve imports with malformed URI
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/asset/percent%.png
  playground/assets/index.html
  playground/assets/nested/テスト-測試-white space.png
  playground/assets/テスト-測試-white space.js
Labels: p3-minor-bug, regression

#16226 docs: clarify enforce vs hook.order
  docs/guide/api-plugin.md
  packages/vite/src/node/plugin.ts
Labels: documentation

#16225 docs(create-vite): link to Vue docs for IDE support info
  packages/create-vite/template-vue-ts/README.md
  packages/create-vite/template-vue/README.md
Labels: p1-chore, feat: create-vite

#16246 fix: avoid SSR requests in waitForRequestIdle
  packages/vite/src/node/server/transformRequest.ts
Labels: p3-downstream-blocker, regression

#16273 fix(sourcemap): don't warn even if the sourcesContent is an empty string
  packages/vite/src/node/server/sourcemap.ts
Labels: p3-minor-bug, feat: sourcemap

#16279 docs: use href attribute for link with rel=modulepreload
  docs/guide/backend-integration.md
Labels: documentation

#16288 feat(hmr): reload when HTML file is created/deleted
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/moduleGraph.ts
Labels: feat: hmr, p2-nice-to-have

#16302 fix(hmr): don't mutate module graph when collecting modules
  packages/vite/src/node/server/hmr.ts
Labels: feat: hmr, p4-important

#16303 fix(hmr): trigger hmr for missing file import errored module after file creation
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/moduleGraph.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/missing-file/index.html
  playground/hmr/missing-file/main.js
Labels: feat: hmr, p3-minor-bug

#16274 chore: deprecate splitVendorChunkPlugin
  docs/guide/build.md
  packages/vite/src/node/plugins/splitVendorChunk.ts
Labels: p1-chore

#16304 docs(css): duplicate `@import` behavior
  docs/config/shared-options.md
Labels: documentation

#16249 feat(hmr): call `hotUpdate` hook with file create/delete
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
Labels: feat: hmr, p2-nice-to-have

#16305 fix(scanner): duplicate modules for same id if glob is used in html-like types
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug, feat: deps optimizer

#16306 fix(css): unknown file error happened with lightningcss
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug

#16307 fix(hmr): multiple updates happened when invalidate is called while multiple tabs open
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/moduleGraph.ts
  playground/hmr/__tests__/hmr.spec.ts
Labels: feat: hmr, p3-minor-bug

#16282 fix: csp nonce injection when no closing tag (#16281)
  packages/vite/src/node/plugins/html.ts
Labels: p3-minor-bug
