Repository vitejs/vite, pull requests merged in 2024-10, with the labels that each got.

#18247 test: fix server-worker-runner flaky test
  packages/vite/src/node/ssr/runtime/__tests__/server-worker-runner.spec.ts
Labels: p1-chore, test

#18255 feat: restrict characters useable for environment name
  packages/vite/src/node/baseEnvironment.ts
Labels: feat: environment API

#18252 fix(hmr): don't try to rewrite imports for direct CSS soft invalidation
  packages/vite/src/node/server/moduleGraph.ts
Labels: feat: css, feat: hmr, p3-downstream-blocker

#18250 fix(legacy): generate sourcemap for polyfill chunks
  packages/plugin-legacy/src/index.ts
  playground/legacy/__tests__/legacy.spec.ts
Labels: plugin: legacy, p3-minor-bug, feat: sourcemap

#18236 feat: support arbitrary module namespace identifier imports from cjs deps
  packages/vite/src/node/__tests__/plugins/import.spec.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have

#18246 fix: `injectQuery` double encoding
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug

#18280 chore(docs): add margin to h4
  docs/.vitepress/theme/components/landing/5. sponsor-section/SponsorSection.vue
Labels: documentation

#18285 fix(create-vite): update qwik URL
  packages/create-vite/template-qwik-ts/README.md
  packages/create-vite/template-qwik-ts/src/app.tsx
  packages/create-vite/template-qwik/README.md
  packages/create-vite/template-qwik/src/app.jsx
Labels: p2-nice-to-have, feat: create-vite

#18273 fix: make it easier to configure environment runner
  packages/vite/src/node/server/environments/runnableEnvironment.ts
  playground/hmr-ssr/__tests__/hmr-ssr.spec.ts
Labels: feat: environment API

#18282 fix: destroy the runner when runnable environment is closed
  packages/vite/src/node/server/environments/runnableEnvironment.ts
Labels: feat: environment API

#18261 fix(middleware-mode): call all hot.listen when server restart
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug, feat: environment API

#18242 fix(assets): make srcset parsing HTML spec compliant (#16323)
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: feat: html, p3-minor-bug

#18152 fix(optimizer): don't externalize transitive dep package name with asset extension
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-with-asset-ext/dep1/index.mjs
  playground/optimize-deps/dep-with-asset-ext/dep1/package.json
  playground/optimize-deps/dep-with-asset-ext/dep2/index.js
  playground/optimize-deps/dep-with-asset-ext/dep2/package.json
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug, feat: deps optimizer

#18299 fix(types): add more overload to `defineConfig`
  packages/vite/src/node/__tests_dts__/config.ts
  packages/vite/src/node/config.ts
Labels: p2-edge-case

#18304 refactor: rename runner.destroy() to runner.close()
  docs/guide/api-environment.md
  packages/vite/src/module-runner/hmrHandler.ts
  packages/vite/src/module-runner/runner.ts
  packages/vite/src/node/server/environments/runnableEnvironment.ts
  packages/vite/src/node/ssr/runtime/__tests__/utils.ts
Labels: feat: environment API

#18308 test(css): make "duplicate CSS" test to focus on what it's testing
  playground/css-dynamic-import/__tests__/css-dynamic-import.spec.ts
Labels: p1-chore, test

#18307 fix(css): dont remove JS chunk for pure CSS chunk when the export is used
  packages/vite/src/node/plugins/css.ts
  playground/glob-import/vite.config.ts
Labels: feat: css, p2-edge-case

#18317 perf: use `crypto.hash` when available
  packages/plugin-legacy/src/index.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have

#18302 fix(resolve): fix resolve cache to consider `conditions` and more
  packages/vite/src/node/__tests__/environment.spec.ts
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions-app/entry.css
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions-app/entry.js
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/index.browser.js
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/index.css
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/index.custom1.js
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/index.custom2.js
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/index.custom3.js
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/index.default.js
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/index.worker.js
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/package.json
  packages/vite/src/node/__tests__/package.json
  packages/vite/src/node/packages.ts
  packages/vite/src/node/plugins/resolve.ts
  pnpm-lock.yaml
Labels: p3-minor-bug

#18321 chore: point deprecation error URLs to main branch docs
  packages/vite/src/node/deprecations.ts
Labels: p1-chore, feat: environment API

#18322 fix(deps): bump tsconfck
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies, p3-minor-bug

#18323 perf: call `module.enableCompileCache()`
  packages/vite/bin/vite.js
Labels: p2-nice-to-have

#18327 test: ssr external / resolveId test
  packages/vite/src/node/__tests__/environment.spec.ts
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions-app/entry-with-module.js
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/dir/index.default.js
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/dir/index.module.js
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/package.json
  packages/vite/src/node/__tests__/resolve.spec.ts
Labels: p1-chore, test

#18333 docs: misc env api docs
  docs/.vitepress/config.ts
  docs/guide/api-environment-frameworks.md
  docs/guide/api-environment-instances.md
  docs/guide/api-environment-plugins.md
  docs/guide/api-environment.md
Labels: documentation

#18334 docs: env api expand runtime agnostic SSR section
  docs/guide/api-environment-frameworks.md
Labels: documentation

#18344 fix: add position to import analysis resolve exception
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p2-nice-to-have

#18316 docs: refactor environment api docs
  docs/.vitepress/config.ts
  docs/guide/api-environment-frameworks.md
  docs/guide/api-environment-instances.md
  docs/guide/api-environment-plugins.md
  docs/guide/api-environment-runtimes.md
  docs/guide/api-environment.md
Labels: documentation, feat: environment API

#18332 fix(resolve): fix resolve cache key for external conditions
  packages/vite/src/node/__tests__/environment.spec.ts
  packages/vite/src/node/packages.ts
Labels: p3-minor-bug

#18352 docs: update ViteConf 24 cta
  docs/.vitepress/theme/components/AsideSponsors.vue
  docs/.vitepress/theme/components/landing/1. hero-section/HeroSection.vue
Labels: documentation

#18354 docs: env expand feature only works for variables in env files
  docs/guide/env-and-mode.md
Labels: documentation

#18349 fix(deps): update `open` dependency to 10.1.0
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/src/node/server/openBrowser.ts
  pnpm-lock.yaml
Labels: dependencies, p3-minor-bug

#18355 docs: relative base path
  docs/guide/build.md
Labels: documentation

#18165 fix(worker): rewrite rollup `output.format` with `worker.format` on worker build error
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/__tests__/fixtures/worker-dynamic/dynamic.js
  packages/vite/src/node/__tests__/fixtures/worker-dynamic/main.js
  packages/vite/src/node/__tests__/fixtures/worker-dynamic/worker.js
  packages/vite/src/node/plugins/worker.ts
Labels: p2-nice-to-have, feat: web workers

#18368 test: remove unnecessary logs from output
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/__tests__/environment.spec.ts
Labels: p1-chore, test

#18364 docs: add multiple entries lib mode example
  docs/guide/build.md
Labels: documentation

#18360 refactor: use `verbatimModuleSyntax` instead of `importsNotUsedAsValues`
  playground/tsconfig-json-load-error/tsconfig.json
  playground/tsconfig-json/__tests__/tsconfig-json.spec.ts
  playground/tsconfig-json/tsconfig.json
Labels: p1-chore

#18356 chore: combine deps license with same text
  packages/create-vite/LICENSE
  packages/vite/LICENSE.md
  packages/vite/rollupLicensePlugin.ts
Labels: p1-chore

#18243 chore(deps)!: migrate `fast-glob` to `tinyglobby`
  docs/config/dep-optimization-options.md
  docs/config/server-options.md
  docs/guide/features.md
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/resolve.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/server/warmup.ts
  packages/vite/src/node/watch.ts
  playground/backend-integration/package.json
  playground/backend-integration/vite.config.js
  playground/css/package.json
  playground/css/postcss.config.js
  pnpm-lock.yaml
Labels: p1-chore, breaking change

#18376 docs: mention pre-bundle uses esbuild in dev
  docs/guide/why.md
Labels: documentation

#18373 ci: show format diff
  .github/workflows/ci.yml
Labels: p1-chore

#18263 feat: add `environment::listen`
  packages/vite/src/node/server/environment.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/warmup.ts
Labels: enhancement, feat: environment API

#18367 fix: augment hash for CSS files to prevent chromium erroring by loading previous files
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p4-important

#18391 chore: unpin playwright
  package.json
  pnpm-lock.yaml
Labels: dependencies, p1-chore

#18377 docs: clarify `target` in `tsconfig.json`
  docs/guide/features.md
Labels: documentation

#18254 chore(deps): bump TypeScript to 5.6
  package.json
  packages/create-vite/template-lit-ts/package.json
  packages/create-vite/template-lit-ts/tsconfig.json
  packages/create-vite/template-preact-ts/package.json
  packages/create-vite/template-preact-ts/tsconfig.app.json
  packages/create-vite/template-preact-ts/tsconfig.node.json
  packages/create-vite/template-qwik-ts/package.json
  packages/create-vite/template-qwik-ts/tsconfig.app.json
  packages/create-vite/template-qwik-ts/tsconfig.node.json
  packages/create-vite/template-react-ts/package.json
  packages/create-vite/template-react-ts/tsconfig.app.json
  packages/create-vite/template-react-ts/tsconfig.node.json
  packages/create-vite/template-solid-ts/package.json
  packages/create-vite/template-solid-ts/tsconfig.app.json
  packages/create-vite/template-solid-ts/tsconfig.node.json
  packages/create-vite/template-svelte-ts/package.json
  packages/create-vite/template-svelte-ts/tsconfig.node.json
  packages/create-vite/template-vanilla-ts/package.json
  packages/create-vite/template-vanilla-ts/tsconfig.json
  packages/create-vite/template-vue-ts/package.json
  packages/create-vite/template-vue-ts/tsconfig.app.json
  packages/create-vite/template-vue-ts/tsconfig.node.json
  packages/vite/src/module-runner/runner.ts
  packages/vite/tsconfig.check.json
  pnpm-lock.yaml
Labels: dependencies

#18390 fix(cli): `--watch` should not override `build.watch` options
  packages/vite/src/node/cli.ts
Labels: p3-minor-bug

#18375 docs: clarify where it applies for each config options
  docs/config/build-options.md
  docs/config/dep-optimization-options.md
  docs/config/preview-options.md
  docs/config/server-options.md
  docs/config/shared-options.md
  docs/config/ssr-options.md
  docs/config/worker-options.md
Labels: documentation

#18394 refactor(resolve): remove `tryEsmOnly` flag
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/fetchModule.ts
Labels: p1-chore

#18382 feat: add .git to deny list by default
  docs/config/server-options.md
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have, feat: dev

#18366 chore(create-vite): mark template files as CC0
  packages/create-vite/LICENSE
  packages/create-vite/build.config.ts
  packages/vite/rollupLicensePlugin.ts
Labels: p1-chore, feat: create-vite

#18357 docs(backend-integration): add an example `importedChunks`
  docs/guide/backend-integration.md
Labels: documentation

#18329 fix(ssr): `this` in exported function should be `undefined`
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/no-this/importee.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/no-this/importer.js
  packages/vite/src/node/ssr/runtime/__tests__/server-runtime.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: feat: ssr, p2-edge-case

#18397 docs: reload due to gsap and shiki
  docs/.vitepress/config.ts
Labels: documentation

#18406 chore: specify TypeScript version with `~`
  package.json
  packages/create-vite/template-lit-ts/package.json
  packages/create-vite/template-preact-ts/package.json
  packages/create-vite/template-qwik-ts/package.json
  packages/create-vite/template-react-ts/package.json
  packages/create-vite/template-solid-ts/package.json
  packages/create-vite/template-svelte-ts/package.json
  packages/create-vite/template-vanilla-ts/package.json
  packages/create-vite/template-vue-ts/package.json
  pnpm-lock.yaml
Labels: p1-chore

#18414 fix(css): don't transform sass function calls with namespace
  packages/vite/src/node/plugins/css.ts
  playground/css-sourcemap/__tests__/css-sourcemap.spec.ts
  playground/css-sourcemap/imported.sass
  playground/css-sourcemap/vite.config.js
  playground/css/nested/_index.scss
  playground/css/sass.scss
  playground/css/scss-dir/main.scss
  playground/css/scss-proxy-dep/index.scss
  playground/css/vite.config-sass-modern.js
  playground/css/vite.config.js
Labels: feat: css, p2-edge-case

#18410 feat: add custom Angular variants
  packages/create-vite/src/index.ts
Labels: p2-nice-to-have

#18407 feat(create-vite): update to svelte 5
  packages/create-vite/src/index.ts
  packages/create-vite/template-preact-ts/src/main.tsx
  packages/create-vite/template-preact/src/main.jsx
  packages/create-vite/template-qwik-ts/src/main.tsx
  packages/create-vite/template-qwik/src/main.jsx
  packages/create-vite/template-react-ts/src/main.tsx
  packages/create-vite/template-react/src/main.jsx
  packages/create-vite/template-solid-ts/src/index.tsx
  packages/create-vite/template-solid/src/index.jsx
  packages/create-vite/template-svelte-ts/package.json
  packages/create-vite/template-svelte-ts/src/lib/Counter.svelte
  packages/create-vite/template-svelte-ts/src/main.ts
  packages/create-vite/template-svelte/package.json
  packages/create-vite/template-svelte/src/lib/Counter.svelte
  packages/create-vite/template-svelte/src/main.js
Labels: enhancement, feat: create-vite

#18358 feat: enable dependencies discovery and pre-bundling in ssr environments
  packages/vite/src/node/external.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/environment.ts
  packages/vite/src/node/ssr/fetchModule.ts
  packages/vite/src/node/ssr/index.ts
  playground/environment-react-ssr/__tests__/basic.spec.ts
  playground/environment-react-ssr/__tests__/environment-react-ssr.spec.ts
  playground/environment-react-ssr/package.json
  playground/environment-react-ssr/vite.config.ts
  pnpm-lock.yaml
Labels: p3-significant, feat: environment API

#18424 docs: center last projects row in landing
  docs/.vitepress/theme/components/landing/3. frameworks-section/FrameworksSection.vue
Labels: documentation

#18209 refactor!: bump minimal terser version to 5.16.0
  docs/config/build-options.md
  packages/vite/package.json
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
Labels: p1-chore, breaking change

#18432 refactor: use builder in `build`
  docs/guide/api-environment-frameworks.md
  docs/guide/cli.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/config.ts
Labels: feat: environment API

#18303 feat(json)!: add `json.stringify: 'auto'` and make that the default
  docs/config/shared-options.md
  packages/vite/src/node/__tests__/plugins/json.spec.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/json.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/transformRequest.ts
  playground/json/__tests__/ssr/json-ssr.spec.ts
Labels: p2-nice-to-have, breaking change

#18444 docs: add some migration guide for v6
  docs/guide/migration.md
Labels: documentation

#16356 fix(ssr): preserve source maps for hoisted imports (fix #16355)
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p3-downstream-blocker, feat: ssr, feat: sourcemap

#18445 fix(preview): set resolvedUrls null after close
  docs/guide/api-javascript.md
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug

#18446 test: fix test conflict
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
Labels: test

#18443 fix(dev): prevent double URL encoding in server.open on macOS
  packages/vite/src/node/server/openBrowser.ts
Labels: p2-edge-case, feat: dev

#18435 fix(create-vite): add tsBuildInfoFile option
  packages/create-vite/template-preact-ts/tsconfig.app.json
  packages/create-vite/template-preact-ts/tsconfig.node.json
  packages/create-vite/template-qwik-ts/tsconfig.app.json
  packages/create-vite/template-qwik-ts/tsconfig.node.json
  packages/create-vite/template-react-ts/tsconfig.app.json
  packages/create-vite/template-react-ts/tsconfig.node.json
  packages/create-vite/template-solid-ts/tsconfig.app.json
  packages/create-vite/template-solid-ts/tsconfig.node.json
  packages/create-vite/template-vue-ts/tsconfig.app.json
  packages/create-vite/template-vue-ts/tsconfig.node.json
Labels: p4-important, feat: create-vite

#15637 fix!: default `build.cssMinify` to `'esbuild'` for SSR
  docs/config/build-options.md
  docs/guide/migration.md
  packages/vite/src/node/build.ts
Labels: has workaround, p2-nice-to-have, breaking change

#18240 refactor: use `originalFileNames`/`names`
  package.json
  packages/vite/package.json
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/manifest.ts
  packages/vite/src/node/plugins/worker.ts
  pnpm-lock.yaml
Labels: p1-chore

#18440 feat(css)!: load postcss config within workspace root only
  docs/config/shared-options.md
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-nice-to-have, breaking change

#18449 fix(ssr): inject identity function at the top
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p4-important, feat: ssr

#17891 fix: use websocket to test server liveness before client reload
  packages/vite/src/client/client.ts
  packages/vite/src/node/server/ws.ts
  playground/client-reload/__tests__/client-reload.spec.ts
  playground/client-reload/__tests__/serve.ts
  playground/client-reload/index.html
  playground/client-reload/package.json
  playground/client-reload/vite.config.ts
  playground/js-sourcemap/test-ssr-dev.js
  playground/ssr-html/test-network-imports.js
  playground/ssr-html/test-stacktrace-runtime.js
  playground/ssr-html/test-stacktrace.js
  playground/test-utils.ts
  pnpm-lock.yaml
Labels: feat: hmr, p3-minor-bug

#17937 feat(css)!: change default sass api to modern/modern-compiler
  docs/config/shared-options.md
  docs/guide/migration.md
  packages/vite/src/node/plugins/css.ts
  playground/backend-integration/vite.config.js
  playground/css-sourcemap/vite.config.js
  playground/css/vite.config.js
  playground/multiple-entrypoints/vite.config.js
Labels: breaking change, p3-significant

#18455 fix: return the same instance of ModuleNode for the same EnvironmentModuleNode
  packages/vite/src/node/server/mixedModuleGraph.ts
Labels: p3-downstream-blocker, feat: environment API

#18456 docs: migration guide for plugin-commonjs upgrade
  docs/guide/migration.md
Labels: documentation

#18133 fix(manifest): non entry CSS chunk src was wrong
  docs/guide/backend-integration.md
  packages/vite/src/node/plugins/manifest.ts
Labels: p2-edge-case

#18458 refactor(css): hide internal preprocessor types and expose types used for options
  packages/vite/package.json
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/types/internal/cssPreprocessorOptions.d.ts
Labels: p1-chore

#18459 fix(css): make sass types work with sass-embedded
  eslint.config.js
  package.json
  packages/vite/types/internal/cssPreprocessorOptions.d.ts
  pnpm-lock.yaml
Labels: feat: css, p3-minor-bug

#18462 fix: handle warmup glob hang
  packages/vite/package.json
  packages/vite/src/node/server/warmup.ts
  playground/backend-integration/package.json
  playground/css/package.json
  pnpm-lock.yaml
Labels: p3-minor-bug

#18411 fix: set scripts imported by HTML moduleSideEffects=true
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/resolve.ts
Labels: p2-to-be-discussed

#18379 feat: allow custom `console` in `createLogger`
  packages/vite/src/node/logger.ts
Labels: p2-nice-to-have

#15235 chore(deps)!: update postcss-load-config to v6
  .npmrc
  docs/guide/migration.md
  eslint.config.js
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/rollup.config.ts
  playground/tailwind/package.json
  playground/tailwind/postcss.config.ts
  playground/tailwind/tailwind.config.ts
  pnpm-lock.yaml
Labels: p3-minor-bug, breaking change

#18460 feat(css): add more stricter typing of lightningcss
  eslint.config.js
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/types/lightningcss.d.ts
  packages/vite/types/internal/lightningcssOptions.d.ts
Labels: feat: css, p2-nice-to-have

#18211 chore: pkg.pr.new preview with label and comment
  .github/workflows/preview-release.yml
  .github/workflows/publish-commit.yml
Labels: trigger: preview

#18475 refactor: top-level createEnvironment is client-only
  packages/vite/src/node/config.ts
Labels: feat: environment API

#18474 docs: top-level client environment config
  docs/guide/api-environment.md
Labels: documentation, feat: environment API

#18480 fix(module-runner): delay function eval until module runner instantiation
  packages/vite/src/module-runner/esmEvaluator.ts
  packages/vite/src/shared/utils.ts
Labels: feat: environment API

#18422 feat!: support `file://` resolution
  packages/vite/src/node/__tests__/fixtures/file-url/entry.js
  packages/vite/src/node/__tests__/fixtures/file-url/package.json
  packages/vite/src/node/__tests__/resolve.spec.ts
  packages/vite/src/node/plugins/resolve.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/file-url.js
  playground/resolve/index.html
  playground/resolve/vite.config.js
  pnpm-lock.yaml
Labels: breaking change, p3-significant

#18437 fix(config): remove error if require resolve to esm
  docs/guide/troubleshooting.md
  packages/vite/src/node/config.ts
Labels: p3-downstream-blocker

#17369 fix: consider URLs with any protocol to be external
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/utils.ts
Labels: p2-to-be-discussed

#18453 feat!: update to chokidar v4
  docs/config/server-options.md
  docs/guide/api-javascript.md
  package.json
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/scripts/dev.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/server/__tests__/watcher.spec.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/watch.ts
  packages/vite/src/types/chokidar.d.ts
  patches/chokidar@3.6.0.patch
  playground/hmr/__tests__/hmr.spec.ts
  pnpm-lock.yaml
Labels: breaking change, p3-significant

#18517 build: reduce package size
  package.json
  packages/vite/LICENSE.md
  packages/vite/rollup.config.ts
  patches/acorn@8.14.0.patch
  pnpm-lock.yaml
Labels: p1-chore

#18514 docs: update fs.deny default in JSDoc
  packages/vite/src/node/server/index.ts
Labels: documentation

#18491 docs: missing changes guides
  docs/changes/per-environment-apis.md
  docs/changes/shared-plugins-during-build.md
  packages/vite/src/node/server/index.ts
Labels: documentation, feat: environment API

#18515 fix: `define` in environment config was not working
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugins/clientInjections.ts
  packages/vite/src/node/plugins/define.ts
  playground/define/__tests__/define.spec.ts
  playground/define/index.html
  playground/define/vite.config.js
Labels: p3-minor-bug, feat: environment API

#18516 docs: add jsdocs to flags in BuilderOptions
  packages/vite/src/node/build.ts
Labels: documentation

#18494 feat(html): support `vite-ignore` attribute to opt-out of processing
  docs/guide/features.md
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/html/__tests__/html.spec.ts
  playground/html/index.html
  playground/html/vite.config.js
Labels: feat: html, p3-significant

#18488 feat(lib)!: use package name for css output file name
  docs/config/build-options.md
  docs/guide/build.md
  docs/guide/migration.md
  packages/vite/src/node/__tests__/plugins/css.spec.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/utils.ts
  playground/lib/__tests__/lib.spec.ts
  playground/lib/__tests__/serve.ts
  playground/lib/src/css-entry-1.js
  playground/lib/src/css-entry-2.js
  playground/lib/src/entry-1.css
  playground/lib/src/entry-2.css
  playground/lib/vite.css-code-split.config.js
  playground/lib/vite.css-multi-entry.config.js
  playground/lib/vite.css-single-entry.config.js
Labels: feat: css, feat: library mode, breaking change, p3-significant

#17922 fix(css)!: remove default import in ssr dev
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/ssr/runtime/__tests__/server-runtime.spec.ts
Labels: feat: css, feat: ssr

#18289 feat: log complete config in debug mode
  packages/vite/src/node/config.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have

#18503 fix: use picomatch to align with tinyglobby
  package.json
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/optimizer/resolve.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  pnpm-lock.yaml
Labels: p2-edge-case

#18070 feat!: proxy bypass with WebSocket
  packages/vite/src/node/server/middlewares/proxy.ts
Labels: p2-edge-case, regression, breaking change

#18518 chore: fix moduleSideEffects in build script on Windows
  packages/vite/rollup.config.ts
Labels: p1-chore

#18519 docs: migration guide for #18070
  docs/guide/migration.md
Labels: documentation

#18194 fix: asset `new URL(,import.meta.url)` match
  packages/vite/src/node/__tests__/plugins/assetImportMetaUrl.spec.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
Labels: p3-minor-bug

#17857 fix(less): prevent rebasing `@import url(...)`
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/index.html
  playground/css/less/components/form.less
  playground/css/less/ommer.less
Labels: feat: css, p3-minor-bug

#18522 fix(scss): improve error logs
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-edge-case

#18524 refactor: client-only top-level warmup
  packages/vite/src/node/config.ts
Labels: feat: environment API

#18530 fix(lib): only resolve css bundle name if have styles
  packages/vite/src/node/plugins/css.ts
Labels: p3-minor-bug, feat: library mode

#18531 ci: use Node 22 for macOS and Windows CI
  .github/workflows/ci.yml
Labels: p1-chore

#18506 fix: allow nested dependency selector to be used for `optimizeDeps.include` for SSR
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/optimizer/resolve.ts
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug

#11138 feat(html)!: support more asset sources
  docs/guide/features.md
  packages/vite/src/node/__tests__/assetSource.spec.ts
  packages/vite/src/node/assetSource.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: feat: html, p2-nice-to-have, breaking change

#18395 feat(resolve)!: allow removing conditions
  docs/config/shared-options.md
  docs/config/ssr-options.md
  docs/guide/migration.md
  packages/vite/src/node/__tests__/environment.spec.ts
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/index.custom2.js
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/index.custom3.js
  packages/vite/src/node/__tests__/fixtures/test-dep-conditions/package.json
  packages/vite/src/node/baseEnvironment.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/external.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/packages.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/define.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/fetchModule.ts
  packages/vite/src/node/ssr/index.ts
  packages/vite/src/node/utils.ts
  playground/resolve/vite.config.js
  playground/ssr-conditions/vite.config.js
  playground/ssr-webworker/vite.config.js
Labels: breaking change, p3-significant, feat: environment API
