Repository vitejs/vite, pull requests merged in 2024-02, with the labels that each got.

#15746 fix: scan entries when the root is in node_modules
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-downstream-blocker :hammer:

#15761 fix(config): improved warning when root path includes bad characters
  .github/workflows/ci.yml
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have :cake:

#15828 fix: disable fs.cachedChecks for custom watch ignore patterns
  packages/vite/src/node/fsUtils.ts
  packages/vite/src/node/server/index.ts
Labels: p3-minor-bug :hammer:

#15831 fix: pass `customLogger` to `loadConfigFromFile` (fix #15824)
  docs/guide/api-javascript.md
  packages/vite/src/node/config.ts
Labels: p3-minor-bug :hammer:

#15837 refactor: remove `vite build --force`
  docs/guide/cli.md
  packages/vite/src/node/cli.ts
Labels: p2-nice-to-have :cake:, feat: deps optimizer, feat: build

#15840 chore: post 5.1 release edits
  docs/blog/announcing-vite5-1.md
  packages/vite/CHANGELOG.md
Labels: p1-chore :broom:

#15845 fix: `asset-import-meta-url` plugin errored with Maximum call stack size exceeded
  pnpm-lock.yaml
Labels: dependencies, p3-minor-bug :hammer:

#15846 fix: empty CSS file was output when only .css?url is used
  packages/vite/src/node/plugins/css.ts
Labels: bug, feat: css, p2-nice-to-have :cake:

#15813 docs: add not about disabling the cache to the performance guide
  docs/guide/performance.md
Labels: documentation

#15866 fix(worker): support UTF-8 encoding in inline workers (fixes #12117)
  packages/vite/src/node/plugins/worker.ts
  playground/worker/__tests__/es/worker-es.spec.ts
  playground/worker/index.html
  playground/worker/my-worker.ts
  playground/worker/worker/main-module.js
Labels: p3-minor-bug :hammer:, feat: web workers

#15799 docs(features): clarify sentences about JSX usage
  docs/guide/features.md
Labels: documentation

#15882 chore: lint
  docs/config/dep-optimization-options.md
Labels: p1-chore :broom:

#15883 chore: prettier dep optimization
  docs/config/dep-optimization-options.md
Labels: p1-chore :broom:

#15884 docs: remove unneeded zero width space in titles
  docs/releases.md
Labels: documentation

#15711 fix(build): do not output build time when build fails
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/reporter.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#15885 chore: update license file
  packages/vite/LICENSE.md
Labels: p1-chore :broom:

#15892 docs: remove vite rollup plugins from resources
  docs/.vitepress/config.ts
Labels: documentation

#15893 docs: remove links to vite-rollup-plugins
  docs/guide/api-plugin.md
  docs/guide/using-plugins.md
Labels: documentation

#15904 refactor(runtime): minor tweaks
  docs/guide/ssr.md
  packages/vite/src/node/ssr/fetchModule.ts
  packages/vite/src/node/ssr/runtime/moduleCache.ts
  packages/vite/src/node/ssr/runtime/runtime.ts
  playground/test-utils.ts
Labels: p1-chore :broom:, feat: runtime

#15914 refactor(runtime): seal ES module namespace object instead of feezing
  packages/vite/src/node/ssr/runtime/__tests__/server-runtime.spec.ts
  packages/vite/src/node/ssr/runtime/esmRunner.ts
Labels: p1-chore :broom:, feat: runtime

#15919 fix: cachedTransformMiddleware for direct css requests
  packages/vite/src/node/server/middlewares/transform.ts
Labels: feat: css, p3-minor-bug :hammer:, regression, feat: dev

#15922 docs: complete team social links
  docs/_data/team.js
Labels: documentation

#15920 fix: fs cached checks disabled by default for yarn pnp
  packages/vite/src/node/fsUtils.ts
Labels: p3-minor-bug :hammer:, feat: dev

#15927 docs(contributing): convert diagrams
  .github/issue-workflow-dark.png
  .github/issue-workflow.excalidraw
  .github/issue-workflow.png
  .github/pr-workflow-dark.png
  .github/pr-workflow.excalidraw
  .github/pr-workflow.png
  CONTRIBUTING.md
Labels: documentation

#15969 chore: review team members
  docs/_data/team.js
Labels: documentation

#15905 fix: srcSet with optional descriptor
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug :hammer:

#15979 fix(watch): build watch fails when outDir is empty string
  packages/vite/src/node/watch.ts
Labels: p3-minor-bug :hammer:

#15983 fix: resolve directory correctly when `fs.cachedChecks: true`
  packages/vite/src/node/fsUtils.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/index.html
  playground/resolve/non-normalized.js
  playground/resolve/vite.config.js
Labels: p3-minor-bug :hammer:, regression

#15985 fix(css): import using imports field in CS was not resolved
  package.json
  patches/postcss-import@16.0.1.patch
  playground/css/__tests__/css.spec.ts
  playground/css/imports-field.css
  playground/css/imports-imports-field.css
  playground/css/index.html
  playground/css/main.js
  playground/css/package.json
  pnpm-lock.yaml
Labels: feat: css, p3-minor-bug :hammer:, regression

#15995 feat(create-vite): add custom remix option for React
  packages/create-vite/src/index.ts
Labels: p2-nice-to-have :cake:, feat: create-vite

#15766 perf: remove unnecessary regex s modifier
  packages/vite/src/client/client.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/ssr/runtime/utils.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have :cake:

#15982 fix(create-vite): remove tsc command from qwik template
  packages/create-vite/template-qwik/package.json
Labels: p3-minor-bug :hammer:, feat: create-vite

#15732 fix: `__vite__mapDeps` code injection
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
  playground/js-sourcemap/after-preload-dynamic-hashbang.js
  playground/js-sourcemap/index.html
  playground/js-sourcemap/vite.config.js
Labels: p3-minor-bug, regression

#15853 fix: optimizeDeps.entries with literal-only pattern(s)
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-downstream-blocker, feat: dev

#15997 chore: update pr review diagram
  CONTRIBUTING.md
Labels: p1-chore

#15206 fix(scanner): respect `experimentalDecorators: true`
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/esbuild.ts
  playground/tsconfig-json/__tests__/tsconfig-json.spec.ts
  playground/tsconfig-json/src/decorator.ts
Labels: p3-minor-bug, regression

#15988 fix(plugin-legacy): replace `esbuild-plugin-browserslist` with `browserslist-to-esbuild`
  packages/plugin-legacy/package.json
  packages/plugin-legacy/src/index.ts
  pnpm-lock.yaml
Labels: plugin: legacy, p2-nice-to-have

#16031 fix(create-vite): ts error in the svelte-ts template
  packages/create-vite/template-svelte-ts/src/main.ts
Labels: p3-minor-bug, feat: create-vite

#16010 fix: normalize literal-only entry pattern
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug

#16055 fix: output correct error for empty import specifier
  packages/vite/src/node/plugins/importAnalysis.ts
Labels: p2-edge-case
