Repository vitejs/vite, pull requests merged in 2024-08, with the labels that each got.

#16083 fix: `build.modulePreload.resolveDependencies` is optimizable
  docs/config/build-options.md
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p3-minor-bug

#17856 fix(lightningcss): search for assets with correct base path
  packages/vite/src/node/plugins/css.ts
  playground/css-lightningcss/__tests__/css-lightningcss.spec.ts
  playground/css-lightningcss/imported.css
  playground/css-lightningcss/index.html
  playground/css-lightningcss/nested/nested.css
Labels: feat: css, has workaround, p3-minor-bug

#17862 docs: reload after invalidate
  docs/guide/api-plugin.md
Labels: documentation

#17865 refactor: remove `handleHotUpdate` from watch-package-data plugin
  packages/vite/src/node/packages.ts
Labels: p1-chore

#17846 fix(worker): handle self reference url worker in dependency for build
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  playground/worker/__tests__/es/worker-es.spec.ts
  playground/worker/__tests__/iife/worker-iife.spec.ts
  playground/worker/__tests__/sourcemap-hidden/worker-sourcemap-hidden.spec.ts
  playground/worker/__tests__/sourcemap-inline/worker-sourcemap-inline.spec.ts
  playground/worker/__tests__/sourcemap/worker-sourcemap.spec.ts
  playground/worker/dep-self-reference-url-worker/index.js
  playground/worker/dep-self-reference-url-worker/package.json
  playground/worker/dep-self-reference-url-worker/worker.js
  playground/worker/index.html
  playground/worker/package.json
  playground/worker/vite.config-iife.js
  playground/worker/worker/main-module.js
  pnpm-lock.yaml
Labels: p2-edge-case, feat: web workers

#16084 fix: resolve relative URL generated by `renderBuiltUrl` passed to module preload
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  playground/preload/__tests__/resolve-deps/preload-resolve-deps.spec.ts
  playground/preload/package.json
Labels: has workaround, p2-edge-case

#17866 chore: remove stale TODOs
  packages/plugin-legacy/src/index.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/ssr/ssrManifestPlugin.ts
Labels: p1-chore

#17864 refactor: use nanoid instead of copying it
  packages/vite/package.json
  packages/vite/src/module-runner/runnerTransport.ts
  pnpm-lock.yaml
Labels: p1-chore

#17886 test: test `server.origin`
  playground/backend-integration/__tests__/backend-integration.spec.ts
  playground/backend-integration/vite.config.js
  playground/tailwind/vite.config.ts
  playground/test-utils.ts
Labels: p1-chore, test

#17863 docs: update misc
  docs/.vitepress/config.ts
  docs/changes/hotupdate-hook.md
  docs/changes/this-environment-in-hooks.md
  docs/guide/api-vite-environment.md
  docs/public/_redirects
Labels: documentation

#17861 docs: reload after invalidate
  docs/changes/hotupdate-hook.md
  docs/guide/api-plugin.md
  docs/guide/api-vite-environment.md
Labels: documentation

#17913 test: fix backend-integration build test flaky fail
  playground/backend-integration/vite.config.js
Labels: p1-chore, test

#17969 refactor: simplify some code and reduce diff
  packages/vite/src/module-runner/types.ts
  packages/vite/src/module-runner/utils.ts
  packages/vite/src/node/baseEnvironment.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/esbuild.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  packages/vite/src/shared/ssrTransform.ts
Labels: p1-chore
