Repository vitejs/vite, pull requests merged in 2025-01, with the labels that each got.

#19080 docs: make SSR page easier to be found
  docs/guide/ssr.md
Labels: documentation

#19108 fix: build time display 7m 60s
  packages/vite/src/node/utils.ts
Labels: p2-edge-case

#19121 docs: capitalize title in sidebar
  docs/.vitepress/config.ts
Labels: documentation

#19059 fix: don't resolve URL starting with double slash
  packages/vite/src/node/server/middlewares/static.ts
  playground/assets-sanitize/__tests__/assets-sanitize.spec.ts
Labels: p2-edge-case, feat: dev

#19174 fix: resolve.conditions in ResolvedConfig was `defaultServerConditions`
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
Labels: p3-downstream-blocker, trigger: preview

#19119 fix(optimizer): use correct default install state path for yarn PnP
  packages/vite/src/node/optimizer/index.ts
Labels: p3-minor-bug, feat: deps optimizer

#19193 fix: avoid SSR HMR for HTML files
  packages/vite/src/node/server/hmr.ts
Labels: p3-minor-bug, feat: environment API

#19176 docs: unify `__dirname` usage
  docs/guide/api-environment-frameworks.md
  docs/guide/build.md
Labels: documentation

#19246 fix: `preview.allowedHosts` with specific values was not respected
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/hostCheck.ts
  packages/vite/src/node/server/ws.ts
Labels: has workaround, p3-minor-bug

#19271 docs: fix `preview.cors` description
  docs/config/preview-options.md
Labels: documentation

#18855 feat: add support for `.jxl`
  packages/vite/client.d.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/asset.ts
Labels: p2-nice-to-have

#18637 feat: use module runner to import the config
  docs/config/index.md
  docs/guide/cli.md
  packages/vite/index.cjs
  packages/vite/src/module-runner/esmEvaluator.ts
  packages/vite/src/node/__tests__/fixtures/runner-import/basic.ts
  packages/vite/src/node/__tests__/fixtures/runner-import/cjs.js
  packages/vite/src/node/__tests__/fixtures/runner-import/dynamic-import-dep.ts
  packages/vite/src/node/__tests__/fixtures/runner-import/dynamic-import.ts
  packages/vite/src/node/__tests__/fixtures/runner-import/plugin.ts
  packages/vite/src/node/__tests__/fixtures/runner-import/vite.config.outside-pkg-import.mts
  packages/vite/src/node/__tests__/fixtures/runner-import/vite.config.ts
  packages/vite/src/node/__tests__/package.json
  packages/vite/src/node/__tests__/packages/child/index.js
  packages/vite/src/node/__tests__/packages/child/package.json
  packages/vite/src/node/__tests__/packages/parent/index.ts
  packages/vite/src/node/__tests__/packages/parent/package.json
  packages/vite/src/node/__tests__/runnerImport.spec.ts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/ssr/runnerImport.ts
  pnpm-lock.yaml
  vitest.config.ts
Labels: p3-significant, trigger: preview

#18403 feat(optimizer): support bun text lockfile
  packages/vite/src/node/optimizer/index.ts
Labels: p2-nice-to-have, feat: deps optimizer

#18940 feat: support async for proxy.bypass
  packages/vite/src/node/server/middlewares/proxy.ts
  playground/proxy-bypass/__tests__/proxy-bypass.spec.ts
  playground/proxy-bypass/index.html
  playground/proxy-bypass/vite.config.js
Labels: p2-nice-to-have

#18922 feat: support log related functions in dev
  packages/vite/rollup.dts.config.ts
  packages/vite/src/node/server/__tests__/pluginContainer.spec.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: rollup plugin compat, p3-significant

#18730 feat: expose createServerModuleRunnerTransport
  packages/vite/index.cjs
  packages/vite/rollup.dts.config.ts
  packages/vite/src/node/index.ts
Labels: p2-nice-to-have, feat: environment API

#19072 feat(css): add friendly errors for IE hacks that are not supported by lightningcss
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-nice-to-have

#19010 feat(worker): support dynamic worker option fields
  packages/vite/src/node/__tests__/plugins/workerImportMetaUrl.spec.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  playground/worker/worker/main-module.js
Labels: feat: web workers, p3-significant

#19085 feat(reporter): add `wasm` to the compressible assets regex
  packages/vite/src/node/plugins/reporter.ts
Labels: p2-nice-to-have

#18840 fix: correctly resolve hmr dep ids and fallback to url
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/hmr/index.html
  playground/hmr/modules.d.ts
  playground/hmr/vite.config.ts
Labels: feat: hmr, p3-minor-bug, trigger: preview

#18584 feat: add the `builtins` environment `resolve`
  packages/vite/src/node/__tests__/resolve.spec.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/external.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/ssr/fetchModule.ts
  packages/vite/src/node/utils.ts
Labels: p3-significant, feat: environment API

#18889 fix(resolve): support resolving TS files by JS extension specifiers in JS files
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/utils.ts
  playground/resolve/__tests__/resolve.spec.ts
  playground/resolve/index.html
  playground/resolve/ts-extension/index-js.js
Labels: p3-minor-bug, trigger: preview

#18901 fix: make `--force` work for all environments
  packages/vite/src/node/cli.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/server/index.ts
Labels: has workaround, p2-edge-case, feat: deps optimizer

#13757 feat: call Logger for plugin logs in build
  eslint.config.js
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/worker.ts
Labels: enhancement, p2-nice-to-have

#19247 fix(utils): clone `RegExp` values with `new RegExp` instead of `structuredClone` (fix #19245, fix #18875)
  packages/vite/src/node/utils.ts
Labels: p2-edge-case

#18979 fix(hmr): register inlined assets as a dependency of CSS file
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/server/hmr.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/css/css-url-url.css
  playground/assets/css/css-url.css
  playground/assets/index.html
  playground/assets/nested/fragment-bg-hmr.svg
  playground/assets/nested/fragment-bg-hmr2.svg
Labels: feat: css, feat: hmr, p4-important

#19163 feat(create-vite): official starters options naming
  packages/create-vite/src/index.ts
Labels: p2-nice-to-have, feat: create-vite

#19286 docs: rephrase browser range and features relation
  docs/guide/build.md
  docs/guide/index.md
  packages/vite/src/node/constants.ts
  packages/vite/src/node/plugins/esbuild.ts
Labels: documentation

#19290 fix(ssr): pretty print plugin error in `ssrLoadModule`
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p2-nice-to-have, feat: ssr, trigger: preview
