Repository vitejs/vite, pull requests merged in 2025-03, with the labels that each got.

#19481 fix(css): stabilize css module hashes with lightningcss in dev mode
  packages/vite/src/node/__tests__/plugins/css.spec.ts
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-minor-bug

#19532 docs: remove $ prefix from create-vite terminal commands in README
  packages/create-vite/README.md
Labels: documentation

#19534 fix(ssr): named export should overwrite export all
  packages/vite/src/module-runner/runner.ts
  packages/vite/src/node/ssr/__tests__/fixtures/named-overwrite-all/dep1.js
  packages/vite/src/node/ssr/__tests__/fixtures/named-overwrite-all/dep2.js
  packages/vite/src/node/ssr/__tests__/fixtures/named-overwrite-all/main.js
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
Labels: p3-minor-bug, feat: ssr, trigger: preview

#19537 perf: flush compile cache after 10s
  packages/vite/bin/vite.js
Labels: p2-nice-to-have

#19561 fix(reporter): fix incorrect bundle size calculation with non-ASCII characters
  packages/vite/src/node/plugins/reporter.ts
Labels: p2-edge-case

#19567 test: convert resolve-config playground to unit tests
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/__tests__/fixtures/config/loadConfigFromFile/.gitkeep
  playground/resolve-config/__tests__/resolve-config.spec.ts
  playground/resolve-config/__tests__/serve.ts
  playground/resolve-config/package.json
  playground/resolve-config/root/index.js
  playground/resolve-config/root/vite.config.ts
  pnpm-lock.yaml
Labels: p1-chore, test

#19568 test: convert config playground to unit tests
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/__tests__/fixtures/config/entry/imports-field.ts
  packages/vite/src/node/__tests__/fixtures/config/entry/package.json
  packages/vite/src/node/__tests__/fixtures/config/entry/vite.config.import-attributes.ts
  packages/vite/src/node/__tests__/fixtures/config/entry/vite.config.ts
  packages/vite/src/node/__tests__/fixtures/config/native-import/basic.js
  packages/vite/src/node/__tests__/fixtures/config/plugin-module-condition/index.cjs
  packages/vite/src/node/__tests__/fixtures/config/plugin-module-condition/index.d.ts
  packages/vite/src/node/__tests__/fixtures/config/plugin-module-condition/index.mjs
  packages/vite/src/node/__tests__/fixtures/config/plugin-module-condition/module.mjs
  packages/vite/src/node/__tests__/fixtures/config/plugin-module-condition/package.json
  packages/vite/src/node/__tests__/fixtures/config/siblings/foo.ts
  packages/vite/src/node/__tests__/fixtures/config/siblings/package.json
  playground/config/__tests__/config.spec.ts
  playground/config/__tests__/serve.ts
  pnpm-lock.yaml
Labels: p1-chore, test

#19566 feat: add `*?url&no-inline` type and warning for `.json?inline` / `.json?no-inline`
  packages/vite/client.d.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/json.ts
Labels: p2-edge-case

#19554 refactor: restore endsWith usage
  packages/plugin-legacy/src/index.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/middlewares/htmlFallback.ts
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/utils.ts
  playground/fs-serve/root/src/index.html
Labels: p1-chore

#19582 docs: clarify `build.manifest` / `build.ssrManifest` option values
  docs/config/build-options.md
Labels: documentation

#19587 refactor: remove `isBuild` check from preAliasPlugin
  packages/vite/src/node/external.ts
  packages/vite/src/node/plugins/preAlias.ts
Labels: p1-chore

#19588 refactor: use `applyToEnvironment` in internal plugins
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/optimizedDeps.ts
  packages/vite/src/node/plugins/preAlias.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
Labels: p1-chore, trigger: preview

#19599 docs(troubleshooting): mention devcontainers as culprit for hanging requests
  docs/guide/troubleshooting.md
Labels: documentation

#19600 chore: extend commit hash correctly when ambigious with a non-commit object
  packages/vite/CHANGELOG.md
  scripts/extendCommitHash.ts
Labels: p1-chore

#19591 feat(worker): show asset filename conflict warning
  packages/vite/src/node/plugins/worker.ts
  playground/worker/__tests__/es/worker-es.spec.ts
  playground/worker/__tests__/iife/worker-iife.spec.ts
  playground/worker/vite.config-es.js
  playground/worker/vite.config-iife.js
Labels: p2-edge-case, feat: web workers

#19590 fix(css): inline css correctly for double quote use strict
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-edge-case

#19612 fix(ssr): use optional chaining to prevent "undefined is not an object" happening in `ssrRewriteStacktrace`
  packages/vite/src/node/ssr/ssrStacktrace.ts
Labels: feat: ssr, p2-edge-case

#19601 fix(indexHtml): ensure correct URL when querying module graph
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: feat: html, p2-edge-case

#19655 ci(publish): remove provenance workaround
  scripts/publishCI.ts
Labels: p1-chore

#19658 ci: migrate to official app token action
  .github/workflows/ecosystem-ci-trigger.yml
Labels: p1-chore

#19669 test(css): fix cssScopeTo test
  playground/css/__tests__/css.spec.ts
Labels: p1-chore, test

#19660 ci: set permissions to workflows
  .github/workflows/ecosystem-ci-trigger.yml
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/release-tag.yml
  .github/workflows/semantic-pull-request.yml
Labels: p1-chore

#19661 fix(css): parse image-set without space after comma correctly
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: feat: css, p2-edge-case, trigger: preview

#19650 docs: `server.https` option is always an options object
  docs/config/preview-options.md
  docs/config/server-options.md
Labels: documentation

#19677 ci: remove "remove enhancement pending" job
  .github/workflows/issue-labeled.yml
Labels: p1-chore

#19517 feat: warn if `define['process.env']` contains `path` key with a value
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have

#19487 chore(deps): unbundle tinyglobby
  packages/vite/LICENSE.md
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies

#19579 feat(types): type hints for hmr events
  docs/guide/api-hmr.md
  packages/vite/types/customEvent.d.ts
  packages/vite/types/hot.d.ts
Labels: p2-nice-to-have, trigger: preview

#19586 refactor: `[hookName].handler` in plugins
  packages/vite/src/node/__tests__/plugins/assetImportMetaUrl.spec.ts
  packages/vite/src/node/__tests__/plugins/define.spec.ts
  packages/vite/src/node/__tests__/plugins/json.spec.ts
  packages/vite/src/node/__tests__/plugins/workerImportMetaUrl.spec.ts
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/define.ts
  packages/vite/src/node/plugins/dynamicImportVars.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/json.ts
  packages/vite/src/node/plugins/loadFallback.ts
  packages/vite/src/node/plugins/modulePreloadPolyfill.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/plugins/wasm.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
Labels: p1-chore, trigger: preview

#19678 fix(css): scoped css order with non-scoped css
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/treeshake-scoped/another.html
  playground/css/treeshake-scoped/barrel/a-scoped.css
  playground/css/treeshake-scoped/barrel/a.js
  playground/css/treeshake-scoped/barrel/b-scoped.css
  playground/css/treeshake-scoped/barrel/b.js
  playground/css/treeshake-scoped/barrel/index.js
  playground/css/treeshake-scoped/index.html
  playground/css/treeshake-scoped/order/a-scoped.css
  playground/css/treeshake-scoped/order/a.js
  playground/css/treeshake-scoped/order/after.css
  playground/css/treeshake-scoped/order/before.css
  playground/css/vite.config.js
  playground/test-utils.ts
Labels: feat: css, p3-downstream-blocker, trigger: preview

#19573 feat(create-vite): add TanStack Router commands
  packages/create-vite/src/index.ts
Labels: p2-nice-to-have, feat: create-vite

#19680 docs: add rolldown chapter
  docs/.vitepress/config.ts
  docs/guide/performance.md
  docs/guide/rolldown.md
Labels: documentation

#19646 fix(optimizer): fix incorrect picomatch usage in filter()
  packages/vite/src/node/optimizer/resolve.ts
Labels: p3-minor-bug, regression, feat: deps optimizer

#19683 feat(config): improve bad character warning
  docs/guide/troubleshooting.md
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
Labels: p2-nice-to-have

#19281 feat(legacy): add sourcemapBaseUrl support
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy

#19071 feat(css): support preprocessor with lightningcss
  packages/vite/src/node/plugins/css.ts
  playground/css-sourcemap/__tests__/lightningcss/lightningcss.spec.ts
  playground/css-sourcemap/package.json
  playground/css-sourcemap/vite.config-lightningcss.js
  playground/css/__tests__/css.spec.ts
  playground/css/__tests__/lightningcss/lightningcss.spec.ts
  playground/css/__tests__/tests.ts
  playground/css/index.html
  playground/css/lightningcss-plugins.js
  playground/css/package.json
  playground/css/postcss.config.js
  playground/css/vite.config-lightningcss.js
  playground/vitestGlobalSetup.ts
  pnpm-lock.yaml
Labels: feat: css, p3-significant

#19702 fix: fs raw query with query separators
  packages/vite/src/node/server/middlewares/transform.ts
  playground/fs-serve/__tests__/fs-serve.spec.ts
  playground/fs-serve/root/src/index.html
Labels: trigger: preview

#19703 fix: backport #19702, fs raw query with query separators
  packages/vite/src/node/server/middlewares/transform.ts
  playground/fs-serve/__tests__/fs-serve.spec.ts
  playground/fs-serve/root/src/index.html
Labels: trigger: preview

#19704 fix: backport #19702, fs raw query with query separators
  packages/vite/src/node/server/middlewares/transform.ts
  playground/fs-serve/__tests__/fs-serve.spec.ts
  playground/fs-serve/root/src/index.html
Labels: trigger: preview

#19701 fix: add back `.mts` to default `resolve.extensions`
  packages/vite/src/node/config.ts
Labels: p3-minor-bug, trigger: preview

#19077 feat(types): make ImportMetaEnv strictly available
  docs/guide/env-and-mode.md
  packages/vite/src/node/__tests_dts__/typeOptions.ts
  packages/vite/types/importMeta.d.ts
Labels: p2-to-be-discussed, trigger: preview

#19602 feat: implement hook filters
  packages/vite/src/node/__tests__/plugins/index.spec.ts
  packages/vite/src/node/__tests__/plugins/pluginFilter.spec.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/pluginFilter.ts
  packages/vite/src/node/plugins/worker.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: p2-nice-to-have, trigger: preview

#19664 feat(experimental): add fetchable environment interface
  docs/guide/api-environment-frameworks.md
  eslint.config.js
  packages/vite/index.cjs
  packages/vite/src/node/index.ts
  packages/vite/src/node/server/environments/fetchableEnvironments.ts
Labels: feat: environment API, trigger: preview

#18983 fix(ssr): hoist export to handle cyclic import better
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/README.md
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/package.json
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test1/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test1/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test1/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test2/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test2/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test2/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test3/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test3/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test3/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test4/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test4/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test4/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test5/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test5/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test5/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test6/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test6/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test6/index.js
  packages/vite/src/node/ssr/runtime/__tests__/server-runtime.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  playground/hmr-ssr/__tests__/hmr-ssr.spec.ts
  playground/hmr-ssr/self-accept-within-circular/c.js
  playground/ssr/__tests__/ssr.spec.ts
  playground/ssr/src/app.js
  playground/ssr/src/circular-import2/a.js
  playground/ssr/src/circular-import2/b.js
  playground/ssr/src/circular-import2/index.js
  pnpm-lock.yaml
  vitest.config.ts
Labels: feat: ssr, trigger: preview

#19557 feat(types): expose `CustomPluginOptionsVite` type
  package.json
  packages/vite/package.json
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/types/metadata.d.ts
  pnpm-lock.yaml
Labels: p2-nice-to-have, trigger: preview

#19735 docs: remove lightningcss preprocessor note
  docs/guide/features.md
Labels: documentation

#19736 fix: align plugin hook filter behavior with pluginutils
  packages/vite/src/node/__tests__/plugins/index.spec.ts
  packages/vite/src/node/__tests__/plugins/pluginFilter.spec.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/pluginFilter.ts
Labels: p3-minor-bug

#19742 docs: fix broken link to shared-plugins-during-build section
  docs/changes/shared-plugins-during-build.md
Labels: documentation

#19760 feat(types): make CustomPluginOptionsVite backward compatible
  packages/vite/types/metadata.d.ts
Labels: p2-edge-case, trigger: preview

#19503 feat(env): add false option for envDir to disable env loading
  docs/config/shared-options.md
  docs/guide/api-javascript.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/env.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/runnerImport.ts
Labels: p2-nice-to-have

#19715 perf: only bundle node version `debug`
  packages/vite/rollup.config.ts
Labels: p2-nice-to-have

#19761 fix: fs check in transform middleware
  packages/vite/src/node/server/middlewares/transform.ts
  playground/fs-serve/__tests__/fs-serve.spec.ts
  playground/fs-serve/root/src/index.html
Labels: trigger: preview
