Repository vitejs/vite, pull requests merged in 2025-02, with the labels that each got.

#19319 test: handle proxy error message
  playground/proxy-bypass/__tests__/proxy-bypass.spec.ts
  playground/proxy-bypass/vite.config.js
Labels: p1-chore, test

#19300 fix(resolve): preserve hash/search of file url
  packages/vite/src/node/__tests__/resolve.spec.ts
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug, feat: ssr

#19318 fix: don't call next middleware if user sent response in proxy.bypass
  packages/vite/src/node/server/middlewares/proxy.ts
Labels: p2-edge-case

#19312 fix(resolve): warn if node-like builtin was imported when `resolve.builtin` is empty
  packages/vite/src/node/__tests__/resolve.spec.ts
  packages/vite/src/node/plugins/resolve.ts
Labels: p3-minor-bug

#19313 fix: use `nodeLikeBuiltins` for `ssr.target: 'webworker'` without `noExternal: true`
  packages/vite/src/node/config.ts
Labels: p3-minor-bug, trigger: preview

#19269 fix(css): less `@plugin` imports of JS files treated as CSS and rebased (fix #19268)
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/less-plugin.less
  playground/css/less-plugin/test.js
  playground/css/main.js
Labels: feat: css, p2-edge-case

#19212 feat: print `port` in the logged error message after failed WS connection with `EADDRINUSE`
  packages/vite/src/node/server/ws.ts
Labels: p2-nice-to-have

#19347 fix: don't call buildStart hooks for `vite optimize`
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-downstream-blocker

#19324 fix: avoid packageJson without name in `resolveLibCssFilename`
  packages/vite/src/node/__tests__/build.spec.ts
  packages/vite/src/node/__tests__/packages/module/package.json
  packages/vite/src/node/__tests__/packages/package.json
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/css.ts
  pnpm-lock.yaml
Labels: p3-minor-bug

#19352 fix: allow expanding env vars in reverse order
  docs/guide/env-and-mode.md
  docs/guide/migration.md
  package.json
  packages/vite/src/node/__tests__/env.spec.ts
  packages/vite/src/node/__tests__/env/.env.development2
  patches/dotenv-expand@12.0.1.patch
  pnpm-lock.yaml
Labels: p3-minor-bug, trigger: preview

#19143 fix(html): fix css disorder when building multiple entry html
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p3-minor-bug, trigger: preview

#19356 fix: avoid builtStart during vite optimize
  packages/vite/src/node/idResolver.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: trigger: preview

#19317 feat: show hosts in cert in CLI
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/utils.ts
Labels: p2-to-be-discussed

#19372 test: isolate less js plugin test
  playground/css/__tests__/css.spec.ts
  playground/css/index.html
  playground/css/less-plugin.less
  playground/css/less-plugin/test.js
Labels: p1-chore, test

#19371 fix(css): run rewrite plugin if postcss plugin exists
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/index.html
  playground/css/main.js
  playground/css/postcss-inject-url.css
  playground/css/postcss.config.js
Labels: feat: css, p2-edge-case, regression

#18941 docs: distinguish the two "env var"s using different words
  docs/config/index.md
  docs/guide/env-and-mode.md
  docs/guide/features.md
Labels: documentation, p2-nice-to-have

#19375 fix(deps): bump tsconfck
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies, p2-edge-case

#19377 docs: add troubleshooting section for path with `*`
  docs/guide/troubleshooting.md
Labels: documentation

#19379 docs: fix anchor name: #mode -> #modes
  docs/config/index.md
Labels: documentation

#19079 fix(legacy): warn if plugin-legacy is passed to `worker.plugins`
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p2-edge-case, feat: web workers

#19378 docs: update security warnings around `server.cors` and `server.allowedHosts`
  docs/config/server-options.md
Labels: documentation

#19381 docs: fix dead link to houdini.how
  docs/guide/assets.md
Labels: documentation

#19397 fix(html): ignore malformed src attrs
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p2-edge-case

#19394 ci: update react-swc plugin version in create-vite by renovate
  .github/renovate.json5
  packages/create-vite/src/index.ts
Labels: p1-chore

#19416 fix: ignore `*.ipv4` address in cert
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/utils.ts
Labels: p2-edge-case

#19415 docs: cleanup features page
  docs/guide/features.md
Labels: documentation

#19404 docs: sunset comparisons page
  docs/.vitepress/config.ts
  docs/blog/announcing-vite2.md
  docs/guide/comparisons.md
  docs/guide/why.md
  docs/public/_redirects
Labels: documentation, p1-chore

#19424 docs: mention pkg.pr.new for unreleased commits
  docs/guide/index.md
Labels: documentation

#19421 docs: framework agnostic features guide
  docs/guide/features.md
Labels: documentation

#19457 refactor: remove custom .jxl mime
  packages/vite/src/node/plugins/asset.ts
Labels: p1-chore

#19467 chore: remove old patch file for sirv
  patches/sirv@3.0.0.patch
Labels: p1-chore

#19389 chore: bump esbuild to 0.25.0
  packages/vite/package.json
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
  pnpm-lock.yaml
Labels: dependencies, trigger: preview

#18808 feat: show `mode` on server start and add env debugger
  packages/vite/src/node/cli.ts
  packages/vite/src/node/env.ts
Labels: p2-nice-to-have

#19475 test: normalize debugId in snapshot
  playground/js-sourcemap/__tests__/js-sourcemap.spec.ts
  playground/test-utils.ts
Labels: p1-chore

#19474 chore(create-vite): remove font family `Inter`
  packages/create-vite/template-lit-ts/src/index.css
  packages/create-vite/template-lit/src/index.css
  packages/create-vite/template-preact-ts/src/index.css
  packages/create-vite/template-preact/src/index.css
  packages/create-vite/template-qwik-ts/src/index.css
  packages/create-vite/template-qwik/src/index.css
  packages/create-vite/template-react-ts/src/index.css
  packages/create-vite/template-react/src/index.css
  packages/create-vite/template-solid-ts/src/index.css
  packages/create-vite/template-solid/src/index.css
  packages/create-vite/template-svelte-ts/src/app.css
  packages/create-vite/template-svelte/src/app.css
  packages/create-vite/template-vanilla-ts/src/style.css
  packages/create-vite/template-vanilla/src/style.css
  packages/create-vite/template-vue-ts/src/style.css
  packages/create-vite/template-vue/src/style.css
Labels: p1-chore, feat: create-vite

#19414 feat: use host url to open browser
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have

#19418 feat(css): allow scoping css to importers exports
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/css.spec.ts
  playground/css/index.html
  playground/css/main.js
  playground/css/treeshake-scoped/a-scoped.css
  playground/css/treeshake-scoped/a.js
  playground/css/treeshake-scoped/another.html
  playground/css/treeshake-scoped/b-scoped.css
  playground/css/treeshake-scoped/b.js
  playground/css/treeshake-scoped/barrel/a-scoped.css
  playground/css/treeshake-scoped/barrel/a.js
  playground/css/treeshake-scoped/barrel/b-scoped.css
  playground/css/treeshake-scoped/barrel/b.js
  playground/css/treeshake-scoped/barrel/index.js
  playground/css/treeshake-scoped/c-scoped.css
  playground/css/treeshake-scoped/c.js
  playground/css/treeshake-scoped/d-scoped.css
  playground/css/treeshake-scoped/d.js
  playground/css/treeshake-scoped/index.html
  playground/css/treeshake-scoped/index.js
  playground/css/vite.config.js
Labels: feat: css, p2-to-be-discussed

#19478 fix(css): temporary add `?.` after `this.getModuleInfo` in `vite:css-post`
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p3-downstream-blocker, trigger: preview

#19476 fix(worker): string interpolation in dynamic worker options
  packages/vite/src/node/__tests__/plugins/workerImportMetaUrl.spec.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
Labels: p2-edge-case, regression, feat: web workers

#19445 feat(create-vite): use `@clack/prompts`
  package.json
  packages/create-vite/LICENSE
  packages/create-vite/package.json
  packages/create-vite/src/index.ts
  patches/@clack__core@0.4.1.patch
  pnpm-lock.yaml
Labels: feat: create-vite

#19507 chore: remove prompts alias
  packages/create-vite/build.config.ts
Labels: p1-chore

#19516 test: add glob import test case
  packages/vite/src/node/__tests__/plugins/importGlob/__snapshots__/fixture.spec.ts.snap
  packages/vite/src/node/__tests__/plugins/importGlob/fixture-a/index.ts
Labels: p1-chore, test

#19515 docs: fix pnpm version in contributing guide
  CONTRIBUTING.md
Labels: p1-chore

#19519 fix(create-vite): make custom command visible
  packages/create-vite/src/index.ts
Labels: p2-edge-case, feat: create-vite
