Repository vitejs/vite, pull requests merged in 2025-06, with the labels that each got.

#20008 feat(create-vite): use more extends in eslint config
  packages/create-vite/template-react-ts/README.md
  packages/create-vite/template-react-ts/eslint.config.js
  packages/create-vite/template-react/eslint.config.js
Labels: p2-nice-to-have, feat: create-vite

#20116 docs: correct environment api stabilization note
  docs/guide/api-environment-frameworks.md
  docs/guide/api-environment-instances.md
  docs/guide/api-environment-plugins.md
  docs/guide/api-environment-runtimes.md
  docs/guide/api-environment.md
Labels: documentation

#20153 docs: correct environment api stabilization note in /docs/changes
  docs/changes/hotupdate-hook.md
  docs/changes/per-environment-apis.md
  docs/changes/this-environment-in-hooks.md
Labels: documentation

#20166 fix(types): prefer sass-embedded types over sass types for `preprocessorOptions.sass` (fix #20150)
  packages/vite/types/internal/cssPreprocessorOptions.d.ts
Labels: feat: css, has workaround, p2-edge-case

#20168 chore: add a way to disable source maps when developing Vite
  CONTRIBUTING.md
  packages/vite/bin/vite.js
  packages/vite/rolldown.config.ts
Labels: p1-chore

#20152 docs(rolldown): add @vitejs/plugin-react-oxc recommendation
  docs/guide/rolldown.md
Labels: documentation

#20188 docs: update @vitejs/plugin-react-swc link in features.md
  docs/guide/features.md
Labels: documentation

#20186 docs: url reference for multiples environments in `this-environment-in-hooks`
  docs/changes/this-environment-in-hooks.md
Labels: documentation

#20193 docs: fix minor grammar issue in `config/build-options`
  docs/config/build-options.md
Labels: documentation

#20205 test: use `getBg` and `getColor`
  playground/assets/__tests__/assets.spec.ts
  playground/assets/__tests__/encoded-base/assets-encoded-base.spec.ts
  playground/assets/__tests__/relative-base/assets-relative-base.spec.ts
  playground/assets/__tests__/runtime-base/assets-runtime-base.spec.ts
  playground/assets/__tests__/url-base/assets-url-base.spec.ts
  playground/dynamic-import/__tests__/dynamic-import.spec.ts
Labels: p1-chore, test

#20208 docs: correct heading level in `ssr-options.md`
  docs/config/ssr-options.md
Labels: documentation

#20206 test: use `expect.poll` instead of `withRetry`/`expectWithRetry`/`untilUpdated`
  playground/alias/__tests__/alias.spec.ts
  playground/assets/__tests__/assets.spec.ts
  playground/backend-integration/__tests__/backend-integration.spec.ts
  playground/cli/__tests__/cli.spec.ts
  playground/csp/__tests__/csp.spec.ts
  playground/css-codesplit/__tests__/css-codesplit.spec.ts
  playground/css-lightningcss/__tests__/css-lightningcss.spec.ts
  playground/css-no-codesplit/__tests__/css-no-codesplit.spec.ts
  playground/css/__tests__/sass-tests.ts
  playground/css/__tests__/tests.ts
  playground/dynamic-import/__tests__/dynamic-import.spec.ts
  playground/environment-react-ssr/__tests__/environment-react-ssr.spec.ts
  playground/glob-import/__tests__/glob-import.spec.ts
  playground/hmr-root/__tests__/hmr-root.spec.ts
  playground/hmr-ssr/__tests__/hmr-ssr.spec.ts
  playground/hmr/__tests__/hmr.spec.ts
  playground/html/__tests__/html.spec.ts
  playground/json/__tests__/csr/json-csr.spec.ts
  playground/legacy/__tests__/legacy.spec.ts
  playground/legacy/__tests__/no-polyfills-no-systemjs/legacy-no-polyfills-no-systemjs.spec.ts
  playground/legacy/__tests__/no-polyfills/legacy-no-polyfills.spec.ts
  playground/lib/__tests__/lib.spec.ts
  playground/multiple-entrypoints/__tests__/multiple-entrypoints.spec.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-missing-deps/__test__/optimize-missing-deps.spec.ts
  playground/proxy-hmr/__tests__/proxy-hmr.spec.ts
  playground/ssr-conditions/__tests__/ssr-conditions.spec.ts
  playground/ssr-deps/__tests__/ssr-deps.spec.ts
  playground/ssr-html/__tests__/ssr-html.spec.ts
  playground/ssr/__tests__/ssr.spec.ts
  playground/tailwind-v3/__test__/tailwind-v3.spec.ts
  playground/tailwind/__test__/tailwind.spec.ts
  playground/test-utils.ts
  playground/transform-plugin/__tests__/tests.ts
  playground/tsconfig-json-load-error/__tests__/tsconfig-json-load-error.spec.ts
  playground/wasm/__tests__/wasm.spec.ts
  playground/worker/__tests__/es/worker-es.spec.ts
  playground/worker/__tests__/iife/worker-iife.spec.ts
  playground/worker/__tests__/relative-base-iife/worker-relative-base-iife.spec.ts
  playground/worker/__tests__/relative-base/worker-relative-base.spec.ts
  vitest.config.e2e.ts
Labels: p1-chore, test

#20222 feat: apply some middlewares before `configureServer` hook
  packages/vite/src/node/server/index.ts
Labels: breaking change, trigger: preview

#20224 feat: apply some middlewares before `configurePreviewServer` hook
  packages/vite/src/node/preview.ts
Labels: p2-nice-to-have, breaking change

#20244 perf(utils): improve performance of `numberToPos`
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/ssr/__tests__/__snapshots__/ssrLoadModule.spec.ts.snap
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have

#20256 chore: update onlyBuiltDependencies
  package.json
Labels: p1-chore

#20276 chore: remove rolldown from onlyBuiltDependencies
  package.json
Labels: p1-chore

#20239 docs: per-environment state in plugins
  docs/guide/api-environment-plugins.md
Labels: documentation, feat: environment API

#20274 feat(types): use terser types from terser package
  eslint.config.js
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugins/terser.ts
  packages/vite/src/types/terser.d.ts
  packages/vite/types/internal/terserOptions.d.ts
Labels: p2-nice-to-have, trigger: preview

#20277 fix(module-runner): expose `normalizeModuleId`
  packages/vite/src/module-runner/evaluatedModules.ts
  packages/vite/src/module-runner/index.ts
Labels: feat: environment API

#19895 chore: move all pnpm settings to `pnpm-workspace.yaml`
  .npmrc
  package.json
  pnpm-workspace.yaml
Labels: p1-chore

#20243 fix(types): add a global interface for Worker
  packages/vite/tsconfig.check.json
  packages/vite/types/importGlob.d.ts
Labels: has workaround, p2-edge-case

#20291 docs: add vite 6 docs to version dropdown
  docs/.vitepress/config.ts
Labels: documentation

#20309 docs: update watch option desc
  docs/config/server-options.md
Labels: documentation

#20300 fix(css): skip resolving resolved paths in sass
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/sass-tests.ts
  playground/css/index.html
  playground/css/nested/replacement-alias.scss
  playground/css/sass.scss
  playground/css/vite.config.js
Labels: feat: css, p3-minor-bug, regression
