Repository vitejs/vite, pull requests merged in 2025-07, with the labels that each got.

#20310 chore: group commits by category in changelog
  package.json
  packages/create-vite/CHANGELOG.md
  packages/plugin-legacy/CHANGELOG.md
  packages/vite/CHANGELOG.md
  pnpm-lock.yaml
  scripts/extendCommitHash.ts
  scripts/release.ts
  scripts/releaseUtils.ts
Labels: p1-chore

#20353 docs: update environment api as release candidate
  docs/changes/index.md
  docs/guide/api-environment-frameworks.md
  docs/guide/api-environment-instances.md
  docs/guide/api-environment-plugins.md
  docs/guide/api-environment-runtimes.md
  docs/guide/api-environment.md
Labels: documentation

#20364 docs: mention `bun.lock` for lockfile
  docs/guide/dep-pre-bundling.md
Labels: documentation

#20234 test: require(json) should return the content
  playground/json/__tests__/csr/json-csr.spec.ts
  playground/json/dep-json-require/content.json
  playground/json/dep-json-require/index.js
  playground/json/dep-json-require/package.json
  playground/json/index.html
  playground/json/package.json
  pnpm-lock.yaml
Labels: p1-chore, test

#20383 docs: fix regular expression on the Rolldown page
  docs/guide/rolldown.md
Labels: documentation

#20379 fix: allow resolving bare specifiers to relative paths for entries
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/plugins/resolve.ts
Labels: has workaround, p3-downstream-blocker, regression

#20394 feat(create-vite): bump vite-plugin-svelte to new major for vite7
  packages/create-vite/template-svelte-ts/package.json
  packages/create-vite/template-svelte/package.json
Labels: feat: create-vite

#20392 fix(legacy): don't lower CSS if legacy chunks are not generated
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p3-minor-bug

#20401 docs: suggest `import.meta.hot.accept` in server entry
  docs/guide/api-environment-frameworks.md
Labels: documentation

#20413 refactor: use `foo.endsWith("bar")` instead of `/bar$/.test(foo)`
  packages/plugin-legacy/src/index.ts
  packages/vite/src/node/plugins/asset.ts
Labels: p1-chore

#20387 perf(legacy): skip lowering when detecting polyfills
  packages/plugin-legacy/package.json
  packages/plugin-legacy/src/index.ts
  packages/plugin-legacy/src/shims.d.ts
  pnpm-lock.yaml
Labels: plugin: legacy, p2-nice-to-have

#20426 chore: update contributing.md vite version
  CONTRIBUTING.md
Labels: p1-chore

#20430 refactor: use environment transform request
  packages/vite/src/node/server/environment.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/transformRequest.ts
Labels: p1-chore

#20438 test: fix `resolve.mainFields.custom-first` test flaky fail
  playground/resolve/vite.config-mainfields-custom-first.js
Labels: p1-chore, test

#20459 chore: remove some files from prettier ignore
  .prettierignore
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/c.ts
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic/entry-cyclic.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic/entry.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test1/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test1/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test2/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test2/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test2/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test3/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test3/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test4/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test4/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test5/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test5/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test6/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test6/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test7/Ion.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test7/IonTypes.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test7/dom/Blob.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test7/dom/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test9/dep.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test9/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/d.ts
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/dynamic-import.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/execution-order-re-export/dep1.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/execution-order-re-export/dep2.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/execution-order-re-export/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/import-external.ts
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test1/dep.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test1/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test2/dep.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test2/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test3/dep.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test3/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test4/dep.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test4/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/top-level-object.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/worker.invoke.mjs
Labels: p1-chore

#19592 chore: stablize `cssScopeTo`
  packages/vite/types/metadata.d.ts
Labels: feat: css, p1-chore

#20279 feat: export `defaultExternalConditions`
  packages/vite/src/node/config.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/ssr/index.ts
Labels: p2-nice-to-have

#20435 feat: add `ssrFixStacktrace` / `ssrRewriteStacktrace` to `removeSsrLoadModule` future deprecation
  docs/changes/ssr-using-modulerunner.md
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have

#19981 feat: resolve server URLs before calling other listeners
  packages/vite/src/node/__tests__/dev.spec.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/server/__tests__/resolveServerOptions.spec.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have, feat: dev

#20301 feat(dev): add `this.fs` support
  package.json
  packages/vite/package.json
  packages/vite/src/node/__tests__/plugins/hooks.spec.ts
  packages/vite/src/node/server/pluginContainer.ts
  pnpm-lock.yaml
Labels: rollup plugin compat, p2-nice-to-have

#20358 refactor: use hook filters in internal plugins
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/assetImportMetaUrl.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/dynamicImportVars.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysisBuild.ts
  packages/vite/src/node/plugins/importMetaGlob.ts
  packages/vite/src/node/plugins/json.ts
  packages/vite/src/node/plugins/modulePreloadPolyfill.ts
  packages/vite/src/node/plugins/wasm.ts
  packages/vite/src/node/plugins/workerImportMetaUrl.ts
  pnpm-lock.yaml
Labels: p1-chore

#20402 refactor: use `http-proxy-3`
  docs/config/preview-options.md
  docs/config/server-options.md
  packages/vite/LICENSE.md
  packages/vite/package.json
  packages/vite/rolldown.dts.config.ts
  packages/vite/src/node/http.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/server/middlewares/proxy.ts
  packages/vite/src/types/http-proxy.d.ts
  packages/vite/src/types/shims.d.ts
  patches/http-proxy@1.18.1.patch
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: p2-nice-to-have, trigger: preview

#20434 feat: implement `removeServerHot` future deprecation
  docs/changes/per-environment-apis.md
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have

#20436 feat: add `removeServerReloadModule` future deprecation
  docs/changes/per-environment-apis.md
  packages/vite/src/node/config.ts
  packages/vite/src/node/deprecations.ts
  packages/vite/src/node/server/index.ts
Labels: p2-nice-to-have

#20373 refactor: extract prepareOutDir as a plugin
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/prepareOutDir.ts
Labels: p1-chore, trigger: preview

#20375 refactor: extract resolve rollup options
  packages/vite/src/node/build.ts
Labels: p1-chore

#20429 perf(client): reduce reload debounce
  packages/vite/src/client/client.ts
Labels: p2-nice-to-have

#20424 refactor: rewrite openchrome.applescript to JXA
  packages/vite/bin/openChrome.applescript
  packages/vite/bin/openChrome.js
  packages/vite/src/node/server/openBrowser.ts
Labels: p1-chore

#19057 feat(client): ping from SharedWorker
  packages/vite/src/client/client.ts
Labels: p2-nice-to-have, trigger: preview

#20410 fix(dev): denied requests overly
  packages/vite/src/node/server/middlewares/static.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/transformRequest.ts
  packages/vite/src/node/utils.ts
  playground/fs-serve/__tests__/fs-serve.spec.ts
Labels: p2-edge-case, feat: dev, trigger: preview

#20260 feat(ssr): support `import.meta.resolve` in module runner
  docs/guide/api-environment-runtimes.md
  packages/vite/src/module-runner/createImportMeta.ts
  packages/vite/src/module-runner/importMetaResolver.ts
  packages/vite/src/module-runner/index.ts
  packages/vite/src/module-runner/runner.ts
  packages/vite/src/module-runner/types.ts
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/worker.invoke.mjs
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/worker.mjs
  packages/vite/src/node/ssr/runtime/serverModuleRunner.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
  playground/ssr/__tests__/ssr.spec.ts
  playground/ssr/src/app.js
Labels: p2-nice-to-have, feat: ssr, trigger: preview

#20492 docs: dark mode not applied properly in landing page
  docs/.vitepress/theme/styles/landing.css
  docs/index.md
  pnpm-workspace.yaml
Labels: documentation

#20495 fix(optimizer): discover correct jsx runtime during scan
  packages/vite/src/node/__tests__/fixtures/scan-jsx-runtime/entry-jsx.tsx
  packages/vite/src/node/__tests__/fixtures/scan-jsx-runtime/entry-no-jsx.js
  packages/vite/src/node/__tests__/fixtures/scan-jsx-runtime/tsconfig.json
  packages/vite/src/node/__tests__/package.json
  packages/vite/src/node/__tests__/scan.spec.ts
  packages/vite/src/node/optimizer/scan.ts
  pnpm-lock.yaml
Labels: p3-downstream-blocker, feat: deps optimizer

#20496 fix(preview): set correct host for `resolvedUrls`
  packages/vite/src/node/config.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/__tests__/resolveServerOptions.spec.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/utils.ts
Labels: p3-downstream-blocker, regression, feat: preview, trigger: preview
