Repository vitejs/vite, pull requests merged in 2025-10, with the labels that each got.

#20864 fix(deps): update artichokie to 0.4.2
  packages/vite/package.json
  pnpm-lock.yaml
Labels: dependencies, p2-edge-case, trigger: preview

#20866 fix(dev): skip JS responses for document requests
  packages/vite/src/node/server/middlewares/transform.ts
  playground/html/__tests__/html.spec.ts
  playground/html/test.js
Labels: p3-minor-bug, regression, feat: dev, trigger: preview

#20870 feat(create-vite): bump TS to 5.9
  packages/create-vite/template-lit-ts/package.json
  packages/create-vite/template-preact-ts/package.json
  packages/create-vite/template-qwik-ts/package.json
  packages/create-vite/template-react-ts/package.json
  packages/create-vite/template-solid-ts/package.json
  packages/create-vite/template-svelte-ts/package.json
  packages/create-vite/template-vanilla-ts/package.json
  packages/create-vite/template-vue-ts/package.json
Labels: feat: create-vite

#20886 test: add test that ensures syntaxes not supported are lowered
  playground/build-old/__tests__/build-old.spec.ts
  playground/build-old/index.html
Labels: p1-chore, test

#20887 fix(dev): remove timestamp query consistently
  packages/vite/src/node/server/transformRequest.ts
Labels: feat: hmr, p2-edge-case, feat: dev

#20888 docs(cli): document `vite preview` with more information
  docs/guide/cli.md
Labels: documentation

#20760 fix(dev): allow aliases starting with `//`
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/alias/__tests__/alias.spec.ts
  playground/alias/dir/url_conflict.js
  playground/alias/index.html
  playground/alias/vite.config.js
Labels: p2-edge-case, feat: dev, trigger: preview
