Repository vitejs/vite, pull requests merged in 2025-08, with the labels that each got.

#20527 refactor: use hook filters in the worker plugin
  packages/vite/src/node/plugins/worker.ts
Labels: p1-chore

#20502 fix: merge old and new `noExternal: true` correctly
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/config.ts
Labels: p3-minor-bug

#20542 fix(manifest): initialize `entryCssAssetFileNames` as an empty Set
  packages/vite/src/node/plugins/manifest.ts
Labels: p2-edge-case

#20544 test: detect ts support via `process.features`
  packages/vite/src/node/__tests__/runnerImport.spec.ts
Labels: p1-chore, test

#20545 test: fix unimportant errors in test-unit
  packages/vite/src/node/__tests__/environment.spec.ts
  packages/vite/src/node/__tests__/plugins/hooks.spec.ts
  packages/vite/src/node/__tests__/resolve.spec.ts
  packages/vite/src/node/ssr/runtime/__tests__/server-runtime.spec.ts
Labels: p1-chore, test

#20547 docs: fix redundant "yet" and add missing punctuation
  docs/changes/hotupdate-hook.md
Labels: documentation

#20393 fix(legacy): `modernTargets` should set `build.target`
  packages/plugin-legacy/README.md
  packages/plugin-legacy/src/index.ts
Labels: plugin: legacy, p4-important

#20560 chore: update 7.1 changelog
  packages/vite/CHANGELOG.md
Labels: p1-chore

#20558 fix: don't consider ids with `npm:` prefix as a built-in module
  packages/vite/src/node/config.ts
  packages/vite/src/node/utils.ts
Labels: p3-downstream-blocker

#20579 docs: show old document warning
  docs/.vitepress/theme/components/OldDocument.vue
  docs/.vitepress/theme/index.ts
Labels: documentation

#20582 chore: bump TS to 5.9 and typecheck docs
  docs/.vitepress/inlined-scripts/banner.d.ts
  docs/.vitepress/theme/components/SponsorBanner.vue
  docs/.vitepress/theme/components/landing/1. hero-section/HeroDiagram.vue
  docs/.vitepress/theme/components/landing/1. hero-section/svg-elements/SvgInputs.vue
  docs/.vitepress/theme/components/landing/1. hero-section/svg-elements/SvgOutputs.vue
  docs/.vitepress/theme/components/landing/2. feature-section/FeatureCI.vue
  docs/.vitepress/theme/components/landing/2. feature-section/FeatureOptimizedBuild.vue
  docs/.vitepress/theme/components/landing/2. feature-section/FeatureSection.vue
  docs/.vitepress/theme/components/landing/3. frameworks-section/FrameworkCard.vue
  docs/.vitepress/theme/components/landing/3. frameworks-section/FrameworksSection.vue
  docs/.vitepress/theme/components/landing/4. community-section/CommunitySection.vue
  docs/.vitepress/theme/components/landing/common/SvgNode.vue
  docs/.vitepress/tsconfig.json
  docs/.vitepress/vite-env.d.ts
  docs/_data/blog.data.ts
  docs/package.json
  docs/tsconfig.json
  package.json
  playground/tsconfig.json
  pnpm-lock.yaml
  scripts/tsconfig.json
Labels: dependencies, p1-chore

#20595 fix(client): add `[vite]` prefixes to debug logs
  packages/vite/src/client/client.ts
Labels: p2-nice-to-have

#20581 fix(hmr): watch non-inlined assets referenced by CSS
  packages/vite/src/node/plugins/css.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/css/css-url.css
  playground/assets/index.html
  playground/assets/nested/donuts-large.svg
Labels: feat: css, feat: hmr, p3-minor-bug

#20596 chore: pnpm dedupe
  pnpm-lock.yaml
Labels: p1-chore

#20643 ci: use `actions-cool/issues-helper` for locking old closed issues
  .github/workflows/lock-closed-issues.yml
Labels: p1-chore

#20646 perf(cli): dynamically import `resolveConfig`
  packages/vite/src/node/cli.ts
Labels: p2-nice-to-have

#20640 feat: support long lines in `generateCodeFrame`
  packages/vite/src/node/__tests__/__snapshots__/utils.spec.ts.snap
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/utils.ts
Labels: p2-nice-to-have

#20641 refactor: use `import` in worker threads
  packages/vite/rolldown.config.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/terser.ts
Labels: p1-chore, trigger: preview

#20647 test: remove `checkNodeVersion` test
  packages/vite/src/node/__tests__/cli.spec.ts
  packages/vite/src/node/cli.ts
Labels: p1-chore, test

#20649 docs: update plugins page
  docs/plugins/index.md
Labels: documentation

#20680 docs(rolldown): update hook filter link
  docs/guide/rolldown.md
Labels: documentation

#20688 docs(config): fix type of preview.allowedHosts to 'string[] | true'
  docs/config/preview-options.md
Labels: documentation
