Repository vitejs/vite, pull requests merged in 2025-04, with the labels that each got.

#19759 docs: plugin authors guide for rolldown-vite
  docs/guide/rolldown.md
Labels: documentation

#19782 fix: fs check with svg and relative paths
  packages/vite/src/node/plugins/asset.ts
  packages/vite/src/node/plugins/wasm.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/server/transformRequest.ts
  playground/fs-serve/__tests__/fs-serve.spec.ts
  playground/fs-serve/root/src/index.html
  playground/fs-serve/root/unsafe.svg
Labels: trigger: preview

#19779 fix: keep entry asset files imported by other files
  packages/vite/src/node/plugins/asset.ts
  playground/backend-integration/__tests__/backend-integration.spec.ts
  playground/backend-integration/frontend/entrypoints/main.ts
  playground/backend-integration/frontend/entrypoints/water-container.svg
Labels: p3-minor-bug, regression, feat: build

#19789 chore: refactor test setup
  playground/vitestSetup.ts
  vitest.config.e2e.ts
Labels: p1-chore

#19767 fix(dev): make query selector regexes more inclusive (fix #19213)
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/html.ts
Labels: feat: html, p2-edge-case

#19791 fix: unbundle `fdir` to fix `commonjsOptions.dynamicRequireTargets`
  packages/vite/LICENSE.md
  packages/vite/package.json
  playground/external/vite.config.js
  pnpm-lock.yaml
Labels: p3-minor-bug, regression

#19799 docs(vite): fix description of `transformIndexHtml` hook
  packages/vite/src/node/plugin.ts
Labels: documentation

#19719 feat(legacy): add 'assumptions' option
  packages/plugin-legacy/src/index.ts
  packages/plugin-legacy/src/types.ts
Labels: plugin: legacy, p2-nice-to-have

#19796 fix(types): remove the `keepProcessEnv` from the `DefaultEnvironmentOptions` type
  packages/vite/src/node/config.ts
Labels: p2-edge-case

#19812 test: tweak generateCodeFrame test
  packages/vite/src/node/__tests__/__snapshots__/utils.spec.ts.snap
  packages/vite/src/node/__tests__/utils.spec.ts
Labels: p1-chore, test

#19810 docs: remove deprecated folder mapping exports warning
  docs/config/shared-options.md
Labels: documentation

#19814 fix(css): remove empty chunk imports correctly when chunk file name contained special characters
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-edge-case

#19818 fix: correct the behavior when multiple transform filter options are specified
  packages/vite/src/node/__tests__/plugins/pluginFilter.spec.ts
  packages/vite/src/node/plugins/index.ts
  packages/vite/src/node/plugins/pluginFilter.ts
Labels: p3-minor-bug

#19768 fix(module-runner): allow already resolved id as entry
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
  packages/vite/src/node/ssr/fetchModule.ts
  packages/vite/src/node/ssr/runtime/__tests__/server-runtime.spec.ts
  packages/vite/src/node/ssr/runtime/__tests__/utils.ts
  playground/hmr-ssr/__tests__/hmr-ssr.spec.ts
Labels: p3-minor-bug, feat: ssr, trigger: preview

#19830 fix: reject requests with `#` in request-target
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/rejectInvalidRequest.ts
  playground/fs-serve/__tests__/fs-serve.spec.ts
Labels: trigger: preview

#19828 refactor: simplify pluginFilter implementation
  packages/vite/src/node/plugins/pluginFilter.ts
Labels: p1-chore

#19794 fix: addWatchFile doesn't work if base is specified (fixes #19792)
  packages/vite/src/node/plugins/importAnalysis.ts
  playground/transform-plugin/__tests__/base/transform-plugin.spec.ts
  playground/transform-plugin/__tests__/tests.ts
  playground/transform-plugin/__tests__/transform-plugin.spec.ts
  playground/transform-plugin/vite.config-base.js
Labels: feat: hmr, p3-minor-bug, trigger: preview

#19793 fix(hmr): run HMR handler sequentially
  packages/vite/src/client/client.ts
  packages/vite/src/module-runner/hmrHandler.ts
  packages/vite/src/module-runner/runner.ts
  packages/vite/src/shared/hmrHandler.ts
  playground/hmr/__tests__/hmr.spec.ts
Labels: feat: hmr, p2-edge-case, trigger: preview

#19843 test: fix flaky transform-plugin playground test
  playground/transform-plugin/__tests__/base/transform-plugin.spec.ts
  playground/vitestGlobalSetup.ts
Labels: p1-chore, test

#19849 docs: bump node version to LTS
  docs/guide/static-deploy.md
Labels: documentation

#19870 fix(hmr): avoid infinite loop happening with `hot.invalidate` in circular deps
  packages/vite/src/node/server/environment.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/shared/hmr.ts
  packages/vite/types/customEvent.d.ts
  packages/vite/types/hmrPayload.d.ts
  playground/hmr-ssr/__tests__/hmr-ssr.spec.ts
  playground/hmr-ssr/hmr.ts
  playground/hmr-ssr/invalidation-circular-deps/circular-invalidate/child.js
  playground/hmr-ssr/invalidation-circular-deps/circular-invalidate/parent.js
  playground/hmr-ssr/invalidation-circular-deps/index.js
  playground/hmr-ssr/invalidation-circular-deps/invalidate-handled-in-circle/child.js
  playground/hmr-ssr/invalidation-circular-deps/invalidate-handled-in-circle/parent.js
  playground/hmr/__tests__/hmr.spec.ts
  playground/hmr/hmr.ts
  playground/hmr/index.html
  playground/hmr/invalidation-circular-deps/circular-invalidate/child.js
  playground/hmr/invalidation-circular-deps/circular-invalidate/parent.js
  playground/hmr/invalidation-circular-deps/index.js
  playground/hmr/invalidation-circular-deps/invalidate-handled-in-circle/child.js
  playground/hmr/invalidation-circular-deps/invalidate-handled-in-circle/parent.js
Labels: feat: hmr, p3-minor-bug, trigger: preview

#19875 fix(create-vite): adding an interactive flag to force interactivity
  packages/create-vite/src/index.ts
Labels: p3-minor-bug, feat: create-vite

#19881 docs(rolldown): clarify rolldown-vite versioning policy
  docs/guide/rolldown.md
Labels: documentation

#19883 chore: reorganize contributing guide
  CONTRIBUTING.md
Labels: p1-chore

#19886 fix: open first url if host does not match any urls
  packages/vite/src/node/__tests__/utils.spec.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/utils.ts
Labels: p2-edge-case, regression

#19852 fix: match default asserts case insensitive
  packages/vite/src/node/constants.ts
Labels: p2-edge-case

#19880 feat(css): improve lightningcss messages
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-nice-to-have

#19863 docs(static-deploy): extract github workflow file for renovate
  .github/renovate.json5
  docs/guide/static-deploy-github-pages.yaml
  docs/guide/static-deploy.md
Labels: documentation

#19884 chore: add section about stylistic changes in contribution guide
  CONTRIBUTING.md
Labels: p1-chore

#19890 docs(rolldown): add `withFilter` + performance chapter
  docs/guide/rolldown.md
Labels: documentation

#19904 chore(deps): update vue32 to vue34
  .github/renovate.json5
  playground/external/__tests__/external.spec.ts
  playground/external/index.html
  playground/external/package.json
  playground/external/vite.config.js
  playground/html/vite.config.js
  pnpm-lock.yaml
Labels: dependencies, p1-chore, test

#19842 fix(ssr): fix live binding of default export declaration and hoist exports getter
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test9/dep.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/cyclic2/test9/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/package.json
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test1/dep.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test1/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test2/dep.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test2/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test3/dep.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test3/index.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test4/dep.js
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/live-binding/test4/index.js
  packages/vite/src/node/ssr/runtime/__tests__/server-runtime.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  pnpm-lock.yaml
Labels: feat: ssr, p2-edge-case, trigger: preview

#19903 test: remove `node-fetch` and use native fetch
  playground/assets/__tests__/assets.spec.ts
  playground/fs-serve/__tests__/base/fs-serve-base.spec.ts
  playground/fs-serve/__tests__/fs-serve.spec.ts
  playground/optimize-missing-deps/__test__/optimize-missing-deps.spec.ts
  playground/package.json
  playground/ssr-html/__tests__/ssr-html.spec.ts
  playground/ssr-pug/__tests__/ssr-pug.spec.ts
  pnpm-lock.yaml
Labels: p1-chore, test

#19902 test(ssr-deps): use `@node-rs/bcrypt` instead of `bcrypt`
  playground/ssr-deps/package.json
  playground/ssr-deps/src/app.js
  pnpm-lock.yaml
Labels: p1-chore, test

#19629 test(ssr): test `ssrTransform` re-export deps and test stacktrace with first line
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/has-error-first-comment.ts
  packages/vite/src/node/ssr/runtime/__tests__/fixtures/has-error-first.js
  packages/vite/src/node/ssr/runtime/__tests__/server-source-maps.spec.ts
Labels: p1-chore, feat: ssr, test

#19496 fix(assets): ensure ?no-inline is not included in the asset url in the production environment
  packages/vite/src/node/plugins/asset.ts
  playground/assets/__tests__/assets.spec.ts
  playground/assets/index.html
Labels: p2-edge-case

#19920 fix(css): resolve relative imports in sass properly on Windows
  packages/vite/src/node/plugins/css.ts
Labels: feat: css, p2-edge-case

#19921 perf: skip sourcemap generation for renderChunk hook of import-analysis-build plugin
  packages/vite/src/node/plugins/importAnalysisBuild.ts
Labels: p2-nice-to-have

#19853 fix: ignore malformed uris in tranform middleware
  packages/vite/src/node/server/middlewares/transform.ts
Labels: p2-edge-case, feat: dev

#19928 fix(legacy): use unbuild 3.4 for now
  packages/plugin-legacy/package.json
  pnpm-lock.yaml
Labels: has workaround, plugin: legacy, p3-minor-bug

#19935 refactor: remove duplicate plugin context type
  packages/vite/rollup.dts.config.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/environment.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/asset.ts
Labels: p1-chore

#19947 docs: capitalize title
  docs/guide/env-and-mode.md
Labels: documentation

#19771 docs: update to express 5
  .github/renovate.json5
  docs/guide/ssr.md
  docs/package.json
  pnpm-lock.yaml
Labels: documentation, dependencies

#19954 chore: remove unused deps
  playground/json/package.json
  playground/object-hooks/package.json
  playground/tailwind-v3/package.json
  playground/tailwind/package.json
  pnpm-lock.yaml
Labels: p1-chore

#19943 docs: add Deno commands
  docs/guide/index.md
Labels: documentation

#19940 fix(optimizer): return plain object when using `require` to import externals in optimized dependencies
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-cjs-with-external-dep/index.js
  playground/optimize-deps/dep-cjs-with-external-dep/package.json
  playground/optimize-deps/dep-esm-external/index.js
  playground/optimize-deps/dep-esm-external/package.json
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  playground/optimize-deps/vite.config.js
  pnpm-lock.yaml
Labels: p3-minor-bug, feat: ssr, feat: deps optimizer

#19927 feat(create-vite): add RedwoodSDK to create-vite app.
  packages/create-vite/src/index.ts
Labels: feat: create-vite
