Repository vitejs/vite, pull requests merged in 2025-05, with the labels that each got.

#19959 fix(ssr): handle uninitialized export access as undefined
  packages/vite/src/node/ssr/__tests__/ssrLoadModule.spec.ts
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/runtime/__tests__/server-runtime.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
  vitest.config.ts
Labels: trigger: preview

#19999 fix(cli): make `cleanGlobalCLIOptions()` clean `--force`
  packages/vite/src/node/cli.ts
Labels: p1-chore, trigger: preview

#20016 test(ssr-html): deconflict filenames for typescript resolution
  playground/ssr-html/__tests__/ssr-html.spec.ts
  playground/ssr-html/src/error-js.js
  playground/ssr-html/src/error-ts.ts
  playground/ssr-html/test-stacktrace.js
Labels: p1-chore, test

#20011 test(optimizer): add test for cjs dep static import
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/cjs-dynamic.js
  playground/optimize-deps/cjs.js
  playground/optimize-deps/index.html
Labels: p1-chore, test, feat: deps optimizer

#20024 docs(i18n): add Persian language docs link
  docs/.vitepress/config.ts
Labels: documentation

#20031 chore: deprecate `ResolvedConfig.createResolver` and recommend `createIdResolver`
  packages/vite/src/node/config.ts
Labels: p1-chore

#20039 fix(client): render the last part of the stacktrace
  packages/vite/src/client/overlay.ts
Labels: p2-edge-case, feat: dev

#19255 chore!: remove deprecated splitVendorChunkPlugin
  packages/vite/src/node/index.ts
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/define.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/plugins/importAnalysis.ts
  packages/vite/src/node/plugins/splitVendorChunk.ts
  packages/vite/src/node/publicUtils.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/middlewares/transform.ts
  packages/vite/src/node/utils.ts
Labels: p1-chore, breaking change

#19349 refactor!: remove deprecated hook-level `enforce`/`transform` from `transformIndexHtml` hook
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
Labels: p1-chore, breaking change

#19972 chore!: remove node 18 support
  .github/workflows/ci.yml
  docs/guide/index.md
  eslint.config.js
  package.json
  packages/create-vite/README.md
  packages/create-vite/build.config.ts
  packages/create-vite/package.json
  packages/create-vite/tsconfig.json
  packages/plugin-legacy/build.config.ts
  packages/plugin-legacy/package.json
  packages/plugin-legacy/tsconfig.json
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/scripts/dev.ts
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/ssr/runtime/__tests__/package.json
  packages/vite/src/node/tsconfig.json
  packages/vite/src/node/utils.ts
  packages/vite/tsconfig.base.json
  playground/ssr-html/test-stacktrace.js
  playground/tsconfig.json
  scripts/tsconfig.json
  vitest.config.e2e.ts
  vitest.config.ts
Labels: p1-chore, breaking change

#19986 refactor: remove deprecated env api properties
  packages/vite/src/node/baseEnvironment.ts
  packages/vite/src/node/optimizer/scan.ts
  packages/vite/src/node/server/hmr.ts
Labels: p1-chore

#19985 refactor!: remove deprecated no-op type only properties
  packages/vite/src/module-runner/types.ts
  packages/vite/src/node/plugins/resolve.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/ssr/runtime/serverModuleRunner.ts
  packages/vite/src/node/ssr/ssrModuleLoader.ts
Labels: p1-chore, breaking change

#19987 refactor!: remove deprecated `HotBroadcaster` related types
  packages/vite/src/node/index.ts
  packages/vite/src/node/server/hmr.ts
Labels: p1-chore, breaking change

#20001 refactor: remove backward compat for calling internal plugins directly
  packages/vite/src/node/__tests__/plugins/css.spec.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/plugins/json.ts
Labels: p1-chore

#19979 chore: declare version range for peer dependencies
  packages/vite/package.json
Labels: p1-chore

#19977 refactor(css)!: remove sass legacy API support
  docs/config/shared-options.md
  packages/vite/src/node/plugins/css.ts
  packages/vite/types/internal/cssPreprocessorOptions.d.ts
  playground/css-sourcemap/__tests__/sass-legacy/sass-legacy.spec.ts
  playground/css-sourcemap/vite.config-sass-legacy.js
  playground/css/__tests__/sass-legacy/sass-legacy.spec.ts
  playground/css/vite.config-sass-legacy.js
  playground/vitestGlobalSetup.ts
Labels: p1-chore, breaking change

#19912 feat(build): provide names for asset entrypoints
  packages/vite/src/node/plugins/manifest.ts
  playground/backend-integration/__tests__/backend-integration.spec.ts
Labels: p2-nice-to-have, feat: build

#19971 feat: buildApp hook
  docs/guide/api-environment-frameworks.md
  packages/vite/src/node/build.ts
  packages/vite/src/node/index.ts
  packages/vite/src/node/plugin.ts
  playground/environment-react-ssr/vite.config.ts
Labels: feat: environment API

#19894 feat: allow passing down resolved config to vite's `createServer`
  packages/vite/src/node/config.ts
  packages/vite/src/node/server/index.ts
Labels: p3-downstream-blocker, trigger: preview

#20013 refactor: remove no-op `legacy.proxySsrExternalModules`
  packages/vite/src/node/config.ts
Labels: p1-chore

#19755 refactor: use hook filters from rollup
  package.json
  packages/vite/package.json
  packages/vite/src/node/build.ts
  packages/vite/src/node/plugins/worker.ts
  pnpm-lock.yaml
Labels: p1-chore

#20059 docs: add backticks
  docs/config/shared-options.md
  docs/guide/performance.md
Labels: documentation

#20057 docs: remove single quote from buildApp hook
  docs/guide/api-environment-frameworks.md
Labels: documentation

#20049 ci: run tests on Node 24 as well
  .github/workflows/ci.yml
  packages/vite/src/node/__tests__/runnerImport.spec.ts
Labels: p1-chore

#19925 chore: use rolldown to bundle Vite itself
  package.json
  packages/vite/package.json
  packages/vite/rollup.config.ts
  packages/vite/rollupLicensePlugin.ts
  packages/vite/scripts/dev.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/packages.ts
  packages/vite/src/node/plugins/css.ts
  packages/vite/src/node/utils.ts
  pnpm-lock.yaml
Labels: p1-chore, trigger: preview

#20040 feat(client): support opening fileURL in editor
  packages/vite/src/client/overlay.ts
Labels: p2-nice-to-have, feat: dev

#20065 chore: use tsdown
  packages/create-vite/index.js
  packages/create-vite/package.json
  packages/create-vite/tsconfig.json
  packages/create-vite/tsdown.config.ts
  packages/plugin-legacy/build.config.ts
  packages/plugin-legacy/package.json
  packages/plugin-legacy/tsconfig.json
  packages/plugin-legacy/tsdown.config.ts
  pnpm-lock.yaml
Labels: p1-chore

#20076 test: skip writing files in build hook filter test
  packages/vite/src/node/__tests__/plugins/index.spec.ts
Labels: p1-chore, test

#19829 refactor(ssr): remove ssrTransform line offset preservation
  packages/vite/src/node/ssr/__tests__/ssrTransform.spec.ts
  packages/vite/src/node/ssr/ssrTransform.ts
Labels: p1-chore, feat: ssr, breaking change, trigger: preview

#20078 feat(create-vite): update target to es2023 in `tsconfig.node.json`
  packages/create-vite/template-preact-ts/tsconfig.node.json
  packages/create-vite/template-qwik-ts/tsconfig.node.json
  packages/create-vite/template-react-ts/tsconfig.node.json
  packages/create-vite/template-solid-ts/tsconfig.node.json
  packages/create-vite/template-svelte-ts/tsconfig.node.json
  packages/create-vite/template-vue-ts/tsconfig.node.json
Labels: p2-nice-to-have

#20077 fix: merge `environments.*.resolve.noExternal` properly
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/utils.ts
Labels: p3-minor-bug, feat: ssr

#20075 docs: refactor components to TypeScript
  docs/.vitepress/theme/components/AsideSponsors.vue
  docs/.vitepress/theme/components/YouTubeVideo.vue
  docs/.vitepress/theme/components/landing/1. hero-section/HeroDiagram.vue
  docs/.vitepress/theme/components/landing/1. hero-section/HeroSection.vue
  docs/.vitepress/theme/components/landing/2. feature-section/FeatureCI.vue
  docs/.vitepress/theme/components/landing/2. feature-section/FeatureFlexiblePlugins.vue
  docs/.vitepress/theme/components/landing/2. feature-section/FeatureInstantServerStart.vue
  docs/.vitepress/theme/components/landing/2. feature-section/FeatureOptimizedBuild.vue
  docs/.vitepress/theme/components/landing/2. feature-section/FeatureRichFeatures.vue
  docs/.vitepress/theme/components/landing/2. feature-section/FeatureSection.vue
  docs/.vitepress/theme/components/landing/3. frameworks-section/FrameworksSection.vue
  docs/.vitepress/theme/components/landing/4. community-section/CommunitySection.vue
  docs/.vitepress/theme/components/landing/5. sponsor-section/SponsorSection.vue
  docs/.vitepress/theme/components/landing/common/SvgNode.vue
  docs/.vitepress/theme/composables/sponsor.ts
  docs/.vitepress/theme/composables/useCardAnimation.ts
  docs/.vitepress/vite-env.d.ts
Labels: p1-chore

#20007 feat!: bump `build.target` and name it `baseline-widely-available`
  docs/config/build-options.md
  docs/guide/build.md
  docs/guide/index.md
  packages/create-vite/template-lit-ts/tsconfig.json
  packages/create-vite/template-preact-ts/tsconfig.app.json
  packages/create-vite/template-qwik-ts/tsconfig.app.json
  packages/create-vite/template-react-ts/tsconfig.app.json
  packages/create-vite/template-solid-ts/tsconfig.app.json
  packages/create-vite/template-svelte-ts/tsconfig.app.json
  packages/create-vite/template-vanilla-ts/tsconfig.json
  packages/vite/package.json
  packages/vite/scripts/generateTarget.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/cli.ts
  packages/vite/src/node/constants.ts
  packages/vite/src/node/optimizer/index.ts
  packages/vite/src/node/plugins/css.ts
  pnpm-lock.yaml
Labels: breaking change, p3-significant

#19990 chore: use rolldown-plugin-dts for dts bundling
  packages/vite/package.json
  packages/vite/rollup.dts.config.ts
  pnpm-lock.yaml
Labels: p1-chore

#20079 fix(optimizer): show error when `computeEntries` failed
  packages/vite/src/node/optimizer/optimizer.ts
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-minor-bug, feat: deps optimizer

#20089 chore: use plugin hooks filter for `patch-types` plugin for bundling vite
  packages/vite/rollup.dts.config.ts
  pnpm-lock.yaml
Labels: p1-chore

#20096 chore: rename rollup to rolldown where appropriate
  CONTRIBUTING.md
  eslint.config.js
  packages/vite/package.json
  packages/vite/rolldown.config.ts
  packages/vite/rolldown.dts.config.ts
  packages/vite/tsconfig.json
Labels: p1-chore

#20097 chore: remove unused deps
  docs/package.json
  package.json
  packages/vite/package.json
  pnpm-lock.yaml
Labels: p1-chore

#20068 fix(css): should not wrap with double quote when the url rebase feature bailed out
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/sass-tests.ts
  playground/css/__tests__/tests.ts
  playground/css/index.html
  playground/css/nested/_index.scss
  playground/css/nested/nested.less
Labels: feat: css, p3-minor-bug

#20099 chore: group rolldown related deps for renovate
  .github/renovate.json5
Labels: p1-chore

#19936 feat: make PluginContext available for Vite-specific hooks
  packages/vite/src/node/__tests__/plugins/hooks.spec.ts
  packages/vite/src/node/build.ts
  packages/vite/src/node/config.ts
  packages/vite/src/node/plugin.ts
  packages/vite/src/node/plugins/html.ts
  packages/vite/src/node/preview.ts
  packages/vite/src/node/server/environment.ts
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
  packages/vite/src/node/server/middlewares/indexHtml.ts
  packages/vite/src/node/server/pluginContainer.ts
Labels: p2-nice-to-have

#20029 fix: importing an optional peer dep should throw an runtime error
  packages/vite/src/node/optimizer/esbuildDepPlugin.ts
  packages/vite/src/node/plugins/resolve.ts
  playground/optimize-deps/__tests__/optimize-deps.spec.ts
  playground/optimize-deps/dep-with-optional-peer-dep-cjs/index.js
  playground/optimize-deps/dep-with-optional-peer-dep-cjs/package.json
  playground/optimize-deps/index.html
  playground/optimize-deps/package.json
  pnpm-lock.yaml
Labels: has workaround, p2-edge-case

#20067 fix(css): sass rebase url in relative imported modules
  packages/vite/src/node/plugins/css.ts
  playground/css/__tests__/sass-tests.ts
  playground/css/index.html
  playground/css/nested/relative.scss
  playground/css/sass.scss
Labels: feat: css, p3-minor-bug

#19992 feat: stabilize `css.preprocessorMaxWorkers` and default to `true`
  docs/config/shared-options.md
  packages/vite/src/node/plugins/css.ts
Labels: feat: css

#19988 refactor!: remove `HotBroadcaster`
  packages/vite/src/node/server/hmr.ts
  packages/vite/src/node/server/index.ts
Labels: p1-chore, breaking change

#20045 fix: treat all `optimizeDeps.entries` values as globs
  docs/config/dep-optimization-options.md
  packages/vite/src/node/optimizer/scan.ts
Labels: p3-downstream-blocker, breaking change, feat: deps optimizer

#20129 fix(types): expose additional PluginContext types
  packages/vite/src/node/index.ts
Labels: has workaround, p3-downstream-blocker

#20134 chore: remove unused `scripts/patchCJS.ts`
  scripts/patchCJS.ts
Labels: p1-chore

#20133 docs: remove `env.d.ts` mentions
  docs/config/shared-options.md
  docs/guide/api-hmr.md
  docs/guide/features.md
Labels: documentation

#20131 chore: speed up typechecking
  package.json
  packages/create-vite/package.json
  packages/create-vite/tsconfig.json
  packages/vite/package.json
  packages/vite/tsconfig.base.json
  playground/package.json
  playground/tsconfig.json
  scripts/tsconfig.json
Labels: p1-chore

#20127 docs: clarify dev browser support version
  docs/guide/index.md
Labels: documentation

#20138 fix: merge `server.allowedHosts: true` correctly
  packages/vite/src/node/__tests__/config.spec.ts
  packages/vite/src/node/utils.ts
Labels: p2-edge-case
